### ISSUE TITLE
The specified value " ?  : 0" cannot be parsed, or is out of range.

### ISSUE THREAD

**Issue by leecolarelli** [alpinejs/alpine#1002]
Using alpine.js with laravel. Getting this error on every page `The specified value " ?  : 0" cannot be parsed, or is out of range.`

References line 665 - `el.value = value` in `function handleAttributeBindingDirective(component, el, attrName, expression, extraVars, attrType, modifiers)`.

**Comment by HugoDF** [comment]
Can you reproduce in a codepen? Or is this only with Laravel?

**Comment by SimoTod** [comment]
That ternary looks broken so I think you have something wrong in your code, you'll need a booean statementh before the question mark and a value to return after.
I.e. `$something ? 10 : 0`

**Comment by leecolarelli** [comment]
Sorry I think the issue was broken code instead of an error in alpine. Thanks for the replies!
