### ISSUE TITLE
this.$watch not working in x-init

### ISSUE THREAD

**Issue by su8898** [alpinejs/alpine#1012]
I was trying to extract an inline function to the script tag. 

$watch is working when adding x-init callback inline as shown below.  [CodePen to replicate the issue](https://codepen.io/domus/pen/rNMQoaV?editors=1011)

```
x-init = "()=>{
 selectP = $refs.ProcCode;
      $(selectP).on('change', (event) => {
        procCode = event.target.value;
        console.log('procCode.change', procCode);
      });
      $watch('procCode', (value) => console.log('code', value));
    }"
```

However, when this.$watch is not working from inside a function.

```<div x-data="page()" x-init="init()">```
```
function page() {
  return {
    procCode2: "",
    init() {
      selectP = this.$refs.ProcCode2;
      $(selectP).on("change", (event) => {
        procCode2 = event.target.value;
        console.log("procCode2.change", procCode2);
      });
      this.$watch("procCode2", (value) => console.log("proccode2", value));
    }
  };
}
```
Any idea what am I missing here?

**Comment by KevinBatdorf** [comment]
You need to use `this` to access properties from within a method, like `this.procCode2 = event.target.value`

Also, you can add the change event to the `<select @change="doSomething($event)">` directly

**Comment by su8898** [comment]
@KevinBatdorf thank you. It did work. Closing the issue.
