### ISSUE TITLE
Dose alpine re-run x-init with x-data?

### ISSUE THREAD

**Issue by MarcGodard** [alpinejs/alpine#1030]
I have a strange situation where I am doing the following to set dark mode in my app.

```html
<body x-data="{ colorDark: false }" x-init="$nextTick(() => { colorDark = $store.color.dark })" x-bind:class="{ 'dark': colorDark }">
...
</body>
```

The way I use alpine is different where I need to use a global store (in this case Spruce). This works well enough because when I switch dark mode on or off in another part of my app, I just add or remove the class from the body. However, every once and a while, it messes up seems to re-init, but only with the x-data, not with the updated value of `$store.color.dark`.

Any ideas?

**Comment by MarcGodard** [comment]
I found a work around.

**Comment by ryangjchandler** [comment]
@MarcGodard Is there any reason why you're not just using the `$store.color.dark` directly, instead of assigning it to another prop?

**Comment by MarcGodard** [comment]
@ryangjchandler Because it was on the initial load, where alpine was loaded, but spruce variables were not initiated yet. That is why I was using the next tick.

**Comment by ryangjchandler** [comment]
Hm, that shouldn't be the case if you've loaded everything in the correct order, e.g. You can use `$store.whatever` as the value of `x-text` or something, no need for next tick.

**Comment by MarcGodard** [comment]
I think it is because I didn't add the value to the store yet (I have a strange set up). I could just move that into the html and that would probably solve that. To be honest, I am using alpine and spruce in very un-recommended ways LOL. But having very good success. I would love to show you my code and discuss off github if you would like.
