### ISSUE TITLE
Things removed from the dom still seem to run

### ISSUE THREAD

**Issue by MarcGodard** [alpinejs/alpine#1039]
I have a component that uses `x-show` and runs a function to figure out if it should show. If I put a console log in that function, it still seems to run after I removed that template from the DOM completely when other modules load.

I assume alpine keeps it in memory and checks all the variables on any change to `x-data` or something. Also, it doesn't seem that the garbage collector is dealing with it.

Is there a way I can clear these? Just want to make my little app really efficient.

**Comment by MarcGodard** [comment]
Does using `x-html` allow alpine in that html? And would it still suffer from the above issue?

**Comment by KevinBatdorf** [comment]
You mean an `x-show` that's inside an `x-if`? I can't reproduce it. Can you share a demo?

**Comment by MarcGodard** [comment]
No just a regular `x-show` inside an element that I remove the whole DOM element, still seems to keep running the `x-show` function when not even displaying the `x-show`. I will make a codepen for it after lunch.

**Comment by KevinBatdorf** [comment]
Yeah a demo would help. I tried to reproduce it here but no luck. Maybe you have an event that's firing off? Anyway, I'll wait for the demo

https://codepen.io/KevinBatdorf/pen/NWRQjEz

**Comment by MarcGodard** [comment]
Maybe it is because I am not using `$refs.show.remove()` but a `document.getElementById().remove()` I will play with this.

**Comment by MarcGodard** [comment]
I am closing this because the more I work with alpine, the more I will be building my own custom solution.

**Comment by ryangjchandler** [comment]
> Maybe it is because I am not using `$refs.show.remove()` but a `document.getElementById().remove()` I will play with this.

This won't be it because `$refs.show` returns the same thing as `document.getElementById`.

**Comment by SimoTod** [comment]
I would check if you are actually removing the right element. Directives are reevaluated at runtime Alpine doesn't keep track of them (at least in v2).
