### ISSUE TITLE
Get data from async functions

### ISSUE THREAD

**Issue by fabianobonin** [alpinejs/alpine#1048]
It would be nice if we could get data from async functions (awaiting for it, off course).

    <label x-text="fn()"></label>

    <script>
      async function fn(key) {
        return 'value';
      }
    </script>

We had some discussion about it here:
https://github.com/alpinejs/alpine/discussions/1042

**Comment by calebporzio** [comment]
Agreed, it's been implemented for V3 of Alpine (no official release date yet however). Closing this as no plans for adding this to V2. Thanks!

**Comment by fabianobonin** [comment]
Hi, Caleb, thanks for your answer.

I am using Alpine in the development version of an application that will be launched some months ahead.

If v3 is open for testing and you need some volunteer, i would be glad to help.

Best regards.

**Comment by calebporzio** [comment]
Great, I'll keep that in mind. Thanks!
