### ISSUE TITLE
class and :class do not work together

### ISSUE THREAD

**Issue by f-liva** [alpinejs/alpine#1059]
```html
<div x-data="{ shouldDisableButton : true }">
    <a class="button" :class="{ 'disabled' : shouldDisableButton }">Button</a>
</div>
```

Trying to use `class` and `:class` togheter it throws this error:

![image](https://user-images.githubusercontent.com/346224/106460746-14183400-6494-11eb-8a46-0bd7603225a4.png)

Anyone it understand why?

**Comment by jesse-deboer** [comment]
The error in the console does not look like it's from the code you have written above it. The code should work as expected, see below:

![image](https://user-images.githubusercontent.com/14839421/106466269-6872e200-649b-11eb-812f-815bd4f01a70.png)

**Comment by f-liva** [comment]
```html
<a :class="place ? 'button block flex-no-shrink' : 'button block flex-no-shrink disabled'" href="#day-1">Scegli il giorno</a>
```

This is the original snippet on which I adopted this subterfuge, but as you can see there is the repetition of `button block flex-no-shrink` and when the page loads you see a flicker effect because the class attribute is added by apline after loading. How would you fix it?

**Comment by ryangjchandler** [comment]
@f-liva Have you got a CodePen that reproduces the problem?

**Comment by KevinBatdorf** [comment]
Maybe check in your editor you type out `"` manually and it not copy/pasted. It could not be an actual double quote.

**Comment by f-liva** [comment]
I found the cause, it was a InlineCss filter in my a PageSpeed package! Sorry and thank for your help!
