### ISSUE TITLE
change delimiters

### ISSUE THREAD

**Issue by Joe2824** [alpinejs/alpine#106]
Hi,

it ist possible to change the delimiters to use this framework in flask or Django?

**Comment by calebporzio** [comment]
Please explain

**Comment by calebporzio** [comment]
Closing because of lack of explanation.

**Comment by AbuzzT** [comment]
Check out Vue...https://vuejs.org/v2/api/#delimiters. I need this too if I want to use alpinejs within Django templates as they conflict with django {{ }}.

**Comment by SimoTod** [comment]
Alpine doesn't use `{{` and `}}`
