### ISSUE TITLE
Alpine Error: "TypeError: element.originalEvent is undefined"

### ISSUE THREAD

**Issue by MarcGodard** [alpinejs/alpine#1066]
I cannot find the "originalEvent" anywhere in the event sent to the function. I am using this for a drag and drop as I need to set that elements event to allow file copy instead of the browser trying to open that file.

```
Alpine Error: "TypeError: element.originalEvent is undefined"
Expression: "$store.adminUploadsItem.prepareDrop($event.target)"
```

**Comment by ryangjchandler** [comment]
@MarcGodard Isn't `event.originalEvent` related to jQuery?

**Comment by MarcGodard** [comment]
@ryangjchandler Ahhh yes... my bad, I am not using jQuery on this project... hahah

**Comment by ryangjchandler** [comment]
> @ryangjchandler Ahhh yes... my bad, I am not using jQuery on this project... hahah

Yeah, Alpine will be giving you a native browser event as `$event`, not a jQuery event.

**Comment by MarcGodard** [comment]
@ryangjchandler Maybe you can help me figure out how to set `dataTransfer.dropEffect = 'copy'` so dropping the file doesn't open the file in the browser?

**Comment by MarcGodard** [comment]
NM... figured it out

**Comment by boustanihani** [comment]
> how to set `dataTransfer.dropEffect = 'copy'`

Could you please share how you figured this out :) ?

**Comment by MarcGodard** [comment]
@boustanihani too long ago and and I no longer use Alpine. Sorry
