### ISSUE TITLE
Dropdown menu does not work with x-for

### ISSUE THREAD

**Issue by mccarlosen** [alpinejs/alpine#1067]
I have created a "PlayGround" with Livewire and alpine to display a search filter and share the problem.

Here I show what happens:

![image](https://s2.gifyu.com/images/ezgif.com-gif-makera41619467ba84b96.gif)

You can take a look around here:
https://laravelplayground.com/#/snippets/e7f2737f-ec89-4edb-989f-5f7bb8d9028d

**Comment by KevinBatdorf** [comment]
You need a unique `:key` value. This should never be the the `index`. 

(I know the docs say this, but the docs are wrong)

Use this:
```html
<template x-for="(n, index) in results" :key="n.id">
```

**Comment by mccarlosen** [comment]
@KevinBatdorf, sorry but I did the following tests:
- I changed the id of the items in the array to a longer integer
- I changed the `:key="index"` to `:key="n.id"`
- I changed `x-for="(n, index) in results"` to `x-for="n in results"`

However it still does not work. Please check the playground:
https://laravelplayground.com/#/snippets/e4f80bc6-0c1a-4354-a157-aa6b1c0898ea

Sometimes I get this error:
![Error](https://s2.gifyu.com/images/ezgif.com-gif-maker---2.gif)

**Comment by KevinBatdorf** [comment]
Just to clarify, the error shows but the functionality now works, right? 

I can't remember the solution to this but let me get back to you, or maybe someone else can chime in.

**Comment by mccarlosen** [comment]
No, it still doesn't work :(

**Comment by KevinBatdorf** [comment]
The drop downs don't open? They are opening for me.

I think the issue is with the nested component trickery you have there. That definitely won't work. There might be another solution though. Let me try something else.

**Comment by mccarlosen** [comment]
When loading the first time it works, then when filtering and then resetting the dropdown of the first item it stops working, even the element is removed from the DOM.

**Comment by KevinBatdorf** [comment]
Well, that's working when I do it. Are you sure you have the right version open and saved?

https://user-images.githubusercontent.com/1478421/107062216-a52c3980-680b-11eb-9508-5c149fd400dc.mp4

**Comment by KevinBatdorf** [comment]
For the dropdowns, you're better off firing an event that the main component listens for, like `$dispatch('dhow-dropdown', n.id)` and  `$dispatch('edit', n.id)` and then in `x-show="open == n.id"`

**Comment by mccarlosen** [comment]
@KevinBatdorf, This is crazy. When you filter with title 3 or title 4 everything works great. but when you filter with title 1 or title 2 everything collapses:

https://user-images.githubusercontent.com/8524361/107064961-2ce15c00-67aa-11eb-8107-5b5df5b36375.mp4

**Comment by mccarlosen** [comment]
> For the dropdowns, you're better off firing an event that the main component listens for, like `$dispatch('dhow-dropdown', n.id)` and `$dispatch('edit', n.id)` and then in `x-show="open == n.id"`

I will try this way anyway, but that error is intriguing... :/

**Comment by KevinBatdorf** [comment]
Hmm, yeah. It might have something to do with how Alpine looks ahead. Like it's losing the reference to the events or something. Maybe. 

Probably better if you can refactor to not have the nested `x-data` as it's finicky. 

But it is interesting so I will try to look deeper at over the weekend.

cc @SimoTod you might be interested in this sort of unexpected behavior

**Comment by mccarlosen** [comment]
> Hmm, yeah. It might have something to do with how Alpine looks ahead. Like it's losing the reference to the events or something. Maybe.
> 
> Probably better if you can refactor to not have the nested `x-data` as it's finicky.
> 
> But it is interesting so I will try to look deeper at over the weekend.
> 
> cc @SimoTod you might be interested in this sort of unexpected behavior

Yeah, it's like losing the reference to the elements or something. I will be aware of any news. Thank you.

**Comment by SimoTod** [comment]
Really weird. I'll try to have a look tomorrow. 👍

**Comment by mccarlosen** [comment]
Hey @KevinBatdorf, @SimoTod.

I have solved the problem by placing a parent element with the `wire:ignore` directive. Because the problem is that livewire re-renders the template and that's why alpine loses focus.

```html
<div wire:ignore>
  <div x-show="results.length === 0">
    <div class="is-flex is-align-items-center is-justify-content-center has-background-white-ter py-2">
      <div class="has-text-grey-light">Not found</div>
    </div>
  </div>
  <template x-for="n in results" :key="n.id">
  <!-- .... -->
  </template>
</div>
```

My playground:
https://laravelplayground.com/#/snippets/a452f1b2-568a-4035-bbc6-b3fd7b5c96e6

**Comment by codeverseproo** [comment]
I ran into a similar issue when implementing dropdowns with x-for loops. The solution I found was to ensure each dropdown has a unique identifier within the loop context.

Instead of sharing a single state variable across all iterations, you can use a more specific approach:

```html
<div x-data="{ openDropdowns: {} }">
  <template x-for="(item, index ) in items" :key="index">
    <div>
      <button @click="openDropdowns[index] = !openDropdowns[index]">
        Toggle Menu
      </button>
      <div x-show="openDropdowns[index]" @click.away="openDropdowns[index] = false">
        Dropdown content
      </div>
    </div>
  </template>
</div>
```

This approach maintains separate state for each dropdown instance within the loop.

I've documented a complete implementation pattern for Alpine.js dropdowns that addresses this and other common challenges: https://beyondit.blog/blogs/8KB-of-Magic-How-Alpine-js-Creates-Perfect-Dropdowns-for-Static-Sites

The key insight was treating the open state as an object indexed by unique identifiers rather than a single boolean value.
