### ISSUE TITLE
Video Object plays without playing...

### ISSUE THREAD

**Issue by MarcGodard** [alpinejs/alpine#1071]
I have the following:

```html

<div x-show="['video/mp4', 'video/ogg', 'video/webm'].includes($store.page.pageDatum.fileType)" class="col-span-3 aspect-w-16 aspect-h-9">
  <video class="max-h-full w-full" controls x-bind:src="$store.page.pageDatum.fileLink" x-bind:type="$store.page.pageDatum.fileType"></video>
</div>
```

However, the player shows up, but its not playing as autoplay is off, but it is playing in the background. Could it be playing in some sort of shadow dom? Does the same thing in firefox and chrome.

Or am I doing something wrong?

**Comment by ryangjchandler** [comment]
@MarcGodard Have you got a CodePen or fiddle that reproduces the problem in an isolated manner?

**Comment by MarcGodard** [comment]
@ryangjchandler Not yet, still fiddling with it.

**Comment by MarcGodard** [comment]
I made this: https://jsfiddle.net/21zmw49a/

But i cannot reproduce the issue...

**Comment by MarcGodard** [comment]
Figured out the issue... I had a hidden image element that used the same source link...

https://jsfiddle.net/21zmw49a/1/

The image would still load the video in the source...
