### ISSUE TITLE
what is x-state and x-description?

### ISSUE THREAD

**Issue by mouyong** [alpinejs/alpine#1078]
this is answer: https://github.com/tailwindlabs/tailwindcss/issues

**Comment by HugoDF** [comment]
Closing this for now, feel free to open a new issue if you're hitting a bug or creating a discussion for questions/feature requests

**Comment by jmonday** [comment]
For others who are curious here's a link to Adam's answer:
https://github.com/tailwindlabs/tailwindcss/issues/3545#issuecomment-775114586
