### ISSUE TITLE
devtools disabled on Production Mode ?

### ISSUE THREAD

**Issue by devhoussam** [alpinejs/alpine#1079]
How I can disabled Alpine.js devtools on Production Mode?

**Comment by ryangjchandler** [comment]
> How I can disabled Alpine.js devtools on Production Mode?

@devhoussam Alpine doesn't have anything to specify "production mode" like Vue and others do.

**Comment by devhoussam** [comment]
> > How I can disabled Alpine.js devtools on Production Mode?
> 
> @devhoussam Alpine doesn't have anything to specify "production mode" like Vue and others do.

thank you

**Comment by HugoDF** [comment]
Quick note for anyone else reporting devtools issues here.

The devtools are a community project that's not directly affiliated with Alpine (although some of the maintainers of that project help over here), so please report issues on that repository directly. https://github.com/alpine-collective/alpinejs-devtools
