### ISSUE TITLE
Alpine.js not working in Edge

### ISSUE THREAD

**Issue by malikkrehic** [alpinejs/alpine#109]
Hello, 

I've been experimenting with Alpine.js today and it looks really nice, but when I tried to test it in Edge and Internet Explorer it didn't look like it was working. I tried the simplest example from the docs, but it didn't work. 

I have added polyfills as described in docs. 

Here is the message that I've got in the console. 

```
SCRIPT1028: SCRIPT1028: Expected identifier, string or number
alpine.js (1,5743)
```

Tested code example:

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        <script src="https://polyfill.io/v3/polyfill.min.js?features=MutationObserver%2CArray.from%2CArray.prototype.forEach%2CMap%2CSet%2CArray.prototype.includes%2CString.prototype.includes%2CPromise%2CNodeList.prototype.forEach%2CObject.values%2CReflect%2CReflect.set"></script>
        <script src="https://cdn.jsdelivr.net/npm/proxy-polyfill@0.3.0/proxy.min.js"></script>
        <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v1.9.2/dist/alpine.js" defer></script>
        <link href="https://fonts.googleapis.com/css?family=Fira+Sans+Condensed:400,500,600,700&display=swap" rel="stylesheet">
    </head> 
    <body>
        <div x-data="{ open: false }">
            <button @click="open = true">Open Dropdown</button>
        
            <ul
                x-show="open"
                @click.away="open = false"
            >
                Dropdown Body
            </ul>
        </div>
    </body>
</html>
```

**Comment by TomS-** [comment]
I'm also having this issue. Edge in my opinion is a must support, IE11 not so much.

**Comment by SimoTod** [comment]
@malikkrehic (or any other windows user) 

Could you check if https://codepen.io/SimoTod/full/ExaGbMr works correctly with Edge please?
If it works, I'll draft a PR and see what Caleb and the others think.

Personally I think we should officially support, at least, the latest 2 versions of Edge.

I can't double check by myself since I don't use windows and I can only install the latest version based on chromium on my mac (I assume you were testing one of the previous versions on Windows 10).

Thanks.

**Comment by the94air** [comment]
I am using Edge v44.17763.1.0 and the demo is working perfectly.

**Comment by SimoTod** [comment]
Thanks @the94air

**Comment by ajgagnon** [comment]
Wouldn't be for long as I believe Edge is rolling out it's chromium browser in the next few months automatically.
