### ISSUE TITLE
Conflict with Chrome extension

### ISSUE THREAD

**Issue by joedixon** [alpinejs/alpine#110]
I use a Chrome extension called [WhatFont](https://chrome.google.com/webstore/detail/whatfont/jabopobgcpjmedljpbcaablpmlmfcogm?hl=en)

This seems to be adding a spurious div to my page with no parent element. This causes an error in the console. It doesn't break anything, but it would be nice to get rid of the error.

<img width="470" alt="Screenshot 2020-01-19 at 20 52 33" src="https://user-images.githubusercontent.com/3438564/72688318-bec5ea80-3afd-11ea-8355-143cd7124610.png">

I have done some digging in the code and I think it can be solved by adding an extra check when setting up the `MutationObserver` as below:

```
if (node.nodeType !== 1) return

// ADD THIS EXTRA CHECK TO ENSURE THE NODE HAS A PARENT
// Check the node has a parent
if (!node.parentElement) return;

// Discard any changes happening within an existing component.
// They will take care of themselves.
if (node.parentElement.closest('[x-data]')) return
```

But I've never used this class before and only just started dabbling with the framework so wanted to run it by you first in case there is anything that this could break.

Lmk - happy to submit a PR if you think the solution works.

Thanks,
Joe

**Comment by calebporzio** [comment]
Should be fixed in the next release. Re-open if not.
