### ISSUE TITLE
Error needing appropriate loader

### ISSUE THREAD

**Issue by codedge** [alpinejs/alpine#112]
Hi,

for a current project I built with [Statamic](https://statamic.dev/) I get the following error when running `npm run dev`:  
```js
ERROR in ./node_modules/alpinejs/dist/alpine.js
Module parse failed: Unexpected token (1:5861)
You may need an appropriate loader to handle this file type.
| !function(e,t){"object"==typeof exports&&"undefined"!=typeof...
```
.

**package.json**
```js
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "cross-env": "^5.1",
        "laravel-mix": "^2.0"
    },
    "dependencies": {
        "alpinejs": "^1.9.3",
        "axios": "^0.19.1",
        "feather-icons": "^4.25.0",
        "tailwindcss": "^1.1.4"
    }
}
```

**bootstrap.js**
```js
// AlpineJS
import Alpine from 'alpinejs'
```

**webpack.mix.js**
```js
const mix = require('laravel-mix');

let resources = [
    'resources/js/site.js',
];

// Add fathom analytics only in production
if(mix.inProduction()) {
    resources.push('resources/js/fathom-analytics.js');
}

mix.js(resources, 'public/js/site.js');

const tailwindcss = require('tailwindcss');
mix.sass('resources/sass/site.scss', 'public/css')
    .options({
        processCssUrls: false,
        postCss: [ tailwindcss('./tailwind.config.js') ],
    })

if (mix.inProduction()) {
    mix.version();
}
```

Any idea what **loader** may be missing? 

**UPDATE**

The error only occurs in version > `1.9.0` - `1.9.1` is the first version that fails. I installed version `1.9.0` and all works flawlessly.

Any idea if there was a change due to loading the code?

Thanks!

**Comment by calebporzio** [comment]
So, I believe that was the first tagged release to include code with "computed property names": https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Computed_property_names

https://github.com/alpinejs/alpine/compare/v1.9.0...v1.9.1#diff-a5a5c10ce61a46ccc5fed18dc812b5ebR40

Maybe try adding this syntax to your build and see if it breaks it, then we know that was the culprit and can revert to a more widely supported syntax. But it's an ES6 feature, and we use babel so I'm not sure why it doesn't work.

Thanks for the thorough issue. Let me know.

**Comment by codedge** [comment]
>adding this syntax to your build

What syntax do you mean? Clickin this link `v1.9.0...v1.9.1diff-a5a5c10ce61a46ccc5fed18dc812b5ebR40` leads to some `There isn’t anything to compare` message.

**Comment by BrandonSurowiec** [comment]
@codedge Try this link: https://github.com/alpinejs/alpine/compare/v1.9.0...v1.9.1

**Comment by SimoTod** [comment]
Hi @codedge 

Short answer: The next release which will be tagged soon should compile correctly without any other changes.

Long answer: The current bundle has some ES6 feature that are not well understood by laravel mix. 
If you want to use Alpine v1.9.1-5, you need to include `babel-loader` in your webpack.mix configuration.

Before the js call:
```js
mix.webpackConfig({
  module: {
    rules: [{
      test: /\.js?$/,
      use: [{
        loader: 'babel-loader',
        options: mix.config.babel()
      }]
    }]
  }
```

**Comment by rzenkov** [comment]
Current laravel build uses `"laravel-mix": "^5.0.1"`  and works fine with default config.

**Comment by codedge** [comment]
Yes, with an update of Laravel Mix the issue is gone. Either with version 4 or 5 of mix, both works in connection with the current `1.9.5` of AlpineJs. :+1: 

So I am back on the Alpine :train2: Thanks for the help.
