### ISSUE TITLE
After Livewire requests, "resize" and "away" events duplicate

### ISSUE THREAD

**Issue by zaandr** [alpinejs/alpine#1122]
**On page load**

![image](https://user-images.githubusercontent.com/45313396/108705281-c54f3e80-7515-11eb-9dd4-d19e7ee4e145.png)

**After liwewire requests**

![image](https://user-images.githubusercontent.com/45313396/108705550-25de7b80-7516-11eb-91ca-9e7fbeffe878.png)

**Comment by ryangjchandler** [comment]
I think this will be fixed with #1058.

**Comment by calebporzio** [comment]
This is now fixed in the latest version of Alpine: v2.8.1 - THANKS!
