### ISSUE TITLE
Conditionally x-transition classes not applied

### ISSUE THREAD

**Issue by dorinniscu** [alpinejs/alpine#1124]
I am trying to add conditionally x-transition classes for a carousel but it is interpreted as string instead on expression or object

**Left direction**
x-transition:enter="transition ease-in-out duration-300 transform"
x-transition:enter-start="translate-x-full"
x-transition:enter-end="translate-x-0"
x-transition:leave="transition ease-in-out duration-300 transform"
x-transition:leave-start="translate-x-0"
x-transition:leave-end="-translate-x-full"

**Right direction**
x-transition:enter="transition ease-in-out duration-300 transform"
x-transition:enter-start="-translate-x-full"
x-transition:enter-end="translate-x-0"
x-transition:leave="transition ease-in-out duration-300 transform"
x-transition:leave-start="translate-x-0"
x-transition:leave-end="translate-x-full"

**Conditionally classes**
x-transition:enter="transition ease-in-out duration-300 transform"
x-transition:enter-start="{ 'translate-x-full': direction === 'left', '-translate-x-full': direction === 'right' }"
x-transition:enter-end="{ 'translate-x-0': direction === 'left', 'translate-x-0': direction === 'right' }"
x-transition:leave="transition ease-in-out duration-300 transform"
x-transition:leave-start="{ 'translate-x-0': direction === 'left', 'translate-x-0': direction === 'right' }"
x-transition:leave-end="{ '-translate-x-full': direction === 'left', 'translate-x-full': direction === 'right' }"

**Comment by ryangjchandler** [comment]
@dorinniscu `x-transition` doesn't support object syntax like `:class` does.

**Comment by dorinniscu** [comment]
Thanks @ryangjchandler. I will try with a function then.

**Comment by iansinnott** [comment]
> use a function that conditionally returns a string.

Is this implemented? I've tried this and the function was never called.

**Comment by dorinniscu** [comment]
@iansinnott I tried it too. Indeed it returns a string instead of executing the function.

**Comment by ryangjchandler** [comment]
> @iansinnott I tried it too. Indeed it returns a string instead of executing the function.
> 
> x-transition:enter="transition()"

Sorry, this is my bad. I completely forgot we were talking about `x-transition` - in my head were talking about `x-bind:class` (it was a busy day)!

The `x-transition` directives only support strings, similar to `x-model`. Whatever value is in the directive will be used for the transitions themselves.

**Comment by dorinniscu** [comment]
@ryangjchandler Don`t worry. I fixed it using another transition effect that does not require directional conditions :)

**Comment by KevinBatdorf** [comment]
Try this: `:x-transition:enter="transition()"`

**Comment by dorinniscu** [comment]
@KevinBatdorf It works. Thanks. I did not think to bind it.

**Comment by dorinniscu** [comment]
I am closing it since we have the function option.

**Comment by jhealey5** [comment]
@dorinniscu Not sure if it's a recent update but this doesn't seem to work? https://codepen.io/jhealey5/pen/LYLrVax
