### ISSUE TITLE
x-if and x-show don't seem to update the dom like it should. Not seeing elements be removed when the conditions are false.

### ISSUE THREAD

**Issue by antboy2020** [alpinejs/alpine#113]
While using x-if and x-show the elements don't seem to be getting removed from the dom. Only happening when dealing with an element assigned to a css-grid section. Not sure if it is a high priority issue current fix is to add a css media query and set display to none.

**Comment by shadoWalker89** [comment]
For me the x-show works but the x-if does not
I'm using v1.9.3 from the cdn

Also i'm getting this error

```
index.js:63 Uncaught TypeError: Cannot read property 'closest' of null
    at index.js:63
    at NodeList.forEach (<anonymous>)
    at MutationObserver.observe.childList (index.js:57)
```

And this is my source code

```php
<div class="inline fields" x-data="{open: false}">
    <div class="field">
        <label for="send_a_copy">@lang('emails.send_a_copy')</label>
    </div>

    <div class="field">
        <div class="ui radio checkbox">
            {{ Form::radio('send_a_copy', "", empty($email->send_a_copy), ['class' => 'hidden']) }}
            <label>@lang('common.no')</label>
        </div>
    </div>

    <div class="field">
        <div class="ui radio checkbox">
            {{ Form::radio('send_a_copy', \App\Models\Email\Email::SEND_CC, null, ['class' => 'hidden']) }}
            <label>@lang('emails.send_a_copy_options.cc')</label>
        </div>
    </div>

    <div class="field">
        <div class="ui radio checkbox">
            {{ Form::radio('send_a_copy', \App\Models\Email\Email::SEND_BCC, null, ['class' => 'hidden']) }}
            <label>@lang('emails.send_a_copy_options.bcc')</label>
        </div>
    </div>
    
    <div class="ten wide field" x-show="open">
        {{ Form::text('copy_emails') }}
    </div>
</div>
```

This is some blade code to show radio buttons.
I'm using the `x-data` at the top and then an `x-show` at the bottom with a input text

**Comment by rzenkov** [comment]
`x-if` works only with `<template>` tag, when condition is truly alpine attach template content just after template tag, if it falsy - removes attached content.
`x-show`  supposed to switch `display:none|block`

both works fine for me @1.9.3.  Which case not works for you?

**Comment by shadoWalker89** [comment]
@rzenkov like i mentionned x-show works fine for me.
The x-if didn't because i wasn't using the `<template>`, i didn't read the readme, because i thought that x-if should work like in vue.

**Comment by calebporzio** [comment]
Added link to docs from error
