### ISSUE TITLE
Problem (?) where @click.away doesn't fire.

### ISSUE THREAD

**Issue by phijma** [alpinejs/alpine#1132]
I posted this issue on the Spruce repo: https://github.com/ryangjchandler/spruce/issues/135

I'm not sure if this is a bug or not. But shouldn't the close method be fired as well in this example if you click "Open modal"?
https://codepen.io/phijma/pen/qBqpeNY
Because as @ryangjchandler mentioned on the other issue: you are clicking "away" from the `<p>` element.

**Comment by SimoTod** [comment]
Yes, the event fires and the modal closes has expected. Are you expecting a different behaviour?

**Comment by phijma** [comment]
> Yes, the event fires and the modal closes has expected. Are you expecting a different behaviour?

Please read my issue more precisely. As I mentioned: it should possibly already fire when you click the “Open modal” button. Besides from clicking “away” from the actual modal.

**Comment by SimoTod** [comment]
Ha, I think I understood what you mean. You are talking about the first time, right? In that case, no. Alpine doesn't handle the away event if the element is not visible. See https://github.com/alpinejs/alpine/blob/master/src/directives/on.js#L22

This is to avoid that, for example, a modal would close immediately after being opened which would defeat the whole purpose of the modifier.

**Comment by SimoTod** [comment]
> > Yes, the event fires and the modal closes has expected. Are you expecting a different behaviour?
> 
> Please read my issue more precisely. As I mentioned: it should possibly already fire when you click the “Open modal” button. Besides from clicking “away” from the actual modal.

It does fire when the modal is visible.

**Comment by phijma** [comment]
> I think I understood what you mean. You are talking about the first time, right? In that case, no. Alpine doesn't handle the away event if the element is not visible. See https://github.com/alpinejs/alpine/blob/master/src/directives/on.js#L22
> 
> This is to avoid that, for example, a modal would close immediately after being opened which would defeat the whole purpose of the modifier.

Thank you for the clear answer! :-)
