### ISSUE TITLE
Double firing click events on labels wrapping radio inputs

### ISSUE THREAD

**Issue by Rio517** [alpinejs/alpine#1149]
I noticed an odd issue on what is essentially `<label><input type="radio" /></label> `.  Clicking on such a label, click events are triggered twice.  If one removes the radio input, the click event is just triggered once.

Example code pen: https://codepen.io/Rio517/pen/GRNdVaw?editors=1000

Code from above pen:
```
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.8.1/dist/alpine.min.js" defer></script>

<h2>Example Double Click</h2>

<form action="" x-data="{count: 0}">
  <h3>Count <span x-text="count"></span></h3>
  <label for="radio-one" @click="count++"> 
    Label wrapping radio input - click to increment fires 2x
    <input type="radio" name="field" id="radio-one" />
  </label>
  <label for="radio-two" @click="count++"> 
    Label without radio - click to increment fires just once
  </label>
</form>
```

Thanks for all the hard work on such a great library!

**Comment by SimoTod** [comment]
That's the standard behaviour. You click on the label (first click), as per spec the browser triggers a click on the radio input. Because the radio input is nested inside the label, click bubbles up and triggers the listener a second time.
Alpine doesn't implement events, it uses the browser native ones.

**Comment by KevinBatdorf** [comment]
You can also stop that behavior by adding `.stop` to the radio

```html
<input @click.stop type="radio" name="field" id="radio-one" />
```

but in this case, you're probably better off not putting a listener on the label instead.

**Comment by Rio517** [comment]
Thanks for clarifying

**Comment by SimoTod** [comment]
> You can also stop that behavior by adding `.stop` to the radio

You probably don't want to do that because if you click exactly on the input, the listener won't be fired. 

Personally I would move the listener on the input itself to cover all scenarios.

**Comment by KevinBatdorf** [comment]
Oh nice. Didn't realize that. I would have expected it to bubble up.
