### ISSUE TITLE
[discuss] Intresting behavior (unattended?)

### ISSUE THREAD

**Issue by rzenkov** [alpinejs/alpine#115]
I had some experiments with events and found that `@event.window` - works fine with CustomEvent.
Are we have vue simple bus in a box?

```html
  <div x-data="scope()">
    <button @click="$emit('close')">
      Close from other component
    </button>
  </div>
  
  <div x-data="{show:false}" @app:close.window="show=false">
    <button @click="show = true" >Open</button>
    <div x-show="show">
      <h2>Modal content</h2>
    </div>
  </div>
```

```js
function scope(){
  return {
    $emit(name, value=null){
      window.dispatchEvent(
        new CustomEvent(`app:${name}`, {detail: value})
      )
    }
  }
}
```
[JsBin](https://jsbin.com/fafosig/edit?html,js,output)

How about adding `$emit` into componet scope?

**Comment by calebporzio** [comment]
So, the latest release has a new magic function called `$dispatch`.

You can feel free to use it in any event listener: `x-on:click="$dispatch('close-modal')"`, and it will fire a `new CustomEvent`. 

I will document soon.

Great suggestion

**Comment by rzenkov** [comment]
Thanks, with bubbles magic it works even better.
Now we have inter-component messaging in a box.

**Comment by dsazup** [comment]
hey @calebporzio, how could I get the example in first message work with $dispatch? 🤔 seems like  below does not work.

```
    <div>
        <button @click="$dispatch('close')">
            Close from other component
        </button>
    </div>

    <div x-data="{show:false}" @close="show=false">
        <button @click="show = true" >Open</button>
        <div x-show="show">
            <h2>Modal content</h2>
        </div>
    </div>
```

**Comment by HugoDF** [comment]
You probably want to try `@close.window`, in your examples the `@close` listener is not in the part of the DOM tree where the event would bubble up to it.
