### ISSUE TITLE
x-bind:class not updating. 

### ISSUE THREAD

**Issue by carltongibson** [alpinejs/alpine#1161]
Hi. Thanks for the great library. Having a lot of fun with it! 

I have an issue such that `x-bind:class` does not seem to be working [as described](https://github.com/alpinejs/alpine#x-bind): 

> For classes, you pass in an object whose keys are class names, and values are boolean expressions to determine if those class names are applied or not.
> 
> For example: `<div x-bind:class="{ 'hidden': foo }"></div>`

From this I'm expecting the `class` attribute of the `div` to have the `hidden` class added and removed as the value of `foo` changes. 

That doesn't seem to be happening. [Examples available in this CodePen](https://codepen.io/carltongibson/pen/GRNBxKV?editors=1100).

## `x-bind:class` Not working

```html
<div x-data="{ state: 'off' }"> 
  <p>Using x-bind. This should update but doesn't.</p>
  <p>State: <span x-text="state"></span></p>
  
  <button x-on:click="state = !state">Toggle</button>
  
  <div x-bind:class="{ 'blue': state == 'on' }">@class</div> 
</div>
```

Here I'm expecting the `.blue` class to toggle on the final nested `div` as the `button` is pressed. Whilst `state` toggles, the class is never set. 

Have I misunderstood (quite possible 🙂) or is this an issue in `x-bind:class`? 

## Alternative approach

Perhaps not the most elegant (suggestions very welcome!), using a little more JS this can be worked around: 

```html
<script>
    function stateObj() {
        return {
            active: false,
            toggle() { 
                this.active = !this.active;
                this.setClass()
            },
            setClass() {
              if (this.active) {
                this.$refs.targetDiv.classList.add('blue')
              } else {
                this.$refs.targetDiv.classList.remove('blue')                
              }              
            }
        }
    }
</script>

<div x-data="stateObj()"> 
  <p>Another way, using more JS.</p> 
  <p>State: <span x-text="active"></span></p>
  
  <button x-on:click="toggle">Toggle</button>
  
  <div x-ref="targetDiv">@class</div> 
</div>
```

Here the `targetDiv` has the `.blue` class toggle as expected. 

Is this the required way to do it? (Is there a nicer way? 😄)

[Both examples are in the CodePen](https://codepen.io/carltongibson/pen/GRNBxKV?editors=1100)
This using (latest) version 2.8.1. 

Thanks again! 🏅

**Comment by KevinBatdorf** [comment]
`x-on:click="state = !state"` when state is `off` will not switch to `on` which clicked, but probably `false` since a string is truthy

**Comment by carltongibson** [comment]
Super! Thank you. What a noob. Doh 😀

Correct example works as expected: 

```html
<div x-data="{ state: false }"> 
  <p>Using x-bind. This should update but doesn't.</p>
  <p>State: <span x-text="state ? 'on' : 'off'"></span></p>
  
  <button x-on:click="state = !state">Toggle</button>
  
  <div x-bind:class="{ 'blue': state }">@class</div> 
</div>
```

Doh. 

🎁
