### ISSUE TITLE
How to use function x-data?

### ISSUE THREAD

**Issue by TomS-** [alpinejs/alpine#117]
I noticed that the examples given shows it using the <script> inline. I tried moving this into my javascript file and it's showing that the function isn't found:
```
import Alpine from 'alpinejs';
import * as basicScroll from 'basicscroll';

function scrollText() {
    return {
        active: 1,
        init() {
            basicScroll.create({
                elem: this.$el,
                from: 'top-top',
                to: 'bottom-bottom',
                direct: true,
                inside: (i, p) => {
                    this.active = Math.ceil( 4 * ( p / 100 ) );
                },
                props: {
                    '--x': {
                        from: "0",
                        to: "100"
                    }
                }
            }).start();
        }
    }
}
```
This is my javascript and my html is as follows:
```
<div x-data="scrollText()" x-init="init()">
    <img src="" width="" height="" loading="lazy" x-show="active === 1">
    <img src="" width="" height="" loading="lazy" x-show="active === 2">
    <img src="" width="" height="" loading="lazy" x-show="active === 3">
    <img src="" width="" height="" loading="lazy" x-show="active === 4">
</div>
```

What is the best way to achieve this?

EDIT:
It's worth noting that I tried declaring the function before loading AlpineJS and nothing changed.
```
import * as basicScroll from 'basicscroll';

function scrollText() {
    return {
        active: 1,
        init() {
            basicScroll.create({
                elem: this.$el,
                from: 'top-top',
                to: 'bottom-bottom',
                direct: true,
                inside: (i, p) => {
                    this.active = Math.ceil( 4 * ( p / 100 ) );
                },
                props: {
                    '--x': {
                        from: "0",
                        to: "100"
                    }
                }
            }).start();
        }
    }
}

import Alpine from 'alpinejs';
```

**Comment by TomS-** [comment]
@SimoTod Figured it out, it's not problem with Alpine at all, it's to do with my brain. Because the script is minfied, it's renaming the function to something like c() {}. I have no idea how to avoid that.

**Comment by TomS-** [comment]
> 
> 
> Do you use webpack? It should be possible to turn it off.
> https://webpack.js.org/configuration/optimization/

I do you use webpack, it's TerserJSPlugin that is doing the minifying. I am concerned about stopping the minification because of file size. Until I know the correct solution, I have created another javascript file included after the minified file that just holds Alpine functions. I did build this originally not using Alpine but running all interactive elements where possible through Alpine seems to make sense to me.

**Comment by SimoTod** [comment]
The order is not important in this case. Alpine doesn't need to know about scrollText() until after the DOM load event.
The issue here is webpack because by default it doese expose any function on the global context (if you google it, you'll find a lot of results and solutions, for example https://stackoverflow.com/questions/52031389/webpack-calling-javascript-functions-at-window-level).

**Comment by TomS-** [comment]
@SimoTod That makes so much sense, my brain today. Thank you.

**Comment by bluebrown** [comment]
You may also have to attach it to the window object. Depending on how your project is set up.

```typescript
interface IPageState {
  gridview: boolean,
  items: any[]
};

(window as any).state = function() {
  return {
    gridview: true,
    items: [],
  } as IPageState
};
```
