### ISSUE TITLE
Suggestions: Demo & Logo

### ISSUE THREAD

**Issue by Shuunen** [alpinejs/alpine#119]
Hi there,

Thanks for this great lib, can't wait to use it on my next project 😄 

I made a demo here mixing Alpine & Tailwind together : https://codepen.io/Shuunen/pen/oNgQQgm

These two libs work really great together 🎉 

It could be nice to have a link to a demo/example/playground in the readme, you can use this one  or fork it to make a better one.

Also it would be nice to identify this lib with a logo IMHO.

**Comment by ryatkins** [comment]
@Shuunen - this looks very nice and helped me debug and issue I was having.

You could even add a transition to your modal by adding the following:

`      x-transition:enter="transition ease-out transition-slow"
        x-transition:enter-start="opacity-0 transform"
        x-transition:enter-end="opacity-100 transform scale-100"
        x-transition:leave="transition ease-in transition-slow"
        x-transition:leave-start="opacity-100 transform scale-100"
        x-transition:leave-end="opacity-0 transform"`

I believe `transition-slow` and variants are being moved to `duration-300` and variants when Tailwind v1.2 comes out per this [PR](https://github.com/alpinejs/alpine/pull/99)

**Comment by the94air** [comment]
I would suggest the demo to be responsive on phones too. I can help with this if approved.

**Comment by Shuunen** [comment]
@ryatkins glad it helped 👍 
@the94air you're right result on phone is not great, don't hesitate to fork my codepen and improve it 🙂

**Comment by bennash** [comment]
Here's a codepen I just published. It demos a few pieces of ui made with alpinejs and tailwindcss: 

Tailwind CSS & Alpine JS page example with Dropdown Menu, Page Scroll Detection, Modal Menu with Escape key function
https://codepen.io/bennash/pen/mdyamBz

**Comment by the94air** [comment]
Here you go @ryatkins https://codepen.io/the94air/pen/WNbLXwG

**Comment by Shuunen** [comment]
@calebporzio why did you close this suggestion ?

**Comment by minemindmedia** [comment]
How can I prevent body scroll when the modal is open?
