### ISSUE TITLE
ReferenceError in console while functioning correctly

### ISSUE THREAD

**Issue by zepfietje** [alpinejs/alpine#1227]
I'm using a variable in an Alpine component to set a css class.
Everything works correctly, but the console does show a ReferenceError related to this variable.

To make it easier to understand the problem, just head over to https://picci.app/9lqzjlxkxujgjv5m and follow the instructions. 😄

The console should show the error quite clearly.
However, let me know if you need additional context information to debug the problem.

**Comment by KevinBatdorf** [comment]
Instead of putting `x-data` on the `<template>` tag wrap it in a `<div>` instead:

```html
<div x-data="{show: false}" x-init>
  <template x-if="show">

**Comment by SimoTod** [comment]
You defined x-data on a template tag having x-if, try to move it to the child element or to a common ancestor instead.
When x-if resolves to true, the content (which has reference to the theme variable) is cloned outside the x-if. The cloned element still has that directive attribute and, being inside a common ancestor having a different x-data, it triggers the error every time Alpine refreshed.
It's a bit complicate to write but to simplify
```html
<template x-html="{foo: bar}"><div x-text="foo"></div></template>
```
becomes
```html
<template x-html="{foo: bar}" x-if="true"><div x-text="foo"></div></template>
<div x-text="foo"></div> <!-- This element cannot see x-data anymore so, if it's inside a different component, it will triggers an error on refresh -->
```

P.s. Better to use discussion when it's not an Alpine bug. People will reply anyway

**Comment by zepfietje** [comment]
I thought this actually was an Alpine bug, so that's why I opened an issue.
Thanks for the explanation!
