### ISSUE TITLE
x-on:click does not render the declared value in x-data using pagination

### ISSUE THREAD

**Issue by luanfreitasdev** [alpinejs/alpine#1242]
**PHP: 8.0.0
Laravel 8.35.1
Livewire: 2.4.2**
https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js

_Using livewire with pagination of a table, when clicked on x-on: the click value receives or the value declared in x-data. This works on the first page.

When we are on the second page, when clicking (for example at id 14) the value returned in x-on: click is the same as id 4 and so on.

works when all results are displayed!_

html
```html
<div
      x-data="{ value: '<span style=\'border-bottom: dotted 1px;\'>Example text</span>' }">
      <button
      x-on:click="value = returnValue(1, 'Example text', 'name');"
      x-html="value"
      ></button>
</div>
```

Javascript function
```
function returnValue(id, value, field) {
        console.log(id, value, field)
        return '<input value=\''+value+'\' class=\'form-control\' @keydown.enter=updateEditableInput($event,'+id+',\''+field+'\') >';
    }

function updateEditableInput(event, id, field) {
        window.livewire.emit('editInput', {
            id: id,
            value: event.target.value,
            field: field
        })
}
```

**Comment by ootri** [comment]
Seems like it's related to https://github.com/livewire/livewire/issues/2046. Try adding: `wire:key="{{ $something->id }}"`

**Comment by luanfreitasdev** [comment]
Worked perfectly 

Thanks @ootri
