### ISSUE TITLE
x-for is not working when x-data is filled from api calls

### ISSUE THREAD

**Issue by muhsenmaqsudi** [alpinejs/alpine#125]
hi, thanks for this amazing minimal framework, i have ran into a problem, i am creating a dynamic select box that depends on the selection of the first select box, first a province will be selected and then the cities of that province will be loaded in the second select box, the problem is that x-for feature is not working correctly after i have filled the cities array in x-data object,
```html
<div x-data='{ provinceId: "", cityId: "" ,cities: []}'>
    <select x-model="provinceId"
            @change="fetch(`cities/${provinceId}`)
                            .then(response => response.text())
                            .then(response => cities = response)"
    >
        @foreach($cities as $city)
            <option
                value="{{ $city['id']  }}"
            >{{ $city['name']  }}</option>
        @endforeach
    </select>
    <div x-text="cities"></div>
    <select x-model="cityId">
        <template x-for="city in cities" :key="city">
            <option x-text="city.name"></option>
        </template>
    </select>
</div>
```
and this is the error i'm getting

```js
app.js:96 Uncaught TypeError: d.forEach is not a function
    at u (app.js:96)
    at app.js:96
    at Array.forEach (<anonymous>)
    at x.resolveBoundAttributes (app.js:96)
    at x.updateElement (app.js:96)
    at app.js:96
    at app.js:96
    at e (app.js:96)
    at e (app.js:96)
    at e (app.js:96)
```

**Comment by stuartpullinger** [comment]
It looks to me like `cities` is overwritten with the text of the response from the API. Shouldn't it be:

```HTML
    <select x-model="provinceId"
            @change="fetch(`cities/${provinceId}`)
                            .then(response => response.text())
                            .then(response => cities = JSON.parse(response))"
    >
```
provided that your API returns a JSON array?

**Comment by muhsenmaqsudi** [comment]
> It looks to me like `cities` is overwritten with the text of the response from the API. Shouldn't it be:
> 
> ```
>     <select x-model="provinceId"
>             @change="fetch(`cities/${provinceId}`)
>                             .then(response => response.json())
>                             .then(response => cities = response)"
>     >
> ```
> 
> provided that your API returns a JSON array?

tnx yes that was the problem, this happens when you copy & paste from the alpinejs github code examples
