### ISSUE TITLE
Alpine resets last array item after unshift

### ISSUE THREAD

**Issue by theMarinac** [alpinejs/alpine#1264]
Hi,

The bug occurs when adding an element to the beginning of the array, alpine fails to render the last element

[Code pen reproducing the bug](https://codepen.io/themarinac/pen/abBQPLR)

**Comment by KevinBatdorf** [comment]
You need a unique ID (a primitive type) on the `x-for` for it to work.

**Comment by theMarinac** [comment]
Thanks a lot, Kevin! It worked 👍🏻 
Closing the issue since its resolved :)
