### ISSUE TITLE
`x-bind:class` not working in combination with class

### ISSUE THREAD

**Issue by amiranagram** [alpinejs/alpine#1267]
I'm pretty sure it's not a bug because in another project I have this working perfectly fine so don't mind me creating a bug report.

As mentioned when using `x-bind:class` in combination with just class an error occurs and it fails to combine them.

HTML:

```html
<div
    class="ml-auto h-5 w-5 transform"
    x-bind:class="{ 'rotate-90': expanded }"
>
    <i class="fas fa-chevron-right"></i>
</div>
```

Error:

![image](https://user-images.githubusercontent.com/38536188/115261081-9deea980-a133-11eb-81c9-6f15a60b4eda.png)

Alpine JS version: 2.8.2

**Comment by ryangjchandler** [comment]
@amiranagram Are you able to reproduce this problem inside of a CodePen / fiddle?

**Comment by amiranagram** [comment]
@ryangjchandler I'm afraid not. [Here](https://codepen.io/amiramisb/pen/abpaarV) is the pen, works good.

**Comment by ryangjchandler** [comment]
The screenshot of the error, it appears the `x-bind:class` has a space between the directive and the target (`class`). Are you rendering your HTML using a template engine?

**Comment by amiranagram** [comment]
@ryangjchandler Yes, Laravel Blade.

**Comment by amiranagram** [comment]
@ryangjchandler It doesn't seem to be any issues with the template engine, because I checked the compiled views and it looks fine.

**Comment by KevinBatdorf** [comment]
Something else is combining the two `class` attributes. Any change if you use the shorthand `:class`?

**Comment by SimoTod** [comment]
Can you post the html snippet from the compiled view? From the error, it doesn't seem properly formatted. Probably a missing quote or something like that and the browser is trying to rearrange it.

**Comment by amiranagram** [comment]
@KevinBatdorf same thing happens.

@SimoTod The compiled view:

```
<div
    x-data="{ expanded: false }"
    class="space-y-1"
>
    <button
        type="button"
        x-bind:class="{
            'group w-full flex items-center pl-2 pr-1 py-2 text-sm font-medium rounded-md focus:outline-none bg-white text-gray-600 hover:bg-gray-50 hover:text-gray-900': !expanded,
            'group w-full flex items-center pl-2 pr-1 py-2 text-sm font-medium rounded-md focus:outline-none bg-gray-100 text-gray-900': expanded
        }"
        x-on:click="expanded = !expanded"
    >
        <div class="mr-3 h-6 w-6 flex items-center justify-center text-gray-400 group-hover:text-gray-300">
            <?php echo e($icon); ?>

        </div>

        <?php echo e($slot); ?>


        <div
            class="ml-auto h-5 w-5 transform"
            x-bind:class="{ 'rotate-90': expanded }"
        >
            <i class="fas fa-chevron-right"></i>
        </div>
    </button>

    <div class="space-y-1" x-show="expanded" x-cloak>
        <?php echo e($menu); ?>

    </div>
</div>
```

I cannot figure out for the life of me what I'm doing wrong.

I should also note that when using `x-bind:class` without class it works fine, like at the beginning of this code snippet.

**Comment by KevinBatdorf** [comment]
It's a long shot but, just try to type out the `"` directly. Some times if you copy/paste from online you get something encoded differently. Otherwise I have no clue. If it were Alpine related I imagine it would show up in CodePen and elsewhere.

**Comment by amiranagram** [comment]
@KevinBatdorf I've tried everything and after 3 days I'm seeking help here.

Note that this is on the project level, as I previously stated it's working perfectly fine (like it should) on another project. Anybody knows any dependencies I should be aware of that could be causing this issue?

**Comment by amiranagram** [comment]
OK, first of all @KevinBatdorf @SimoTod @ryangjchandler my apologies for wasting your time. The issue was [this middleware](https://github.com/renatomarinho/laravel-page-speed/blob/master/src/Middleware/InlineCss.php) from [renatomarinho/laravel-page-speed](https://github.com/renatomarinho/laravel-page-speed) Laravel package. After disabling it everything works fine. 

Time to PR the repository 🤷‍♂️

Also I wonder if Google Pagespeed does the same. If you has this module installed let me know.
