### ISSUE TITLE
Div Modal Shown on Page Load Then Hidden Split Second Later

### ISSUE THREAD

**Issue by seanlabs** [alpinejs/alpine#1275]
I have a Laravel Jetstream application and I am using a TailwindUI modal component. I have it setup to show/hide correctly using Alpine.js, but I am having an issue where on page load I see the modal for a split second and then it is hidden like its supposed to.

Its like the page is loaded all the div's without respect for my x-show variable. Then, after the page loads a little while it then accounts for the x-show.

Is this like an order of operations things where Alpine.js is not getting loaded until the end? Any ideas on how to fix this?

**Comment by SimoTod** [comment]
X-cloak

**Comment by seanlabs** [comment]
Thanks... I originally tried that and it was working, but found out that my CSS was not pulling in x-cloak correctly. Thanks for the help.
