### ISSUE TITLE
x-model does not catch element.value changes

### ISSUE THREAD

**Issue by lupinitylabs** [alpinejs/alpine#1277]
This is more of a documentation request than an issue report.

The documentation does not seem to mention anywhere that when any script programmatically changes the value of an input that is bound to data via `x-model` by doing something like...

```javascript
document.getElementById('some-element').value = 12345
```

...AlpineJS is unable to track the change, because no event is emitted. I feel that it should be explicitly mentioned that it is crucial to have such a value assignment be followed by a manual dispatch of an event that prompts AlpineJS so sync the data:

```javascript
document.getElementById('some-element').dispatchEvent(new Event('input'))
```

It might be obvious if you are aware of that, but I cost me some time figuring out why the `x-model` attribute didn't do anything when a third party script changed the value of an input.

**Comment by yasinallana1** [comment]
I believe `x-model` reacts to event changes not the value update itself. The event for input elements is `oninput` as evident from [here](https://github.com/alpinejs/alpine/blob/d98733ee9e642ee4429412e49205aa43a0688285/src/directives/model.js#L7-L10).
So either update the JSON which will cause `x-model` to react or trigger an `oninput` event [like so](https://stackoverflow.com/a/35659572)

**Comment by ryangjchandler** [comment]
@lupinitylabs I'm not sure this is something that Alpine should document, since it's more of a JavaScript/browser caveat than an Alpine one.
