### ISSUE TITLE
browser translation not work apines.js

### ISSUE THREAD

**Issue by FuriosoJack** [alpinejs/alpine#1282]
hello you know why the components with x-text is not translated with google. I have tried to see that I cannot find that the whole page can be translated except what is in apline.js.

Thanks

**Comment by SimoTod** [comment]
I believe google translate doesn't run javascript so those dom elements will be empty.

**Comment by FuriosoJack** [comment]
I DISCOVERED THAT IT IS NOT TRANSLATED BECAUSE THE TEXT IS INSIDE THE FONT LABELS INSTEAD OF IT IS INSIDE THE INNERHTML

![image](https://user-images.githubusercontent.com/26976637/117305293-3aa78b80-ae44-11eb-8380-5966c9154fa9.png)
