### ISSUE TITLE
cannot bind to correct, after refresh x-data @entangle livewire 

### ISSUE THREAD

**Issue by coldcaphe** [alpinejs/alpine#1291]
hi. 
i'm happy to alpine with livewire for using make something.

today i got some strange action so i make this issue.

i want make is.
make viewing html relationship data with database hierachical data set all user.

same like this. (sorry for make understand. my english is....)
https://www.researchgate.net/profile/Robert-Scott-20/publication/39284446/figure/fig2/AS:669038866874389@1536522704896/Hierarchical-cluster-diagram-plotting-the-mesowear-datasets-of-H-intrans-from-Rudabanya.png

i try to this.

1. make hierachical data set for all user (on my database)
2. using AlpineJs for making accordian function for looking nice so make get every root user id from laravel livewire every request (get data from database)
3. x-data is bind with livewire using @entangle (i using "selectedUser" variable on livewire)
4. $selectedUser will get rootuser information every livewire request
3. i try to make exist on database leaf user make change to root user. and i make new root user too. 
4. after all processing is done. i check source code (chrome developer mode). is there (children node) has correct own parents information (it mean, livewire is working correct).
5. but when i toggle action with AlpineJs is not working or wrong working.
6. i thougnt. livewire work fine. but AlpineJs is not. AlpineJs x-data is don't know about change structure (same like, don't know about need to refresh node, because i make F5, force refresh after they are correct working)

so i tried make some function after livewire render method. but i cannot find a way.

sorry for make understanding. but i think this is bug. so i make this opinion.
what i need to provide information for AlpineJs make good more? please comment to me.

thanks

**Comment by calebporzio** [comment]
Sorry, this request belongs as a new discussion on the livewire repository. Please resubmit it there along with actual code snippets for people to help you. Closing this. Thanks

**Comment by coldcaphe** [comment]
> Sorry, this request belongs as a new discussion on the livewire repository. Please resubmit it there along with actual code snippets for people to help you. Closing this. Thanks


i'm newbie on github. so i don't know about sharing issue. 
anyway. i will follow your a way with sorry for make some noise on this repository. :)

**Comment by coldcaphe** [comment]
ah. im sorry. but this is problem on alpine.

so i wrote. i will make issue on livewire repository. but please check my issue on alpine side thank.

**Comment by calebporzio** [comment]
Ok, and don't open an issue on livewire, open a discussion please

**Comment by coldcaphe** [comment]
> Ok, and don't open an issue on livewire, open a discussion please

Sure.
Anyway When I first came across livewire, the screencast from you made was so great that I could understand the overall usage at once. I am so grateful.
