### ISSUE TITLE
TypeError: proxy set handler returned false for property

### ISSUE THREAD

**Issue by TomS-** [alpinejs/alpine#132]
I'm unsure if this will be fixed, or ever could be fixed without a huge refactor. But I thought I'd just check to see if it's anything I'm doing wrong. I want to store a slider in the proxy so I can access it for further functions. In this example I want to select the next slide when I fire a click `@click="nextSlide()"`. To do this I've stored the slider as data. However, it's returning the error `TypeError: proxy set handler returned false for property`. The code is:
```
let flkty = new Flickity(el, {
                    wrapAround: true,
                    prevNextButtons: false,
                    pageDots: false,
                    setGallerySize: el == this.$refs.slider ? false : true,
                    selectedAttraction: 0.01,
                    friction: 0.15
});

this.slider = flkty;
```

Thanks

**Comment by rzenkov** [comment]
I don't understand where is issue. Your code lacks of clarity.  
But here is example, all things works fine for me. Slider stored in scope, buttons uses slider.
[JsBin](https://jsbin.com/hojasov/edit?js,output)

**Comment by TomS-** [comment]
@rzenkov how bizarre, my code is pretty much the exact same as yours:
```
export function blockSlider() {
    return {
        x: 0,
        y: 0,
        sliders: [],
        init() {
            [this.$refs.slider, this.$refs.overlaySlider].forEach((el) => {
                let flkty = new Flickity(el, {
                    wrapAround: true,
                    prevNextButtons: false,
                    pageDots: false,
                    setGallerySize: el == this.$refs.slider ? false : true
                });

                this.sliders.push(flkty);
            });
        },
        changeSlide(dir) {
            this.sliders.forEach((el) => {
                if(dir == 'next') {
                    el.next(true);
                } else {
                    el.previous(true);
                }
            });
        }
    }
}
```
Might be something wrong with my build process?

**Comment by rzenkov** [comment]
Imho issue occurs not with sliders... Somewhere else..

**Comment by TomS-** [comment]
@rzenkov yup, you're right. Tried just doing a small component:
```
export function statCounter() {
    return {
        count: 0,
        init() {
            this.count = 1200;
        }
    }
}
```

**Comment by rzenkov** [comment]
try to use `this.$nextTick(()=>{/* your code */})`. 

From docs:
`$nextTick` is a magic property that allows you to only execute a given expression AFTER Alpine has made it's reactive DOM updates

**Comment by TomS-** [comment]
Strange however, it works in your example without the need to do that. I can not favom any different between your jBin and my code. It has to be my build process that is throwing it out of wack some how. In the meantime until I figure out why, I'll use $nextTick.

**Comment by rzenkov** [comment]
issue appears when you try to manipulate DOM when Alpine doing this, or something else. You simply need to split up code, one part applies scope changes, other part apply DOM changes, one part runs in function itself, other in $nextTick callback

`x-init` allows do the same thing by returning function expression, then you can split you code in init function one part in init itself, other - in callback.

```js
function scope(){
    function init(){
        // some DOM manipulations
        return () {
             // some state manipulation
        }
    }
}
```
that is why your second example works
