### ISSUE TITLE
Uncaught TypeError when using Statamic debug bar

### ISSUE THREAD

**Issue by nobleintegrations** [alpinejs/alpine#135]
I'm getting an Uncaught TypeError when using the Statamic debug bar and Apline JS. The AlpineJS functionality still works on the site, but this error shows up in the console.

<img width="433" alt="alpine-error1" src="https://user-images.githubusercontent.com/31256225/73081261-e960cc00-3e8c-11ea-80bc-fe16f16cfb07.png">

<img width="689" alt="alpine-error2" src="https://user-images.githubusercontent.com/31256225/73081262-e960cc00-3e8c-11ea-88d9-ae032d5258c0.png">

The error goes away once you disable the Statamic debug bar.

Here is a snap of the code. I've tried to rearrange the divs and simplify the structure, but still get the same error.

<img width="1229" alt="Screen Shot 2020-01-24 at 9 44 28 AM" src="https://user-images.githubusercontent.com/31256225/73081985-3b562180-3e8e-11ea-83cc-5f9d080a683b.png">

**Comment by calebporzio** [comment]
Should be fixed now
