### ISSUE TITLE
x-show doesn't work outside of x-data

### ISSUE THREAD

**Issue by iamarpitpatidar** [alpinejs/alpine#1356]
Hi, well I know it doesn't make much sense to hide something with JavaScript while we could simply add `display: none` to that, but I wanna know why does `x-show` not work if I simply give it a bool

Here is a demo markup
```css
<!DOCTYPE html>
<html>
<head>
  <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.8.2/dist/alpine.min.js" defer></script>
</head>
<body>
  <div x-show="false">
    <span>this should be hidden. no?</span>
  </div>
</body>
</html>
```

**Comment by ryangjchandler** [comment]
@iamarpitpatidar Alpine will only work inside of an `x-data` attribute. In your case, you could use:
```html
<div x-data x-show="false">

</div>
```
