### ISSUE TITLE
Alpine tripping over a random node

### ISSUE THREAD

**Issue by johnRivs** [alpinejs/alpine#136]
I must have a Chrome extension inserting something that Alpine doesn't like. The error: `Uncaught TypeError: Cannot read property 'closest' of null`. It triggers inside `listenForNewUninitializedComponentsAtRunTime`. 

The node causing problems:
```html
<div style="visibility: hidden; border: 0px; width: 0px; height: 0px; position: static; top: 0px; margin-top: 1px;">
    <div style="position: absolute; top: 0px; left: 0px; width: 1px; height: 1px; margin: 0px; visibility: hidden; border: 0px;">
        <div style="position: relative; top: 0px; left: 0px; width: 1px; height: 1px; margin: 0px; border: 5px solid rgb(0, 0, 0); padding: 0px; overflow: hidden;">
            <div style=""></div>
        </div>
        <table style="position:absolute;top:0;left:0;width:1px;height:1px;margin:0;border:5px solid #000;padding:0;" cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
```
I don't even know where in the DOM this is inserted. Can't see it in dev tools.

I know this isn't Alpine's fault but I don't know where else to ask. Any ideas other than disabling the extension causing the problem?

**Comment by thormeier** [comment]
Fixed here: https://github.com/alpinejs/alpine/pull/126 :)
