### ISSUE TITLE
Inspecting values for debugging

### ISSUE THREAD

**Issue by Wulfheart** [alpinejs/alpine#142]
Is it possible to display the current values just like in VueDebugger? This would be really helpful. Thanks in advance.

**Comment by the94air** [comment]
You mean, a DevTools for Alpine? :thinking:

**Comment by Wulfheart** [comment]
Exactly

**Comment by SimoTod** [comment]
Yeah, you can inspect it but data is a bit hidden.

In dev console (I use chrome) go to the `Elements` tab and click on the component you want to inspect (the tag with the x-data attribute). In the right column, where you see `Styles` by default, click on the `Properties` tab, open the first element and scroll down until you find the `__x` property: this is your alpine component. 

If you then open it and click on `$data` > `[[Target]]` you can see the data context.

Some times, when you refresh, chrome doesn't show anything in the properties tab (I don't know why). When it happens, you need to close the dev console and open it again.

It would be good if somebody wrote an Alpine inspector to make it more user friendly.

**Comment by Wulfheart** [comment]
An Alpine Inspector would be really cool!

**Comment by calebporzio** [comment]
Agreed

**Comment by MarcelRusu** [comment]
Is there a way through the console we can currently get components and see current values?

**Comment by Wulfheart** [comment]
@MarcelRusu Unfortunately I'm getting `undefined` when running it in the console.

**Comment by abakermi** [comment]
@Wulfheart normally you will get something like that 

![Screenshot from 2020-03-14 14-11-47](https://user-images.githubusercontent.com/60294727/76680879-cf767680-65fd-11ea-9403-8c396bcfddeb.png)

**Comment by SimoTod** [comment]
A first version of the inspector is now available at https://github.com/Te7a-Houdini/alpinejs-devtools

**Comment by ryangjchandler** [comment]
Thanks for sharing the link @SimoTod, came here to do the same thing. I'm going to close this issue now though since the new inspector / developer tools are available.

If you notice any issues or bugs with the dev tools please make an issue on the correct repository. Thanks! :)

**Comment by flappix** [comment]
Another way of easy debugging is do add this custom directive to your Alpine initialization.

```
Alpine.directive('debug', (el, { expression }, { evaluate }) => {
	el.style.backgroundColor = 'black'; 
	el.style.fontFamily = 'monospace'; 
	el.style.color = 'lightgreen'; 
	el.style.fontWeight = 'bold'; 
	el.style.padding = '0.5em'; 
	el.style.whiteSpace = 'pre'; 

	let v = evaluate (expression);
	console.log (v);
	el.textContent = JSON.stringify (v, null, 2);
});
```

Then you can use it in your code like this

```
<div x-debug="app.deeply.nested.object.value" />
```
This outputs a formatted debugging-block in the style of Laravel's dump/dd function.

**Comment by netAction** [comment]
Should be reopened as the Devtools don't look alive anymore.

**Comment by browner12** [comment]
yah, hasn't been alive for awhile. and we're probably circling the drain of it actually continuing to work, because as soon as Chrome Extensions are forced to upgrade to Manifest v3, it'll probably stop working due to it the CSP issues.
