### ISSUE TITLE
Alpine UI?

### ISSUE THREAD

**Issue by tomtev** [alpinejs/alpine#147]
When will Alpine UI (Like Tailwind UI) come ? 😬

Would love to pay for access to simple accessible Accordion, Dropdown, Tabs, Drawer, Modal ++ examples.

**Comment by TomS-** [comment]
I believe Tailwind UI will contain such things - also built using Alpine JS. Adam Wathan has already announced that.

**Comment by Wulfheart** [comment]
But TailwindUI will cost 💸

**Comment by TomS-** [comment]
> But TailwindUI will cost

And absolutely would be worth every penny

**Comment by Wulfheart** [comment]
But not suitable for Open Source applications.

**Comment by danfascia** [comment]
@Wulfheart that would depend on the license model @adamwathan chooses rather than the fact that TailwindUI will be a paid product. It can be paid to access but still licensable to use in open source projects.

**Comment by Wulfheart** [comment]
To make it clear: I'm sure that Adam Wathan's UI kit is worth its money. 
However I cannot think of a way to make it licensable for open source software. This would open the door for copycats.

**Comment by adamwathan** [comment]
You'll be allowed to use the components in open source projects, the only thing we want to make sure we prevent is people just uploading the entire thing for free and trying to distribute it maliciously or create their own UI kit that's derived from it 👍 If it's just used as part of an app that's open source that will be totally fine. Making a free or paid "Alpine UI Kit" based on it won't be allowed though.

**Comment by Wulfheart** [comment]
For me that seems like a reasonable decision.
Based on your statement I have to decide what I am going to do with my private UI kit based on tailwind.😏

**Comment by tomtev** [comment]
I was thinking more about ready-to-use markup examples without styling. Digging into accessibility etc is a lot of work so would be nice to just have something to copy and paste from.

**Comment by calebporzio** [comment]
Great suggestions, I agree that having style-agnostic markup examples (with accessibility notes in there) would be super handy.

Let's keep it on the radar.

Closing for now.
