### ISSUE TITLE
Input change hander - this has to be the wrong approach?

### ISSUE THREAD

**Issue by GavinRay97** [alpinejs/alpine#149]
I was trying to do something like this:
```html
<input @change="e => console.log(e)">
```

But I noticed it did not work. It only works if I call a function defined in the `x-data` method, but you cannot invoke it with a change handler lambda (IE `e => doSomething(e)`), only by direct invocation with no arguments it seems: `doSomething()`.

I have a nasty hack to work around this that uses the default `arguments` meta-value that is supplied to all methods, but there must be some easier way?

```html
<div x-data="example()">
  <input @change="doThing(arguments)">
</div>

<script>
  // Arguments { 0: Proxy, 1: change, 2: getDispatchFunction(event, detail) }
  const alpineEventHandler = func => ([_, event]) => func(event)

  function example() {
    return {
      doThing: alpineEventHandler(e =>
        console.log(`e.target.value is`, e.target.value)
      )
    }
  }
</script>
```

**Comment by tlgreg** [comment]
The event argument can be accessed with the `$event` magic property, which you are extracting in your second example. `$event` should be documented though either in magic properties or under `x-on`.
(It's currently in example under `$dispatch` and `$nextTick`.)
```html
<input @change="console.log($event.target.value)">
```
```html
<input @change="doThing($event)">
```

**Comment by GavinRay97** [comment]
Ahh yeah that is much easier, thank you!

**Comment by calebporzio** [comment]
Yep, use `$event`. I added it's own section to the docs. Thanks!
