### ISSUE TITLE
:x-ref on dynamic items not added to main this.$refs ?

### ISSUE THREAD

**Issue by yabdab** [alpinejs/alpine#1517]
So I have a <template> setup to display dynamic items loaded via fetch. I use the :x-ref="someRef". 
In v3 I can no longer do this. I checked and the main this.$refs in my data() does not reflect any dynamic refs added after page loads.

**Comment by KevinBatdorf** [comment]
If you console.log the `$refs` is `name` there? Can you make a demo?

**Comment by ryangjchandler** [comment]
I believe this might be related to the cached `x-ref` results in 3.x.

**Comment by yabdab** [comment]
> I believe this might be related to the cached `x-ref` results in 3.x.

Is there a way to refresh the cache of refs?

**Comment by KevinBatdorf** [comment]
I don't know why you're editing your initial post to make comments confusing, but following on my previous comment. I made a demo and it seems to be working. I used this code and it logged the expected element.

```html
<div x-data="">
  <p x-ref="hello"></p>
  <button @click="() => {var myVar = 'hello'; console.log($refs[myVar])}">press</button>
</div>
```

Can you put up a demo where it's broken?

**Comment by yabdab** [comment]
Sorry @KevinBatdorf , did not mean to confuse.  I just discovered the actual issue and wanted to update the issue.

I read your thread in discord and it seems to be the same issue danjac has. 

Your demo is static (not dynamic) so that is why it works.

Here is a demo of what does not work...

```
<template x-for="item in items" :key="item.id" >
<div :x-ref="item.name">
some content ...
</div>
</template>

```

**Comment by KevinBatdorf** [comment]
Oh I missed the binding part of your question. yeah you can't bind x-ref anymore. it was sort of a hack to begin with though I think (although useful). You may need a custom directive to handle that instead for now. 

Could be a useful feature though. I would start a discussion on it and let people upvote to show demand.

**Comment by yabdab** [comment]
OK. I will just use your suggestion from discord until I can revisit the issue...

`let ref = document.querySelector('[x-ref="item-' + pid + '"]');`

**Comment by KevinBatdorf** [comment]
Yeah, or something clunky like this would work too:

```html
<div x-data="{foo: 'bar'}">
  <p x-ref="hey">Hey</p>
  <p x-init="() => {
    const $root = $el.closest('[x-data]')
    $root._x_refs || ($el.closest('[x-data]')._x_refs = {})
    $root._x_refs[foo] = $el
  }"></p>
  <button @click="console.log($refs)">press</button>
</div>
```
Which you may be able to abstract somehow.

https://codepen.io/KevinBatdorf/pen/vYxbgXL

**Comment by yabdab** [comment]
THanks! So id it safe to assume other things cannot bind in templates now? Things like :href and :class ?

**Comment by KevinBatdorf** [comment]
> So is it safe to assume other things cannot bind in templates now? Things like :href and :class ?

I don't think that's accurate at all. That's one of Alpine's core features.

I don't think Alpine directives were meant to be bound though. I haven't checked but binding other directives might also not produce the same behavior, like `x-bind:x-transition="myFunc()"`. But it could still work. I just haven't tried it yet.
