### ISSUE TITLE
Importing as a separate script does not appear to work

### ISSUE THREAD

**Issue by GavinRay97** [alpinejs/alpine#152]
This may be an issue with Parcel specifically, but I tried setting up the basic `x-data` example on Codesandbox. If the script is not inlined in the page, but is imported from a separate file, Alpine will not function.

See:
https://codesandbox.io/s/cranky-wozniak-rgn7s

**Comment by the94air** [comment]
Tested with Poi bundler (technically webpack). Working just fine. Maybe only parcel issue.

**Comment by the94air** [comment]
Tested locally with Parcel `v1.12.4` Alpine `v1.9.7`. Working normally.
https://github.com/the94air/alpinejs-parcel

**Comment by SimoTod** [comment]
@GavinRay97 
It's codesandbox.io messing up with your index.js (alpine looks fine). 
Not sure why since I've never used it but you can try to ask them directly (or switch to a different sandbox).

If you look at https://ejn8g.csb.app/ (the compiled code that gets loaded in the iframe) and you try to call `dropdown()` from the chrome inspector, you'll get `VM2381:1 Uncaught ReferenceError: dropdown is not defined`.

https://ejn8g.csb.app/src/index.js looks empty as well but, using the inspector, it shows a different source code
```javascript 
(function evaluate(require, module, exports, process, setImmediate, global, __dirname, __filename) {"use strict";

function dropdown() {
  return {
    show: false,
    open: function open() {
      this.show = true;
    },
    close: function close() {
      this.show = false;
    },
    isOpen: function isOpen() {
      return this.show === true;
    }
  };
}

console.log("Imported");
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi9zcmMvaW5kZXguanMiXSwibmFtZXMiOlsiZHJvcGRvd24iLCJzaG93Iiwib3BlbiIsImNsb3NlIiwiaXNPcGVuIiwiY29uc29sZSIsImxvZyJdLCJtYXBwaW5ncyI6Ijs7QUFBQSxTQUFTQSxRQUFULEdBQW9CO0FBQ2xCLFNBQU87QUFDTEMsSUFBQUEsSUFBSSxFQUFFLEtBREQ7QUFFTEMsSUFBQUEsSUFGSyxrQkFFRTtBQUNMLFdBQUtELElBQUwsR0FBWSxJQUFaO0FBQ0QsS0FKSTtBQUtMRSxJQUFBQSxLQUxLLG1CQUtHO0FBQ04sV0FBS0YsSUFBTCxHQUFZLEtBQVo7QUFDRCxLQVBJO0FBUUxHLElBQUFBLE1BUkssb0JBUUk7QUFDUCxhQUFPLEtBQUtILElBQUwsS0FBYyxJQUFyQjtBQUNEO0FBVkksR0FBUDtBQVlEOztBQUVESSxPQUFPLENBQUNDLEdBQVIiLCJzb3VyY2VzQ29udGVudCI6WyJmdW5jdGlvbiBkcm9wZG93bigpIHtcbiAgcmV0dXJuIHtcbiAgICBzaG93OiBmYWxzZSxcbiAgICBvcGVuKCkge1xuICAgICAgdGhpcy5zaG93ID0gdHJ1ZTtcbiAgICB9LFxuICAgIGNsb3NlKCkge1xuICAgICAgdGhpcy5zaG93ID0gZmFsc2U7XG4gICAgfSxcbiAgICBpc09wZW4oKSB7XG4gICAgICByZXR1cm4gdGhpcy5zaG93ID09PSB0cnVlO1xuICAgIH1cbiAgfTtcbn1cblxuY29uc29sZS5sb2coYEltcG9ydGVkYCk7XG4iXX0=
//# sourceURL=https://ejn8g.csb.app/src/index.js
})
``` which means that your function is not available on the global scope.

**Comment by HugoDF** [comment]
For future reference, the issue here, as @SimoTod pointed out is that when using Webpack, Parcel (or mostly any bundler for that matter), the function you rely on in `x-data` is not set on the global scope (`window`).

The workaround is to explicitly define it on the window object:

```js
window.dropdown = function () {
  return {
    show: false,
    open: function open() {
      this.show = true;
    },
    close: function close() {
      this.show = false;
    },
    isOpen: function isOpen() {
      return this.show === true;
    }
  };
}
```

**Comment by GavinRay97** [comment]
@HugoDF Brilliant! Haven't tested but that makes perfect sense.

Maybe good info for the docs?

**Comment by danbrellis** [comment]
For anyone coming back here for Alpine v3, there is a callout in the docs:

> If you imported Alpine into a bundle, you have to make sure you are registering any extension code IN BETWEEN when you import the Alpine global object, and when you initialize Alpine by calling Alpine.start().

This is what worked for me then (note `Alpine.start()` at the **end**:

```js
import Alpine from "alpinejs";

document.addEventListener("alpine:init", () => {
  Alpine.data("dropdown", () => ({
    open: false,
    toggle() {
      this.open = !this.open;
    },
  }));
});

Alpine.start();
```

**Comment by KondorB** [comment]
@danbrellis I'm pretty sure I would have spent a helluva lot of time fixing my front-end after the update if not for your comment.
