### ISSUE TITLE
Detecting an escape key - which element to listen on?

### ISSUE THREAD

**Issue by danfascia** [alpinejs/alpine#154]
I'm trying to listen for an escape key to close a full screen modal using

```
@keydown.escape="playerActive = false"
```

But the problem is which element to place this on. So far, if I place it on the triggering `<a href>` then it works, but as soon as I click onto the modal to interact with it the escape binding no longer works.

Placing the escape key binding on the modal itself does not work, and placing it on both of the above also does not work.

I wonder if someone could help me understand the behaviour and correct approach here.

The codepen in question is https://codepen.io/danfascia/full/jOEoQzg

Click on the first 'Chest' item and you will see the behaviour I describe

**Comment by SimoTod** [comment]
How about `@keydown.escape.window`? 
It means that the listener will be added to the window object so it will always be captured.
The position of the directive in your DOM at that point will be more a semantical argument since it would work everywhere: I would personally put that on the modal.

**Comment by danfascia** [comment]
That's perfect, works well and I agree it should live on the modal.

Thanks for your help, I've updated my https://codepen.io/danfascia/full/jOEoQzg

**Comment by rzenkov** [comment]
Only DOM elements wih focus can listen keys events. You can use trick, wich bootstrap uses. 
Shortly it is wrapper with `tabindex="-1"` and `el.focus()` on showing.

[example on JSBin](https://jsbin.com/dipaqez/edit?html,output)

**Comment by danfascia** [comment]
Thanks, that's another neat tip although binding to .window seems to work well

**Comment by calebporzio** [comment]
Good suggestions here. Closing.

**Comment by mrtnpro** [comment]
Since I just ran into this as well: This is what worked for me:

`<div x-data="{ open: false }" x-on:keydown.ctrl.g.window="open = !open"></div>`
