### ISSUE TITLE
[request] Fetch wrapper

### ISSUE THREAD

**Issue by dkuku** [alpinejs/alpine#157]
I think this might be be usefull to retrieve dynamic data for dropdowns
```
<div x-fetch:items="{url: 'api.address.url'}">
    <template x-for="item in items" :key="item">
        <div x-text="item"></div>
    </template>
</div>
```

**Comment by danfascia** [comment]
This is a really good idea imho, I would welcome this wrapper even though writing fetch functions isn't that hard.

**Comment by stuartpullinger** [comment]
I was thinking of attempting this if/when there was a plugin API for Alpine. Something along the lines of Intercoolerjs but smaller and integrated into Alpine. I'm not sure if this fits into the Alpine core or if it would be better developed as an add-on/plugin.

**Comment by keyurshah** [comment]
Yeah this would be great to have natively or through the custom directive feature under discussion.  intercooler style behavior would be useful.

**Comment by tlgreg** [comment]
Maybe an `x-async` similar to svelte, that handles promises to conditionally render pending / resolved / rejected states.

**Comment by calebporzio** [comment]
Eventually, we will likely add a custom directive system so you could define things like this yourself and publish them as third party packages.

But I don't envision adding something like this as a first-class offering.

Closing for now.
