### ISSUE TITLE
Unbinding global event listeners w/ Turbolinks

### ISSUE THREAD

**Issue by luizpvas** [alpinejs/alpine#167]
The `window` and `document` modifier for `x-on` doesn't work well with turbolinks. The event listener gets duplicated each time the element is initialized (see [this minimal project](https://github.com/luizpvas/alpine-window-event-with-turbolinks) that reproduces the issue).

I think this could be solved by watching removed nodes in mutation observer, but Alpine would need to keep track of the global handlers associated with each element. I'm not sure this is a good path.

I'm glad to work on a PR if there is a good solution for this issue :+1:

**Comment by SimoTod** [comment]
I think the same thing happens if you use vanilla JS
```javascript
<script>window.addEventListener("keydown", event => {
  if(event.key == 'e') alert('e pressed')
});</script>
```
I'm not sure that Alpine should be responsible for fixing it. 

It seems more like a turbolinks bug to me. Probably it's worth to ask them if it's the expected behaviour or not.

**Comment by luizpvas** [comment]
Yeah, it happens with vanilla JS, but at least in this case I have control over the handler function and can unbind it manually.

With Alpine, I can see people thinking that event handlers "live together" the element they're defined on, even if they have `window` or `document` modifiers.

**Comment by SimoTod** [comment]
I see your point but it would set a dangerous precedent. 
It's my personal view, though. If the community feels it's right, I won't complain. :)

**Comment by rzenkov** [comment]
Imo, `.window` listeners  doesn't  applicable for SPA's (of any type). Unlike DOM element event listeners,  which deletes along with DOM elements, window listeners keeps independently of DOM-changes. 

We have no way to delete `.window` listeners at this moment, therefore if you use it on SPA-like page you should handle them yourself.

it is sad, but `.window` listeneres is the only way to send custom message to not parent component.  As far as I know, Caleb has not yet made any decisions regarding inter-component communications.

I think we need something like Vue `beforeDestroy()`  hook, in alpine style `x-destroy` then we can handle component removing.

**Comment by SimoTod** [comment]
@luizpvas 

> With Alpine, I can see people thinking (I did) that event handlers "live together" with the element they're defined on, even if there is `window` or `document` modifiers.

About this point, it would probably make more sense to have a generic solution to remove a global handler when the element who created it is removed from the DOM.

I think that dealing with the mutationObserver is quite hard and, performance wise, really demanding but it's probably doable with a few lines of code if, at the beginning of the handler, we check if the element is still attached to the DOM. If not, we remove the handler and call return.

It means that you actually remove the handler when you try to use it the second time but it would save you from keeping a list in memory.

That should work for turbolinks and also for any other libraries which removes an element from your DOM.

Any thought?

**Comment by luizpvas** [comment]
Yes... that sounds amazing. It solves this issue without having to keep track of events and watch for removed nodes.

I think [`document.body.contains(node)`](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains) at the beginning of the event handler is probably good enough in terms of browser support and performance.

If that sounds good, I'll start working on a PR and submit it tomorrow :+1:

**Comment by sotirislp** [comment]
Is this still working? Because I don't find it in the source code of v3.10.2 and the problem still exists.
I remove the element where it had x-on.custom-event.window and the eventListener on the window object is still intact. Do we have a newer approach to this?
