### ISSUE TITLE
[Feature] IntersectionObserver events

### ISSUE THREAD

**Issue by jreviews** [alpinejs/alpine#168]
While it's possible to implement this now using x-init, it's a bit verbose.  Would be great to have a way to do with events like x-on:enter and x-on:leave. 

I made some changes to support these and posted a couple of examples here https://codepen.io/jreviews/pen/zYGGBvP

The once modifier also works and disconnects the observer.

This implementation doesn't allow to pass options when instantiating the IntersectionObserver API because there's no way to do that with the x-on:enter and x-on:leave syntax.

**Comment by danfascia** [comment]
Funny you posted this, I came up against this recently and found a workaround to not use IntersectionObserver but since others have mentioned it yes it would be good to have and not too hard since it would be a wrapper of an API already there.

**Comment by jreviews** [comment]
Here's the code that runs when either "enter" or "leave" events are used. Not sure it's the best implementation, so open to suggestions or re-writes if there's any interest in adding it. 

```
        const handler = (entries, observer) => {
            let e = entries[0].target
            if ( event == 'enter' && entries[0].isIntersecting ) {
                    e.dataset.intersected = true
                component.evaluateCommandExpression(entries[0], expression, () => {
                    return {...extraVars(), '$event': e, '$observer': observer }
                })
                if (modifiers.includes('once')) {
                    observer.disconnect()
                }
            } else if ( undefined !== e.dataset.intersected && event == 'leave' && !entries[0].isIntersecting) {
                component.evaluateCommandExpression(entries[0], expression, () => {
                    return {...extraVars(), '$event': e, '$observer': observer }
                })
                if (modifiers.includes('once')) {
                    observer.disconnect()
                }
            }
        }

        let io = new IntersectionObserver((entries, observer) => {
            handler(entries, observer)
        })

        io.observe(el)is.
```

The use of ` e.dataset.intersected = true` seems pretty bad to me, but I didn't know how else to flag this so "leave" is not triggered before "enter" if an element is not visible on page load.

It might be better to use a single `x-intersect` directive so the API is instantiated just once per component ....

**Comment by ryangjchandler** [comment]
Hi guys, I'm quite interested in this one too. I'm going to play around with some implementations this weekend to see if there's a nice, optimised way to achieve this. Will update this issue as we go along. Thanks for the idea!

**Comment by ryangjchandler** [comment]
Hi guys, I'm not sure if this fits inside the scope of the project currently. It's hard to get this sort of feature right and keep it performant and lightweight (hence why Vue doesn't support any intersection observer events out of the box), there's just too many edge cases I think.

I would still go down the route of registering the handlers through the `x-init` hook currently. I'm happy to leave the issue open if you think the feature is worth it, but I can't imagine too many people using these events often enough to warrant it being part of the core itself.

In the future, this would make for a great custom directive (once that API is available in core).

**Comment by jreviews** [comment]
I agree. Closing it now.

**Comment by ay13** [comment]
@danfascia You mentioned you did intersection observer like interaction with actually using it, can you post an example?

**Comment by davidwebca** [comment]
I'm sorry guys but I'm looking at implementing intersection observer so that I can make elements transition as they appear in the viewport. @jreviews I also found your CodePen example : https://codepen.io/jreviews/pen/zYGGBvP, but it seems like a custom build of Alpine I was wondering how to plug into Alpine to make it happen. Can you share a bit about your method?

**Comment by jreviews** [comment]
This is quite old and I never really used it for anything. Someone posted another example in the [Alpine discord](https://discord.com/channels/697534128706551828/697534289419436142/758290041947815947) and here's the [codepen](https://codepen.io/SimoTod/pen/YzqdJey)
