### ISSUE TITLE
Transitions out not working?

### ISSUE THREAD

**Issue by shornuk** [alpinejs/alpine#171]
HI, 

Just started having a play after hearing about this on Full Stack Radio. Liking it so far, but running into an issue that I'm not sure how to solve. 

I'm trying to create a panel that slides up. Showing this panel (sliding it up) works fine, but I can't slide it back down again. It appears that the transition out is not running as the items gets the `display:none;`

Here's a simple example (obvs using tailwind for the styling)...

```html
<div x-data="{ openPanel: false }">

	<button x-on:click="openPanel= true">Open Panel</button>

	<div
		x-show="openPanel"
		class="overlay"
		:class="{ 'visible': openPanel }">

		<div
			x-show="openPanel"
			class="fixed inset-0 z-50"
			x-transition:enter="transition-transform ease-in-out duration-500"
			x-transition:enter-start="transform translate-y-full"
			x-transition:enter-end="transform translate-y-0"
			x-transition:leave="transition-transform ease-in duration-500"
			x-transition:leave-start="transform translate-y-0"
			x-transition:leave-end="transform translate-y-full">

			<div class="bg-gray-100 mt-24 h-full relative" @click.away="openPanel = false">

				<div class="flex items-center pt-4 md:pt-12 mb-8 max-w-3xl mx-auto">
					<a class="ml-auto" href="#" x-on:click="openPanel= false" x-on:click.prevent>Close</a>
				</div>

				<div class="max-w-3xl mx-auto">
					<p>Content</p>
				</div>

			</div>

		</div>
	</div>

</div>
```

Am I missing something?

**Comment by SimoTod** [comment]
Your external div (. overlay) becomes hidden when you click close.
The internal transition happens but it's not visible because you have already set display none on the parent div.

If you remove x-show from the parent, it works. -> https://codepen.io/SimoTod/pen/ZEGbxpp

**Comment by shornuk** [comment]
Awesome. I missed that. All working now.
