### ISSUE TITLE
Separating the show trigger from the target?

### ISSUE THREAD

**Issue by shornuk** [alpinejs/alpine#176]
Hi, 

Not sure if this is the best place to be asking but couldn't find anywhere else that seems good to discuss Alpine. 

I've just started and playing and thanks to @SimoTod I've got my sliding panel working. 
https://codepen.io/SimoTod/pen/ZEGbxpp (His codepen, not mine)

I've extended it a little further and have extracted it into a function so I could also add classes to the body. 
```javascript
function panel() {
        return {
            show: false,
            open() {
            	this.show = true;
            	if (!body.classList.contains('overflow-hidden')) {
            		body.classList.add('overflow-hidden')
            	};
            },
            close() {
            	this.show = false;
            	if (body.classList.contains('overflow-hidden')) {
            		body.classList.remove('overflow-hidden')
            	};
            },
            isOpen() { return this.show === true },
        }
    }
```

What would be really nice is to separate out the trigger from the panel. That way, when I have multiple panels, the triggers are in the flow of the page, and the panels can all be sat at the bottom ready to be exposed. (Helps wit z-index'ing etc).

Only, I'm not are how to do this? Would it be a case of adding the `x-data="panel()"` to the `<body>` or is there a simpler way that I'm missing?

**Comment by TomS-** [comment]
@shornuk The $dispatch magic property (https://github.com/alpinejs/alpine#dispatch) is what you're looking for.

On your `body` you can do
`<body x-data="{ show: false }"  :class="{ 'overflow-hidden': show }" @panel-toggle="show = !show">`

Then simply do `<button @click="$dispatch('panel-toggle')">Toggle</button>`

That way you wouldn't even need to use a function too.

**Comment by shornuk** [comment]
@TomS- That's great. Thought there must have been a better way to adding the class to the body. 

With regards to the separation, I think what I'm ideally trying to do is something along the lines of...

```html
<body>

    <button>Trigger for panel 1</button>
    <button>Trigger for panel 2</button>

    <div>Panel 1</div>
    <div>Panel 2</div>

<body>
```
I'd be creating the panels from a partial/macro so Ideally would there be a way to do this without manually add the x-data for each to the body? - Does that make sense?

**Comment by TomS-** [comment]
@shornuk You can use an index for that so you can use:
```
<body x-data="{ panelOpen: false }" :class="{ 'overflow-hidden': show !== false }" @panel-toggle="panelOpen = $event.details.open">

    <button @click="$dispatch('panel-toggle', { open: 1 })">Trigger for panel 1</button>
    <button @click="$dispatch('panel-toggle', { open: 2 })">Trigger for panel 2</button>

    <div x-show="panelOpen === 1">Panel 1</div>
    <div x-show="panelOpen === 2">Panel 2</div>

<body>
```

You may not need to use dispatch and you can simply do
```
<button @click="panelOpen = 1">Trigger for panel 1</button>
```
If you don't intend to use this inside another component. I haven't tested this at all, but it should work.

**Comment by shornuk** [comment]
Awesome, I think that's pretty much got me there. 
Have this working now...

```html
<body x-data="{ panel: false }" :class="{ 'overflow-hidden': panel !== false }">

    <button @click="panel = 1">Trigger for panel 1</button>
    <button @click="panel = 'id2'">Trigger for panel 2</button>
    <button @click="panel = 3">Trigger for panel 3</button>

    <div class="fixed inset-0 bg-white max-w-sm" x-show="panel === 1" @click.away="panel = false">Panel 1</div>
    <div class="fixed inset-0 bg-white max-w-sm" x-show="panel === 'id2'" @click.away="panel = false">Panel 2</div>
    <div class="fixed inset-0 bg-white max-w-sm" x-show="panel === 3" @click.away="panel = false">Panel 3</div>

<body>
```
All seems to be working as expected!

**Comment by TomS-** [comment]
@shornuk Amazing, please close the issue if you're happy with the solution

**Comment by calebporzio** [comment]
A GH issue is fine for something like this @shornuk.

Thanks for lending a hand @TomS- , great suggestions.

Yeah, using the event system is the way I'd go for something like this.

Want to keep the API minimal. So closing for now. Re-open if I missed something!

**Comment by shornuk** [comment]
Great stuff. Thanks for the help @TomS- and for creating a useful package @calebporzio 👍🏼
