### ISSUE TITLE
Alpine not updating when data changes outside

### ISSUE THREAD

**Issue by adrianschubek** [alpinejs/alpine#184]
Alpine does not update/re-render on data changes from outside.
Demo: https://codepen.io/welt101/pen/vYOKYoa
- Object is attached to `window` (alternatives?)
- Value is increased by 1 every second.
#### Current behavior
Data is only updated when the button is pressed.
#### Expected behavior
Data updates on every data change.

**Comment by SimoTod** [comment]
It's expected. Components react only to internal changes. If you use a global variable and you change it from the outside, the component won't be aware of it until you trigger an update from the inside.
There are technical reason why this is not possible (all the changes need to go throw special proxy objects and this happens only from the component context).

You can try to encapsulate your logic into the component context and use the init function to start the counter. I modified your codepen, I don't know if it does exactly what you need but it's just to show you what I mean. https://codepen.io/SimoTod/pen/ZEGOYXy

**Comment by adrianschubek** [comment]
Thank you! That's just what I needed

**Comment by drifteaur** [comment]
For reference, here's a good article on triggering events in Alpine components from the outside: https://tonylea.com/setting-alpine-data-outside-of-the-component
