### ISSUE TITLE
CustomEvent & x-on

### ISSUE THREAD

**Issue by samhibberd** [alpinejs/alpine#185]
We are looking to update the data stored on a component using a custom event, which then updates the attributes set on an <a> tag:

``` twig
<div x-data="{ qty: 0 }">
    <a @updatecart="qty: $event.detail.qty" :class="{ 'disabled pointer-events-none': qty == 0 }" href="#">Continue</a>
</div>
```

And then dispatching the event from a separate callback, which is triggered after a successful ajax add to cart:

``` js
var event = new CustomEvent('updatecart', {
    bubbles: true,
    cancelable: true,
    detail: { qty: 8 },
});
window.dispatchEvent(event);
```

Not sure if I am missing something obvious, or if this isn't even possible, any help would be greatly appreciated.

PS. Loving alpine, perfect partner to tailwind and vanilla js. :)

**Comment by tlgreg** [comment]
If you dispatch an event on the window you should listen on it there.
Alpine has a modifier for this with `x-on`:
```html
<a @updatecart.window="...">...</a>
```

**Comment by samhibberd** [comment]
Ah of course, thanks @tlgreg, and if the event dispatched on the element then it would get caught without this.

For completeness, are there any alternative (better) ways to achieve this, or is this right?

**Comment by tlgreg** [comment]
On the same element or when the event `bubbles` it can be caught on an ancestor element too.

Alpine's `$dispatch` function sends custom events ([docs](https://github.com/alpinejs/alpine#dispatch)), which is especially handy inside the template.

**Comment by samhibberd** [comment]
Thanks!
