### ISSUE TITLE
Error when used with Wordpress V3+

### ISSUE THREAD

**Issue by PremDev2014** [alpinejs/alpine#1875]
I really can't figure this out.
Alpine 3.2.2 is a blast to use in any project but will when I try to upgrade from 2.8.2 either as a bundle or cdn in a Wordpress project I get the following error. (This is when I tried via CDN in the header).

 Uncaught SyntaxError: Invalid shorthand property initializer
    at new AsyncFunction (<anonymous>)
    at jr (cdn.min.js:1)...

Has anyone else seen this??

?

**Comment by PremDev2014** [comment]
So I now do have it working in a different instance of Wordpress so the issue has to be something to do with the specific project. Which is great actually!

**Comment by KevinBatdorf** [comment]
Maybe you mixed up JS syntax with PHP? The error message indicates you did something like:

```js
const myObject = {
  foo => 'bar'
}
```
or even `=`

**Comment by PremDev2014** [comment]
I stripped out all other JS for both use cases. CDN & npm module import. For CDN I simply pasted in the script src markup right before the </head>. I'm relieved that it is working fine on another WP project that I also updated from 2.8.2 to 3.2.2. Still a mystery why it won't play nice on the other project. Thanks for you reply :)

**Comment by PremDev2014** [comment]
Got it! (If you were interested :D)
My bad, earlier version of Alpine ignored this error @click="{  show = ! show }"
that should have been
@click="show = ! show"
Nothing to do with WP or Alpine.
Everything to do with me getting the syntax wrong!
