### ISSUE TITLE
ReferenceError xx is not defined with x-for and x-if combination and dynamic content

### ISSUE THREAD

**Issue by bvalentino** [alpinejs/alpine#189]
An exception is thrown when the `x-data` is updated and re-evaluated.

Using this structure:

``` html
<div x-data="{ items: [...] }">
  <template x-for="item in items" :key="item">
    <div>
      <template x-if="...">
        ...
      </template>
      <template x-if="...">
        ...
      </template>
    </div>
  </template>
</div>
```

When a new item is added and the `x-data` updated, it will render OK but the exception `Uncaught ReferenceError: item is not defined` is seen in the console.

Here's an example: https://codepen.io/bvalentino/pen/BaNQKZo

**Comment by jokarz** [comment]
Had the same problem as well using component logic way.

https://codepen.io/juki/pen/PoqbKeX  (forked from the example above)
