### ISSUE TITLE
Add eslint to ensure code quality

### ISSUE THREAD

**Issue by julioocamargoo** [alpinejs/alpine#190]
Like editorconfig, I think eslint will help with this. What do you think?

**Comment by Calinou** [comment]
Which style should be picked? Since the current codebase doesn't seem to use semicolons, going for Standard would make more sense. It's not as strict as the Airbnb style though.

**Comment by thormeier** [comment]
Suggestion: A pretty robust setting I personally use for many projects is `vue/recommended` (https://eslint.vuejs.org/rules/) paired with prettier (https://prettier.io/docs/en/options.html):
```
// .eslintrc.json
{
  "root": true,
  "extends": [
    "plugin:vue/recommended"
  ],
  "plugins": [
    "prettier"
  ],
  "rules": {
    "prettier/prettier": "error"
  }
}
```

```
// .prettierrc
{
  "trailingComma": "none",
  "tabWidth": 2,
  "semi": false,
  "singleQuote": true
}
```

Some of the Vue rules are obviously ignored, but the standard JS stuff is pretty sane, imho. What do you think?

**Comment by HugoDF** [comment]
I've had pretty good success with just prettier, fewer config settings, harder to break prettier rules (since it's a formatter)

**Comment by HugoDF** [comment]
I've had pretty good success with just prettier, fewer config settings, harder to break prettier rules (since it's a formatter)

**Comment by Calinou** [comment]
ESLint and Prettier detect a different range of issues, so I think we should be either using just ESLint or ESLint + Prettier, not just Prettier. ESLint catches "code smells" and poor programming practices in addition to some code style issues, whereas Prettier *only* focuses on code style.

**Comment by HugoDF** [comment]
To be fair, with a project/codebase this size and this number of contributors ESLint/Prettier aren't necessary until @calebporzio gives write access to a bunch of other contributor.

Right now all PRs need to be merged by him, so he can decide whether there are any style/format issues or "code smells".

**Comment by jonaskuske** [comment]
@thormeier Instead of setting `plugins`
` and `rules` manually, you also add `plugin:prettier/recommended`, just like with `vue`. Oh and as the third entry to `extends` you'll probably want to add `prettier/vue` to handle Vue-specific ESLint rules :)

**Comment by HugoDF** [comment]
I'm going to close this for now, as mentioned, Caleb is the only one with write access to the repository so he ends up doing the linting himself before/after merging 😄
