### ISSUE TITLE
Can I translate the README for PT-BR???

### ISSUE THREAD

**Issue by suissa** [alpinejs/alpine#191]
I'm very interesting about this framework and I want to promote it in Brazil.

Am I allowed to translate to PT-BR?

**Comment by samuelpetroline** [comment]
Nice one! Would love to help on this as well.

**Comment by acauamontiel** [comment]
@samuelpetroline are you sure you'll trust this jerk to translate and promote your project?
https://www.youtube.com/watch?v=KJ4tmc1HL7Y

**Comment by nandordudas** [comment]
> @samuelpetroline are you sure you'll trust this jerk to translate and promote your project?
> https://www.youtube.com/watch?v=KJ4tmc1HL7Y

~6 years => more language practices :smiley:
