### ISSUE TITLE
[Question] Reusable Form Controller

### ISSUE THREAD

**Issue by evergreenwebsystems** [alpinejs/alpine#195]
I was interested to see if I could make my forms submit using alpine whilst requiring zero server side code changes to my Controllers in my Laravel app.

I removed the ```<form>``` tags, i.e. so it isn't necessary to limit yourself to the restrictions that come about through the use of the ```<form>``` tag.

For example, here is the data to be submitted to the server contained in a ```<div>``` wrapper:
```html
    <div id="js-target-1" x-data="formController()" x-init="
    action = '/projects',
    formData.title = '{{ old("title") }}',
    formData.description = '{{ old("description") }}'
    ">
        <h3>Create a Project</h3>
        <div id="Form1">
            <input type="text" name="title" placeholder="Title" x-model="formData.title">
            <select name="description" x-model="formData.description">
                <option value="">Please select one</option>
                <option value="books">Books</option>
                <option value="html">HTML</option>
                <option value="css">CSS</option>
                <option value="php">PHP</option>
                <option value="js">JavaScript</option>
            </select>
            <div class="button inline-block" x-on:click="submitForm('#js-target-1')">Add project</div>
        </div>
        <ul id="errors" class="field mt-6 list-reset">
            @if ($errors->{ $bag ?? 'default' }->any())
            @foreach ($errors->{ $bag ?? 'default' }->all() as $error)
            <li class="text-sm text-red">{{ $error }}</li>
            @endforeach
            @endif
        </ul>
    </div>
```

Include the form controller once somewhere in the app template:
```html
@include('partials.form-controller')
```

Form controller:
```javascript
<script type="text/javascript">
    function formController() {
        return {
            action : '',
            formData: {
                _token : '{{ csrf_token() }}',
            },
            submitForm(targetId) {
                var formData = new FormData();
                for (let [key, value] of Object.entries(this.formData)) {
                    formData.append(key, value);
                }
                // console.log([...formData]);
                fetch(this.action, {
                    method: 'POST',
                    body: formData,
                })
                .then(
                    response => response.text()
                )
                .then(text => {

                    // select the element that will be replaced
                    var currentHtml = document.querySelector(targetId);

                    // get new element from response
                    const parser = new DOMParser();
                    const htmlDocument = parser.parseFromString(text, 'text/html');
                    const newHtml = htmlDocument.documentElement.querySelector(targetId);

                    // replace element
                    currentHtml.parentNode.replaceChild(newHtml, currentHtml);

                });
            },
        }
    }
</script>
```

The alpine model object is converted to a form object which is POST'ed using the native fetch api and from response the section in the DOM which contains the form is extracted and updated.

It all seems to work fine, I can have multiple forms on the same page and that works as expected. I am really just interested as to whether anyone has an opinion on if this approach is a good idea, terrible idea, etc....

**Comment by MarcelRusu** [comment]
I've been investigating forms in alpine
I think if you are just replacing the form with the html there's not really a point of using alpine, I don't know laravel but I imagine you can use SJR and its much less code.

This needs to be fleshed out more - form libraries.. but it definitely is possible to do completely client side forms with injected data from rails/php/whatever which will get json responses and react to errors / success.

I'm curious if anyone is making any progress in json forms in alpine?

**Comment by HugoDF** [comment]
Closing this feel free to reopen a discussion, drop into the [Discord chat](https://alpinejs.codewithhugo.com/chat/) or check out [awesome-alpine](https://github.com/alpinejs/awesome-alpine) to see what people are up to with regards to this.
