### ISSUE TITLE
Object doesn't support property or method 'forEach' IE 11

### ISSUE THREAD

**Issue by lalov** [alpinejs/alpine#20]
I get an "Unhandled promise rejection" when used with Internet Explorer 11. 

Unhandled promise rejection TypeError: Object doesn't support property or method 'forEach'

**Comment by keyurshah** [comment]
You probably need to create a polyfill and load that before project-x. 

This is a good service to create a url. You can search for foreach and add it in. You will probably need a few others as well, such as 

* Mutation Observer, 
* Array.from
* Array.foreach
* Map
* Set

**Comment by pryley** [comment]
@lalov You can also use https://polyfill.io

**Comment by keyurshah** [comment]
I got it to work in IE 11 by adding the following polyfills

```
<script src="https://polyfill.io/v3/polyfill.min.js?features=MutationObserver%2CArray.from%2CArray.prototype.forEach%2CMap%2CSet%2CArray.prototype.includes%2CString.prototype.includes%2CPromise%2CNodeList.prototype.forEach%2CObject.values%2CReflect%2CReflect.set"></script>
<script src="https://cdn.jsdelivr.net/npm/proxy-polyfill@0.3.0/proxy.min.js"></script>
```



You can view a [demo ](https://cdpn.io/kjshah/debug/8b5b5e4d7d4e98068222849f81cd4e31) here

**Comment by calebporzio** [comment]
Hey @keyurshah, would love a PR to the README for the required polyfill links to support IE11. Up for it?

**Comment by keyurshah** [comment]
sure, sounds good, will try to write that up.

**Comment by calebporzio** [comment]
Thanks @keyurshah! Done.
