### ISSUE TITLE
When I click a button I want to hide an html table and show another html table in Alpine.js - Laravel Livewire

### ISSUE THREAD

**Issue by mzhasan2016** [alpinejs/alpine#2001]
I am working in a Laravel 8 Livewire 2 project. There, when a button is clicked, I want to hide an html table and show another html table using Alpine.js. I am trying with below code in Livewire Blade, but not working. Please let me know what is wrong with my code. Please let me know how I can show an html table and hide another html table when button is clicked using Alpine.js in Laravel Livewire. Thanks in advance.

<div x-data="{id: 1}">
    <button @click="$dispatch('open-dropdown',{id})">Open Dropdown</button>
</div>

<table x-data="{ open: true }"
    x-show="open"
    @open-dropdown.window="if ($event.detail.id == 1) open = false"
    @click.away="open = true" class="table-fixed w-full" >
    <thead>
        <tr class="bg-gray-100">
        <th class="px-4 py-2">Folder Name</th>
        </tr>
    </thead>
</table>

  <table x-data="{ open: false }"
  x-show="open"
  @open-dropdown.window="if ($event.detail.id == 1) open = true"
  @click.away="open = false" class="table-fixed w-full" >
  <thead>
      <tr class="bg-gray-100">
          <th class="px-4 py-2">Folder Name</th>
      </tr>
 </thead>
 </table>

**Comment by mzhasan2016** [comment]
By the way, I pasted my code here, but why it is not showing? Why it is showing Open Dropdown, Folder Name? Please help. Thanks

**Comment by hualiii** [comment]
> By the way, I pasted my code here, but why it is not showing? Why it is showing Open Dropdown, Folder Name? Please help. Thanks
I think you can show your code like this
![image](https://user-images.githubusercontent.com/60037943/131645826-3770f5a7-d4b4-4d62-8d55-e4d9ccd4f42f.png)
