### ISSUE TITLE
[Question] Using Objects in x-data and dealing with Proxies

### ISSUE THREAD

**Issue by mitkins** [alpinejs/alpine#206]
I've added the following component to my page:

```
<div x-data="{ some_date: new Date() }">
    <button @click="console.log(some_date)">Eep!</button>
</div>
```

When I click the button, I see the following in the console:

> Proxy {}
> [[Handler]]: Object
> [[Target]]: Fri Feb 28 2020 10:02:47 GMT+1100 (Australian Eastern Daylight Time)
> [[IsRevoked]]: false

Which was a bit of a surprise to me! After a bit of digging around, I realised that I didn't know about the [Proxy object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy). After some speculation and some reading, I realised that the Proxy object must be used to do data binding/magic stuff.

Which is cool, but it's not clear to me how I'm supposed to dereference an Object (like my `Date` Object in the example above). I'm working around the issue by using a primitive instead - a formatted string representation of my date. I then parse the string to create a `Date` object.

I'm missing something, do I need to create my own Proxy object so the getter will return a `Date` object? Is there a method of dereferencing the `Date` object with the Proxy that's been auto-generated for me?

Apologies because this is a Proxy object question and not directly related to Alpine. But I thought if others are in the same boat, then this question might be helpful?

**Comment by calebporzio** [comment]
Try it now with the new reactivity core in v2.1.0

Otherwise, the undocumented this.getUnobservedData() method should do it!

**Comment by mitkins** [comment]
I’ve updated to 2.1.0 and the above code was successful! Thanks for the tip too

**Comment by jelib3an** [comment]
Just wanted to link this with another issue we encountered related to proxies in the hope someone might be able to shed some light on things. Thanks!
https://github.com/ueberdosis/tiptap/issues/1515

**Comment by Mushr0000m** [comment]
@jelib3an same here
