### ISSUE TITLE
evaluatorMemo cache leaks memory and DOM elements

### ISSUE THREAD

**Issue by bep** [alpinejs/alpine#2126]
### Discussed in https://github.com/alpinejs/alpine/discussions/2125

<div type='discussions-op-text'>

<sup>Originally posted by **bep** September 24, 2021</sup>
* The core of this issue lives in the `evaluatorMemo` cache: https://github.com/alpinejs/alpine/blob/4f272c579d9f9e132544096f93934f73d2b35f8a/packages/alpinejs/src/evaluator.js#L46
* That cache gets written to, but never deleted from.
* When values in that cache has references to a DOM element (as in the `x-for` example below), it effectively prevents garbage collection and leaks DOM elements and memory. 

There is a example that reproduces this at https://alpine-testlab.netlify.app/leak1/ running with the latest AlpineJS -- description repeated below:

* Open the Memory profiler in Chrome
* Click the red button, all the `x-for` components are removed.
* Click the garbage icon in the profiler to force GC.
* Click on the round button to create a new profile.
* Filer by `Detached HTMLTemplateElement`

You should now see 20 detached elements. If you click on one, it points to `evaluatorMemo`.</div>

**Comment by calebporzio** [comment]
Thank you for catching this @bep - do you have thoughts on the best way to clean these up?

**Comment by bep** [comment]
@calebporzio My first instinct was to use a `WeakMap`, but the current key is a string and that doesn't work. But since this `evaluatorMemo` cache will get refilled if you clear it, I guess you could do that as part of the `destroyTree` function (which also would be great to have exported (for the Turbo use case etc.).

**Comment by SimoTod** [comment]
Another option would be to store the cache on an element property so it naturally disappear one the element is removed. This means that the cache becomes per component rather then global but I assume the main reason for this cache was the x-for directive since hits between different components are probably not too frequent

**Comment by danddanddand** [comment]
> Another option would be to store the cache on an element property so it naturally disappear one the element is removed. This means that the cache becomes per component rather then global but I assume the main reason for this cache was the x-for directive since hits between different components are probably not too frequent

Note https://github.com/alpinejs/alpine/pull/2027 passes el into generateFunctionFromString function because it is needed to log element if expression errors out so this solution makes a lot of sense to me

**Comment by bep** [comment]
I totally agree with @SimoTod and @danddanddand -- but to show that a variant of the above will fix this particular case, I have pushed a simple patched version to my test page: https://alpine-testlab.netlify.app/leak1/

**Comment by calebporzio** [comment]
@bep, thanks for all your work on this. I'm open to adding some cache clearing to `destroyTree`. I'd love to see this work in a PR for some of these fixes mentioned in both issues

**Comment by bep** [comment]
I have had another round on this, and this is a simpler variant that also fixes the above:

```js
if (node.localName === 'body') {
    node.querySelectorAll('[x-data]').forEach((el) => {
        onElRemoveds.forEach((i) => i(el));
        el.remove();
    });
}
```

* If I remove any of the "remove" lines above, I get a DOM node leak per component on Turbo navigation.
* Since `onElRemoveds.forEach((i) => i(el));` is also called for this component via `destroyTree`, I'm guessing it's an order thing (`onElRemoveds` first, then `el.remove`).
* The need for `el.remove()` I guess comes from one of the `_x_` (`_x_runEffects`?) attributes holding on to a DOM node reference or something.

I have had enough JavaScript/browser stuff for a couple of days, but I might eventually be able to demonstrate this with a test case.

**Comment by bep** [comment]
I'm talking a little to myself here, I guess, but I think it's important to somehow record this.

I suggest you ignore my latest remarks about the `el.remove()` above in the discussion about this issue. The core of that turned out to live in Turbo (leaking DOM nodes with permanent components, I will report that upstream, even after they expire from cache).
