### ISSUE TITLE
Allow multiple  x-bind: on an element

### ISSUE THREAD

**Issue by sellig** [alpinejs/alpine#217]
Will like the possibility to do

<div x-bind:class="{ 'text-orange-700': selected !== 0 }"
        x-bind:class="{ 'bg-gray-300': isAdmin }" ></div>

Currently, only the first x-bind:class is applied

Thanks.

**Comment by sellig** [comment]
Will like the possibility to do

`<div x-bind:class="{ 'text-orange-700': selected !== 0 }"
        x-bind:class="{ 'bg-gray-300': isAdmin }" ></div>`

Currently, only the first x-bind:class is applied

Thanks.

**Comment by nandordudas** [comment]
`<div x-data="{ selected: 1, isAdmin: true }"><div x-bind:class="{ 'text-orange-700': selected !== 0, 'bg-gray-300': isAdmin }" /></div>`

If you dont need bind multiple times

**Comment by sellig** [comment]
Thank you Nandor
