### ISSUE TITLE
Add TypeScript typings for better intellisense and TypeScript support.

### ISSUE THREAD

**Issue by zoeleu** [alpinejs/alpine#2199]
Add typings for Alpine.data and Alpine.store for type checking in VSCode and other IDEs.

**Comment by matteoturini** [comment]
closed so @danddanddand can make his own pr

**Comment by lbineau** [comment]
Any news on typescript support? https://definitelytyped.org/ would be fine.

**Comment by wtho** [comment]
@lbineau check out https://github.com/archtechx/alpine-typescript

**Comment by matteoturini** [comment]
[typescript has been added @types/alpinejs](https://www.npmjs.com/package/@types/alpinejs)

**Comment by wtho** [comment]
Yeah, I added them. Feel free to test them thoroughly and ping me if they are incorrect or incomplete (or just open a PR on definitelytyped directly)

**Comment by jessedobbelaere** [comment]
Thanks for adding `@types/alpinejs` @wtho!! I tried it out but had a question about Alpine.store. Should it support a generic like @danddanddand used in the types example above in this issue? 

I have a basic example inspired by the [Alpine.js docs](https://alpinejs.dev/globals/alpine-store#registering-a-store) that I'm trying to migrate from the types of @danddanddand to `@types/alpinejs`:

```typescript
interface DarkModeStore {
    on: boolean;
    toggle: () => void;
}

Alpine.store<DarkModeStore>('darkMode', {
    on: false,

    toggle() {
        this.on = !this.on;
    },
});
```

However, a store has no generic in the DefinitelyTyped version and supports `XData` ([source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/alpinejs/index.d.ts#L204)). Would the generic be an improvement? Or how would you implement the example above?

**Comment by wtho** [comment]
Thanks for the feedback!

I really liked the example with the generics by danddanddand and first tried to implement it the same way, but DefinitelyTyped's linting does not allow generics which are only used once, so I had to remove it unfortunately, although I think it makes sense to have it there.

I might add a new PR next week to try to circumvent the linting for this line specifically, maybe we find other libraries using the same pattern in some types to justify it. If you have more feedback I bundle the improvements in a single PR.

**Comment by hirasso** [comment]
Hi there! I have a question that is very likely not directly related to this, but I hope that someone reading this might be able to help me: 

I installed `@types/alpinejs` from @wtho, so that I don't get warnings for magics like `this.$watch` or `this.$store`. 

While this is working as expected, all my other intellisense stops working (I'm in VS Code). 

Without the type hint on the component, if I `option-hover` the function `sayHello`, my IDE properly detects the function and it's arguments:

![image](https://user-images.githubusercontent.com/869813/206906872-1d527e4c-0179-4afb-bf52-5cab9be313f2.png)

As soon as I add the type hint, the intellisense suddenly stops working:

![image](https://user-images.githubusercontent.com/869813/206906999-f377a726-1867-4d4f-92ca-3f9458003a6e.png)

The only functions that are now recognized are the types defined in the `AlpineComponent` interface:

![image](https://user-images.githubusercontent.com/869813/206907203-22a1e276-dc48-4593-9e5a-4925fd6448d7.png)

I'm pretty new to typescript and pretty sure I'm missing something obvious here. Any helping hand would be much appreciated 🙏

**Comment by hirasso** [comment]
@wtho can I reach you via email somehow? I have a proposition.

**Comment by oleksandr-luxmedien** [comment]
Hey guys, correct me if I'm wrong, but the most obvious way to make it work is to customize types file from `@types/alpinejs` package by adding additional overload for `state` that uses generics as @jessedobbelaere mentioned. 
Like this:

```typescript
...
/**
   * Retrieves state in the global store.
   *
   * @param name state key
   */
  store(name: string): XData;
  /**
   * Retrieves state in the global store and casts it to the specific store type.
   *
   * @param name state key
   */
  store<T>(name: string): T;
   ...
   ```
   
   This one line:
   
   ```typescript
   store<T>(name: string): T;
   ```
   
   Will allow you to get typed store with:
   
   ```typescript
   const store = Alpine.store<storeInterface>('storeName');
   ```

**Comment by hirasso** [comment]
@oleksandr-luxmedien I like that a lot! This would be a much cleaner alternative to what I'm doing now:
```ts
const store = Alpine.store('storeName') as StoreInterface;
```
It would be amazing to also get support for this for the `this.$store` magic. Right now that resolves to a generic `XData` type

**Comment by hirasso** [comment]
@wafiahartono actually I didn't, really. The only way to get it to *kind of* work was by defining all methods I was using in the component to help IntelliSense to pick it up:

```js
import type { AlpineComponent } from "alpinejs";

type Component = AlpineComponent<{
   open: boolean;
   method1: () => void;
   method2: () => void;
   // .... 😐
}>

export default () => {

  return <Component>{
    open: false,
    init() {
        this.method1(); // this method will be found because it is defined in the Component's type definition
        this.someOtherMethod(); // this method won't be found, it's not in the type definition
    },
    method1() {},
    method2() {},
    someOtherMethod() {},
};

```
And then I can use "Go to Implementations" in VsCode to jump from a function call to the actual implementation (instead of the type definition). I created a custom keyboard shortcut for that (<kbd>⌘</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd>), since  the <kbd>Option</kbd>-click seems not to be customizable in VsCode.

**Comment by hirasso** [comment]
Hmm, don't know what's wrong there. It's working for me:

![image](https://github.com/alpinejs/alpine/assets/869813/1e62e880-2356-43fe-a128-c4dc9b6ec1bb)

**Comment by ajschmidt8** [comment]
@wafiahartono, did you get this working?

I can't seem to get VSCode to recognize the `this` object either for my components.

Here's my minimal reproducer:

<details><summary>Source Code</summary>
<p>

```ts
import { AlpineComponent } from "alpinejs";

interface TestComponent {
  property1: string;
  property2: string;
  method1(): string;
  method2(): string;
}

export default (): AlpineComponent<TestComponent> => ({
  property1: "string1",
  property2: "string2",
  method1() {
    this.method2();
    return "";
  },
  method2() {
    return "";
  },
});
```

</p>
</details> 


Here's a screenshot of the `this` keyword resolving to `any`:

![image](https://github.com/alpinejs/alpine/assets/7400326/cdd504be-101b-4175-aa92-36a64274704a)

Here's a version dump:

```yaml
alpinejs: 3.12.3
@types/alpinejs: 3.7.2
vscode: 1.78.2
```

**Comment by ajschmidt8** [comment]
I was able to work around this by adding `this: TestComponent` as an argument to the methods in my component signature:

<details><summary>Source Code</summary>
<p>

```ts
import { AlpineComponent } from "alpinejs";

type TestComponent = AlpineComponent<{
  property1: string;
  property2: string;
  method1(this: TestComponent): string;
  method2(this: TestComponent): string;
}>;

export default function (this: TestComponent): TestComponent {
  return {
    property1: "string1",
    property2: "string2",
    method1() {
      this.method2();
      return "";
    },
    method2() {
      return "";
    },
  };
}

```

</p>
</details> 

Here's a screenshot of `this` being recognized now:

![image](https://github.com/alpinejs/alpine/assets/7400326/86896d20-8e6d-4dc0-a864-5f06173b0c65)

**Comment by dannylindquist** [comment]
For anyone else trying to make this work well. The typing for `AlpineComponent` use `ThisType` which only works if you have `"noImplicitThis": true,` set within your `tsconfig` file. Just turned this on and now have all the magics showing up for this along with the rest of the type def.

**Comment by mickaelchanrion** [comment]
@hirasso Your approach with components was interesting but having the type definition separated from the implementation is a bit annoying since you kind of have to type things "twice".

I managed to fix this issue using a helper function. Its sole purpose is to augment the types with Alpine's internals and return the function as is:

In a utils file:
```ts
import type { AlpineComponent } from 'alpinejs'

const defineComponent = <P, T>(fn: (params: P) => AlpineComponent<T>) => fn

export { defineComponent }
```

In the component file:
```ts
import { defineComponent } from '~/utils/define-component'

export default defineComponent(() => ({
  isOpen: false,
  init() {
    this.$watch('isOpen', (value) => {
      this.onIsOpenChange(value)
    })
  },
  onIsOpenChange(value: boolean) {
    console.log('isOpen changed to ', value)
  }
}))
```

**Comment by hirasso** [comment]
@mickaelchanrion this is beautiful, thanks for sharing!

**Comment by mickaelchanrion** [comment]
@hirasso I can't think of a better way. I'd do that as well or just take advantage of `x-ref`.

That being said, it's usually [recommended](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v49.0.0/docs/rules/no-null.md#why) to use `undefined` over `null`.

```ts
export default defineComponent(() => ({
  myElement: undefined as HTMLElement | undefined,
  init() {
    const myElement = this.$root.querySelector('.my-element')
    if (myElement) {
      this.myElement = myElement
    }
  }
}))
```

Or 
```html
<div x-ref="myElement"></div>
```
```ts
export default defineComponent(() => ({
  myElement: undefined as HTMLElement | undefined,
  init() {
    this.$refs.myElement
  }
}))
```

**Comment by hirasso** [comment]
@mickaelchanrion thanks for this! I was using `null` for the initial value of `myElement` since that's what `querySelector` returns if it doesn't match any element. And I'm aware of `$refs`, but had some weird behavior with that magic in the past, so I developed a routine to not use it. (was sometimes not returning the `ref` although I had it defined in my markup).

**Comment by IHIutch** [comment]
@mickaelchanrion Thanks for the util function, its really helpful. Im still a bit of a TS noob, is there anything similar that could be done for Alpine globals? In my case, for example, I'm trying to create custom directives rather than components.

**Comment by mickaelchanrion** [comment]
@IHIutch Yes indeed. You can use a wrapper function as well. 
I will actually share all my setup so everyone can benefit from it. It's far from perfect though so I'll be happy to read suggestions :)

`utils/alpine.ts`:
```ts
import type { AlpineComponent, DirectiveCallback } from 'alpinejs'

/**
 * Define an Alpine component (wraps the function with Alpine's internals)
 */
export const defineComponent = <P, T>(
  function_: (parameters: P) => AlpineComponent<T>,
) => function_

/**
 * Define an Alpine directive (wraps the function with Alpine's internals)
 */
export const defineDirective = (function_: DirectiveCallback) => function_

export default { defineComponent, defineDirective }
```

**Example of directive**
```ts
interface Options {
  message: string
  delay?: number
}

const isOptionsValid = (value: unknown): value is Options => {
  if (typeof value !== 'object' || !value) return false
  return !!('message' in value && typeof value.message === 'string')
}

/**
 * x-alert directive: Alerts on click
 * @example Say "Hello!" with a delay of 500ms
 * <button x-alert="{ message: 'Hello!', delay: 500 }">Say hello</button>
 */
defineDirective((element, { expression }, { evaluate }) => {
  element.addEventListener('click', (event) => {
    event.preventDefault()
    const options = evaluate(expression)
    if (!isOptionsValid(options)) return

    const { message, delay = 0 } = options
    setTimeout(() => {
      window.alert(message)
    }, delay)
  })
})
```

I also made the store public as sometimes, I need to read/write states from outside of Alpine's scope:

```ts
document.addEventListener('alpine:initialized', () => {
  // Make Alpine's store available globally
  const result = document.querySelector('[x-data]')

  if (result) {
    // @ts-expect-error Alpine's store will be available at this path so this is type-safe
    window.$store = result._x_dataStack[0].$store
  } else {
    throw new Error(
      'No x-data found, the page should have at least one element with the x-data attribute.',
    )
  }
})
```

The store can also be typed (here I have a simple example with a store module called ui where I put everything related to the user interface):

`store/index.ts`
```ts
import Alpine from 'alpinejs'
import ui from './ui'

export default function register() {
  Alpine.store('ui', ui)
}

export type Store = {
  ui: typeof ui
}

declare global {
  type Store = {
    ui: typeof ui
  }

  interface Window {
    $store?: Store
  }
}

```

Now, to use the typed Store:
- inside the alpine's context (like a component): `(this.$store as Store).ui`
- outside: `window.$store` (beware, the type is `Store | undefined` as you might try to access that before Alpine was even initialized)

While I agree that those statements are not great, I created a composable function:

`composables/useStore.ts`
```ts
import { Magics } from 'alpinejs'

function useStore(scope: Magics<object>): Store
function useStore(scope?: undefined): Window['$store']
function useStore(scope: Magics<object> | undefined): Store | Window['$store'] {
  if (scope !== undefined) return scope.$store as Store
  return window.$store
}

export { useStore }
```

**Usage inside a component**
```ts
import { defineComponent } from '~/utils/alpine'
import { useStore } from '~/composables/useStore'

export default defineComponent(() => ({
  init() {
    const store = useStore(this) // yay! 💪
  }
})
```

**Usage without Alpine's Magics available**
```ts
import { useStore } from '~/composables/useStore'

const store = useStore() // Store | undefined
```

**Comment by IHIutch** [comment]
Thank you for sharing!

**Comment by elied** [comment]
I'm not the most adept TypeScript user and I couldn't really figure out how to use the @types/alpinejs typing to help me when defining a component. I briefly tried @mickaelchanrion's solution but it wasn't working for me, and I also am not familiar enough with TypeScript to see how it was supposed to work.

My (maybe naive) perspective is that the typings in @types/alpinejs are technically very accurate, but aren't actually that helpful or easy to use if you just want to be able to write a component with type-safety that can check if you are using properties correctly. I would love if I am wrong here and someone could better explain how to use the standard types here, but I'm not seeing it.

I went with the approach of rolling out my own basic setup with a simpler typing that I found to be more useful. The approach is inspired by the [alpine-typescript](https://github.com/archtechx/alpine-typescript) package that was designed for Alpine v2. Basically, we just define a class hierarchy and then provide a method to convert a class instance into the flat object literal structure that Alpine expects.

I've briefly tested things and it seems to work pretty well, though it is not thoroughly battle-tested so YMMV.

Basically I've just defined a base class like this:

```js
export interface ReactiveProps {}
export interface ComponentRefs {}
export interface DefaultComponentRefs
    extends Record<string, HTMLElement | undefined> {}

export abstract class BaseAlpineComponent<
    T extends ReactiveProps,
    R extends ComponentRefs = DefaultComponentRefs,
> {
    $data!: T;
    $el!: HTMLElement;
    $refs!: R;
    $root!: HTMLElement;
    $store!: Record<string, any>;

    $dispatch!: (eventType: string, detail?: any) => void;
    $id!: (name?: string, key?: number | string) => string;
    /* NOTE: The callbacks for $nextTick and $watch functionally work correctly, but
    debuggers can get confused about `this` inside of the callback and may show "not available".
    Rest assured that `this` still points to the Alpine component correctly.
    Use console.log() for debugging instead. */
    $nextTick!: (callback: () => void) => void;
    $watch!: <K extends keyof T>(
        property: K,
        callback: (newValue: T[K], oldValue: T[K]) => void,
    ) => void;

    init?(): void;
    destroy?(): void;

    toAlpineData(): Record<string, any> {
        // Convert the instance to a flat object
        const instance = this;
        const alpineData: Record<string, any> = {};

        // Copy over properties from class instance
        Object.getOwnPropertyNames(instance).forEach((prop) => {
            alpineData[prop] = instance[prop];
        });

        // Handle methods defined in the prototype as well
        let prototype = Object.getPrototypeOf(instance);
        while (prototype && prototype !== Object.prototype) {
            // Avoid iterating over Object's prototype properties/methods
            const descriptors = Object.getOwnPropertyDescriptors(prototype);
            for (const [key, descriptor] of Object.entries(descriptors)) {
                if (
                    key !== "constructor" &&
                    typeof descriptor.value === "function"
                ) {
                    alpineData[key] = descriptor.value;
                }
                if (descriptor.get) {
                    alpineData[key] = descriptor.get();
                }
            }
            prototype = Object.getPrototypeOf(prototype);
        }

        return alpineData;
    }
}
```
Note that `ComponentRefs` are optional. If you want to create an interface for your component's $refs, you can do that and get typings for them. If you don't specify anything, `this.$refs` will allow any string and return HTMLElement | undefined.

To actually define a component, you would define it like this:
```js
interface DropdownSearchProps extends ReactiveProps {
    open: boolean;
    searchText: string;
}

interface DropdownSearchRefs extends ComponentRefs {
    search: HTMLInputElement;
}

class DropdownSearch
    extends BaseAlpineComponent<DropdownSearchProps, DropdownSearchRefs>
    implements DropdownSearchProps
{
    open = false;
    searchText = "";

    constructor(initialText: string) {
        super();
        this.searchText = initialText;
    }

    toggle() {
        this.open ? this.closeDropdown() : this.openDropdown();
    }

    openDropdown() {
        this.open = true;
        this.$nextTick(() => {
            this.$refs.search.focus();
        });
    }

    closeDropdown() {
        this.open = false;
    }

    // I like to define encapsulated x-bind directives as getters.
    // Note that we do still need to add an explicit type annotation for `this` for the inner functions.
    get toggleButton() {
        return {
            ["@mousedown"]: function (this: DropdownSearch) {
                this.toggle();
            },
        };
    }

    // Encapsulated x-bind directives can also be defined as properties with object literals
    otherToggleButton = {
        ["@mousedown"]: function (this: DropdownSearch) {
            this.toggle();
        },
    };
}
```

And then to pass that to Alpine, you would call this:
```js
Alpine.data("dropdownSearch", (initialText:string) => new DropdownSearch(initialText).toAlpineData());
```

The simpler typing means that you get more reliable type-safety around `this`, and the `$watch` magic can also check that you are passing in a valid property name.

One obvious downside is that these types are overly simplified and do not represent what might be actually happening at runtime. One example of this is that `this.$data` will contain any nested properties, but this type system will pretend like it only contains the properties defined in this component. I don't think these downsides are very consequential though - whenever I am writing a reusable component, I don't rely on inherited data properties.

The other big downside is that it doesn't leverage the standard types from @types/alpinejs, but like I said in the beginning, I found those hard to use.

Hopefully this can be useful to someone else who struggles with advanced TypeScript.

**Comment by Mushr0000m** [comment]
> @hirasso Your approach with components was interesting but having the type definition separated from the implementation is a bit annoying since you kind of have to type things "twice".
> 
> I managed to fix this issue using a helper function. Its sole purpose is to augment the types with Alpine's internals and return the function as is:
> 
> In a utils file:
> 
> ```ts
> import type { AlpineComponent } from 'alpinejs'
> 
> export const defineComponent = <P, T>(fn: (params: P) => AlpineComponent<T>) => fn
> ```
> 
> In the component file:
> 
> ```ts
> import { defineComponent } from '~/utils/define-component'
> 
> export default defineComponent(() => ({
>   isOpen: false,
>   init() {
>     this.$watch('isOpen', (value) => {
>       this.onIsOpenChange(value)
>     })
>   },
>   onIsOpenChange(value: boolean) {
>     console.log('isOpen changed to ', value)
>   }
> }))
> ```

I realy like your solution but can't find a way to writte multiple initial parameters like `defineComponent((foo:string, bar: boolean).....` that come from HTML `x-data='someComponent("lorem-ipsum", false)'` any suggestion ?

**Comment by mickaelchanrion** [comment]
@Mushr0000m 
> I realy like your solution but can't find a way to writte multiple initial parameters like `defineComponent((foo:string, bar: boolean).....` that come from HTML `x-data='someComponent("lorem-ipsum", false)'` any suggestion ?

Very good question. This is what I also wanted to do at first but I couldn't find a way to express this in typescript. What I do is I pass an object. It's not very elegant in the html but it works and everything remains typed.

```ts
export interface MyComponentOptions {
  foo?: string
  bar?: number
}

export default defineComponent((options: MyComponentOptions = {}) => ({
  // component stuff
}))
```

**Comment by mickaelchanrion** [comment]
The setup I shared last year has evolved a bit.
- `useStore()` now deprecated in favor of `this.$store`, fully typed with all registered modules
- typed custom magics (`this.$myMagic`)
- auto import components, directives, magics and store modules (using vite): create a file in the corresponding folder and voilà, it just works

If anyone is interested, I'll be glad to share!

**Comment by hirasso** [comment]
> If anyone is interested, I'll be glad to share!

Yes please do share 🤠

**Comment by mickaelchanrion** [comment]
I've just created a repo to reference all that. Enjoy :) 
https://github.com/mickaelchanrion/alpine-ts

**Comment by hirasso** [comment]
Wow @mickaelchanrion thank you so much, that is a valuable resource!! I especially love the simpler approach for typed stores 👏
