### ISSUE TITLE
Details boolean attribute "open" doesn't seem to be supported

### ISSUE THREAD

**Issue by wishinghand** [alpinejs/alpine#220]
According to the docs:

> Most common boolean attributes are supported, like readonly, required, etc.

I'm trying to open multiple `<details>` elements and am trying to bind them in the same scope.

Here is an example of how I'm trying to accomplish this:

```
<div x-data="flags()">
    <details x-bind:open="enforcement">
        <summary  @click="toggleEnforcement()">Enforcement</summary>
    </details>
....

    <details x-bind:open="enforcement">
        <summary  @click="toggleEnforcement()">Enforcement</summary>
    </details>
</div>

...

<script>
function flags() {
    return {
        enforcement: false,
        toggleEnforcement() {
          console.log(this.enforcement)
          this.enforcement = !this.enforcement
        }
    }
}
</script>
```

I can't seem to get all of the details to open if any particular element is opened. Is `open` supported?

**Comment by HugoDF** [comment]
It looks like `open` is not currently treated as a boolean attribute. I'll submit a PR to fix.

**Comment by HugoDF** [comment]
@calebporzio 👆 

I'll create a new issue to support all boolean attributes if that's something we want to do?
