### ISSUE TITLE
Iteration is reversed when used with x-if

### ISSUE THREAD

**Issue by Jelenkee** [alpinejs/alpine#2210]
### Discussed in https://github.com/alpinejs/alpine/discussions/2209

<div type='discussions-op-text'>

<sup>Originally posted by **Jelenkee** October 10, 2021</sup>
https://codepen.io/kuhschubser/pen/zYdYpOY</div>

**Comment by SimoTod** [comment]
There are also issue when moving elements because the generated HTML doesn't follow the parent template tag so for now it's safer to use a div around your x-if.
Unfortunately, the current PR does not fix it yet (https://codepen.io/SimoTod/pen/jOLzRXN) cc @domcorvasce

**Comment by domcorvasce** [comment]
@SimoTod you are right, good catch. I went straight for `x-if` but I will try to check `x-for` logic and see if I notice something. Thanks again.

**Comment by SimoTod** [comment]
@domcorvasce I believe you need to do something in here: https://github.com/alpinejs/alpine/blob/main/packages/alpinejs/src/directives/x-for.js#L156-L157
When you move elements, if they have _x_currentIfEl, you will also move the generated element (or something along those lines).

**Comment by gbro3n** [comment]
I have found that if you nest `x-if`, when combined with `x-for`, the output is still reversed (version 3.13.2).

In my case it was 2 x `x-for` and 2 x `x-if` e.g.

```
<template x-for="...">
    <template x-if="...">
        <template x-if="...">
            <template x-for="...">
            </template">
        </template">
    </template">
</template">
```

The logic from the 2 `x-if`s can be combined so I only require 1 `x-if`, but this might not always be the case.

**Comment by ramiboutas** [comment]
> I have found that if you nest `x-if`, when combined with `x-for`, the output is still reversed (version 3.13.2).
> 
> In my case it was 2 x `x-for` and 2 x `x-if` e.g.
> 
> ```
> <template x-for="...">
>     <template x-if="...">
>         <template x-if="...">
>             <template x-for="...">
>             </template">
>         </template">
>     </template">
> </template">
> ```
> 
> The logic from the 2 `x-if`s can be combined so I only require 1 `x-if`, but this might not always be the case.

I have the same problem. I even have an example in production (see link below), it there any workaround or fix?

https://ramiboutas.com/tools/invoice/

**Comment by ramiboutas** [comment]
In my small  tool, when I add a new article for generating an invoice, the new article gets in the first position.

Let us say we have these articles:
![grafik](https://github.com/alpinejs/alpine/assets/33960822/c9515798-a2b9-43d6-8daf-0d9e7e28fd67)

And now we want to add a new one, the behavior of x-for is as follows:

![grafik](https://github.com/alpinejs/alpine/assets/33960822/4f88f01f-9fbf-4798-83d1-69f8c6df5369)

**Comment by pohlt** [comment]
This bit me several times now. If fixing is out of the question, could we please add a comment in the x-for docs mentioning this quirk?
