### ISSUE TITLE
Feature: support more/all boolean attributes

### ISSUE THREAD

**Issue by HugoDF** [alpinejs/alpine#223]
Follow up from https://github.com/alpinejs/alpine/issues/220, where the "open" boolean attribute was not implemented as such.

> A number of attributes are boolean attributes. The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents the false value.
>
> as per the HTML spec: https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes

The following seems to be a table of boolean attributes although it might be worth cross-referencing with the HTML spec: https://github.com/iandevlin/html-attributes/blob/master/boolean-attributes.json

HTML spec attributes table: https://html.spec.whatwg.org/multipage/indices.html#attributes-3:boolean-attribute

If I can get signoff from @calebporzio I'm happy to contribute this.

**Comment by calebporzio** [comment]
Would love a PR to support all of them. Thanks!
