### ISSUE TITLE
Fire events after load, update, reload, etc

### ISSUE THREAD

**Issue by ryangjchandler** [alpinejs/alpine#228]
I think this would be useful for anyone who wants to hook into Alpine from outside of their components, possibly inside of a scoped JS file.

I have a working branch for this, using the dispatch() function from Livewire. I'm also working on a devtools panel for alpine and this would be super useful so I don't have to mess around with more Proxies etc, cc/ @calebporzio

**Comment by ryangjchandler** [comment]
After some dispute on the events that should be fired, to begin with I'm going to keep the list short:

* alpine:loaded
* alpine:transition-start
* alpine:transition-end

**Comment by ryangjchandler** [comment]
Closing this issue for now, since this will probably be re-evaluated for v3.

**Comment by TheMangoTrain** [comment]
This is exactly what's needed for something like sequential animations, instead of trying to fake it with animation delays.
