### ISSUE TITLE
Listen to a custom event and pass event

### ISSUE THREAD

**Issue by keyurshah** [alpinejs/alpine#23]
Seeing if it would be possible for `x-on` to listen to a custom event and pass the event to the expression function.

In the example below, I'm trying to pass data between components. 

https://codepen.io/kjshah/pen/fe0ecb50b49d61a0eb55eaeb9c3bf7d2?editors=1011

It would be great if the following example could work, with `cart-quantity-updated` being the custom event (listened to) and `updateTotal(event)` being called when the event occurs.

```
<span x-text="total" x-on:cart-quantity-updated="updateTotal(event)"></span>
```

**Comment by calebporzio** [comment]
So, Project X CAN actually listen for custom events. Check out the following example:

```html
<div x-data="{}">
    <span x-on:hey="console.log('hey')">
        <div x-data="{}">
            <button x-on:click="$dispatch('hey', { target: $event.target })">Fire Event</button>
        </div>
    </span>
</div>

<script>
        // I grabbed this from Turbolink's codebase.
 function $dispatch(eventName, { target, cancelable, data } = {}) {
    const event = document.createEvent("Events")
    event.initEvent(eventName, true, cancelable == true)
    event.data = data || {}

    // Fix setting `defaultPrevented` when `preventDefault()` is called
    // http://stackoverflow.com/questions/23349191/event-preventdefault-is-not-working-in-ie-11-for-custom-events
    if (event.cancelable && ! preventDefaultSupported) {
        const { preventDefault } = event
        event.preventDefault = function () {
            if (! this.defaultPrevented) {
                Object.defineProperty(this, "defaultPrevented", { get: () => true })
            }
            preventDefault.call(this)
        }
    }

    (target || document).dispatchEvent(event)
    return event
}

const preventDefaultSupported = (() => {
    const event = document.createEvent("Events")
    event.initEvent("test", true, true)
    event.preventDefault()
    return event.defaultPrevented
})()
</script>
```

**Comment by keyurshah** [comment]
thanks for that, that helped me get it working.

here's a [working demo](https://codepen.io/kjshah/pen/7028dd5acd9b9a92ab28ec0c62720367?editors=1010) with the example you gave with `createEvent`

and i realized the issue with the initial example I gave, I was using `document.dispatchEvent()` instead of `window.dispatchEvent()`

and then also adding `.window` to the `x-on` listener. here's the [fixed version](https://codepen.io/kjshah/pen/6a873cf747a4bad5c581a710dae0809a?editors=1011)

**Comment by keyurshah** [comment]
actually, one more question on this, would there be any benefit to adding a `.document` modifier for `x-on`? or does the `.window` modifier cover all use cases?

**Comment by pfrlv** [comment]
> actually, one more question on this, would there be any benefit to adding a `.document` modifier for `x-on`? or does the `.window` modifier cover all use cases?

Many libraries such as Swup or Turbolinks cause custom events on document. I often use global events such as `mediaQueryUpdated` and `resized`

**Comment by keyurshah** [comment]
looks like it was added in PR #41 . Thanks!
