### ISSUE TITLE
Is this possible with Alpine?

### ISSUE THREAD

**Issue by adbarnes** [alpinejs/alpine#239]
Hi,

Is it possible to write something similar to this with Alpine?

:class="{ sidebarOpen ? 'classiftrue' : 'classiffalse' }"

Been trying to get this work but it wont.

Thanks

**Comment by adbarnes** [comment]
That's great, thank you.

**Comment by adbarnes** [comment]
Hi,

So the above worked but I noticed it acts differently to Vue.

I'm trying to replicate the following Vue code:

`:class="sidebarOpen ? 'translate-x-0 ease-out transition-medium' : '-translate-x-full ease-in transition-medium'"`

I'm using the following Alpine example based on the suggestion above:

`:class="{ [sidebarOpen ? 'translate-x-0 ease-out transition-medium' : '-translate-x-full ease-in transition-medium']: true }"`

The problem is that with Vue, the classes get added and removed.  But it seems with the Alpine example above the classes are added but not removed.

Am I doing something wrong?

Thanks

**Comment by HugoDF** [comment]
@adbarnes your snippet is using both object and array syntax

`:class="{ [sidebarOpen ? 'translate-x-0 ease-out transition-medium' : '-translate-x-full ease-in transition-medium']: true }"`

Should actually be

`:class="[sidebarOpen ? 'translate-x-0 ease-out transition-medium' : '-translate-x-full ease-in transition-medium']"`

Or
`:class="{  'translate-x-0 ease-out transition-medium' : sidebarOpen, '-translate-x-full ease-in transition-medium': !sidebarOpen }"`

**Comment by HugoDF** [comment]
@adbarnes be aware that my last example in the initial comment might have been wrong, I've edited to illustrate what I actually meant.

**Comment by adbarnes** [comment]
Yep, that did it.

Many , many thanks
