### ISSUE TITLE
reactivity doesnt work in array objects

### ISSUE THREAD

**Issue by nkostadinov** [alpinejs/alpine#240]
```
<li class="nav-item" x-show="groups.length === 0">
     <div class="text-center pt-2 hint">Click on a link to see the matched groups here.</div>
</li>
```
In the above example the condition is correctly checked on load, but if you later add an item to the groups object nothing happens. It seems that arrays are not properly observed.
I tried :
```
groups.push(item)
groups = items
```

**Comment by HugoDF** [comment]
@nkostadinov the workaround is to replace the whole `group` array with a copy

eg.
```
groups = groups.concat(item)
```

**Comment by nkostadinov** [comment]
Actually it works but only sometime. Look at this jsfiddle: https://jsfiddle.net/nikolakk/wb1cj4dx/

If I attach a handler via addEventListener it doesnt work.

**Comment by tlgreg** [comment]
That fiddle has a different issue. The `this` in the manual event handler is a different `this` then you expect and doesn't have access to `groups`.
You can bind the handler manually.
```diff
-      btn.addEventListener('click', this.addEl);
+      btn.addEventListener('click', this.addEl.bind(this));
```

**Comment by nkostadinov** [comment]
thanks @tlgreg :) you solution works fine :). I come from Vue and it did work that way there.
