### ISSUE TITLE
Reduce shipped npm module size

### ISSUE THREAD

**Issue by HugoDF** [alpinejs/alpine#244]
Kinda low priority & "nice to have"

Currently the package on npm includes src, test, example etc folders which aren't necessary to use the npm module.

We probably want to add a "files" property to package.json to only ship the "dist" folder so that people installing alpine.js get a snappy experience.

See https://docs.npmjs.com/files/package.json#files

Alternatively we can use an `.npmignore` file.

**Comment by calebporzio** [comment]
I personally like it when I can source dive deps directly in node-modules. Unless it's an actual problem, let's hold off on this.

**Comment by HugoDF** [comment]
Makes sense to me

**Comment by HugoDF** [comment]
Just adding a comment here, since the fact the size of the npm module can create confusion, see https://github.com/alpinejs/alpine/discussions/745.

Currently the npm module is shipping 700kb+ and 64 files, of which only 2 are used (the `dist` JS files), other usefule files would be the README & package.json. Which is 4 files vs 60+. See https://www.npmjs.com/package/alpinejs

![Screenshot 2020-09-04 at 13 40 21](https://user-images.githubusercontent.com/6459679/92240336-5ec95c00-eeb4-11ea-8cc3-e3a974b7f1d8.png)

This compares poorly with regards to eg. React: https://www.npmjs.com/package/react, with unpacked size "204 kB" & 10 files.

Even Vue (which has a large unpacked size because they include the source files) filters to only select `src`, `dist` and `types` (see https://github.com/vuejs/vue/blob/dev/package.json#L10-L14) even though its unpacked size comes to about 3MB (https://www.npmjs.com/package/vue)
