### ISSUE TITLE
Getting syntax error with NextJS

### ISSUE THREAD

**Issue by AlexanderArvidsson** [alpinejs/alpine#246]
I am getting the following error when attempting to use this with NextJS:
```
Failed to compile
./components/Navbar.js
SyntaxError: /home/metamist/dev/node/utlaggdtek/components/Navbar.js: Unexpected token (3:29)

  1 | import React from "react";
  2 | 
> 3 | const Component = () => <div @keydown.window.escape="open = false" />;
    |                              ^
  4 | 
  5 | // const Navbar = () => (
  6 | //   <nav x-data="{ open: false }" @keydown.window.escape="open = false" class="bg-gray-800">
This error occurred during the build time and cannot be dismissed.
```
Here is a simple component that I cannot get working:
```
const Component = () => <div @keydown.window.escape="open = false" />;
```

This is my .babelrc:
```
{
  "presets": ["next/babel"],
  "plugins": [
    "babel-plugin-root-import"
  ]
}
```

I cannot find any information about any package and I am using the latest packages (I just updated everything).
It is pretty much a completely fresh NextJS project with barely anything in it.

Am I missing something in my babelrc or some plugin? Prettier cannot parse the file either.

Using Node v10.13.0 on Linux (Archlinux).

**Comment by HugoDF** [comment]
JSX compilers don't support @ or Alpine.js' use of colons inside of attributes.

To use Alpine.js you'll need to use dangerouslySetInnerHTML, I've written a post up about this: https://codewithhugo.com/alpine-js-react/

**Comment by HugoDF** [comment]
The good news is that Alpine.js _does_ work when run inside of React.

**Comment by AlexanderArvidsson** [comment]
@HugoDF that's a little too bad, I would have loved to use React with Alpine to have easy state management when dealing with simple open/close states for example.
Thank you for the post, I'll make sure to read through it!

**Comment by HugoDF** [comment]
You can use Alpine.js inside of React, you just can't write Alpine.js attribute bindings in JSX, hence the workaround I've posted.

**Comment by AlexanderArvidsson** [comment]
@HugoDF I understand that, but writing my components in template strings kind of defeats the entire purpose of React, which means the only option with your workaround is either using React, or using Alpine, not both together.
It also would mess up Prettier auto formatting on save.
It would be nice if JSX compilers would support those attributes so that they could work together rather than independently.

**Comment by dancomanlive** [comment]
[ ready ] compiled successfully - ready on http://localhost:3001
ReferenceError: navigator is not defined
at isTesting /node_modules/alpinejs/dist/alpine.js:79:5

```
import React, { useState, useEffect } from 'react';
import "./index.css"
import 'alpinejs';

const alpineTemplate = `<div x-data="counter()">
  <button @click="inc()">Increment</button>
  <p x-text="count"></p>
</div>`;

const AlpineWidget = () => (
  <div dangerouslySetInnerHTML={{__html: alpineTemplate}} />
);

function Button({ children, ...buttonProps }) {
  return (
    <button
      className="px-2 py-1 rounded-lg bg-green-400 text-green-800 text-xl font-light uppercase shadow-md hover:shadow-lg"
      {...buttonProps}
    >
      {children}
    </button>
  );
}

export default function Home() {
  
  return (
    <AlpineWidget />
  )
}
```

Using Next js with Tailwind

**Comment by HugoDF** [comment]
I'm assuming that happens when server-rendering?

The offending line is https://github.com/alpinejs/alpine/blob/master/src/utils.js#L27 

If you could make the AlpineWidget run client-side only that would fix it I think.

**Comment by AlexanderArvidsson** [comment]
@dancomanlive You can solve that error by importing Alpine with dynamic and disabling SSR. Essentially, only load Alpine on the client since server has no state.

**Comment by HugoDF** [comment]
@AlexanderArvidsson @dancomanlive have you managed to get Alpine.js working inside of Next? If yes, would be good to close this issue.

**Comment by AlexanderArvidsson** [comment]
No, I dropped the matter since I'd rather wait for some kind of solution for parsers to work with the extra symbols. So I'll close it for now. Thanks anyway :)

**Comment by BosNaufal** [comment]
The errors seem to come from the JSX parser. We can trick it by using spread object props.

```jsx
<div x-data="{ isEditing: false }">
  <textarea 
    class="textarea w-full textarea-ghost font-normal"
     {...({"@keyup.esc": "isEditing = false"})}
  ></textarea>
</div>
```
