### ISSUE TITLE
Not minified since 2.1 release

### ISSUE THREAD

**Issue by adevade** [alpinejs/alpine#249]
[2.0.2](https://cdn.jsdelivr.net/gh/alpinejs/alpine@2.0.2/dist/alpine.js) vs [2.1.0](https://cdn.jsdelivr.net/gh/alpinejs/alpine@2.1.0/dist/alpine.js)

Any particular reason for it not being minified anymore?

**Comment by HugoDF** [comment]
Yes see @calebporzio's comment on the PR that introduced this change:

https://github.com/alpinejs/alpine/pull/230#discussion_r388699671

And for resolution you can load `alpine.min.js` from JSDeliver: https://cdn.jsdelivr.net/gh/alpinejs/alpine@2.1.0/dist/alpine.min.js minified using Terser on their end.

From this comment

https://github.com/alpinejs/alpine/pull/230#discussion_r389148806

**Comment by adevade** [comment]
Thank you for the info! 👍
