### ISSUE TITLE
Pushing to array under x-data will cause repeated rendering

### ISSUE THREAD

**Issue by ahmedkandel** [alpinejs/alpine#250]
Hi,

First i have to thanks you all for the great work :clap:. I am working on a **Shopping Cart** app that adds a list items to the cart then calculate the **Total** and **Tax**. To make it easier i will use a todo app to demonstrate my issues. Here is a codepen https://codepen.io/tomorrowsystem/pen/ZEGavzW?editors=1001

My issues are: 

1. When `x-text` directive is assigned to a function output the function gets call one on `x-data` update or delete which is correct while on `x-data` addition it gets called multiple times, i doubt it may be a BUG.

2. The `todoCount()` is a computed property. Is there a better way to get it other than assigning a function to `x-text` directive ?

3. After the `x-for` directive and the computed values finish rendering i want to do some DOM manipulation e.g. focus on an input. I can't use `$nextTick` as there is no event. So how can i listen to Render or Refresh or `$nextTick` at component level ?

Thanks.

**Comment by ahmedkandel** [comment]
Hello Guys,

After some more examination it seems not to be related to `x-text` but in general adding items to child array of `x-data` will re-render the component multiple times, so i have changed the title of this issue. Here is a simple example https://codepen.io/tomorrowsystem/pen/zYGRRmL?editors=1001

Am i doing something wrong?

Thanks

**Comment by SimoTod** [comment]
No, it's correct. It's something that could be improved in the future, I think.
At the minute, the component refreshes every time there is a change to a property in x-data or in one of the nested objects. When you push something to an array, the javascript engine sets 2 properties:
the item itself (for example, todos[0]) and the length property of the array (Javascript don't count the element when you use array.length, it returns the value of that cached property).

**Comment by ahmedkandel** [comment]
Thanks @SimoTod, Yes the proxy is setting the array length property which will cause another refresh as  it is treated as a mutated value.

I was digging more and found that in "salesforce/observable-membrane" inside the `set` trap of `ReactiveProxyHandler` there is a conditional statement to check if the mutated property is array length, Here: https://github.com/salesforce/observable-membrane/blob/master/src/reactive-handler.ts#L80

I think if we change it from `if (key === 'length' && isArray(originalTarget))` to `if (key === 'length' && isArray(originalTarget) && oldValue !== value)` this will skip marking length property as mutated when is not needed.

There is a comment in "salesforce/observable-membrane" telling that this part is a fix for issue number 236 but as observable-membrane was a part of another multi-package i can't track what was the reason for this fix.

My concern here regrading repeated refresh is for performance when dealing with large set of data.

Thanks.

**Comment by SimoTod** [comment]
It won't be easy to convince salesforce to change their library because of Alpine. It's a completely different project and if they put that code there, they probably need it but you can try. 

It's more likely that you can prevent it in Alpine itself when we run the mutated property handler (https://github.com/alpinejs/alpine/blob/df1bec9ee5bad0105ff940372ccac89b7c0e22b8/src/component.js#L87) and send a PR for Caleb to review but you need to make sure it won't break other functionalities.

**Comment by ahmedkandel** [comment]
Fixed accordingly by #276
