### ISSUE TITLE
Documentation Website

### ISSUE THREAD

**Issue by octoper** [alpinejs/alpine#255]
Hey,
Are you planning to built a documentation website?
If you won't I can make it, let me know if you want me to make it

**Comment by HugoDF** [comment]
I'm happy to help with this as well. It seems the README is the documentation site at the moment.

I've been hanging around the issues helping out where I can, updating the README, publishing articles on my own website and setting up some examples repo at https://github.com/HugoDF/alpinejs-playground.

We might need input from @calebporzio on how to work towards official Alpine.js resources.

**Comment by octoper** [comment]
Yeah we might need.
However I've already started setting up things for the site

**Comment by ryangjchandler** [comment]
I think Caleb is waiting for the documentation in the README to get out of hand before working on a separate site.

**Comment by Christophvh** [comment]
Would be nice, the current documentation would benefit from more example components.

**Comment by HugoDF** [comment]
There's a couple sites that aggregate examples out there, check out https://github.com/alpinejs/awesome-alpine for a list of those sites
