### ISSUE TITLE
expose helper function globally

### ISSUE THREAD

**Issue by UrielCh** [alpinejs/alpine#256]
hi,

I'm trying to use Alpine JS in very small pages, some function from alpineJS can be needed form the global scope.

Can you expose them from the Global Alpine variable (as Alpine.fn.saferEval for example).

In my case I need to use saferEval to parse some `data-XX="{key='value'}"`

I do not want to duplicate any code.

- kebabCase
- arrayUnique
- debounce
- isNumeric
- saferEvalNoReturn
- walk

may also be usefull.

if you open expose saferEval, you could allso replace:
`function saferEval(expression, dataContext, additionalHelperVariables = {})`
by 
`function saferEval(expression, dataContext = {}, additionalHelperVariables = {})`

**Comment by HugoDF** [comment]
In this case, couldn't you make the data attribute an Alpine.js binding?

**Comment by UrielCh** [comment]
I have just start with AlpineJs. I'm not sure.

I need to change a href in <a> using values managed by Alpine data

my page look like that:
```html
<div x-data="allData"> <!-- I use a in script defined variable to work from external script-->
<a @click="AClic($event)"
   data-page="page.html"
   data-param="{age:96, config:'total', pause:60, auto:true}"
   href="#">actions 1</a>
</div>
```

my javascript look like that:
```javascript
        var allData = {
            dom: 'dev.domain.com',
        }
        function AClic(event) {
            const  {saferEval } = window.Alpine.fn;
            let {target} = event;
            let page = target.getAttribute('data-page');
            while (!page) { // move up to the <a> is e child is the target
                target = target.parentElement;
                if (!target)
                    return;
                page = target.getAttribute('data-page');
            }
            // get object containig attribut to append to URL
            const att = saferEval(target.getAttribute('data-param'));
            let params = '';
            if (att)
                params = Object.entries(att).map(([k, v]) => {
                    if (v instanceof Array) { // may be an array
                        return v.map(v2 => `${k}=${encodeURIComponent(v2)}?`).join('&');
                    } else {
                        return `${k}=${encodeURIComponent(v)}`
                    }
                });
            const url = `https://${allData.dom}/${page}?${params}`;
            target.setAttribute('href', url);
        }
```

**Comment by HugoDF** [comment]
In this case you can pass the data into the event handler function directly

```html
<a @click="AClic($event, 'page.html',{age:96, config:'total', pause:60, auto:true})"
   href="#">actions 1</a>
</div>
```

Then AClic will have parameters (event, page, config)

**Comment by ryangjchandler** [comment]
Hi guys, I'm going to close this issue due to inactivity and no further comment from OP. @UrielCh If you encounter any problems, please open another issue or join the Discord server for some help and advice. Thanks! :)
