### ISSUE TITLE
@Alpinejs/trap 3.7.3 missing dist folder

### ISSUE THREAD

**Issue by Lupennat** [alpinejs/alpine#2574]
### Discussed in https://github.com/alpinejs/alpine/discussions/2573

<div type='discussions-op-text'>

<sup>Originally posted by **Lupennat** January 14, 2022</sup>
step to reproduce the bug

`npm install @alpinejs/trap@latest`

`import '@alpinejs/trap'`

`Module not found: Error: Can't resolve '@alpinejs/trap'`

folder `dist` is missing on `node_modules/@alpinejs/trap`</div>

**Comment by SaeedKhader** [comment]
The Trap plugin has been deprecated and been replaced by Focus plugin in the latest release.

**Comment by Lupennat** [comment]
I think that the solution of deprecating a plugin with a minor tag is not a very good choice.

**Comment by SimoTod** [comment]
The focus plugin replaces it without breaking change. Alternatively you can require 3.7.1 which is the latest working version

**Comment by Lupennat** [comment]
@SimoTod Yes of course, but the problem is that updating the libraries via npm automatically downloaded 3.7.3. I suppose if a library is deprecated it shouldn't update to the next version, especially if the next patched version doesn't work.

Anyway, thanks for the replies ;)

**Comment by SimoTod** [comment]
@Lupennat Yeah, I don't know why it downloads 3.7.3, it's not even an Alpine release. 🤷 
I suspect it's to force users to migrate to the focus plugin.
