### ISSUE TITLE
This project is unreasonably difficult to find via search engine

### ISSUE THREAD

**Issue by GavinRay97** [alpinejs/alpine#26]
I am not sure Project-X was any easier to search, but Alpine has more of a ring at least :joy: 

![image](https://user-images.githubusercontent.com/26604994/71143167-95a4f800-21e7-11ea-9c93-74c16ec63ae6.png)

![image](https://user-images.githubusercontent.com/26604994/71143185-a6ee0480-21e7-11ea-9614-fa9493a7c69c.png)

**Comment by skatetdieu** [comment]
Probably because it was released literally today and the search engines hasn't caught up yet. Give it a few days for it to index and rank this project properly.

**Comment by GavinRay97** [comment]
You mean renamed?

It was Project-X before, almost a month ago now.

**Comment by keyurshah** [comment]
It’s number 1 in the listings now. 

![5DA3FEB9-3D05-4397-8DCB-E468A9B37298](https://user-images.githubusercontent.com/744385/71229032-022bff80-2299-11ea-8e7f-447118b2770e.jpeg)

**Comment by calebporzio** [comment]
Lol, thanks
