### ISSUE TITLE
Multiple 'x-show' expressions?

### ISSUE THREAD

**Issue by richgcook** [alpinejs/alpine#263]
Is it possible to allow mutliple `x-show` expressions and if one of them is true it'll show? I'm basically trying to implement a simple filtering system.

```
<div x-data="{ filterID: 0 }">
	<ul>
 		<li><a 
				href="#"
				:class="{ '--active': filterID === 1 }"
				x-on:click.prevent="filterID = 1"
			>Filter 1</a></li>
		<li><a 
				href="#"
				:class="{ '--active': filterID === 2 }"
				x-on:click.prevent="filterID = 2"
			>Filter 2</a></li>
		<li><a 
				href="#"
				:class="{ '--active': filterID === 3 }"
				x-on:click.prevent="filterID = 3"
			>Filter 3</a></li>
		<li><a data-filter href="#">View all</a></li>
	</ul>
	<ul>
		<li x-show="filterID === 1">An item with filter 1</li>
		<li x-show="filterID === 2">An item with filter 2</li>
		<li x-show="filterID === 3">An item with filter 3</li>
		<li x-show="filterID === 1 | 2 | 3">An item with filter 3</li>
		<li x-show="filterID === 1" x-show="filterID === 2" x-show="filterID === 3">An item with filter 3</li>
	</ul>
</div>
```

**Comment by HugoDF** [comment]
Your question boils down to JS expressions.

You can do:

```
<li x-show="[1, 2, 3].includes(filterID)">An item with filter 3</li>
```
Alternatively you can define a function where you put this logic:

```
<div x-data="{ filterID: 0, filter: (id, allowed) => allowed.includes(id) }">
  <li x-show="filter(filterID, [ 1 ])">An item with filter 1</li>
  <li x-show="filter(filterID, [1, 2, 3])">An item with filter 3</li>
</div>
```

**Comment by richgcook** [comment]
That's great! Much appreciated help.

**Comment by HugoDF** [comment]
Happy to help

**Comment by richgcook** [comment]
@HugoDF Sorry to bring this back up but is the same thing possible with `x-on`? For example, if, on click I wanted to set two expressions?

`x-on:click.prevent="filterID = 1, categoryID=5"`

**Comment by HugoDF** [comment]
Yeah, as long as it's valid JS and the variables are in scope of the x-on it should work.

Again you can also extract to a function and use this.varName

**Comment by richgcook** [comment]
Thanks, @HugoDF. I used `[filterID = 1126, categoryID = 1124]` which works but just wasn't sure if it was the best method. Thanks again.
