### ISSUE TITLE
I have jquery on my site and i want to use alpine js, is that possible?

### ISSUE THREAD

**Issue by jajamoks** [alpinejs/alpine#264]
I have jquery on my site and i want to use alpine js, is that possible?

**Comment by HugoDF** [comment]
Sure, there's nothing in Alpine that conflicts with jQuery.

**Comment by the94air** [comment]
> Sure, there's nothing in Alpine that conflicts with jQuery.
@HugoDF I haven't seen this line of text for a long time. Normal DOM is the BEST!
