### ISSUE TITLE
Drop-down select bind selected input

### ISSUE THREAD

**Issue by jajamoks** [alpinejs/alpine#265]
Hi i want to check if the todo value is equal to my 'dp' and i want to add attribute 'selected' on it. Any suggestion about this?

![image](https://user-images.githubusercontent.com/24262635/76395665-d1002e80-63b2-11ea-8504-c4666dce778c.png)

**Comment by jajamoks** [comment]
I got it working

**Comment by basepack** [comment]
@jajamoks do you mind sharing how you did get this working?

Thanks!
