### ISSUE TITLE
Multiple key/values within component scope object error when mixing string/number

### ISSUE THREAD

**Issue by richgcook** [alpinejs/alpine#268]
Within my component scope you can have multiple key/value pairs. I've done this no problem with something like `<div x-data="{ categoryID: 0, filterID: 0 }">` – however when I mix the values with a string and a number within the same object I get a `filterID is not defined` error on load.

`<div x-data="{ view: 'text', filterID: 0 }">`

Am I missing something?

**Comment by HugoDF** [comment]
Could you create a codepen with relevant code?

Off the top.of my head that looks like it should work and you're getting an issue somewhere other than x-data.

**Comment by richgcook** [comment]
https://codepen.io/johnthepainter/pen/bGdLyeN

Thanks for your help, again (!!), @HugoDF

**Comment by HugoDF** [comment]
I'm not seeing any errors

**Comment by richgcook** [comment]
@HugoDF in the DevTools console...

![Screenshot 2020-03-12 at 12 37 56](https://user-images.githubusercontent.com/901289/76522325-5d1b6000-645e-11ea-9312-8e6f1544d709.jpg)

**Comment by richgcook** [comment]
Is it due to having nested x-data scopes?

**Comment by SimoTod** [comment]
Nested Alpine components don't have access to the parent scope so `<div class="project col-span:12@xs col-span:4@sm" x-data="{ overlay: 'hide' }" x-show="[0,1085].includes(filterID)">` is not going to work at the minute.

There was an old issue on that topic but I believe that, at least for now, it's been decided not to implement it and to use native events to communicate between components.

You need to refactor your page so your components dispatch and capture events to communicate between each other.

**Comment by richgcook** [comment]
> Nested Alpine components don't have access to the parent scope so `<div class="project col-span:12@xs col-span:4@sm" x-data="{ overlay: 'hide' }" x-show="[0,1085].includes(filterID)">` is not going to work at the minute.

I'm thinking this is the case. I have a x-data div and it contains set other x-data (both of which where filterID sit) so it must be this issue.

Thanks for the help!

**Comment by HugoDF** [comment]
@richgcook are we good to close this then?

**Comment by richgcook** [comment]
> @richgcook are we good to close this then?

Closed 👍🏻
