### ISSUE TITLE
Detect scroll.window each elements by ID

### ISSUE THREAD

**Issue by luckyfor** [alpinejs/alpine#269]
Hi, this is my code
```
<main class="flex justify-between "
      x-data="{atElement: 'introduce'}"
      @scroll.window="atElement = (window.pageYOffset > document.querySelector('#review').getBoundingClientRect().top) ? 'review' : 'introduce'"
```
But unfortunately, this part function not work with me.
And I receive a error message. 
```
Uncaught ReferenceError: saferEvalNoReturn is not defined
    at eval (eval at saferEvalNoReturn (alpine.js:122), <anonymous>:3:37)
    at saferEvalNoReturn (alpine.js:122)
```
My task is detect and highlight by ID of element, if I can make @scroll.window to function will be great because I have a lot of elements.

**Comment by HugoDF** [comment]
Which version of Alpine.js are you running? A codepen, codesandbox or jsfiddle link would be useful too

**Comment by luckyfor** [comment]
So amazing,
I'm code on codepen and everything work with me,
Thank @HugoDF alot.

https://codepen.io/luckyfor/pen/BaNraGm

**Comment by HugoDF** [comment]
You might have been on an old version of Alpine.js, feel free to close this issue.

**Comment by luckyfor** [comment]
Wait me a second.
https://codepen.io/luckyfor/pen/BaNraGm
What's wrong with 4 elements.
#news not don't working, can u help me again 
thanks @HugoDF

**Comment by SimoTod** [comment]
@luckyfor The implementation doesn't seem to match what you need.

I think it should be something like
```
@scroll.window="atElement = document.querySelector('#more').getBoundingClientRect().top <= 0 ? 'more' : (document.querySelector('#news').getBoundingClientRect().top <= 0 ? 'news': (document.querySelector('#review').getBoundingClientRect().top <= 0 ? 'review' : 'introduce'))
```
or
```
@scroll.window="atElement = document.querySelector('#more').getBoundingClientRect().top <= window.innerHeight ? 'more' : (document.querySelector('#news').getBoundingClientRect().top <= window.innerHeight ? 'news': (document.querySelector('#review').getBoundingClientRect().top <= window.innerHeight ? 'review' : 'introduce'))
```

You can use `0` if you want to change when a section reaches the top of your window or you can use `window.innerHeight` if you want to change as soon as a section is visible at the bottom of your window.

**Comment by luckyfor** [comment]
It's work with me,
Thanks you @SimoTod alot ;)
