### ISSUE TITLE
Keydown modifier .exact

### ISSUE THREAD

**Issue by danieldevsquad** [alpinejs/alpine#273]
The .exact modifier would allow you to control the exact combination of system modifiers needed to trigger an event.

```
<!-- this will fire even if Alt or Shift is also pressed -->
<button x-on:click.ctrl="onClick">A</button>

<!-- this will only fire when Ctrl and no other keys are pressed -->
<button x-on:click.ctrl.exact="onCtrlClick">A</button>

<!-- this will only fire when no system modifiers are pressed -->
<button x-on:click.exact="onClick">A</button>
```

**Comment by danieldevsquad** [comment]
Inspired on https://vuejs.org/v2/guide/events.html#exact-Modifier.

**Comment by HugoDF** [comment]
Sounds useful & Caleb likes to have feature parity with Vue.js, do you want to have a crack at implementing it?

Otherwise I'll go ahead and do it

**Comment by danieldevsquad** [comment]
@HugoDF I won't have time do work on it any time soon. Please, feel free to implement it.

**Comment by HugoDF** [comment]
It turns out `click` system key modifiers weren't implemented either.

I've added `keydown.exact`, `click.exact` without system key modifiers and `click.exact` with system key modifiers

**Comment by HugoDF** [comment]
@calebporzio any chance you could have a look at the related PR?

Happy to split it into 2-3 PRs if you prefer

**Comment by calebporzio** [comment]
Going to hold off on this feature for now. I don't want to add the extra code bloat for a feature only requested by one person.

Let's wait to see if others would benefit, what there use-cases are etc...

Thanks for pitching in everyone!

**Comment by tiago-sb** [comment]
+1

**Comment by liamjoc** [comment]
+1

My use case is a chat messaging app. When a user hits enter it should send the message. If the user hit cmd+enter/shift+enter it should not sent the message but create a new line. This is how many of the web app messaging apps work.

**Comment by gwleuverink** [comment]
I've been using [this](https://wangchujiang.com/hotkeys) alongside alpine. It's relatively small and works well so far

**Comment by clekstro** [comment]
I'd like to allow users to select multiple dates from a custom datepicker when pressing `⌘`/`ctrl` and clicking, similar to `<select multiple>`

**Comment by tfwright** [comment]
+1

**Comment by HugoDF** [comment]
This sounds like something we can revive? cc @calebporzio it's time to weigh whether the added bulk is worth the use case as mentioned by people in this thread.

**Comment by santaimark** [comment]
+1

**Comment by arnarstef** [comment]
+1

**Comment by dinhkhanh** [comment]
+1

A common use-case is submit button with textarea. Eg: a Comment form is usually a textarea instead of a input. When user write down a comment and hit Enter key, it should submit the form, but hit Shift Enter key combination will create a new line in textarea instead.

**Comment by KevinBatdorf** [comment]
You can do this now with Alpine:

https://codepen.io/KevinBatdorf/pen/yLeQaGe?editors=1000

**Comment by f3l1x** [comment]
+1

**Comment by ryzexsp** [comment]
+1

**Comment by piotrze** [comment]
You can always use `if`

**Comment by piotrze** [comment]
You can use `if`

**Comment by piotrze** [comment]
You can use `if`
```html
<textarea
        x-on:keyup.enter="if (!$event.shiftKey) alert('only enter pressed')"
></textarea>
```

**Comment by seabasss** [comment]
+1

**Comment by seabasss** [comment]
> You can do this now with Alpine:
> 
> https://codepen.io/KevinBatdorf/pen/yLeQaGe?editors=1000

How about shift+click? This is only for key strokes right?

**Comment by Joe45M** [comment]
+1 on this. 

Really useful for contextual/quick menus.

**Comment by cainytheslave** [comment]
+1 need this

**Comment by amandasaurus** [comment]
I also would like a way to make “enter w/o shift” = submit & “enter+shift” do something else. A feature like `.exact` (or `@keyup.enter.not-shift`) would solve that.

**Comment by fschoenfeldt** [comment]
+1

**Comment by fschoenfeldt** [comment]
For anyone wondering, you can workaround this issue via https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/shiftKey in your code.
