### ISSUE TITLE
Morph plugin not working correctly in docs on website

### ISSUE THREAD

**Issue by jasonlfunk** [alpinejs/alpine#2768]
### Discussed in https://github.com/alpinejs/alpine/discussions/2738

<div type='discussions-op-text'>

<sup>Originally posted by **jasonlfunk** March  9, 2022</sup>
I'm trying to use the morph plugin in my application but am running into problems with it. I then noticed that even on the docs site, it's not working correctly.

https://alpinejs.dev/plugins/morph

It's most clearly demonstrated by repeatedly clicking the morph button. My impression is that the headers should appear but everything else remain the same, but that's not what is happening.

![CleanShot 2022-03-09 at 11 52 43](https://user-images.githubusercontent.com/685188/157406672-ba271e2c-9491-41bc-ac9f-2083ba4c0337.gif)

</div>

**Comment by SimoTod** [comment]
it seems to work correctly if you pass `{lookahead: true}` as the third parameter. https://codepen.io/SimoTod/pen/popyGeq

**Comment by SimoTod** [comment]
It's also not happening in the latest main without the lookahead flag so I believe one of the latest PRs already fixed it (you just need to wait for the next release)

**Comment by jasonlfunk** [comment]
Thanks 👍
