### ISSUE TITLE
x-model .number modifier prevents typing negative numbers and fractions

### ISSUE THREAD

**Issue by ahmedkandel** [alpinejs/alpine#284]
Using `number` modifier without `lazy` modifier on `<input type="number">` will not allow users to type in negative values `-123` or fractions `.5` . While using it on `<input type="text">` will give a `NaN`.

The reason for this is that Alpine tries to cast the value of HTML input elements _" which always returns a string"_  to numeric using `parseFloat()`.

In HTML5 spec. [here](https://html.spec.whatwg.org/multipage/input.html#number-state-(type%3Dnumber)), `<input type="number">` will pass empty string to Alpine in `event.target.value` which makes it even worse.

One solution is to use `lazy` modifier to delay the model binding until input changes. But in some cases where live updates are needed still an issue. So I was working on a PR for `number` modifier to return:

- `null` if the input is empty or invalid in case of `<input type="number">`  start typing - or .
- original value "_string_" if casting to numeric fails
- numeric value if casting passes

This will fix the `NaN` issues and allow typing negative numbers and fractions in `<input type="number">.

**Comment by ahmedkandel** [comment]
Here is a codepen to demo the issue, Try typing `-123` or `.5`:
https://codepen.io/tomorrowsystem/pen/WNvywOq?editors=1001

Here another codepen after the PR:
https://codepen.io/tomorrowsystem/pen/yLNEOvY?editors=1001

**Comment by calebporzio** [comment]
Let's match Vues behavior in this situation. Can you verify how vuejs behaves in these cases? Then we can match that

**Comment by ahmedkandel** [comment]
Yes, I got this behavior from [Vue](https://vuejs.org/v2/guide/forms.html#number), If the value cannot be parsed with `parseFloat()`, then the original value `string` is returned. Here is the same codepen but in Vue:
https://codepen.io/tomorrowsystem/pen/BaNVwNP?editors=1011

While the addition we have here is to return null if the input with `x-model.number` is empty. which is more JS idiomatic and Vue team said it will be considered in Vue 3 [Here](https://github.com/vuejs/vue/issues/4742#issuecomment-410653467)
