### ISSUE TITLE
x-html causing a flicker / blink issue when any state is updated

### ISSUE THREAD

**Issue by rhengles** [alpinejs/alpine#286]
I'm rendering many things using `x-html`, but when I change any property on the state of the component, not only when the property directly being rendered on the `x-html` attribute, a render of the html is triggered and this makes the content blink or flicker. In particular I'm rendering images inside the html and the blinking is very noticeable and distracting.

Shouldn't the `x-html` trigger an update only when its contents have actually updated?

Thanks!

**Comment by rhengles** [comment]
In case anyone is interested, I'm doing a workaround parsing the html text into vnodes and patching the element with snabbdom.

**Comment by calebporzio** [comment]
Yeah, that is currently how Alpine works. If it's a big enough problem for people we can reevaluate.

**Comment by rhengles** [comment]
Thanks @calebporzio for the answer.

To document here my solution:

Using [@arijs/stream-xml-parser](https://www.npmjs.com/package/@arijs/stream-xml-parser) ([Github](https://github.com/arijs/stream-xml-parser)):

```

function elGetHtml (el) {
	// to get the outer element opening and closing tags
	// required by snabbdom to compare
	var t = String(el.tagName).toLowerCase();
	var a = '';
	var ea = el.attributes;
	var eac = ea.length;
	for (var i = 0; i < eac; i++) {
		var eai = ea[i];
		// encode possibily invalid characters to be safe
		var ean = htmlEntitiesEncodeHtmlAttribute(eai.name);
		var eav = htmlEntitiesEncodeHtmlAttribute(eai.value);
		// allow single quotes in the attribute value
		eav = eav.replace(/&#39;/g,'\'');
		a += ' '+ean+'='+JSON.stringify(eav);
	}
	var isVoid = StreamXMLParser.htmlVoidTagMap[t];
	return {
		open: '<'+t+a+(isVoid ? '/' : '')+'>',
		close: sc ? '' : '</'+t+'>'
	};
}

function htmlToVnodes (html) {
	var sxp = StreamXMLParser;
	var tb = new sxp.TreeBuilder({
		element: sxp.elementSnabbdom()
	});
	var xp = new sxp.XMLParser(tb.parserEvent.bind(tb));
	xp.end(html);
	return tb.root.tag.children;
}

function patchElHtml (el, html) {
	var patch = snabbdom.init([
		require('snabbdom/modules/attrs').default
	]);
	var outer = elGetHtml(el);
	html = outer.open+html+outer.close;
	html = htmlToVnodes(html);
	el = snabbdom.toVNode(el);
	patch(el, html[0]);
}

```

Then I changed the Alpine library to use my `patchElHtml` function above:

```diff
           case 'html':
-            el.innerHTML = this.evaluateReturnExpression(el, expression, extraVars);
+            patchElHtml(el, this.evaluateReturnExpression(el, expression, extraVars);
             break;
```

**Comment by QuentinGab** [comment]
Hi, I know this issue is closed but I'm facing the same problem when rendering a img tag autogenerated in the backend (by laravel-media-library). All images blink when another one is added to the list. I'm using alpine inside livewire so maybe it's not the full story

**Comment by chwan97** [comment]
solve this problem by not use x-html, instead of direct taget.innerHTML = 'what i want'
