### ISSUE TITLE
$nextTick after component update or after render?

### ISSUE THREAD

**Issue by ahmedkandel** [alpinejs/alpine#287]
`$nextTick` is expected to execute a given expression AFTER Alpine has made its reactive DOM updates the same as Vue-nextTick. But looking at the source code there is some confusion "Maybe I am wrong".

Here in [component.js line 107](https://github.com/alpinejs/alpine/blob/master/src/component.js#L107) the expression should be excuted. But it will not, as `self.nextTickStack` will be empty already when reaching this point because it has been iterated in `initializeElements` or `updateElements`.

@HugoDF @SimoTod what do you think? should lines [107-109] be removed if they are useless?

**Comment by SimoTod** [comment]
I see, in my opinion line 107-109 are correct but lines 179-182 are wrong. 
I need to try a couple of cases, though.

**Comment by SimoTod** [comment]
okay, I think you are right. lines 107-109 seem pointless and it makes more sense to keep the one in updateEvents.

**Comment by ahmedkandel** [comment]
Yes, I will do more checks then make a PR. Thanks @SimoTod
