### ISSUE TITLE
Link to docs in component pages take you to installation page

### ISSUE THREAD

**Issue by Silver343** [alpinejs/alpine#2910]
### Discussed in https://github.com/alpinejs/alpine/discussions/2909

<div type='discussions-op-text'>

<sup>Originally posted by **Silver343** May  8, 2022</sup>
Clicking on the required plugins for the alpine components takes you to [installation](https://alpinejs.dev/essentials/installation).</div>

**Comment by wtld** [comment]
Clicking on the "collapse" plugin returns 404.
