### ISSUE TITLE
[doc] ja:Translate v2.2.1

### ISSUE THREAD

**Issue by 53able** [alpinejs/alpine#293]
Documentation updated
Original: https://github.com/alpinejs/alpine/compare/333665f106921aa2d36ef1f02663c6f103d1fbe4...35f7efe4af0d4f4355ee687d796709c780e6a32b

**Comment by 53able** [comment]
@calebporzio Consider it done🙋‍♂️

**Comment by ryangjchandler** [comment]
@53able - I'm going to close this issue since v2.2.1 is quite out of date now, but please feel free to open a PR with updates for the latest version. Thanks!
