### ISSUE TITLE
How to fire events in tabs?

### ISSUE THREAD

**Issue by thevipinmishra** [alpinejs/alpine#295]
I am using datatables in my tabs and the other tab (which isn't visible by default) doesn't respond to datatables and no controls are there. I tried passing some events and options but no luck!

**Comment by Haaruun-I** [comment]
By tab do you mean browser tabs or tabs like two divs?
If you mean browser tabs, you cant communicate between them unless one tab spawned the other.
And if you mean divs make sure you're not using x-if and the event is able to bubble up to the tab you want.

**Comment by HugoDF** [comment]
Some sample code would be very useful (using codepen or similar is ideal)

**Comment by thevipinmishra** [comment]
> By tab do you mean browser tabs or tabs like two divs?
> If you mean browser tabs, you cant communicate between them unless one tab spawned the other.
> And if you mean divs make sure you're not using x-if and the event is able to bubble up to the tab you want.

tabs like 2 divs man. I am initializing a datatable on each table inside the 2 divs with same id but its just doesn't work.

**Comment by HugoDF** [comment]
I don't think you can have the same HTML I'd attribute on 2 elements, but that's a HTML/DOM problem rather than Alpine
