### ISSUE TITLE
[Documentation]: `window.deferLoadingAlpine` is undocumented

### ISSUE THREAD

**Issue by HugoDF** [alpinejs/alpine#297]
From the release notes:

> A mechanism for third-party libs to defer loading Alpine until they are finished doing their thing
> 
> ```js
> window.deferLoadingAlpine = callback => {
>     // When some condition is met, call callback() and Alpine will load
> }
> ```

We probably should add this to the documentation, either in the "install" section or a new "advanced" or "options" section.

cc @calebporzio @ryangjchandler @SimoTod

**Comment by ryangjchandler** [comment]
Yeah, agreed. Documentation is getting pretty lengthy now, hopefully Caleb buys a domain soon :)

**Comment by HugoDF** [comment]
Opinions on whether this belongs in "install" or we need a new "advanced usage"/"integration with 3rd party libraries" section?

**Comment by ryangjchandler** [comment]
> Opinions on whether this belongs in "install" or we need a new "advanced usage"/"integration with 3rd party libraries" section?

I'd say this should go under an advanced usage section. Not really an installation step. I'd add the "deferred loading" part as a subheading underneath.

**Comment by calebporzio** [comment]
I don't want to document this piece. I put it there for Livewire that use mainly. It's a pretty niche internal thing.
