### ISSUE TITLE
Set state outside x-data and get reactivity working

### ISSUE THREAD

**Issue by jaronwanderley** [alpinejs/alpine#298]
I'm trying to listen window.matchMedia and set state outside x-data, but there not reactivity, what is the best way to achieve this?
```
<div x-data="darkMode()">
    <button x-on:click="setDark(!isDark)">Toggle Dark</button>
    <button x-on:click="notDark()">Not Dark</button>
    <div x-show="isDark">
        Is Dark Now
    </div>
     <div x-show="!isDark">
        Is Light Now
    </div>
</div>

function darkMode() {
  let data = {
    isDark: window.matchMedia('(prefers-color-scheme: dark)').matches,
    setDark (e) { this.isDark = e },
    notDark () { this.isDark = false }
  }
  window.matchMedia('(prefers-color-scheme: dark)').onchange = function (e) {
    data.isDark = e.matches
    // data.setDark(e.matches)
  }
  return data
}
```

**Comment by yatagasaru** [comment]
Currently there is no way to do that as stated in #254 

But you can workaround it like this https://github.com/alpinejs/alpine/issues/254#issuecomment-596325378

```html
<div x-data="darkMode()" x-trigger="theme">
    <button x-on:click="setDark(!isDark)">Toggle Dark</button>
    <button x-on:click="notDark()">Not Dark</button>
    <div x-show="isDark">
        Is Dark Now
    </div>
      <div x-show="!isDark">
        Is Light Now
    </div>
  </div>
  <script>
    const theme = new AlpineData('theme', 'setTheme')
    function darkMode() {
      let data = {
        isDark: window.matchMedia('(prefers-color-scheme: dark)').matches,
        setDark (e) { this.isDark = e },
        notDark () { this.isDark = false },
        setTheme(){this.isDark = theme.get()}
      }
      window.matchMedia('(prefers-color-scheme: dark)').onchange = function (e) {
        const isDark = e.matches
        theme.set(isDark)
      }
      return data
    }
  </script>
```

**Comment by jaronwanderley** [comment]
I loved how simple u made this. Thank u! One more question, can be possible to x-trigger get mor than one event?

**Comment by jaronwanderley** [comment]
Sorry about the question, I already did this... 
I hope some day Alpine.js can do this by default...

here is my modified implementation... did I say already that I love yours?
`class AlpineData {
    constructor(xTrigger, functionName = ''){
        this.isType('string', xTrigger, 'on parameter 1')
        this.isType('string', functionName, 'on parameter 2')
        this.xTrigger = xTrigger
        this.functionName = functionName
        
        const xTriggerEl = Array.from(document.querySelectorAll('[x-trigger]'))
            .filter(e => e.attributes['x-trigger'].value.includes(this.xTrigger))
        xTriggerEl.forEach(el => {
            const div = document.createElement('div')
            div.className = 'x-trigger-click'
                  
            if(functionName !== ''){
                div.setAttribute('x-on:click', functionName)
            }
          
            el.appendChild(div)
        })
    }
    set(data) {
        const xTriggerElData = Array.from(document.querySelectorAll('[x-trigger]')).filter(e => e.attributes['x-trigger'].value.includes(this.xTrigger))
        xTriggerElData.forEach(el => {
          el.setAttribute('data-init', JSON.stringify(data))
          Array.from(el.children).forEach(e => {
            if (e.className === 'x-trigger-click' && e.attributes['x-on:click'].value === this.functionName) { e.click() }
          })
        })
    }
    get() {
       let xTriggerElData = Array.from(document.querySelectorAll('[x-trigger]')).filter(e => e.attributes['x-trigger'].value.includes(this.xTrigger))[0]
       return JSON.parse(xTriggerElData.attributes["data-init"].value)
    }
    isType(expected, target, errMessage){
        const currType = Object.prototype.toString.call(target).slice(8, -1).toLowerCase()
        if(currType !== expected){
            throw new TypeError(`${expected} expected. ${currType} given ${errMessage}`, '', '')
        }
    }
}`

**Comment by jaronwanderley** [comment]
@yatagasaru  May need I close this issue, because already exist #254 ?

**Comment by yatagasaru** [comment]
If that's okay with you

**Comment by peaceful-james** [comment]
For posterity: there is an easier way to do this without the `AlpineData` class:

```
<div
  x-data="{...watchPrefersColorScheme()}"
  x-init="window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change',   e => {
      setPrefersColorSchemeDark(e.matches);
    });"
>
 <!-- ...put your themed HTML here -->
</div>

<script>
  function watchPrefersColorScheme() {
    let data = {
      prefersColorSchemeDark: window.matchMedia('(prefers-color-scheme: dark)').matches,
      setPrefersColorSchemeDark(value) {
        this.prefersColorSchemeDark = value;
      },
    };
    return data;
  }
  </script>
```

**Comment by bronze** [comment]
@peaceful-james do you have an example with this implemented? i am getting `watchPrefersColorScheme is not defined`

**Comment by peaceful-james** [comment]
> @peaceful-james do you have an example with this implemented? i am getting `watchPrefersColorScheme is not defined`

Are you using Phoenix? Define it in your `app.js` if so.
