### ISSUE TITLE
Distributed js is not minified?

### ISSUE THREAD

**Issue by georges-gomes** [alpinejs/alpine#301]
Testing Alpine on webcomponents.dev

/dist/alpine.js is not minified.

There could be much smaller. (7k (with Terser) vs 15k)

Cheers

**Comment by SimoTod** [comment]
See https://github.com/alpinejs/alpine/issues/249

**Comment by calebporzio** [comment]
Yeah... we should update the docs to reference “alpine.min.js” from JS Deliver yeah? That would do it right?

**Comment by georges-gomes** [comment]
Yes you could use js delivery feature to minify but you have less control on what is going on.
Also js delivery will do it on-demand (then cache). It's a performance impact at the beginning of new releases.

Updating the documentation would probably bring some nice "free" performance improvement 👍

It's really your call. Not a problem for me.

Take care!

**Comment by calebporzio** [comment]
I updated the docs. Thanks!

**Comment by deadcoder0904** [comment]
Not sure if why isn't this minified because the `alpinejs` from `npm i` is `65.7kB` & the one from CDN is `22.8kB` which is huge. Probably due to mangling variable names I think.

Why not ship the minified version?

**Comment by ryangjchandler** [comment]
> Not sure if why isn't this minified because the `alpinejs` from `npm i` is `65.7kB` & the one from CDN is `22.8kB` which is a huge difference. Probably due to mangling variable names I think.
> 
> Why not ship the minified version?

I don't think it makes much of a difference. It makes debugging much easier and I imagine you're minifying your own bundle anyway.

**Comment by deadcoder0904** [comment]
> It makes debugging much easier

How so since everyone bundles anyway?

> I imagine you're minifying your own bundle anyway.

Nope, that's exactly why I asked 😂 

Not too much of a problem but I always include `*.min.*` files so was confused why `alpinejs` isn't shipping with it.

**Comment by ryangjchandler** [comment]
> > It makes debugging much easier
> 
> How so since everyone bundles anyway?
> 
> > I imagine you're minifying your own bundle anyway.
> 
> Nope, that's exactly why I asked 😂
> 
> Not too much of a problem but I always include `*.min.*` files so was confused why `alpinejs` isn't shipping with it.

Alpine only has one single build for bundling and CDN, since the CDN installation is preferred. Also, out of curiosity, why aren't you minifying your bundle? There's also clear information above about why there is no min files in the dist.

**Comment by deadcoder0904** [comment]
> Also, out of curiosity, why aren't you minifying your bundle?

I'm currently testing out Alpine JS with Tailwind & since Tailwind intellisense wasn't working in VSCode as it needs `tailwind.config.js`, I opted out of the original minified CDN version to use `npm` for both.

That's why I said `Not too much of a problem` but was curious since the size difference looked huge to me.
