### ISSUE TITLE
Split into components

### ISSUE THREAD

**Issue by anonimusprogramus** [alpinejs/alpine#302]
This is not an issue, but rather questions. 

1. Can I split parts (like header, nav, footer, register form, login dialog, etc) into some files I can import and reuse later?

2. Can I use Alpine for a middle-sized app like HR app?

Thank you!

**Comment by calebporzio** [comment]
We will probably need more clarification on your first question, but here is a general answer for both of them:

Alpine isn’t meant to be a full templating language/engine like Vue or React. Alpine is great for any sized app, but not for managing all of the templates of the app.

Things like includes are better done with a backend templating engine or if you want to use a front-end framework, Vue would be a better choice.

**Comment by anonimusprogramus** [comment]
OK, clear. Thanks Caleb!

**Comment by gwleuverink** [comment]
Just came across this question. I'll drop my approach here for future reference.

There probably is a more resilient way but nonetheless, this is wat I do:

In my js bootrap file I declare an object on the window all alpine components will live inside. Namespacing reduces the risk of having naming collisions later on.

``` JavaScript
window.app = {}
```

The drawback is that if you write all you components inside that object you lose the single file flavor you are used to with Vue. To come a little closer to that I encapsulate the alipne component inside a Laravel blade component.

``` blade
<div x-data="app.someComponent">
    <!-- -->
</div>

@pushonce('js:someComponent')
<script>
app.someComponent = function() {
    return {
        // component logic
    }
}
</script>
@endpushonce
```

The push once blade directive was borrowed from  [here](https://github.com/appstract/laravel-blade-directives). Using this you are safe to use the blade component inside of a @foreach loop. The script will only be added to the js stack once.

I'm sure in time my approach will evolve. But I hope this is helpful to someone.
