### ISSUE TITLE
[Question] Calculate Collision / Direction Aware Dropdown

### ISSUE THREAD

**Issue by f3l1x** [alpinejs/alpine#303]
Hi guys!

Thanks for awesome lib, I've been looking for this kind of lib loooong time. Straight to the point.

We are using Alpine to create very simple dropdowns. Everything works fine, but client just hit the "collision issue". When you're too near to end of the window, right. 

I would like to ask you, how would you solve that? I don't want to pollution our templates with many conditions. 

We're using webpack to bundle all kind of stuff together or to many chunks.

I was thinking about some custom function, registered at global space, `window.ALPINEX`.

```js
window.ALPINEX = {
  calculateCollision() { ... }
}
```

```html
<div @click="ALPINEX.calculateCollision">...</div>
```

In this function I would change some css classes or sth to open dropdown in the right direction. 
What do you think? Thanks for the feedback.

Felix

**Comment by calebporzio** [comment]
Ah yeah, that makes sense. I think the collision problem is out of the Alpine’s scope and implementing a global function that you can use in your components is the way to go.

I’m going to close this for now, but please share your findings as you go here for others later on if you can.

Thanks!
