### ISSUE TITLE
Issue with x-show on Livewire page refresh

### ISSUE THREAD

**Issue by oliverbj** [alpinejs/alpine#304]
I am using a Livewire DataTable [plugin](https://github.com/kdion4891/laravel-livewire-tables), which can sort table columns. However, when sorting the table columns, it is messing up something with Alpine (I believe it to be related to `x-data` and `x-show`).

Please see below small gif:

[![enter image description here][2]][2]

As you can see, the modal works fine on the initial page load. However, after I try to sort the table, it will simply open up all modals on the page.

The modals are placed in a blade file, like this:

```html
<div class="float-right mt-2">
    <!-- Edit Car -->
    <div x-data="{open:false}" class="float-right inline-block">
        <a x-on:click="open = true"
           class="py-1 px-2 text-center rounded text-gray-500 bg-gray-200 hover:bg-gray-300 cursor-pointer">
            Edit Car
        </a>
        <div x-show="open" x-on:click.away="open = false">
            @livewire('cars.edit-car', $car_id)
        </div>
    </div>
</div>
```

As you can see, I have set `x-data="{open:false}"` by default, so I am a little bit confused.

I have tried to combat this by using `x-cloak` on my modals, like:

```html
<!-- Edit Car -->
<div x-data="{open:false}" class="float-right inline-block" x-cloak>
```

Which does help hiding the modals, but the x-cloak is not being removed again (Maybe similar to #47 ?) See below gif, after I added `x-cloak`, the modal buttons are being hidden completely.:

[![enter image description here][1]][1]

I am not quite sure what other code to post, as I don't really know why/where this is happening. 

Can anyone guide me in the right direction here?

  [1]: https://i.stack.imgur.com/HLkj9.gif
  [2]: https://i.stack.imgur.com/O9kMD.gif

**Comment by sweco-semtne** [comment]
I think this might be the same issue as #282?

**Comment by oliverbj** [comment]
@sweco-semtne it seems to be the same issue, however I am not sure how I can solve this only using Alpine.js? (Not using Phoenix Liveview)

**Comment by HugoDF** [comment]
Is this still happening with the latest Alpine.js and LiveWire?

**Comment by ryangjchandler** [comment]
@HugoDF I think we can close this issue since it's been stale for quite a while. If anyone notices anymore problems that are Alpine related, please re-open this issue with some more details or open a fresh one and reference this.

**Comment by sirshaun** [comment]
Has this issue been solved for livewire 1.*? I am still getting the same issues as the OP

**Comment by SimoTod** [comment]
Can you find anything useful in the livewire forum? The issue, if still there, is due to livewire reinserting html in your page which for alpine is a new component. It "should" clone the previous component (code for it is in the livewire repo) and share the same state. 
If your modal doesn't hide after a Livewire refresh, it looks like Alpine doesn't restart on that component.

**Comment by sirshaun** [comment]
I fixed the problem by placing "x-cloak" and "x-show" outside of the livewire component as shown below, and then wrapping the with a "wire:ignore.self" on the parent component so that only the child component now refreshes. Don't know if it's the correct way or its a hack.

`
<div wire:ignore.self>
      <div x-cloak>
            <div x-show="foo">
                   <livewire:foo-bar />
             </div>
      </div>
</div>
`
