### ISSUE TITLE
x-init SyntaxError: expected expression, got keyword 'return'

### ISSUE THREAD

**Issue by alessandrotesoro** [alpinejs/alpine#305]
I think I've got something weird going on. I have the following line of code:

```
<div class="irregular-openings" x-data="{items: <?php echo htmlspecialchars( wp_json_encode( $irregulars, ENT_QUOTES ) ); ?>}" x-init="return () => { // we have access to the post-dom-initialization state here // }">
```

However the console shows the following error: `SyntaxError: expected expression, got keyword 'return'`

Weirdly enough, the console says the error is coming from alpine.js:3:35

```
typeof define === 'function' && define.amd ? define(factory) :
```

If I use x-init without "return" the error disappears but obviously can't do what I need it do. I need to trigger something after the DOM has been updated, that's why I was going to use return...

Any idea what's wrong with it?

**Comment by HugoDF** [comment]
What are you trying to do?

If you need something to run only on "unmount" you can do
`x-init="() => () => { /* do something */ }"`

If you're trying to run something on "mount" ie. init: `x-init="() => { /* do something */ }"`

**Comment by alessandrotesoro** [comment]
Basically it's a form. Inputs are formatted through Cleavejs. So I need to run cleavejs after the data is initialized into the component. 

`x-init="() => { /* do something */ }"` seems to work.

`x-init="return () => { // we have access to the post-dom-initialization state here // }"` Is mentioned into the readme file but it's triggering that error on my end that's why I was confused 🤔

**Comment by HugoDF** [comment]
Oh right, pretty sure that shouldn't work, might need to update the README. If it _is_ supposed to work, we've got a bug 😁.

@calebporzio? Should having a `return` statement in x-init work?

**Comment by SimoTod** [comment]
I think the documentation needs updating. 
Whatever is in the x-init function will eventually hit https://github.com/alpinejs/alpine/blob/915164ed2cf577702d4767c4ab8960a4b659c184/src/utils.js#L70 generating the string `return return () => {}` which is not valid.
It probably used to work in one of the first releases.

If the code needs to wait for the component to be initialised, `() => {...}` should be enough now.

**Comment by calebporzio** [comment]
Sorry, I updated the README. You should leave out the `return`
