### ISSUE TITLE
Is there any router for alpinejs?

### ISSUE THREAD

**Issue by shirazsoft** [alpinejs/alpine#306]
Is there any router for alpinejs?

**Comment by HugoDF** [comment]
There is no router, you can read the URL and replace/add to it using DOM APIs directly (window.location, URL object, and history API)

**Comment by the94air** [comment]
If you want a simple router, check this out: https://dev.to/aminnairi/a-router-without-a-web-server-in-vanilla-javascript-3bmg
If you want a lib to do so, try https://github.com/egoist/franxx or https://github.com/krasimir/navigo

**Comment by ryangjchandler** [comment]
Alpine isn't really meant for building entire single page applications. It's possible, but not what it's meant for.

**Comment by calebporzio** [comment]
Thanks for weighing in everyone.

**Comment by ajusa** [comment]
Just to give an example: if you really, really want to do routing (or even some sort of show and hide thing based on the URL) you can do 
```html
<div x-data="{page: location.hash}" @hashchange.window="page = location.hash">
<span x-show="page === ''">Index Page</span>
<span x-show="page === '#contact'">Contact Page</span>
</div>
...
<a href="#contact">Contact Us!</a>
```

**Comment by chhaihongsrun** [comment]
> Just to give an example: if you really, really want to do routing (or even some sort of show and hide thing based on the URL) you can do
> 
> ```
> <div x-data="{page: location.hash}" @hashchange.window="page = location.hash">
> <span x-show="page === ''">Index Page</span>
> <span x-show="page === '#contact'">Contact Page</span>
> </div>
> ...
> <a href="#contact">Contact Us!</a>
> ```
> 
> No external framework required!

You saved my days!

**Comment by james0r** [comment]
> Just to give an example: if you really, really want to do routing (or even some sort of show and hide thing based on the URL) you can do
> 
> ```
> <div x-data="{page: location.hash}" @hashchange.window="page = location.hash">
> <span x-show="page === ''">Index Page</span>
> <span x-show="page === '#contact'">Contact Page</span>
> </div>
> ...
> <a href="#contact">Contact Us!</a>
> ```
> 
> No external framework required!

I love how lightweight this solution and how it leverages the built-in hash handling. I'm thinking of using this method to route to articles fetched using AJAX on a site. Does usings hashes like this have inherent SEO drawbacks?

**Comment by KevinBatdorf** [comment]
> Does usings hashes like this have inherent SEO drawbacks?

My intuition here says that it would have a negative effect. I don't think Google will index content loaded in by hash links. But I suppose you could try it and find out. You'd have to tell Google to index the page and wait awhile.

**Comment by MeetAmin** [comment]
> Just to give an example: if you really, really want to do routing (or even some sort of show and hide thing based on the URL) you can do
> 
> ```
> <div x-data="{page: location.hash}" @hashchange.window="page = location.hash">
> <span x-show="page === ''">Index Page</span>
> <span x-show="page === '#contact'">Contact Page</span>
> </div>
> ...
> <a href="#contact">Contact Us!</a>
> ```
> 
> No external framework required!



> Just to give an example: if you really, really want to do routing (or even some sort of show and hide thing based on the URL) you can do
> 
> ```
> <div x-data="{page: location.hash}" @hashchange.window="page = location.hash">
> <span x-show="page === ''">Index Page</span>
> <span x-show="page === '#contact'">Contact Page</span>
> </div>
> ...
> <a href="#contact">Contact Us!</a>
> ```
> 
> No external framework required!

@ajusa how to add or remove classes using this though?

**Comment by devBabinski** [comment]
> Just to give an example: if you really, really want to do routing (or even some sort of show and hide thing based on the URL) you can do
> 
> ```
> <div x-data="{page: location.hash}" @hashchange.window="page = location.hash">
> <span x-show="page === ''">Index Page</span>
> <span x-show="page === '#contact'">Contact Page</span>
> </div>
> ...
> <a href="#contact">Contact Us!</a>
> ```
> 
> No external framework required!

Does this work with location.href?

**Comment by MeetAmin** [comment]
> > Just to give an example: if you really, really want to do routing (or even some sort of show and hide thing based on the URL) you can do
> > ```
> > <div x-data="{page: location.hash}" @hashchange.window="page = location.hash">
> > <span x-show="page === ''">Index Page</span>
> > <span x-show="page === '#contact'">Contact Page</span>
> > </div>
> > ...
> > <a href="#contact">Contact Us!</a>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > No external framework required!
> 
> Does this work with location.href?

yes it does

**Comment by melnikaite** [comment]
I made an example of router with dynamic js and templates loading similar to @ajusa solution, also without any dependencies
https://github.com/melnikaite/alpine-router

**Comment by shaunlee** [comment]
An easy to use and flexible router for Alpine.js. Hope you will like it!
https://github.com/shaunlee/alpinejs-router

```html
<a x-link href="/hello/world">Hello World</a>

<a x-link href="/somewhere">Load template</a>

<template x-route="/hello/:name">
  <!-- Inner template -->
  <div>Say hello to <span x-text="$router.params.name"></span></div>
</template>

<!-- Separate template file -->
<template x-route="/somewhere" template="/somewhere.html"></template>
```

**Comment by pbastowski** [comment]
This is brilliant, thanks Shaun 🚀

**Comment by rustavellyne** [comment]
@MeetAmin @devBabinski Caan you give an example how to work with  location.href instead of hash?

**Comment by boustanihani** [comment]
Here is a good one: https://pinecone-router.github.io/router/
