### ISSUE TITLE
binding radio input values

### ISSUE THREAD

**Issue by pcohen12** [alpinejs/alpine#308]
Hi there!

Is there a way to bind radio input values? I had figured this would be possible - and it works fine for checkboxes - but I can't get any kind of `x-bind:value="blah"` to work on radios. All the examples I can find online only have hardcoded values.

CodePen example: https://codepen.io/pcohen12/pen/ExjGmEG?editors=1000

**Comment by SimoTod** [comment]
I think it's a bug. 
Alpine doesn't assign the value for radio buttons in src/directives/bind.jd (only the checked attribute).
Good first PR if anyone wants to have a go.

**Comment by Rusya13** [comment]
This is workaround:
`<input x-value="selectedListID" type="radio" name="radio" x-on:input="selectedListID = list.id.toString()" :id="list.name">`
