### ISSUE TITLE
Multiple executions when loading through webpack

### ISSUE THREAD

**Issue by keyurshah** [alpinejs/alpine#31]
Hello,

I am trying to load alpine from webpack (laravel mix) given the instructions

```
import Alpine from 'alpinejs'
Alpine.start()
```

on my page, if i use this code

```
<div x-data="{}">
  <div x-on:click="console.log('hello')">Click here</div>
</div>
```

i see 2 executions in my console log

![image](https://user-images.githubusercontent.com/744385/71336731-4586a800-24fd-11ea-852c-f190408aec9d.png)

This doesn't happen if I load alpine with the script tag outside of webpack.

------------

Also, trying to organize alpine components in webpack, and wondering if there were any best practices. 

I got it to work by assigning custom functions to the window object. not a problem, just want to make sure this is the proper way.

`app.js`
```
import * as product from './alpine/product'
window.product = product;
```

`alpine/product.js`
```
export function add() {
  return {
    name: 'blue widget',
}
```

and then declaring as follows

`index.html`
```
<div x-data="product.add()">
   <div x-text="name"></div>
</div>
```

Thanks!

**Comment by calebporzio** [comment]
@keyurshah - try it now with v1.1.1 from npm. I'm not positive it will work, but hopefully.

**Comment by keyurshah** [comment]
sorry, still doesn't seem to work.

i tested locally in a clean laravel install and i setup a demo on stackblitz

https://js-s3mrft.stackblitz.io

**Comment by operkot** [comment]
I have same problem, just remove ` Alpine.start()` from code and all works perfect.

**Comment by keyurshah** [comment]
I tried that but then alpine stops working.

**Comment by calebporzio** [comment]
Would love it if someone could tackle this and PR the solution, it's a nice scoped task and it's not my area of expertise

Or at least maybe others can weigh in about how other packages do this (auto-initialize when included via a script tag, but not when imported in a build).

**Comment by donnysim** [comment]
@calebporzio I think one of the solutions could be:
```js
mix.webpackConfig({
    output: {
        libraryTarget: 'umd',
        library: 'Alpine',
        libraryExport: 'default',
        umdNamedDefine: true,
    },
});
```

```js
if (typeof window !== 'undefined' && ! isTesting()) {
    window.addEventListener('DOMContentLoaded', () => {
        window.Alpine.start()
    })
}
```

the problem is, you cannot execute any kind of code in the exporting script without some kind of waiting - reason being, webpack has not yet assigned the variable to the global object (it being window) as in:

```js
root["Alpine"] = factory(); // <- factory() is retrieving the export, root is `window`
```
so normally it would never trigger on `if (window.Alpine)` in tweaked case, doing it otherwise results in multiple executions because you will never know how it was used (imported etc.).

**Comment by calebporzio** [comment]
Thanks for the info @donnysim.

I ended up switching to a wrapper for rollup called microbundle.

Also, I think we should just auto-initialize for `import` statements. Like not make the user run `Alpin.start()` at all.

That's the current strategy, it will prevent the double execution problem.
