### ISSUE TITLE
Communicate with Alpine component via event listener

### ISSUE THREAD

**Issue by booni3** [alpinejs/alpine#310]
I am using the new-ish livewire method to dispatch a browser event:

```php
$this->dispatchBrowserEvent('showToaster', [
    'title' => 'Oops!',
    'message' => $error
]);
```

Within the HTML, I am initialising my Alpine toaster component and then initiating the event listener within the component method:

```html
<div x-data="toaster()" x-init="listen()">
  <div x-show="show">
    <p x-text="title"></p>
    <p x-text="message"></p>
  </div>
</div>

<script>
    function toaster() {
      return {
        show: false,
        title: '',
        message: '',
        trigger(title, message) {
          this.show = true;
          this.title = title;
          this.message = message;
        },
        listen() {
          this.$el.addEventListener('showToaster', (event) => {
            this.trigger(event.detail.title, event.detail.message);
          });
        }
      }
    }
</script>
```

I feel like I really just stumbled across this method by accident and would like to get some feedback on the best approach for this.

I found that listening for the event outside of the Alpine method would result in the event being fired and the Alpine (`trigger()`) method also being successfully called... but the dom was not effected.

**Comment by HugoDF** [comment]
You can add a global listener using the `.window` or `.document` modifiers eg. `x-on:show:toaster.window` or `x-on:show-toaster.document`.

I believe your specific issue is that camelCased event names cause some odd behaviour so switching to a `:` or `-` separated event will make it work.

I've got a working codepen at https://codepen.io/hugodf/pen/qBdgyzN

Full code, note that `x-on:` needs to be on an element that is a child of the one that has `x-data`.

```html
<div x-data="{ showing: false }">
  <span x-on:show-toast.window="showing = !showing" x-on:show:toast.document="showing = !showing"></span>
  <h2>Demo</h2>
  <button x-on:click="$dispatch('show:toast')">Trigger <code>show:toast</code> on the window/document</button>
  <button x-on:click="$dispatch('show-toast')">Trigger <code>show-toast</code> on the window/document</button>
  <div role="alert" x-show="showing">
    <h3>Alert</h3>
    <p>Showing an alert triggered toggled using a global event</p>
  </div>
</div>
```

**Comment by HugoDF** [comment]
@booni3 did the above solve your problem?

**Comment by ryangjchandler** [comment]
@HugoDF wondering whether we should include a note in the docs about this too...

**Comment by HugoDF** [comment]
🤷🏼‍♀️ there's a lot of other issues with events such as some Livewire & jQuery events that can't be listened to from Alpine since they're not native events.

Not sure I'm a fan of the ergonomics of listing all the caveats that aren't directly Alpine related in the README, it would probably fit more in a "guides" section, which currently is just random blog posts on the internet 🙂.

**Comment by HugoDF** [comment]
@ryangjchandler I think it's safe to close this

@booni3 feel free to reopen if it didn't solve your issue

**Comment by rathod4rathod** [comment]
https://www.youtube.com/watch?time_continue=21&v=njioiqdQX7Y&feature=emb_logo

this is working toster in livewire

**Comment by nathandaly** [comment]
Not to point out the obvious but if we use the HTML syntax of `@custom-event.window` then this works for me.
```js
export default function (state = {
  open: false
}) {
  return {
    open: state.open,

    attachEvent () {
      window.addEventListener('sidebar:show', () => {
        this.open = true;
      });
    }
  }
}

```
