### ISSUE TITLE
Alpine-IE11 spread operator does not work in Edge

### ISSUE THREAD

**Issue by JeanPaulvB** [alpinejs/alpine#312]
### [See jsFiddle example](https://jsfiddle.net/qu4ntyl/rzwvty9o/)

When I use `x-data="dataOne()"` it works both in Chrome (80.0.3987.149) and Edge (44.18362.449.0) but when I use `x-data="{ ...dataOne() }"` it does not work in Edge (nor IE 11).

Is this a known issue? If so, perhaps we should update the [x-data README section](https://github.com/alpinejs/alpine#x-data) to reflect this.

I'm also confused why [**caniuse.com**](https://caniuse.com/#feat=mdn-javascript_operators_destructuring) does show that Edge 14-79 is supported (but [not mentioned here](https://caniuse.com/#search=object%20destructuring)).

**Comment by SimoTod** [comment]
Yeah, spread operator is not fully supported in old versions of edge like the one you mentioned (this should be the page you are after https://caniuse.com/#feat=mdn-javascript_operators_spread_spread_in_object_literals).
Developers can check by themselves that what they use is okay for their target audience (you would have the same eissue using vanilla js) but I think you can send a PR if you feel the documentation is misleading.

**Comment by calebporzio** [comment]
Agreed
