### ISSUE TITLE
x-ref won't focus an input

### ISSUE THREAD

**Issue by flick36** [alpinejs/alpine#317]
Hi so, I've a modal wich i  open abusing the dispatch events (so i can open from outide the component), and i want to focus an input so I've tried using `x-ref` on the input and then applied focus via ` $nextTick`  but it won't focus the input, contrary to when i do `$el.focus()` it'll focus the modal correctly. I've setup an JSBIN here: https://jsbin.com/wigupiloxa/edit?html,output. Any idea what can i do to focus the input?

**Comment by HugoDF** [comment]
Does using setTimeout instead of $nextTick work?

I do believe there's an issue where $nextTick is run at the wrong time during updates

**Comment by flick36** [comment]
Yes, setTimeout works :o

**Comment by HugoDF** [comment]
Cool, there's probably a $nextTick issue then

**Comment by ryangjchandler** [comment]
I'm going to close this issue and ask for any further discussion to be moved to the issue and PR mentioned above. Thanks guys!
