### ISSUE TITLE
x-model debounce not working

### ISSUE THREAD

**Issue by BernhardBaumrock** [alpinejs/alpine#318]
Hi everybody!

Testing AlpineJS for the first time and it looks great, thank you!

Did I miss something or why is debounce not working in this simple codepen? https://codepen.io/baumrock/pen/ExjrdwL

I've tried several different options (with ms, without ms, using x-model or using x-on:input). The value of foo is always instantly updated!

Thank you in advance,
Bernhard

**Comment by SimoTod** [comment]
Your codepen seems to work okay for me. Which browser do you use?

**Comment by jreviews** [comment]
Also works for me.

**Comment by BernhardBaumrock** [comment]
Crazy - it also works for me now. I'm using a recent chrome and I also tried using devtools no-cache setting... No idea what was going on!
I also didn't change my testing scripts where it didn't work before. Now everything works. I've not even changed the version (I'm using the CDN script). No idea, but nevertheless happy that it works now :) Thx guys!

**Comment by SimoTod** [comment]
@BernhardBaumrock no worries. If you use `https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js`, I think it was just the CDN cache. Jsdelivr caches files for about 24 hours and debounce was added in v2.2.2 (less then 2 days ago) so it was probably still serving 2.2.1 for part of the day yesterday.

**Comment by BernhardBaumrock** [comment]
@SimoTod thx that would explain things :)
