### ISSUE TITLE
Prevent copying alpinejs code from view source

### ISSUE THREAD

**Issue by emmatraversy** [alpinejs/alpine#3184]
Hi everyone
The only thing I have problem with alpinejs and tailwindcss is that they can be copied easily from your site source.

Is there any way that we can prevent alpinejs code from easily being copied from source?
Or at least make it harder?

**Comment by emmatraversy** [comment]
Because we spent a lot of time to create something sophisticated with it and we dont wan't it to be copied with very small effort


I remember about 10 12 years ago, some js libraries were coded (transformed) in some jibrish language to make it harder to change the library or copyright.
I though such a thing is possible with alpinejs.

**Comment by DEV-ONI** [comment]
You're referring to an minifier and/or uglifier. You need a build-step to transform your code.
https://www.npmjs.com/package/uglify-js 

You need a bundler in your workflow to automate this process for production builds.

**Comment by emmatraversy** [comment]
I'm sorry, I don't want to uglify the source code of alpinejs. I want to somehow uglify the alpinejs syntax in my frontend.
I have something like this: multiple nested loops and I dont want it to be copied easily:
```
        <template x-for="(attribute, rootindex) in attributes">
          <div
            x-data="{open: false, items:[ ...new Set(products.filter((p) => Object.keys(sele ....
```
or about other components that I have built with alpinejs, Is there any way?

**Comment by SimoTod** [comment]
Nothing out of the box. 
Using x-bind as much as you can and putting your Alpine logic in a js file allows you to uglify the sorce code. 

You can set a custom evaluator copying the Alpine one that decrypts an expression but you also need your server (or some pre deployment process) to encrypt it.

The latter is more complicated and requires you to fork the standard evaluator.

**Comment by emmatraversy** [comment]
Thank you very much for your response.
