### ISSUE TITLE
x-bind on data attributes confusion

### ISSUE THREAD

**Issue by richgcook** [alpinejs/alpine#322]
I'm having a hard time being able to bind to data attributes, much like you can do with `x-bind:class` or `:class`.

`x-bind:data-panel-active="{ 'true' : panelID !== 0 }"`

In devtools it outputs as:

`data-panel-active="[object Object]"`

Any thoughts?

**Comment by SimoTod** [comment]
You are binding an object to a normal attribute (classes are special cases as described in the readme).
You probably just need something like `x-bind:data-panel-active="panelID !== 0"`.
(there's no much context so it might not be what you need, but the readme should show you an example).

**Comment by richgcook** [comment]
Ah okay, that makes sense!
