### ISSUE TITLE
x-for not working anymore in version 2.2.4

### ISSUE THREAD

**Issue by WL1981** [alpinejs/alpine#326]
x-for in combination with a x-if not working any more.
See jsfiddle example to repoduce

**AlpineJS - 2.3.3** (Working)
https://jsfiddle.net/WFL1981/j4hn9ofw/2/

**AlpineJS - 2.3.4** (Not working)
https://jsfiddle.net/WFL1981/0v5b46r1/3/

**Comment by calebporzio** [comment]
Thanks for the bug report, this issue has been fixed in v2.2.5
