### ISSUE TITLE
x-mask $money() input allows characters

### ISSUE THREAD

**Issue by finesheer** [alpinejs/alpine#3267]
x-mask $money() input allows characters that are not numeric.

`<input x-mask:dynamic="$money($input)">
`

This is the example from the docs. If you visit  [#Money Inputs] (https://alpinejs.dev/plugins/mask#money-inputs) , you can reproduce.

<img width="769" alt="Screenshot 2022-11-09 at 6 54 30 PM" src="https://user-images.githubusercontent.com/32717047/200967062-e5f9a75e-e7c6-4347-a67f-dd55a06f2e6d.png">

**Comment by gaetan-hexadog** [comment]
Just saw it too.

If the first char is not a number then we can put any characters.
But once we put a number the previous non-number characters are deleted and we can't add characters other than numbres.
