### ISSUE TITLE
Unexpected token ... in Alpine.min.js

### ISSUE THREAD

**Issue by jn-cavera** [alpinejs/alpine#3269]
I run Checkbot on all of my projects and I keep getting the same error every time I use Alpine. Alpine works fine but I'd love to not have to explain this error to my clients every time. Would love it if  there was something I can do to fix it. The error I get is...

`Line 1, Column 3531, Unexpected token ...`

Which is not super helpful. I believe the error originates the following line in the D(e) function

`Object.defineProperty(i, n, { ...c, get: s, set: a })`

Anyone have any thoughts?

**Comment by SimoTod** [comment]
The decostructing syntax is supported by all modern browsers as far as I know. I assume Checkbot is targetting some older browsers like Internet Explorer that are not supported by Alpine.

The only way would be to use the npm version and transpile for old browsers but it will make the size of the file sensibly bigger.

**Comment by jn-cavera** [comment]
Thanks @SimoTod. I'm all for going for efficiency or support for IE which at this point feels a little pointless. That at least gives me a good technical reason I can give to my clients as opposed to just blaming it on Alpine blindly. Really appreciate it.
