### ISSUE TITLE
Load more system

### ISSUE THREAD

**Issue by seb-jean** [alpinejs/alpine#327]
Hi :),

I would like to know if it is possible to make a "Load more" system with Alpine JS.

For example, for a blog post, I would like to display 2 comments, then 2 more, etc.

The URL which will display the first 2 comments is: https://jsonplaceholder.typicode.com/posts/1/comments?_page=1&_limit=2

Then we click on the button to see more comments.

The second URL called is:

https://jsonplaceholder.typicode.com/posts/1/comments?_page=2&_limit=2

Then we click a new one on the button to see more comments.

The third URL called is:

https://jsonplaceholder.typicode.com/posts/1/comments?_page=3&_limit=2

I would like to display the name and body.

I think you should use the fetch function but after that I am completely lost.

Thank you for helping me :)

**Comment by KiryaAfimin** [comment]
Hi! For example like this [jsfiddle](https://jsfiddle.net/6au1onme/1/) !

**Comment by calebporzio** [comment]
Thanks for the suggestion @KiryaAfimin! There are plenty of ways to do this. I'm going to close this issue for now, but others are free to chime in and offer other guidance.
