### ISSUE TITLE
x-for - how to use with pre-existing lists in html?

### ISSUE THREAD

**Issue by piotrpog** [alpinejs/alpine#329]
Let's say that I have list of images that were rendered by the backend of my website and exist in HTML. I want to have ability to add new images to that using alpine but I start with existing HTML elements.

How can I use `x-for` in such a situation to loop through all images and add new ones?

**Comment by SimoTod** [comment]
Alpine doesn't support a mixed approach. We discussed a couple of ways to implement it here -> https://github.com/alpinejs/alpine/issues/196
The easiest way is to print your serverside data in a js object, pass it to x-for and let Alpine render your list.

**Comment by ryangjchandler** [comment]
Agreed. I would actually dump the server side items into its own script tag on the page with a variable attached to the window, then reference that in your Alpine data.

**Comment by ryangjchandler** [comment]
Closing this issue now, as the one mentioned above has been closed and there's no current easy way to do this. If you want to discuss ideas on implementation though, please feel free to create a new issue. Thanks! :)
