### ISSUE TITLE
Using magic variables in external functions

### ISSUE THREAD

**Issue by piotrpog** [alpinejs/alpine#331]
How can I use magic variables like `$refs` in external functions?

**Comment by piotrpog** [comment]
To aleborate - in this codepen example:

https://codepen.io/piotrpog/pen/dyoLwJO

I already have `start()` method in external function, but cannot have function attached to button - because shows error that `$refs` is not defined.

**Comment by SimoTod** [comment]
Do you mean inside a function in your component data context (like the start function in your codepen)? You need to use this.$refs inside the function.

**Comment by ryangjchandler** [comment]
Exactly as @SimoTod said. When writing an inline handler, Alpine will automatically handle any reference to your data. Outside that scope, (inside of your JS file), the functions context will be bound to `this`.

**Comment by ryangjchandler** [comment]
Hi guys. Closing this issue since @SimoTod provided an answer. If you have any problems @piotrpog with the method provided, please open another issue.
