### ISSUE TITLE
Update state from outside component (Laravel Echo)

### ISSUE THREAD

**Issue by matsava** [alpinejs/alpine#332]
I am looking for a way to update a component's state outsite the component. My use case is a simple chat implementation based on Laravel Echo. I'd like to listen for the event and somehow push to the messages array of the state. Is this possible right now?

```
<div x-data="{messages: []}">
// loop
</div>

Echo.private('App.User.' + {{ auth()->user()->id }})
     .listen('MessageReceived', (response) => {
         // push to alpine
     });

```

**Comment by SimoTod** [comment]
You can use browser events to communicate with a Alpine
```html
<div x-data="{messages: []}" @message.window="messages.push($event.detail.msg)">...</div>
...
var event = new CustomEvent('madeBlue', {detail: {msg: 'YOUR MESSAGE' }});
window.dispatchEvent(event);
```

https://codepen.io/SimoTod/pen/BaNEbMW

**Comment by matsava** [comment]
Thas was it! Thank you very much @SimoTod :)
