### ISSUE TITLE
Click outside event

### ISSUE THREAD

**Issue by piotrpog** [alpinejs/alpine#334]
Hey,
is there some option for funning code if user clicked outside an element? Something like `@clickOutside`.
I think it would be really useful, for example for closing modals.

**Comment by HugoDF** [comment]
For this you should be able to use the `.away` modifier. Eg. `@click.away`

**Comment by ryangjchandler** [comment]
@piotrpog have you had any more issues with this?

**Comment by ryangjchandler** [comment]
Hi guys. Gonna close this since @HugoDF provided an answer. If you've got any problems @piotrpog, please open another issue.
