### ISSUE TITLE
Alpine discord

### ISSUE THREAD

**Issue by piotrpog** [alpinejs/alpine#335]
I think the alpine community could really use a discord channel!

**Comment by piotrpog** [comment]
Hey, until something official is created, I decided to create some temporary server:

https://discord.gg/D2NWvJ

**Comment by HugoDF** [comment]
Should we close this since we've got a community discord now?

**Comment by philippbosch** [comment]
@piotrpog I think the invite link expired. How to get on the discord now?

**Comment by HugoDF** [comment]
This link should work https://discord.gg/snmCYk3

**Comment by the94air** [comment]
@piotrpog Publish a permanent link here please so others can join. Thanks.

**Comment by quasipickle** [comment]
This is the #1 Google result for "alpinejs discord".  If it's an official channel it could be advertised better.

**Comment by HugoDF** [comment]
> This is the #1 Google result for "alpinejs discord".  If it's an official channel it could be advertised better.

There's a badge in the README

**Comment by quasipickle** [comment]
Oh jeez, I totally missed it.  Graphics in that style are usually related to project or test status, I skipped right over it.

**Comment by hasansezertasan** [comment]
> There's a badge in the README

I couldn't find it. Can you share it again?

**Comment by SirNovi** [comment]
Is there an Alpine Discord or not? Don't see anything in the readme

**Comment by SimoTod** [comment]
The link was removed from the readme since it's not an official channel. You can still see it on the readme if you switch to the old v2 branch. The discord channel hasn't changed
