### ISSUE TITLE
x-modelable and x-model not working with equal names

### ISSUE THREAD

**Issue by ahlvd** [alpinejs/alpine#3352]
I spotted an unexpected behaviour using x-modelable. If the variables name in x-modelable equals the name used in x-model it won't work.

Example:
```blade
<div 
   x-data="{items: []}" 
   x-init="setTimeout(() => items.push({id: Date.now(), name: 'TEST'}), 1000)">
  
    This snippet will work as expected, displaying '1' on the inner div:
    <div x-data="{things: []}" x-modelable="things" x-model="items">
        <div x-text="things.length"></div>
    </div>  

    While this snippet remains displaying '0':
    <div x-data="{items: []}" x-modelable="items" x-model="items">
        <div x-text="items.length"></div>
    </div> 
</div>
```

Rendered HTML:
```blade
<div x-data="{items: []}" x-init="items.push({id: Date.now()})">
    <div x-data="{things: []}" x-modelable="things" x-model="items">
        <div  x-text="things.length">1</div>
    </div>
    <div x-data="{items: []}" x-modelable="items" x-model="items">
        <div x-text="items.length">0</div>
    </div>
</div>
```

In the second snippet the name used by x-modelable and x-model is equal. This is an issue because I was trying to make a reusable blade component where it can break functionality if a developer doesn't know the internal uses name and will be surprised if it does not work as expected.

Am I missing something or is this kind of a bug?

Used versions: alpine.js 3.10.5 / Google Chrome (current)

**Comment by SimoTod** [comment]
You are redefining items in your inner x-data so the inner x-model will point to that one rather than the external one maxe your x-modelable superfluous. At some point someone proposed to allow x-modelable to bind to an external x-model which I think will also fix your use case but it hasn't been implemented so far.

**Comment by ahlvd** [comment]
Can you modify my example as you think I should handle it? I think I did not get your point.

I came over this issue when we tried to do some nested x-for loops where we sometimes got `item is not defined errors` we tried to solve using x-modelable:

We changed:
```blade
<div x-data="{items: [...]}>
   <template x-for="(item, index) in items">
       <div x-text="item.id"></div>
   </template>
</div>
```
to:
```blade
<div x-data="{items: [...]}>
   <template x-for="(item, index) in items">
       <div x-data="{item: {}}" x-modelable="item" x-model="item">
           <div x-text="item.id"></div>
      </div>
   </template>
</div>
```
But that does not work.

If we change one name to eg. "thing" it works:
```blade
<div x-data="{items: [...]}>
   <template x-for="(thing, index) in items">
       <div x-data="{item: {}}" x-modelable="item" x-model="thing">
         <div x-text="item.id"></div>
      </div>
   </template>
</div>
```

If that is the expected behaviour it should be stated in the [docs](https://alpinejs.dev/directives/modelable).

**Comment by SimoTod** [comment]
so... in your component, when you access a property (for example items) it reads it from the closest x-data that define the property (which is kind of obvious if you think about that)

```html
<div x-data="{foo: 'bar'}">
   <div x-data="{baz: 'bob'}"
     <span x-text="foo"></span> <!-- prints "bar" -->
  </div>
</div>

<div x-data="{foo: 'bar'}">
   <div x-data="{foo: 'bob'}"
     <span x-text="foo"></span> <!-- prints "bob" -->
  </div>
</div>
```

In your first example, you have an array called items where you push an element every 100ms, then in your inner component you redefine items so, in that context, the items property is always an empty list. The x-model you added to the inner component again points to the closest x-data (including the current element) so it's bound to the empty list.

If you think it would beneficial to have something in the docs, you can send a PR. Usually, the maintainer accepts documentation improvement.

**Comment by ahlvd** [comment]
@SimoTod Ok I think I got it now. It's all about the scope ^^. 

Thanks for your help!

**Comment by ahlvd** [comment]
… I just found out in the sources that there will probably be a `parent`-modifier for `x-model` to support my issue. But it's not yet in the official release. Then I could use it like this:

```blade 
<div x-data="{items: []}" x-modelable="items" x-model.parent="items">
    <div x-text="items.length"></div>
</div>
```

`x-model` will then reference to the closes `x-data` of the parent element. 🤞
