### ISSUE TITLE
Is it possible to use x-text to replace element original content conditionally?

### ISSUE THREAD

**Issue by piotrpog** [alpinejs/alpine#336]
I have some element which is filled with server-rendered content. Can I use `x-text` (or `x-html`) conditionally, so variable replaces original content only if some condition is met?

**Comment by HugoDF** [comment]
Not the prettiest but you I think you can conditionally make `x-text`/`x-html` a noop using `$el.innerText` and `$el.innerHTML`, eg:
`<div x-text="someBoolean ? newValue : $el.innerText">My text</div>`

See the codepen with x-html example https://codepen.io/hugodf/pen/YzXbYVq

**Comment by HugoDF** [comment]
You can also probably use refs (`x-ref` + `$refs`) instead of `$el`. 

And to top the whole thing off, on x-init, save the initial content/markup so you can toggle it on/off.

**Comment by ryangjchandler** [comment]
This is possible as far as I know. I'd probably go down the route that @HugoDF suggested in the first comment.

**Comment by ryangjchandler** [comment]
Hi @piotrpog , anymore problems with this one?

**Comment by ryangjchandler** [comment]
Going to close this issue since there are a couple of solutions mentioned in the thread. @piotrpog if you have any more problems, please create another issue. Thanks! :)

**Comment by piotrpog** [comment]
@ryangjchandler Sure, thanks!
