### ISSUE TITLE
Spelling error in comments

### ISSUE THREAD

**Issue by ryangjchandler** [alpinejs/alpine#338]
There is a small spelling error inside of the `component.js` file. This would make a great first contribution, especially to please all of those grammar nazis.

**Comment by HugoDF** [comment]
Might be time to revive that PR 😂

**Comment by ryangjchandler** [comment]
> Might be time to revive that PR 😂

I think you might be right haha, will re-open PR.

**Comment by AdetunjiTejumade** [comment]
Should I do this?

**Comment by ryangjchandler** [comment]
> Should I do this?

Yeah go for it man. Would be a great first issue to get that contributor badge :)

**Comment by AdetunjiTejumade** [comment]
#373

**Comment by AdetunjiTejumade** [comment]
only found one spelling error

**Comment by AdetunjiTejumade** [comment]
Line 58

**Comment by AdetunjiTejumade** [comment]
#385

**Comment by calebporzio** [comment]
Thanks everyone, merged change
