### ISSUE TITLE
combine x-for with x-data on same element

### ISSUE THREAD

**Issue by Te7a-Houdini** [alpinejs/alpine#339]
when i try this

```html
<div  x-data="{ items: ['foo', 'bar'] }" >

	<template x-for="item in items" :key="item" x-data="{'some' :'sort'}">
		<div x-text="item">

		</div>
	</template>
</div>
```
gives this error

![Screenshot from 2020-04-04 00-21-27](https://user-images.githubusercontent.com/17250137/78409539-3c33ce00-760a-11ea-9c3b-32da15adcf87.png)

**Comment by ryangjchandler** [comment]
Data is not passed as you are expecting. Adding `x-data` to the template tag will declare and initialise a new component that has no knowledge of the `item` variable. 

What exactly are you trying to use the nested `x-data` attribute for?

**Comment by Te7a-Houdini** [comment]
@ryangjchandler i wanted same behavior of vue js like looping on multiple components

```html
//we are inside PostList.vue
<template>
     <Post v-for="post in posts" :post="post">
 </tempalte>
```

**Comment by SimoTod** [comment]
The Vue example is different from the one you wrote in Alpine, though.

It would translate to something like
```html
	<template x-for="post in posts">
		<Post :post="post"></Post>
	</template>
```

Be aware that, at the moment, Alpine doesn't work with custom elements using the shadow DOM.

**Comment by Te7a-Houdini** [comment]
@SimoTod  thanks for the clarification . actually i don't want to create custom element i just want to be able to add x-data to x-for . it's like creating multiple components on the fly using x-for

**Comment by ryangjchandler** [comment]
For what purpose do you want those on the fly components? If you need to track data for each item, do it using the item itself.

**Comment by Te7a-Houdini** [comment]
@ryangjchandler  my use case is something like that

```html
<div x-data="{students : [{"name" : 'ahmed' , 'details' : {somedetails}}]}">
 <template x-for="student in students" x-data="{'open' : false}">
    <a href="#" class="block component" :class="{'opened' : open == true}" @click="open = !open">
               //here some HTML tags
     </a>
 </template>
</div>

**Comment by ryangjchandler** [comment]
Yeah, I would add an open property to the item object instead, you can then use `item.open` instead of `open`.

**Comment by Te7a-Houdini** [comment]
@ryangjchandler thanks for suggestion and i will implement it right now . 

but aquick note . these data are from backend server so basically i will add an extra complexity if i mapped the data and added this property while for me it seems that each student is a component .

**Comment by ryangjchandler** [comment]
Just add the extra open property on the server, no front end processing then.

**Comment by ryangjchandler** [comment]
@Te7a-Houdini have you had any further problems with this?

**Comment by Te7a-Houdini** [comment]
@ryangjchandler nope i didn't

**Comment by ryangjchandler** [comment]
> @ryangjchandler nope i didn't

Could you please close the issue, thanks!
