### ISSUE TITLE
Can not use $refs in x-if

### ISSUE THREAD

**Issue by sibbngheid** [alpinejs/alpine#34]

**Comment by calebporzio** [comment]
Should work well, just tried locally. $refs had a bug that I recently fixed, and maybe that'd be the problem. Re-open if not.

**Comment by sibbngheid** [comment]
My original issue was using v1.1.1. Works in v1.1.3. Looks like fixed in here: https://github.com/alpinejs/alpine/compare/v1.1.2...v1.1.3#diff-d24fe73020f46dde060f58786e987b61
