### ISSUE TITLE
Removing H2 element from example code unexpectedly changes behavior

### ISSUE THREAD

**Issue by codepilotsf** [alpinejs/alpine#3419]
### Discussed in https://github.com/alpinejs/alpine/discussions/3417

<div type='discussions-op-text'>

<sup>Originally posted by **codepilotsf** February 11, 2023</sup>
Using the morph example provided in the Alpine Morph plugin docs, I'm getting unexpectedly different behavior by simply removing the unrelated H2 element in the example.

Steps to repeat:

1. Create a simple HTML doc with morph plugin and alpine core CDN tags
2. In the newHTML to be morphed, change x-data message val to "Changed!"
3. Test in browser and observe that it behaves normally
4. In the newHTML to be morphed, remove this line:
    `<h2>See how new elements have been added</h2>`

With that unrelated H2 element removed, the behavior is completely different. Rather than immediately changing the value of `message`, the first click retains previous state, then the second click updates the value of `message`. Why should removing that H2 element cause this change in behavior?

Here's a < 90 seconds video showing the issue: https://capture.dropbox.com/hdjYA6L8Si1TLdgL

</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/alpinejs/alpine/discussions/1423
