### ISSUE TITLE
Remove and add classes to elements when Alpine initialises

### ISSUE THREAD

**Issue by MikeHarrison** [alpinejs/alpine#343]
I am using Tailwind CSS for styling my site, and adding Alpine as progressive enhancement to certain elements (e.g. navigation). As a result, I would like the ability to remove and add classes to some elements when Alpine initialises, as some of my "non-js" styles are not required.

Is it possible to remove classes from elements on Alpine initialisation? Currently I am doing this to add classes, in this example it is to make the header fixed when javascript and Alpine are running:

```
x-data="{ navOpen: false }"
:class="[navOpen ? 'fixed' : 'fixed']"
```

But I would also like to remove some classes as well.

Any pointers would be great

**Comment by ryangjchandler** [comment]
Good question. I've not actually needed to do this, will do some research. Maybe @HugoDF or @SimoTod will know an answer sooner, or @calebporzio if he's not busy rewriting Alpine ;)

**Comment by HugoDF** [comment]
From working on this part of the codebase, there isn't a mechanism for it.

When the class attribute is bound the classes from `:class` will be added to the static classes from `class`.

So to support this should probably only use the classes in the binding.

**Comment by ryangjchandler** [comment]
It's possible you could return a callback from the `x-init` directive if you want to run some code after Alpine has initialised and run it's first DOM updates. 

You could remove / add the class then.

**Comment by SimoTod** [comment]
As the guys said, it's not possible at the moment. You can either use init as suggested by Ryan or you can write your css in a way that, when Alpine classes are added, other classes stop working. I think you can add something like 'alpine-loaded'  and use the not selector in your css `.yourclasss:not(.alpine-loaded) {...rules that you want to apply only without alpine...}`

**Comment by MikeHarrison** [comment]
Hi all,

Thanks for all the responses, I appreciate it.

@SimoTod this would definitely work - I am aiming not to write custom CSS for this project beyond Tailwind customisations, but will do this if I can't get an "on-page" solution to work

@ryangjchandler I am trying the `x-init` approach you suggest, as that method seems to provide what I am after. Is it possible to run this on elements within the component? Reduced test case component below to illustrate what I am attempting:

```
<div 
  x-data="{ open: false }"
  >
<button 
  class="hidden"
  x-init="() => { $el.classList.remove('hidden');$el.classList.add('block') }"
  >
  Button</button>
</div>
```
I am new to Alpine so may be mis-using the `$el` or `x-init` properties here, but the above does not work for me. If I add the `x-init` to the same element as `x-data` it functions as I would expect.

Thanks again for the help, really enjoying using Alpine

**Comment by ryangjchandler** [comment]
`x-init` can only be used on the root element, similar to how Vue's `mounted` hook is at the component level too.

**Comment by SimoTod** [comment]
Basically you can have something like

```html
<div x-data="{...}" x-init="$refs.mybutton.classList.remove('hidden')">
   <button :class="block" x-ref="mybutton">click me</button>
</div>
```

I've typed it from my phone so there could be typos in the snippet but that's the general concept. You can check out the x-ref section in the readme for more details. 

If you are just after hiding element before Alpine starts, you probably just want to use x-cloak (https://github.com/alpinejs/alpine/blob/master/README.md#x-cloak). You'll just need to add 1 line of css in that case.

**Comment by MikeHarrison** [comment]
That is great! Between `x-cloak` and the `$refs` method from @SimoTod above I have the toolkit I need to do my progressive enhancement of components.

Thanks for the help all

**Comment by AhmadAlaraj71** [comment]
You can try this 

```
  :class="{ 'block' : !open , 'hidden' : open}"
```

or 

```
  :class="{ 'block' : open , 'hidden' : !open}"
```

depend on what you need,  in this case the class will be removed and add a new class

**Comment by anujkamboj7** [comment]
Thanks ahmad it's working prefectly

**Comment by SimonPadbury** [comment]
> You can try something like
> 
> ```
>   :class="{ 'block' : !open , 'hidden' : open}"
> ```

Thankyou, very useful. This above can be used with a ternary operator (from Alpine 3 anyway, if not before).

```
:class="open ? 'block' : 'hide-md-up'"
```

Here e.g. I have CSS for hiding a dropdown in a menubar above its `md` breakpoint, (while I can hide the button below the `md` breadpoint).

Besides putting 'block' in there, if you are using a framework with utility classes, you can put in all the positioning, rounded corners, box shadows, background color. So, a dropdown within an uncollapsed menubar could be e.g.:

```
:class="open ? 'block absolute-sm mt-1 px-3 py-1 bs-1 rounded-sm bg-white' : 'hide-md-up'"
```

Alpine FTW

**Comment by casam** [comment]
I have similar Alpine problem but in my case it's to make an item in a drop-down list to be active when clicked on.

<div class="select-menu" x-data="{ open: false }" :class="open ? 'active' : ''">
                            <div class="select-btn" @click="open = ! open">
                                <div class="d-flex">
                                    @if ($planSelected)
                                        <span class="mr-2 fas fa-hand-holding-seedling"></span>
                                        <span class="sBtn-text">{{ $planSelected->name }}</span>
                                    @else
                                        <span class="sBtn-text">Select your a plan</span>
                                    @endif
                                </div>
                                <i class="fas fa-angle-down"></i>
                            </div>
 
                            <ul class="options">
                                @foreach ($plans as $plan)
                                    <li class="option" wire:click="selectPlan({{ $plan->id }})"
                                        @click=" open=false">
                                        <i class="fas fa-hand-holding-seedling"></i>
                                        <span class="option-text">{{ $plan->name }}</span>
                                    </li>
                                @endforeach
 
                            </ul>
                        </div>

**Comment by casam** [comment]
I am having a similar alpine problem on my drop down list. I want to make a selected item on the list to be active after selection but instead it closes the list.

    '''
<div class="select-menu" x-data="{ open: false }" :class="open ? 'active' : ''">
                            <div class="select-btn" @click="open = ! open">
                                <div class="d-flex">
                                    @if ($planSelected)
                                        <span class="mr-2 fas fa-hand-holding-seedling"></span>
                                        <span class="sBtn-text">{{ $planSelected->name }}</span>
                                    @else
                                        <span class="sBtn-text">Select your a plan</span>
                                    @endif
                                </div>
                                <i class="fas fa-angle-down"></i>
                            </div>
 
                            <ul class="options">
                                @foreach ($plans as $plan)
                                    <li class="option" wire:click="selectPlan({{ $plan->id }})"
                                        @click=" open=false">
                                        <i class="fas fa-hand-holding-seedling"></i>
                                        <span class="option-text">{{ $plan->name }}</span>
                                    </li>
                                @endforeach
 
                            </ul>
                        </div>
'''

**Comment by casam** [comment]
I am having a similar alpine problem on my drop down list. I want to make a selected item on the list to be active after selection but instead it closes the list.

class="select-menu" x-data="{ open: false }" :class="open ? 'active' : ''"

class="select-btn" @click="open = ! open

                             @if ($planSelected)
                                        <span class="mr-2 fas fa-hand-holding-seedling"></span>
                                        <span class="sBtn-text">{{ $planSelected->name }}</span>
                                    @else
                                        <span class="sBtn-text">Select your a plan</span>
                                    @endif
                                </div>
