### ISSUE TITLE
$refs and $el already exist on VueJs

### ISSUE THREAD

**Issue by ik19** [alpinejs/alpine#345]
Hello,
I just tested this great framework in my VueJs project.
Unfortunately, `$refs` and `$el` already exist on VueJs, so it is impossible to use them in a VueJs project.
Using `x-on` instead of `@` avoids confusion with VueJs, is it possible to change `$ref` to a variable more specific to Alpine ?
Thank you :)

**Comment by ryangjchandler** [comment]
Can I ask why you're using Alpine alongside Vue, just out of curiosity?

**Comment by ik19** [comment]
> Can I ask why you're using Alpine alongside Vue, just out of curiosity?

Because my project is already in vueJs, also vueJs is very complete, so I can't do without it.
How did I come to discover Alpine ?
I was looking for how to open my sidebar from my header knowing that the two have no parent-child relationship and the cleanest and simplest solution seems to me, is to be using $ref with Alpine.
I also want to adopt it for my dumbs components (modals, dropdown, etc ...) because everything is from scratch and Alpine is very simple and clean for this type of components.

**Comment by ryangjchandler** [comment]
Okay. This is a limitation in the way of the framework, since Alpine is meant to replace your Vue / React components.

There would be no renaming of variables on v2 as it is a breaking change, so your best bet is to either use Vue or pull those component out of your Vue components completely and instead use regular HTML.

**Comment by ik19** [comment]
Ah okay, I thought the use of both was possible. In any case, this project has a bright future ahead of it.

**Comment by HugoDF** [comment]
> Unfortunately, $refs and $el already exist on VueJs, so it is impossible to use them in a VueJs project.

Do you have an example of this? I'm pretty sure you can work around it by using the `function` style of `x-data` component definition.

**Comment by ryangjchandler** [comment]
> > Unfortunately, $refs and $el already exist on VueJs, so it is impossible to use them in a VueJs project.
> 
> 
> 
> Do you have an example of this? I'm pretty sure you can work around it by using the `function` style of `x-data` component definition.

You could take this approach, so long as the function is outside of your component to make sure that `this` is always bound correctly.

**Comment by ik19** [comment]
In my case, I have approximatively this :
```
<main>
    <Header />
    <Sidebar />
</main>
```
```
// Header
    <button @click="openSidebar"></button>
```
```
// Sidebar
<anElement/>
<aside ref="sidebar" show="open"></aside>
```
A priori, yes I can use `x-data` by putting it in the parent file around the 2 components.
But I was looking for the cleanest possible solution and I found that creating a global event bus in VueJs was what I needed.

I am new in vueJs also so I have trouble seeing its full scope but for the dumbs components I know that I'll always be able to rely on Alpine

**Comment by HugoDF** [comment]
@ik19 I think if you have Vue.js available you should probably leverage that as much as possible.

Alpine.js is a great alternative (with a similar API) for when you don't need all the Vue.js functionality or you enjoy the fact that it's explicitly designed for direct CDN include (vs having CLI etc).

**Comment by ryangjchandler** [comment]
Agree with @HugoDF on this one. Using the functional approach to `x-data` should fix all of the problems you're having. Will close this issue now :)
