### ISSUE TITLE
@click fires twice within an x-if template

### ISSUE THREAD

**Issue by atomgiant** [alpinejs/alpine#348]
@click handlers on a button are firing twice each time the button is clicked if the button is inside an x-if template.

I wrote up a simple example to highlight this behavior:

https://codepen.io/atomgiant/pen/ExVYxxy

Thanks!

**Comment by ryangjchandler** [comment]
Thanks for giving an example. This looks like a bug, unless it's intended behaviour but I doubt it. Will investigate.

**Comment by SimoTod** [comment]
It does look like a bug. I think we had similar issue with the x-for directives at the beginning. 
I've drafted a PR which should fix it.

**Comment by ryangjchandler** [comment]
Well, ya beat me to it. Nice work @SimoTod!

**Comment by atomgiant** [comment]
Wow thanks for the incredible turnaround on fixing this one guys.  Really appreciate it 👍
