### ISSUE TITLE
x-if: if there are more than one element on root level of template first one will be removed but others stay

### ISSUE THREAD

**Issue by sibbngheid** [alpinejs/alpine#35]
```html

      <template x-if="open">
        <div>this will be removed from dom</div>
        <div>this will stay in dom</div>
      </template>
```

If i cover them in a div it is works. Maybe this is must be documented.

**Comment by calebporzio** [comment]
Hmmm... this is not in the docs. It makes sense based on the current implementation.

I'm just trying to figure out if it's possible to implement this with multiple roots, but for now, let's just say no (and I'll document it)

Thanks!
