### ISSUE TITLE
Select inside x-if resets values

### ISSUE THREAD

**Issue by murwa** [alpinejs/alpine#3646]
### Discussed in https://github.com/alpinejs/alpine/discussions/3645

<div type='discussions-op-text'>

<sup>Originally posted by **murwa** July  7, 2023</sup>
I've made a pen [here](https://codepen.io/Murwa/pen/KKrXmzG) to show this behaviour. To reproduce on the pen:-
- select a value
- press next
- press previous to show the select input again

The initially selected framework will not be selected on the select, but the value is still intact. It's like x-model just turns a blind eye.</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/alpinejs/alpine/discussions/1423
