### ISSUE TITLE
x-model jumps cursor to end in Safari

### ISSUE THREAD

**Issue by gilbert** [alpinejs/alpine#366]
To reproduce:

- Open [this flems](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8YWACcyAB3gACMKNgBeADogc8CWFQB6LbCR0MAKzBJoZAG6iMdCPC0BzLFoZQJZG8eev3EAALmAJgwggFYtJDIwOxc3GwxcdyMwFQA+QS0RcSkUpTpcwSgGACNoFIAVAE8JCGksCFEIVHTCkqgcukEI82kADwBaJAZ4BmUQYGkkVGkAcmnpAF9U3OlpQXcJAFcZeCqIUcQe+BVevtxuUyhRpCW6FeEJBlv+g-gr1PSwB7p29K72zkgMAQZF4VHQIVQAQAbCB5oR6EwWOgkpweHwIAJ0LD4SBGMxWBhYGAqMQ0fx4KxYQBdeZAA) in desktop or mobile safari
- Type some text into the text box
- Move your cursor to the middle of your text
- Type or delete a character

The cursor jumps to the end of the input.

**Comment by muzafferdede** [comment]
This issue has been acquired in multiple js frameworks. 
I played around and use a stupid way to fix it and it worked. But i believe Caleb will have better way to implement and understand the issue. Here is what i have done at:
`src/directives/model.js`
```typescript
function generateModelAssignmentFunction(el, modifiers, expression) {
    ...
    return (event, currentValue) => {
       ...
        } else {
            //Get the origin cursor position before updating the value
            const cursorPosition = {
                start: el.selectionStart,
                end: el.selectionEnd,
            }

            const rawValue = event.target.value
            const number = rawValue ? parseFloat(rawValue) : null

            //Set the current curspor position back to origin
            setTimeout(() => {
                el.selectionStart = cursorPosition.start
                el.selectionEnd = cursorPosition.end
            }, 10)

            return modifiers.includes('number') ?
                (isNaN(number) ? rawValue : number) :
                (modifiers.includes('trim') ? rawValue.trim() : rawValue)
        }
    }
}

```

I don't know why i can't set origin position right after value being updated. So i have to use timeout the prevent jumping. Otherwise cursor will still jump to the end event setting the cursor position manually. 

Hopefuly this will help.

**Comment by SimoTod** [comment]
@muzafferdede have you tried fixing it at this line https://github.com/alpinejs/alpine/blob/master/src/directives/bind.js#L39? 
I assume we can read the cursor position before, set the value and set the position again after without using timeouts.

**Comment by muzafferdede** [comment]
I just tried as well and worked like charm. Cheers for the suggestion. I did send pull request. Happy to contribute :)

**Comment by muzafferdede** [comment]
Test failed. 
```js
test('x-model casts value to number if number modifier is present', async () => {
    document.body.innerHTML = `
        <div x-data="{ foo: null }">
            <input type="number" x-model.number="foo"></input>
        </div>
    `

    Alpine.start()

    fireEvent.input(document.querySelector('input'), { target: { value: '123' }})

    await wait(() => { expect(document.querySelector('[x-data]').__x.$data.foo).toEqual(123) })
})
```
Is it because "text" and "number" inputs uses same test?
