### ISSUE TITLE
x-trap does not working in Shadow DOM

### ISSUE THREAD

**Issue by bty888** [alpinejs/alpine#3665]
### Discussed in https://github.com/alpinejs/alpine/discussions/3663

<div type='discussions-op-text'>

<sup>Originally posted by **bty888** July 18, 2023</sup>
hi ,
i'm trying to implement this example show in the documentation  https://alpinejs.dev/plugins/focus#x-trap using web components (with Shadow DOM) , the tabbing dose not work with shadow DOM but does without it .

A snippet to reproduce this issue : https://codepen.io/vm09/pen/vYQxBqY</div>

**Comment by joshhanley** [comment]
/
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/alpinejs/alpine/discussions/1423
