### ISSUE TITLE
[Events] x-on:submit and x-on:submit.prevent does not work

### ISSUE THREAD

**Issue by nugetchar** [alpinejs/alpine#37]
Let us say I have a form: 

```html
        <form>
            <input type="text">
            <button type="submit">Do something</button>
        </form>
```

If I want to prevent the default submit, the following code does not work:

```html
        <form x-on:submit.prevent>
            <input type="text">
            <button type="submit">Do something</button>
        </form>
```

And neither does:

```html
        <form x-on:submit="event.preventDefault();">
            <input type="text">
            <button type="submit">Do something</button>
        </form>
```

Am I doing it incorrectly, or maybe it is not implemented yet (if so I would gladly try to contribute myself).

**Comment by tlgreg** [comment]
Both works here. The form is a descendant of an element with `x-data`, right?

**Comment by nugetchar** [comment]
Ha, no, sorry, I did not do that. I am going to test with that, thank you!

**Comment by gavinhewitt** [comment]
> Both works here. The form is a descendant of an element with `x-data`, right?

Thanks, that was it for me too

**Comment by bogstandard** [comment]
Just as a note to anyone trying the above descendent fix & still struggling, having `action=".."` and/or `method=".."` on the form stopped Alpine's `e.preventDefault` or `x-on:submit.prevent` from working as expected in my case. Removing these from the `<form>` element solved the issue.

**Comment by arthurshlain** [comment]
Just another note: if you use `$dispatch` shortcut for form ancestors, don't call your custom event as `submit`.
