### ISSUE TITLE
Why not include Polyfills for IE11 in core project? 

### ISSUE THREAD

**Issue by rverrips** [alpinejs/alpine#38]
I know IE11 is a pain, but considering it's still shipped with Windows 10 chances are it'll be around until 2023 or even 2025 :(    
@calebporzio could you advise you don't just include the polyfills for IE11 in the core of alpine?    
(to me this feels like the kind of "invisibility" alpine and livewire are all about)

**Comment by keyurshah** [comment]
For me it’s better to not have it included. You can then conditionally load the polyfills only if the browser needs it. I use loadjs for that purpose.

**Comment by calebporzio** [comment]
Yeah, I'm pretty torn on this. I see your point @rverrips, but I also want to keep the bundle size down.

If we did include them, would you be willing to PR this change?

**Comment by calebporzio** [comment]
Closing for now
