### ISSUE TITLE
ZPT compatibility

### ISSUE THREAD

**Issue by georgpfolz** [alpinejs/alpine#3875]
### Discussed in https://github.com/alpinejs/alpine/discussions/3874

<div type='discussions-op-text'>

<sup>Originally posted by **georgpfolz** November 15, 2023</sup>
When using alpine.js with Zope Page Templates, all directives containing a colon provoke a compilation error `unknown namespace directive`.

For some directives, there is the possibility to just use the shorthand version as a workaround, like `x-on:click` → `@click`. Unfortunately there are directives whose shortcut also contains a colon, such as `:attributes`.

Fortunately there is a workaround in Zope, that's using `tal:attributes` to create the directive dynamically: `<button tal:attributes="x-on:click string:alert('')">alert</button>`. This works fine, but it makes the code somewhat less readable.

Maybe there could be an alternative to the colon that works with the alpine parser, some other character that's not used in any known programming context like `§` or `…` (U+2026), eg: `x-on§click=alert('')` or `x-on…click=alert('')`.

I also wouldn't mind having to specify the new separator explicitly, for example in `x-init`.</div>

**Comment by SimoTod** [comment]
It's not possible at the moment. Have you tried asking the ZPT community since it seems like it's an error with their compiler?

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/alpinejs/alpine/discussions/1423
