### ISSUE TITLE
Lifecycle Methods

### ISSUE THREAD

**Issue by pfrlv** [alpinejs/alpine#39]
Well done, you guys! I'm giving up all these Vue, React and Stimulus ) will keep an eye out!
Does Alpine lifecycle methods, like stimulus connect/disconnect?

**Comment by ryangjchandler** [comment]
I think this would be quite a nice idea and I'm willing to implement it. Would be nice to have some sort of booted event, or even allowing a callback to be passed into Alpine.start().

**Comment by keyurshah** [comment]
possibly if there are  `connect`, `disconnect`, `init` events inside the return function for `x-data` then they can be executed.

**Comment by calebporzio** [comment]
Ok, I added a basic `x-init` directive that can be attached to the root div. Let's see how this does for now, and we can revisit later if we need something more. Thanks!
