### ISSUE TITLE
`x-on:change()` triggering only on blur of input field.

### ISSUE THREAD

**Issue by mikebronner** [alpinejs/alpine#391]
I have the following input field:

```php
    <input
        class="m-4 p-6 block bg-transparent rounded border-dashed border-4 border-gray-400"
        type="text"
        x-on:change="console.log('test');"
    >
```

The change event seems to only be triggered on blur, instead of whenever the content actually changes (drag/drop, paste, typing, deleting, etc.).

Is there a way to get change reactivity to work? Thanks :)

**Comment by ryangjchandler** [comment]
Have you tried on input?

**Comment by ryangjchandler** [comment]
You might also be interested in this page: https://javascript.info/events-change-input

The browser has different events for different input changes, I don't believe pasting, etc triggers the change event at all.

**Comment by mikebronner** [comment]
Hi @ryangjchandler, thanks for the suggestions. Yes, different browsers have different limitations when they trigger a change event. I'll keep working on this and see if I can figure out a solution.

**Comment by ryangjchandler** [comment]
> Hi @ryangjchandler, thanks for the suggestions. Yes, different browsers have different limitations when they trigger a change event. I'll keep working on this and see if I can figure out a solution.

No worries. I've never really thought about those sort of scenarios where text is being pasted in, I generally just use the change event, assuming the user will click outside or tab out of the field. 

I imagine the input event will work, but you might want to debounce it using the modifier. Would be great to get some extra info on this issue, I'll mark it as a question too and leave it open :)

Good luck!

**Comment by HugoDF** [comment]
@ryangjchandler @mikebronner 
Have we figured out whether this is an Alpine.js issue or a generic "JS events on inputs" issue?

**Comment by ryangjchandler** [comment]
It's just JavaScript behaviour. Probably worth closing.

**Comment by HugoDF** [comment]
Cool closing for now, feel free to reopen if it turns out to be an Alpine.js issue (not DOM/JavaScript)
