### ISSUE TITLE
How to show list of all `$refs`?

### ISSUE THREAD

**Issue by mikebronner** [alpinejs/alpine#392]
I'm working on an element that is designated with a `x-ref` attribute, but I seem to be unable to access it:

```php
<div
    x-data="imageUploader()"
>
    <input
        class="m-4 p-6 block bg-transparent rounded border-dashed border-4 border-gray-400"
        type="text"
        :name="fieldName"
        x-ref="fieldName + '-file'"
        x-on:dragover.stop.prevent=""
        x-on:drop.stop.prevent="captureFile"
        x-on:click="showFileUploadDialogue()"
        :style="'background-image: url(' + imagePreviewData + ')'"
    >
</div>
```

```js
    function imageUploader() {
        return {
            // ...
            processFiles: function (event) {
                console.log(this.$refs, this.fieldName);
                if (event.dataTransfer.files.length > 0) {
                    this.$refs[this.fieldName + '-file'].files = event.dataTransfer.files;
                    this.$refs[this.fieldName + '-file'].dispatchEvent(new Event('change', { 'bubbles': true }));

                    return true;
                }

                return false;
            },
        };
    }
```

`this.$refs` is a proxy object and doesn't list any refs, and ` this.$refs[this.fieldName + '-file']` gives me the following error:
```
TypeError: undefined is not an object (evaluating 'this.$refs[this.fieldName + '-file'].files = event.dataTransfer.files')
```

Any suggestions on what I might be doing wrong? Thanks!

**Comment by ryangjchandler** [comment]
Hi again @mikebronner! Currently, the $refs are generated and accessed at runtime so there's no in memory store of them. 

I'm not sure if they support this dynamic syntax at the moment, but you'll have to let me confirm. 

Are you to access the element by its reference when using a fixed, scalar string?

**Comment by mikebronner** [comment]
Thanks @ryangjchandler :)

I changed the input tag to the following (passed in from PHP):

```
    <input
        class="m-4 p-6 block bg-transparent rounded border-dashed border-4 border-gray-400"
        type="text"
        name="{{ $name }}"
        x-ref="{{ $name }}-file'"
        x-on:dragover.stop.prevent=""
        x-on:drop.stop.prevent="captureFile"
        x-on:click="showFileUploadDialogue()"
        x-bind:style="'background-image: url(' + imagePreviewData + ')'"
    >
```

It still isn't working. Is it better to access it by `getElementById()` instead?

**Comment by ryangjchandler** [comment]
Looks like you've got an extra apostrophe in the ref attribute, that could be the problem :)

**Comment by ryangjchandler** [comment]
I don't think the `x-ref` attribute has any knowledge of your data context either, so it won't resolve the value of one of your data properties. 

You might be able to find the value of `x-ref` though:

```html
<input type="text" :x-ref="fieldName + '-file'">
```

I haven't actually tried this, but I imagine it _should_ work. Apologies if it doesn't. Let me know how you get on though, I think others would find this useful.

**Comment by mikebronner** [comment]
Thanks @ryangjchandler ... unfortunately your idea didn't pan out, it didn't work, same error.

I was able to use `id="..."`, but not `x-bind:id="..."`. X-bind doesn't seem to be working at all for me, I tried it in the name and style attributes, and it didn't resolve them correctly.

**Comment by SimoTod** [comment]
As Ryan said, x-ref is not a real alpine directive (v3 will remove the x- prefix and just use ref) but a standard html attribute. I think there must be another syntax error somewhere in your script because the suggested solution using the dynamic binding should work.
See https://codepen.io/SimoTod/pen/OJyXJKX

Can you post a full example on codepen or jsfiddle and past the link here, please?

**Comment by ryangjchandler** [comment]
Was just going to ask for a CodePen too :)

**Comment by FelixLuciano** [comment]
I had a similar issue that I easily fixed by inspecting with `console.log({ ...this.$refs })`.

**Comment by ryangjchandler** [comment]
Hi guys, this issue has been stale for a little over a month now so I'm going to close it. As a final note, you can bind to the value of the `x-ref` attribute, using the regular `x-bind` or `:` syntax.

**Comment by mikebronner** [comment]
Thanks, sorry for not getting back to you. I got pulled to other projects and must have sorted this out some other way back then.
