### ISSUE TITLE
<template> in <svg> can not be handled correctly

### ISSUE THREAD

**Issue by lovetingyuan** [alpinejs/alpine#3945]
### Discussed in https://github.com/alpinejs/alpine/discussions/3944

<div type='discussions-op-text'>

<sup>Originally posted by **lovetingyuan** December 21, 2023</sup>
```html
<svg viewBox="-50 -50 100 100">
    <template x-for="i in 12">
        <line class="major" y1="35" y2="45" :transform="`rotate(${30 * i * 5})`" />
    </template>
</svg>
```
the code will throw error:
`Alpine Expression Error: Failed to execute 'importNode' on 'Document': parameter 1 is not of type 'Node'.`</div>

template element in svg element is not a HTMLTemplateElement, it will be treated as normal svg node.

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/alpinejs/alpine/discussions/1423
