### ISSUE TITLE
x-model for input[type=range] changes

### ISSUE THREAD

**Issue by richgcook** [alpinejs/alpine#397]
Is it possible to use `x-model` to change the font-size on an element based on an `input[type=range]` value with the available directives, or would this require a separate function?

**Comment by SimoTod** [comment]
it should be possible. Did you try and got an error?
It should be something like https://codepen.io/SimoTod/pen/yLYaaYz

**Comment by richgcook** [comment]
@SimoTod That's it! I didn't think of the `x-bind:style` part. This is great. Thanks!
