### ISSUE TITLE
Expose Alpine.js version on Alpine global

### ISSUE THREAD

**Issue by HugoDF** [alpinejs/alpine#398]
We get a bunch of questions about whether the feature made it into the release every time Alpine.js gets released (due to caching at CDN level). 

It would probably be useful to expose a `Alpine.version` field (which matches what's in the package.json) so that people can check it and reference it when they're reporting bugs/issues.

Happy to contribute it if it's something that we'll use.

**Comment by ryangjchandler** [comment]
Thinking about this, the only problem would be the extra manual update - it could get forgotten. It might be possible to do this using a Rollup plugin, maybe the `replace` plugin that's already in the config?

**Comment by muzafferdede** [comment]
@ryangjchandler is [this](https://www.npmjs.com/package/rollup-plugin-version-injector) something you are talking about?

**Comment by ryangjchandler** [comment]
@muzafferdede Yeah that could work - there is already a text replace plugin on build too though.

**Comment by HugoDF** [comment]
I agree @ryangjchandler 

We can read the version in package.json directly by requiring it.

Only issue is that there'll be a need to rebuild after bumping the version and before publishing.

**Comment by ryangjchandler** [comment]
> I agree @ryangjchandler
> 
> We can read the version in package.json directly by requiring it.
> 
> Only issue is that there'll be a need to rebuild after bumping the version and before publishing.

True, true, true. Let's experiment with a solution :)

**Comment by muzafferdede** [comment]
```js
        replace({
            "process.env.NODE_ENV": "'production'",
            __version__: '/* Version: ' + require('./package.json')['version'] + '*/'
        }),
```
Grabbing value from `package.json` is ok but not sure how to place it at first line of build.

**Comment by ryangjchandler** [comment]
Key needs to be a string and we should be assigning the value to a property, instead of a comment on top of build.

**Comment by SimoTod** [comment]
not related to this implementation but Jsdelivr has a private api to purge the cache which can be called when tagging a new release: https://github.com/jsdelivr/jsdelivr#purge-cache
@calebporzio can probably contact them to get access and add something to his release check list.

**Comment by muzafferdede** [comment]
// Changes
```js
// rollup.config.js
replace({ 
   "process.env.NODE_ENV": "'production'" ,
   __version__: require('./package.json')['version']
}),

// index.js
const Alpine = {
    version: '__version__',
    start: async function () {
        if (! isTesting()) {
            await domReady()
        }
```
Output
```js
// alpine.js
  const Alpine = {
    version: '2.2.5',
    start: async function start() {
      if (!isTesting()) {
        await domReady();
      }
```
Dev Console 

```
Alpine.version
"2.2.5"
```

**Comment by HugoDF** [comment]
Nice one @muzafferdede wanna create the PR?

**Comment by muzafferdede** [comment]
>Happy to contribute it if it's something that we'll use.

@HugoDF I could if you want me to but i think it's your contribution. :)

**Comment by HugoDF** [comment]
Haha yeah but I mean you literally put the required code in a comment 🙂

Although I have to say 

```
require​(​'​./package.json​'​)[​'​version​'​]
```
Could be

```
require​(​'​./package.json​'​).version
```

**Comment by muzafferdede** [comment]
Haha, sorry for what i have done! Can't stop when see see something to play around :) Credit is yours. And yeah, your suggest is the right path.

**Comment by HugoDF** [comment]
@muzafferdede went yet another way in the PR 😄
