### ISSUE TITLE
Listen event in Alpine component fired from Livewire

### ISSUE THREAD

**Issue by sanjayojha** [alpinejs/alpine#399]
I am emitting an event from livewire component 
`$this->emit('custom-event', 'foo');`

And listening it in a alpine component like below
```html
<div x-data="handler()">
<div @custom-event="title = $event.detail.foo"> 
</div>
```
But it is not working. I know that you can listen to these event using JavaScript like below
```javascript
window.livewire.on('custom-event', foo => {
        console.log(foo);
)
```
But not sure how to access it in alpine

**Comment by SimoTod** [comment]
Unless an event is fired on your alpine component (or one of it's child) you need to use the window modifier so Alpine will listen for that event on the window object.

In this specific case
`@custom-event.window="..."`

**Comment by sanjayojha** [comment]
@SimoTod 
I tried this also. But not working.
For some reason event triggered by `$this->emit('custom-event', 'foo');` is not listened by `@custom-event.window` also.
A few minute earlier I discovered the `$this->dispatchBrowserEvent('foo')` and this is working with `@custom-event.window` but **not** with `$this->emit('custom-event', 'foo')`. I am not sure why though.

**Comment by muzafferdede** [comment]
Sorry, don't have a setup to try Livewire with Alpine currently. Can you try
`@custom-event.window.livewire="..."`

in your case it should be 
```html
<div @custom-event.window.livewire="title = $event.detail.foo"> 
</div>
```

**Comment by sanjayojha** [comment]
@muzafferdede 
No not working. I think another way is to create a window event and dispatch it in `window.livewire.on`
```javascript
window.livewire.on('custom-event', foo => {
       var event = new CustomEvent('custom-event', {detail: {foo: 'value' }});
       window.dispatchEvent(event);
     }
)
```
You need to adjust emitter considering this code

**Comment by HugoDF** [comment]
Do we have a `.livewire` modifier?

**Comment by SimoTod** [comment]
Unfortunately we don't have a `livewire` modifier so I think it won't work. Since are both Caleb's project, he could be okay with adding it. I don't have much knowledge of the livewire codebase but Alpine needs to listen for standard browser events (which need to bubble up to the window object).
I assume emit creates some event which doesn't bubble up so it won't work.
Can you use dispatchBrowserEvent or is it a no go for your project?

**Comment by sanjayojha** [comment]
Ok, Got it working as I expected. It worked.
I am using `dispatchBrowserEvent` and its easier and take less code. I was just checking if there is a way to listen and event triggered from `$this->emit('custom-event', 'foo')` in Alpine.
Thanks everyone for helping

**Comment by muzafferdede** [comment]
An example scenario for those who need:

PHP Livewire Component
```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Listener extends Component
{
    public $name = 'Livewire';

    protected $listeners = ['change-name' => 'changeNameAndForwardToAlpine'];

    public function render()
    {
        return view('livewire.listener');
    }

    public function changeNameAndForwardToAlpine()
    {
        $this->name = 'Alpine';
        $this->dispatchBrowserEvent('name-changed',['name'=>$this->name]);
    }
}
```
Alpine + Livewire blade component as:

```php

<div x-data="{name:'{{ $name }}'}">
    <button wire:click="$emit('change-name')">
    <span @name-changed.window="name = $event.detail.name" x-text="name"></span>
</div>
```

So, using  `dispatchBrowserEvent` Alpine is able to listen to events and act on them.

**Comment by sanjayojha** [comment]
@muzafferdede 
I am using it. But I wanted to know why event triggred by livewire `$this->emit('foo')` is not getting bubbled up to window object? I don't know the reason but if anyone wants to listen this type of event in his alpine component he can use your suggested code and also something like below
```javascript
window.livewire.on('change-name', name => {
       var event = new CustomEvent('name-changed', {detail: name });
       window.dispatchEvent(event);
     }
)
```

**Comment by muzafferdede** [comment]
~~Why:~~
 I guess livewire events are not bubbled up to the window object. I think this is a good question to be asked in Livewire repo. Feel free to open a question there.

Your workaround might work but in my opinion you literally done everything on vanilla javascript. There is not much going on with Alpine. So, i can't say this is an Alpine way of doing things. And  thank you for sharing your workaround.

**Comment by sanjayojha** [comment]
Agree this is not an alpine way and that's why I used dispatchBrowserEvent in my original code, this was just an alternate approach that I wanted to share when I found solution.

**Comment by musa11971** [comment]
In Livewire 3.4, April 2024:
```php
// From your component
$this->dispatch('post-created');
```

```js
// In Alpine
this.$wire.on('post-created', function(event) {
	// ...
});
```
