### ISSUE TITLE
Setting Single-value stores to 'null' breaks Alpine

### ISSUE THREAD

**Issue by colinaut** [alpinejs/alpine#4082]
### Discussed in https://github.com/alpinejs/alpine/discussions/3204

<div type='discussions-op-text'>

<sup>Originally posted by **colinaut** October 10, 2022</sup>
Found out that if I set a [Single-value stores](https://alpinejs.dev/magics/store#single-value-stores) to `null` it breaks everything and gives the following error:

```
null is not an object (evaluating 'Object.getOwnPropertyDescriptors(obj)')
```</div>

**Comment by joshhanley** [comment]
This issue has been closed as we are now using discussions to track bugs and ideas, and as there is already a discussion open we will continue investigating in that discussion.
See this announcement for more details https://github.com/alpinejs/alpine/discussions/1423
