### ISSUE TITLE
Getting Alpine working in Jigsaw (static site generator)

### ISSUE THREAD

**Issue by userlastname** [alpinejs/alpine#409]
Hi all,

<details><summary>I get the following error in my console, after both including Alpine as a script in head, or NPM installing and building into my main.js...</summary>

`VM20150:3 Uncaught (in promise) SyntaxError: Unexpected identifier
    at new Function (<anonymous>)
    at saferEval (alpine.js?df24:101)
    at new Component (alpine.js?df24:1285)
    at Object.initializeComponent (alpine.js?df24:1692)
    at eval (alpine.js?df24:1640)
    at eval (alpine.js?df24:1656)
    at NodeList.forEach (<anonymous>)
    at Object.discoverComponents (alpine.js?df24:1655)
    at Object.start (alpine.js?df24:1639)`
</details>

This is happening with the Laravel/Blade based static site generator, [Jigsaw](https://jigsaw.tighten.co/).

My fix to this was to set my x-data as a window variable in main.js, which solves the above issue. 

<details><summary>But now I get the following issue (when using x-bind)...</summary>

`Uncaught (in promise) SyntaxError: Unexpected token ':'
    at new Function (<anonymous>)
    at saferEval (alpine.js?df24:101)
    at Component.evaluateReturnExpression (alpine.js?df24:1547)
    at handleAttributeBindingDirective (alpine.js?df24:518)
    at eval (alpine.js?df24:1510)
    at Array.forEach (<anonymous>)
    at Component.resolveBoundAttributes (alpine.js?df24:1496)
    at Component.initializeElement (alpine.js?df24:1415)
    at eval (alpine.js?df24:1399)
    at eval (alpine.js?df24:1389)`
</details>

This entire affair seems similar to the previous issue of using Alpine in React, but I'm not sure what the fix would be in Blade/Jigsaw.

Help would be appreciated!

**Comment by ryangjchandler** [comment]
It would be great to get a CodePen with some of the HTML being generated!

**Comment by ryangjchandler** [comment]
Off the bat, it sounds like you've got some missing characters / invalid syntax in your data. I assume you're outputting something using Blade inside of your `x-data` attribute. Make sure that you're wrapping the `{{ $variable }}` in double quotes (if it's a string).

**Comment by userlastname** [comment]
Will have a look at getting a Codepen running, but here's some more context.

In my main.js:

`
require("alpinejs");
window.colorVariables = () => {
  return {
    primary: "#DF3030",
    secondary: "#FFC107",
  };
};
`

and in my Blade:

`
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="description" content="{{ $page->meta_description ?? $page->siteDescription }}">

        <meta property="og:title" content="{{ $page->title ?  $page->title . ' | ' : '' }}{{ $page->siteName }}"/>
        <meta property="og:type" content="website" />
        <meta property="og:url" content="{{ $page->getUrl() }}"/>
        <meta property="og:description" content="{{ $page->siteDescription }}" />

        <title>{{ $page->title ?  $page->title . ' | ' : '' }}{{ $page->siteName }}</title>

        <link rel="home" href="{{ $page->baseUrl }}">
        <link rel="icon" href="/favicon.ico">

        @stack('meta')

        @if ($page->production)
            
        @endif

        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital@0;1&family=Inter:wght@400;600&family=Work+Sans:wght@700&display=swap" rel="stylesheet">

        <link rel="stylesheet" href="{{ mix('css/main.css', 'assets/build') }}">

    </head>

    <body x-data="styleVariables()" role="main">
        <main :style="--primary: primary, --secondary: secondary;" >
            @yield('body')
        </main>

        <footer role="contentinfo">
            
        </footer>
       <script src="{{ mix('js/main.js', 'assets/build') }}"></script>
        @stack('scripts')
    </body>
</html>
`

**Comment by userlastname** [comment]
My temporary solution is to mock my own "x-style" on the main tag through a function called on x-init, and whenever I want to change those values:

`window.styleVariables = () => {
  return {
    primary: null,
    secondary: null,
    setVariables: function(primary = "#DF3030", secondary = "#FFC107") {
      this.primary = primary;
      this.secondary = secondary;
      document
        .getElementsByTagName("main")[0]
        .setAttribute(
          "style",
          `--primary: ${primary}; --secondary: ${secondary};`
        );
    },
  };
};`

**Comment by HugoDF** [comment]
@userlastname currently style bindings only support strings

So you need to do 
```
:style="`--primary: ${primary}; --secondary: ${secondary};`"
```

The issue for this is here https://github.com/alpinejs/alpine/issues/213

I've submitted a PR but Caleb has opted not to use it, maybe mention that you would use bindings other than string over there.

**Comment by userlastname** [comment]
@HugoDF Legend! Can't believe I didn't think to try that.
