### ISSUE TITLE
Render Component from outside

### ISSUE THREAD

**Issue by mvaliolahi** [alpinejs/alpine#410]
Is there any way to rerender a component from the outside?

for example when one component state changed then effect on another component by re-render it.

**Comment by ryangjchandler** [comment]
Hi @mvaliolahi - currently the simplest way to communicate between 2 components is through events.

You can dispatch an event from one component using the `$dispatch` magic function and then listen for that event on another component at the window level using `x-on:event-name.window`.

You'll want to dispatch the event with some data and then assign that data to the other component. This will cause Alpine.js to re-render the component.

**Comment by mvaliolahi** [comment]
@ryangjchandler  Thanks

**Comment by mvaliolahi** [comment]
@ryangjchandler Hello again, can I dispatch event inside a click event like below:

<button @click="foo"></div>

<script>
    function foo() {
    dispatch(...);
   }

</script>

**Comment by ryangjchandler** [comment]
The `$dispatch` magic variable isn't available in function callbacks. You can pass it through with `@click="foo($dispatch)"` and then accept as an argument in your function.

**Comment by mvaliolahi** [comment]
@ryangjchandler  Thanks a lot.
