### ISSUE TITLE
[Question] :  Error Selection when uses type="number"> 

### ISSUE THREAD

**Issue by adinata-id** [alpinejs/alpine#415]
i got error when use input type="number" 

error message :  Uncaught DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.

my code : 

    <div x-data="form()">
        <input type="number" class="form-control" name="price"  x-model="price">
    </div>

<script> 
    function form() {
        return {
            price : 0
        }
    }
</script> 

nb : i am use latest version

**Comment by ryangjchandler** [comment]
Hi @adinata-id , a regression was report in v2.3.0. A fix has been submitted at #403 and discussion on #401. In the meantime, please use v2.2.x

If you've got anymore questions, please commentt on #401. Thanks! :)

**Comment by adinata-id** [comment]
thanks you so much  @ryangjchandler

**Comment by HugoDF** [comment]
@ryangjchandler worth pinning #401 on the issues page?

**Comment by ryangjchandler** [comment]
> @ryangjchandler worth pinning #401 on the issues page?

Yeah, I'm not sure we've got permissions to do so.
