### ISSUE TITLE
How work with webpack and other build tools

### ISSUE THREAD

**Issue by pfrlv** [alpinejs/alpine#42]
As I understand it, the functions of the components must be global and located in the `window` object. But then what about modules, iife and build tools like Laravel Mix?  Tell me about usage and file structure,  please.

**Comment by gozeon** [comment]
and [parcel](https://parceljs.org/).

**Comment by calebporzio** [comment]
You can assign modules to the window. namespace in your build and that should do it.

**Comment by IP-Developer** [comment]
@calebporzio is there any way to achieve lazy loading of components via webpack's dynamic imports?

**Comment by HugoDF** [comment]
> @calebporzio is there any way to achieve lazy loading of components via webpack's dynamic imports?

You can lazy load using dynamic import but then you would need to delay Alpine initialisation, there's an undocumented/private `deferAlpineLoading` method that you can use to that end.

See how it's used in the magic-helpers community repo https://github.com/alpine-collective/alpine-magic-helpers/blob/master/src/component.js#L58

**Comment by IP-Developer** [comment]
@HugoDF it's not really clear to me how this can be implemented. Do you have any examples?

**Comment by HugoDF** [comment]
> @HugoDF it's not really clear to me how this can be implemented. Do you have any examples?

No examples unfortunately.

But you could try to keep track of dynamic imports and not call the `deferLoadingAlpine` callback until all your dynamic imports have been loaded.

Something like:

```js
window.deferLoadingAlpine = async (cb) => {
  const { myFn } = await import('./myModule');
  window.myFn = myFn;
  cb ();
}
```

Note that deferLoadingAlpine is not a public API and using it incorrectly might break libraries like Livewire, Spruce or magic-helpers.

**Comment by IP-Developer** [comment]
@HugoDF ok, now I understand. I would abstain from using this method as per your suggestion. 
The main thing I was trying to achieve is complete lazy loading based on x-data attribute. So setting the component name: `x-data="myComponent({})"` or maybe using a custom function to load the component `x-data="component('myComponent')({})` would make use of webpack's dynamic imports. Unfortunately I wasn't able to set this up directly, considering that webpack's `import()` returns a promise.

**Comment by HugoDF** [comment]
@IP-Developer you're right, `x-data` can't return a Promise at the moment

**Comment by sbrow** [comment]
> @IP-Developer you're right, `x-data` can't return a Promise at the moment

Are there any plans to add this feature?

**Comment by codemonkeynorth** [comment]
@pfrlv are you trying to embed alpine with a `<script>` tag or in your js bundle?

**Comment by pfrlv** [comment]
> @pfrlv are you trying to embed alpine with a `<script>` tag or in your js bundle?
> 
> 
> 
> 

I'm already find super solution ) for vite workflow and dynamic import
