### ISSUE TITLE
x-model example in Readme is missing. Debounce example is there instead

### ISSUE THREAD

**Issue by edjw** [alpinejs/alpine#422]
The example given for x-model in the readme is the debounce example. It should be an example for x-model

**Comment by edjw** [comment]
It was added on this commit

https://github.com/alpinejs/alpine/commit/a01d30d0b9ba786a74f21064def716e20a2eb812

**Comment by SimoTod** [comment]
Hi @edjw 
if you scroll further down (https://github.com/alpinejs/alpine#x-model) you can find examples for x-model with and without the debounce modifier.
Is it what you were looking for?

**Comment by SimoTod** [comment]
@edjw are you okay with closing this issue or do you have other questions? Thanks

**Comment by HugoDF** [comment]
Closing this for now (it's been almost a month and no further questions).

**Comment by edjw** [comment]
Hi, yes of course. Sorry for not replying sooner
