### ISSUE TITLE
How to update component state from outside

### ISSUE THREAD

**Issue by holgerw** [alpinejs/alpine#426]
Is there support to update a component's state from outside?

I am implementing a multistep wizard. In order to support the browser back button I push a new route with the browser history API. Doing this reactively is straightforward with the $watch magic property.  Now, when the window.onpopstate event fires I would have to update the state of the Alpine component and have the UI transition back to the former state.

I did not find an API to update a component's state from outside. Is this supported? Would there be a solution interacting directly with the domNode.__x object, even being a private API that could break in the future? In this case I would suggest a public API as I think this feature would allow valuable new use cases, like wizards.

**Comment by holgerw** [comment]
Eventually I figured it out. The solution is to dispatch a custom event on the component's dom node. The event can be dispatched from outside the component, in this case from a window.onpopstate event listener. I basically redispatch the onpopstate event making it available inside the component allowing it to act on the event and update the component state.

Going to close this issue.

**Comment by QJan84** [comment]
Do you have an example code for this?

**Comment by HugoDF** [comment]
I've written a couple of guides about this:

- https://codewithhugo.com/alpinejs-component-communication-event-bus/
- https://codewithhugo.com/alpinejs-inspect-component-data-from-js/

**Comment by jmariller** [comment]
Regarding the approach with the `__x` property, that does not seem to work anymore with version 3.* - any advice/best practice on how to update state from outside the component?

**Comment by jmariller** [comment]
hi @calebporzio, please see my above comment - what is your view on this?
