### ISSUE TITLE
Extract Component Logic - using function name "delete()" doesn't work

### ISSUE THREAD

**Issue by jacksegal** [alpinejs/alpine#429]
You cannot use the function name "delete()" when extracting component logic - you get the error: 

```Uncaught (in promise) SyntaxError: Unexpected token ')'```

![Screenshot 2020-04-28 at 11 21 15](https://user-images.githubusercontent.com/9342782/80479196-8fb5e500-8946-11ea-9c0c-497e62c51c73.png)

Here is a jsfiddle example, where I have taken the dropdown example from README in "Extract Component Logic" section and renamed the `isOpen()` function to `delete()`, to demonstrate the issue: https://jsfiddle.net/jacksegal/r71Lpkgu/

Not sure if this is a bug, or if there are just reserved function names that you cannot use - if the latter, it might be nice to add a one-liner to the "Extract Component Logic" section of docs (happy to write this), or try and catch it in the code and throw a more understandable exception?

**Comment by HugoDF** [comment]
This is a JavaScript issue, "delete" is a keyword so can't be used as the name in a function declaration.

**Comment by jacksegal** [comment]
Ah right - thanks @HugoDF.

One option would be to check whether the function name (`expression`) was a keyword and throw a friendly exception (list of keywords: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords).

Understand that this is more of a JS thing so feel free to just close the issue.

If you are interested in adding it in, I'm happy to add a simple function to `utils.js` that checks whether the `expression` is a keyword.

**Comment by HugoDF** [comment]
Yeah I'll close this for now.

I'll probably spawn a blog post or something about fixing this issue, hopefully anyone searching will find this issue in the meantime.
