### ISSUE TITLE
Modify x-data properties from outside component

### ISSUE THREAD

**Issue by andruu** [alpinejs/alpine#43]
I'm using livewire and triggering an event that I'm trying to listen to in alpine. What's the best way to do this?

**Comment by andruu** [comment]
For a temporary work around I'm listening for the livewire event and then firing a window event and listening for that with x-on.

**Comment by calebporzio** [comment]
Hey @andruu, I recently came across this myself.

I'm adding a Livewire component method in the next release:

```php
$this->dispatchBrowserEvent('foo')
```

that can be called from the backend, and the root div of the livewire component will dispatch this. Then Alpine can listen for it.

**Comment by calebporzio** [comment]
This has been added in the latest Livewire release.
