### ISSUE TITLE
x-show gets overridden by :style

### ISSUE THREAD

**Issue by gilbert** [alpinejs/alpine#434]
See [this 2.3.1 example](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8YWACcyAB3gACMKNgBeADogc8CWFQB6LbCR0MAKzBJoZAG6iMdCPC0BzLFoZQJZG8eev3EAALmAJgwAZgwARi0kMjA7FzcbDFx3IzAVAD5BLRFxKTSlOnzBKPN86WkADwBaJAZ4BmUQYGksMlNUaXhRAFcIaQBfFVKKytgobgYAayGqsCxuAHcGgEIW00G6MtQYgE8YBoADHjHRdtFkffW8jekATW4u2TmuqH0AchlIXuZCyIsrzkgMAQZF4VHQADZUAEAiA+oR6EwWOgUpweHwIAJ0LD4SBGMxWBhYGAqMQ0fx4KxqFVRuMJgBdaRNKJgCRQBjbdp0XgQADc-XyAOgcHgILoYJAYVQAAZYXS+kA). The text shows up when it shouldn't. If you delete the `:style` line, or empty its value, or remove the backticks, it works as expected.

**Comment by muzafferdede** [comment]
i think it's because order of attributes. try this:
```html
<div
  x-data="{ hide: true }"
  :style="`color: red`"
  x-show="!hide"
>
  You shouldn't see me
</div>
```

`x-show` should come after `x-bind:style`. Not sure why exactly this is happening but worth to check it out in core.

**Comment by qysp** [comment]
This happens because x-bind:style overwrites the style attribute of the element whereas x-show only mutates the display property of the inline style.

**Comment by muzafferdede** [comment]
Yes, that's exactly what is happening. `x-bind` overwrites style attribute instead of merging. `x-bind` should respect previous styles.

**Comment by SimoTod** [comment]
At the minute, class is the only attribute which would merge the preexisting value. As @muzafferdede suggested, when using different directive dealing with the style attribute, the safeat way is to put `:style` early in the attribute list since Alpine processes directives in order.
There was a pr to improve this behaviour but it's been put on hold for now. I think it's something it'll be looked at in v3.

**Comment by HugoDF** [comment]
Is there something obvious we need to fix here?

Directive precedence might be something we want to have a look at.

**Comment by ryangjchandler** [comment]
> Is there something obvious we need to fix here?
> 
> Directive precedence might be something we want to have a look at.

I don't think precedence is a major problem now, maybe it just needs to be clear that there is an order of execution / evaluation. Might be worth putting it in the README.

**Comment by PaulMorel** [comment]
I think it would be good to document this quirk in the Readme for the time being.

**Comment by ryangjchandler** [comment]
I'm going to open a PR in a bit with some documentation updates so we can get this one closed.

**Comment by HugoDF** [comment]
@ryangjchandler did you have a chance to create that docs PR?

**Comment by ryangjchandler** [comment]
@HugoDF feel free to open it, been a bit caught up with work!
