### ISSUE TITLE
Input Range Flickering

### ISSUE THREAD

**Issue by jjjrmy** [alpinejs/alpine#440]
I am trying to do a range slider in Alpine, the slider should not be able to cross or be within 100 of each other.

Currently I have it mostly working by using `x-on:input` but as you can see in the screenshot below it flickers and allows you to still drag the slider marks past the allowed point until being pulled back.

```
x-on:input.prevent="if(Number(max) <= Number(min) + 100) { min = Number(max) - 100; }"
```

![Range Slider](https://i.imgur.com/IL9afAU.gif)
![Range Slider](https://i.imgur.com/h2SMmaG.gif)
_Due to the compression of the video it's a lot less noticeable_

On Vanilla JS it does not do this, you can see my code below:
https://codepen.io/jjjrmy/pen/jObGbmB

Any help would be appreciated!

**Comment by ryangjchandler** [comment]
This one has been resolved now. Since Alpine evaluates the directives in the order they're declared, the `input` event listener that `x-model` is registering gets run before the listener declared inside of `@input`, causing the jump back effect.

**Comment by jjjrmy** [comment]
**Solution:**
Move `x-model` until after the `x-on:input` ...
`x-on:input="if(Number(max) <= Number($event.target.value) + 100) { $event.target.value = Number(max) - 100; }"`
