### ISSUE TITLE
Alpine not working with Eleventy

### ISSUE THREAD

**Issue by gigamesh** [alpinejs/alpine#441]
I'm trying to use Alpine with [11ty](https://www.11ty.dev/). 

This page renders, and I've verified `window.Alpine` exists on the page, but the @click isn't firing the alert function:

```
<html lang="en">
  <head>
      src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@2.x.x/dist/alpine.min.js"
      defer
    ></script>
  </head>
  <body>
    <button type="button" @click="alert('clicked')">click me</button>
  </body>
</html>
```

I thought 11ty might be messing with the DOM, but the `@click` hasn't been tampered with:
![image](https://user-images.githubusercontent.com/32403632/80757809-9fb9fa00-8ae9-11ea-9418-9564e4f1d0d7.png)

Any ideas?

**Comment by ryangjchandler** [comment]
Looks like you're missing the `x-data` attribute, you can add it to the button directly or wrap the button in a div / other element :)

**Comment by gigamesh** [comment]
Welp that's embarrassing. I definitely missed that in the docs. Thanks!
