### ISSUE TITLE
[Idea] Enable discussions tab on the repo

### ISSUE THREAD

**Issue by adevade** [alpinejs/alpine#443]
It would be nice to have this place to discuss implementations and random related stuff. 

I don't know if it's generally available yet, or still in limited beta, but maybe Caleb can work his magic to get in on this beta...? 😉

**Comment by ryangjchandler** [comment]
In the meantime @adevade, you can join the Discord server where we have help channels, general discussion channels amongst others.

**Comment by adevade** [comment]
Great! Thanks!

Anothing (another thing); maybe disable the tabs for Wiki and Project, since they are not in use? Can always enable them again in the future if needed.

**Comment by ryangjchandler** [comment]
> Great! Thanks!
> 
> Anothing (another thing); maybe disable the tabs for Wiki and Project, since they are not in use? Can always enable them again in the future if needed.

We'll have to let Caleb do that one since I don't have access :)

**Comment by adevade** [comment]
Sounds good! Pinging @calebporzio for action.

**Comment by calebporzio** [comment]
Yeah, I agree that's be great. I don't *think it's available yet, but I'll ask around.

**Comment by calebporzio** [comment]
I pinged the head of the Discussions product about access. Now we wait. Thanks for pushing this!

**Comment by FezVrasta** [comment]
@calebporzio may you help me get in touch with them? Do you have an email you could share? Thank you!

**Comment by SimoTod** [comment]
The discussion tab is already active @FezVrasta
