### ISSUE TITLE
alpinejs 65.7 kB vs vuejs 58.8 kB

### ISSUE THREAD

**Issue by jenstornell** [alpinejs/alpine#444]
When reading about alpinejs it seems like it is smaller than Vue, but it seems not to be. Then was is "at a lower cost" refering to?

**Comment by SimoTod** [comment]
Isn't the latest version of Vue JS about 90KB?
https://github.com/vuejs/vue/blob/v2.6.11/dist/vue.min.js

To be fair, this is not really the selling point anyway. It's more about being more simple imo. Vue is still a great tool and it's more appropriate in other use case (E.g. an SPA).

**Comment by HugoDF** [comment]
Yep, Alpine is more of a "simple declarative rendering & reactive data/event binding library with no build step required" but that's a mouthful.

**Comment by ryangjchandler** [comment]
I hope a lot of people who are using Alpine are going to have gzip compression enabled on their servers too which brings the size down dramatically of course.

**Comment by carlmjohnson** [comment]
https://twitter.com/carlmjohnson/status/1069968685606031360

> All those JS libraries bragging about how light they are when gzipped is like me bragging about how light I am on the Moon.

**Comment by SimoTod** [comment]
@jenstornell Do you have a reference you can post showing that vue is 58 kB? I had a look but I couldn't find that figure anywhere. Thanks

**Comment by carlmjohnson** [comment]
In any event, Alpine is 22.8KB (7.5KB gzip) on the CDN, so the 65.7KB number doesn't really reflect reality.

**Comment by carlmjohnson** [comment]
I think this should just be closed. It's not actionable and it doesn't appear to be factual either. 😆

**Comment by jenstornell** [comment]
@SimoTod Alright, I admit that I Google it. I shouldn't have done that, sorry.

![www google com_search_q=vue+js+file+size oq=vue+js+ aqs=chrome 0 69i59l2j0j69i57j0l3j69i60 1903j0j7 sourceid=chrome ie=UTF-8](https://user-images.githubusercontent.com/927011/80836475-1bed3400-8bf5-11ea-8a5c-dace31dab3e0.png)

Even if you have me thumbs down, I've got some great answers. I like what Alpine is ment to solve, so I'll probably try it out.

I'll close it. Thanks everyone!

**Comment by SimoTod** [comment]
@jenstornell no worries, I did not thumb you down. 🤣 I was just puzzled by the figures. 
I think you got confused because you compared the not minified version of Alpine with an old stat from google (probably minified). 
Glad you got your answers though. 👍

**Comment by muzafferdede** [comment]
@jenstornell becareful, you might fall in love to Alpine at first sight. Hopefully we will see you coming up with some bugs with Alpine and would love to take a look at them. 🤟😁
