### ISSUE TITLE
Transitions not working properly

### ISSUE THREAD

**Issue by ilyosjon09** [alpinejs/alpine#45]
First of all, this is awesome library!

I wanted to play with newly released transition feature but I could not make it work. I just copied the example code and modified it a bit.

You can see it here:

https://codepen.io/ilyosjon/pen/eYmebap

**Comment by tlgreg** [comment]
The example would assume you have transition utilities, which the current version of tailwindcss doesn't have yet.

A fork of your pen with adding the missing classes:
https://codepen.io/tlgreg/pen/OJPOdgG

**Comment by ilyosjon09** [comment]
Hey @tlgreg,
Thanks for clarifying this!
