### ISSUE TITLE
AlpineJS for a carousel

### ISSUE THREAD

**Issue by roni-estein** [alpinejs/alpine#451]
Hey, Just dipping my toes into Alpine, would a carousel be something that you would just pull in vue for? (I'm sure there are several already) Or is alpine a good candidate for something like this?

I was thinking of just swapping around some divs but it may be more complicated than that, for example infinite scrolling, pushing and popping elements but then if I need to relate them to some signifier of how many slide elements there are, like a dot notifier.

Anyhow, just some thoughts for people more experienced to weigh in on.

**Comment by ryangjchandler** [comment]
I'd say that Alpine is great for components like that. You might be able to find some examples here https://www.alpinetoolbox.com/, alongside other resources.

Let me know if you've got any questions :)

**Comment by HugoDF** [comment]
To add to what @ryangjchandler said

You can build your own Alpine carousel but you can also pull in a Vanilla JS one and integrate it using `x-ref` and `x-init`

**Comment by ryangjchandler** [comment]
> To add to what @ryangjchandler said
> 
> You can build your own Alpine carousel but you can also pull in a Vanilla JS one and integrate it using `x-ref` and `x-init`

Yeah this ^^, there's a couple examples on the Toolbox that integrate third party libs I believe :)

**Comment by roni-estein** [comment]
oh, thanks for the link! Somone already built a pretty simple one. I may hack on that as a starting point.

**Comment by ryangjchandler** [comment]
Sure thing @roni-estein , I'll leave this issue open for a bit incase you've got any questions etc!

**Comment by HugoDF** [comment]
Closing this now since it's not active and not an Alpine.js issue per se. Feel free to go to the Discord to discuss components etc.
