### ISSUE TITLE
Is there a collision using alpinejs in laravel blade components?

### ISSUE THREAD

**Issue by roni-estein** [alpinejs/alpine#452]
I was just playng around trying to learn blade components and alpine. Here is an example.

I often use a submit button that shows a loading spinner on the button and disables it from being pressed twice. So I started building it out, and decided to try alpine out.

```js
<span x-data="{ loading: false }">
  <button @click="loading = !loading" class="flex items-center bg-blue-500">
    <div x-show="loading" class="btn-spinner mr-2" />
    {{ $slot }}
  </button>
</span>
```

Slot stops rendering and no JS happens.

**Comment by muzafferdede** [comment]
Issue in your case is missing closing div tag.
`<div x-show="loading" class="btn-spinner mr-2" />`
should be
`<div x-show="loading" class="btn-spinner mr-2"></div>`
But why it doesn't work at first case? Is it because of Alpine? That's the question..

**Comment by roni-estein** [comment]
Thanks @muzafferdede. No, I think I had a messed up import in my new laravel setup, sorry I should have posted that an hour ago. Also the self closing div was another issue. Is there something like a view <template> tag I can bind data too in case I don't want to have a surrounding parent rendered?

**Comment by roni-estein** [comment]
That's a separate issue, I'll close this an open up another issue to not pollute the topic.

Here is rudimentary version for posterity if someone ever lands here:


```
@if(isset($loading))
  <span x-data="{ loading: {{ $loading }} }">
    <button @click="loading = !loading" x-bind:disabled="loading"
            :class="{ 'bg-disabled': loading }" {{ $attributes->merge(['class'=>'flex items-center']) }}>
    <span class="">
      <div style="display: none" x-show="loading" class="btn-spinner mr-2"></div>
    </span>
      <span class="block">{{ $slot }}</span>
    </button>
  </span>
@else
  <span>
  <button {{ $attributes->merge(['class'=>'flex items-center']) }}>
    <span class="block">{{ $slot }}</span>
  </button>
  </span>
@endif
```

**Comment by muzafferdede** [comment]
> Thanks @muzafferdede. No, I think I had a messed up import in my new laravel setup

Probably but still, the closing tag was the issue Alpine didn't work properly in the example you shown. Not sure how was your Laravel or blade setup, for current example, that was the issue. Hopefully you can figure out.
