### ISSUE TITLE
Log a warning if Alpine starts but no components are found on the page

### ISSUE THREAD

**Issue by HugoDF** [alpinejs/alpine#461]
One for @calebporzio 

Does it make sense to `console.warn` a message if `Alpine.start` runs but there are no components on the page.

Something like `"No Alpine.js component(s) found on the page, are you missing the 'x-data' attribute?"`?

Relevant issues which are obvious user errors in hindsight but would have likely benefitted from a warning: 

- https://github.com/alpinejs/alpine/issues/441
- https://github.com/alpinejs/alpine/issues/460

Candidates for this warning, `if (rootEls.length === 0) console.warn()`:

- https://github.com/alpinejs/alpine/blob/master/src/index.js#L30
- https://github.com/alpinejs/alpine/blob/master/src/index.js#L38

**Comment by snapey** [comment]
could this also address the issue where alpine is loaded on the page, but there are no components using alpine (or maybe they get injected with livewire later)

Currently I see an error 'Cannot read property 'closest' of null' if there are no x-data elements on the page.

**Comment by mblarsen** [comment]
Wouldn’t that create a lot of noise? I’m using alpine for a few components on a larger site. Not all pages rely on Alpine.

**Comment by HugoDF** [comment]
> Wouldn’t that create a lot of noise? I’m using alpine for a few components on a larger site. Not all pages rely on Alpine.

Any reason your pages load Alpine.js if they're not using it? Bundling your JS to a single file?

**Comment by jonaskuske** [comment]
> Any reason your pages load Alpine.js if they're not using it? Bundling your JS to a single file?

For me, I just include Alpine in the shared `<head />` snippet that all my pages use. Some of the page templates use Alpine, some don't, but I really don't want to specify whether to load Alpine or not for each page that I create – for me, the main advantage of Alpine is that I can just drop in `x-data` in my templates where ever I want, without the additional complexity of loading a script, initializing a Vue instance etc.

**Comment by HugoDF** [comment]
Yeah that makes sense, I think it's safe to close this issue then.

**Comment by mblarsen** [comment]
> Any reason your pages load Alpine.js if they're not using it? Bundling your JS to a single file?

I use the CDN.
