### ISSUE TITLE
Smooth Accordion

### ISSUE THREAD

**Issue by QJan84** [alpinejs/alpine#463]
How do I run the show and hide animations simultaneously? They should be finished at the same time.

Check out my codepen: https://codepen.io/QJan84/pen/zYvRMMw

This is how the animation should look (animations run simultaneously): https://codepen.io/agrayson/pen/aLpKB

**Comment by jreviews** [comment]
I think the issue may be with having the same ref name for each container. I renamed them 1, 2 and 3 and I think that's closer to what want https://codepen.io/jreviews/pen/WNQMVPp

**Comment by QJan84** [comment]
Works perfect! Thanks!
