### ISSUE TITLE
Alternative binding  for directives?

### ISSUE THREAD

**Issue by edric-AU** [alpinejs/alpine#464]
Hey,

I wonder if it is possible to specify a custom directive (e.g data-x-data instead of x-data). I am having trouble of implementing Alpinejs in Salesforce lightning framework.

**Comment by ryangjchandler** [comment]
There's not currently any option for defining custom directives. Similar ideas have been discussed for compliant directives here #450.

**Comment by HugoDF** [comment]
I think I might see how much effort adding support for `data-` prefixed directives would be... No promises timeline wise or if it'll get merged.

**Comment by ryangjchandler** [comment]
> I think I might see how much effort adding support for `data-` prefixed directives would be... No promises timeline wise or if it'll get merged.

Realistically, it should be as simple as modifying the RegEx... but I'm not too sure.

**Comment by ryangjchandler** [comment]
@HugoDF Figured I'd play around with it whilst I had some time on my hands and it wasn't actually that difficult. See PR mentioned above (#506).

**Comment by HugoDF** [comment]
Crushing bugs today @ryangjchandler

**Comment by calebporzio** [comment]
As much as I'd love to see the salesforce ecosystem adopt Alpine, if I recall lightening web components is a full front-end framework with templating and such itself.

I think using Alpine inside of other frameworks like Vue, React, and this (lwc) is outside the scope of reasonable usage.

I am curious your thoughts though.

**Comment by ryangjchandler** [comment]
> As much as I'd love to see the salesforce ecosystem adopt Alpine, if I recall lightening web components is a full front-end framework with templating and such itself.
> 
> I think using Alpine inside of other frameworks like Vue, React, and this (lwc) is outside the scope of reasonable usage.
> 
> I am curious your thoughts though.

Yeah after looking into it, it seems like a full framework.

**Comment by HugoDF** [comment]
The 2 PRs attempting to solve this have been closed, I don't think this is a use-case that Alpine.js is looking to support at the moment so it might be worth closing this issue?

Anyone should feel free to reopen or comment about their usecase which a build with `data-*` attributes would fix.

**Comment by ryangjchandler** [comment]
Hey all, going to close this issue now. Been stale for a couple of weeks and previous attempts at a solution have been closed.
