### ISSUE TITLE
Using Alpine within GatsbyJS

### ISSUE THREAD

**Issue by pascalandy** [alpinejs/alpine#473]
Hi folks! I discovered AlpineJS thanks to TailwindCSS. They use alpine in their examples and I enjoy very much how light everything is using HTML/TailwindCSS/Alpine. 

Now I want to step my game a notch and I want to go **JAMstack** using **GatsbyJS** as my main framework.

My question: Is there anyone over here that use AlpineJS within GatsbyJS? I know it's kind of weird as React is the core feature, but...

I would love to keep the **HTML/TailwindCSS/Alpine** while having Gatsby to care about fetching content within my CMS and optimize picture rendering and the overall blazing fast performances it offers. For me, React is overkill at this point.

Thank you in advance for your help!

**Comment by HugoDF** [comment]
Hey @pascalandy 

I've written up a post about running Alpine inside of react: https://codewithhugo.com/alpine-js-react/

**Comment by pascalandy** [comment]
Oh yes, I saw your post @HugoDF. But I still cannot translate it into Gatsby :-p

**Comment by HugoDF** [comment]
Closing this for now, feel free to reopen or start a "discussion" thread once you've got a better idea of what's breaking.

**Comment by pascalandy** [comment]
At this point, I don't know how to configure GatsbyJS to import AlpineJS. It's not breaking per say.

**Comment by ywroh** [comment]
I am building an ecommerce site with gatsby and tailwind, and I was wondering how to use components made with alpinejs. Thank you for the good information.

**Comment by alexcochran** [comment]
Is this still unachievable? I'd love to know before going down the rabbit hole and trying develop in that direction.

**Comment by HugoDF** [comment]
> Is this still unachievable? I'd love to know before going down the rabbit hole and trying develop in that direction.

It's probably achievable, you need to ensure alpine only gets I cluded client side and that the custom directives don't break your JSX compilation (by putting the alpine code in a string and inner HTML-ing it)
