### ISSUE TITLE
Following a coding Style

### ISSUE THREAD

**Issue by szepeviktor** [alpinejs/alpine#476]
Continuation of #475 

What coding Style are you willing to follow?

**Comment by SimoTod** [comment]
Some people started a discussion on this thread #190. At the moment, no coding style is enforced.

**Comment by HugoDF** [comment]
Like @SimoTod said there's an existing issue about this, in addition the only person with write access to the repository (ie. Only person who can merge anything) is @calebporzio so I dunno if automated style checking or event having a style guide is useful in that context.

**Comment by szepeviktor** [comment]
Okay-okay.

I think liberalism can kill, following a style guide is a must for principled developer.
@douglascrockford leads the ways with https://github.com/douglascrockford/JSLint

Although it hurts feeling which is very important in a collaborative project!

**Comment by HugoDF** [comment]
Hmmm the velocity of contributions is low on the project, since everything has to be merged by Caleb. In that context, I dunno what value automated style checks bring.

**Comment by szepeviktor** [comment]
I think without a style guide contributions are merged easier and code quality is a bit lower.
