### ISSUE TITLE
x-bind:[attribute] on a falsy value still includes the attribute

### ISSUE THREAD

**Issue by richgcook** [alpinejs/alpine#485]
If I write `x-bind:href="article.external_url"` and if the value of `article.external_url` is `null` or `false` then in Alpine the `href` is still bound but with a value of `null`

![Screenshot 2020-05-13 at 23 57 07](https://user-images.githubusercontent.com/901289/81874311-88611f00-9575-11ea-98bc-ad9870c86b3e.jpg)

However, from the Vue.js docs, for example: https://vuejs.org/v2/guide/syntax.html#Attributes

> If isButtonDisabled has the value of null, undefined, or false, the disabled attribute will not even be included in the rendered <button> element.

What is the expected output here?

**Comment by SimoTod** [comment]
The one you experienced at the moment. We discussed that a while ago on this thread: https://github.com/alpinejs/alpine/issues/280#issuecomment-600007000

**Comment by richgcook** [comment]
> The one you experienced at the moment. We discussed that a while ago on this thread: [#280 (comment)](https://github.com/alpinejs/alpine/issues/280#issuecomment-600007000)

Oh! And no outcome? Hmm.

**Comment by SimoTod** [comment]
We were waiting for feedback then we just forgot, I suppose. 😂

**Comment by HugoDF** [comment]
We can open a PR for it.

I think Caleb's unlikely to merge it because it's gonna have too many changes 🤷🏼‍♀️

**Comment by HugoDF** [comment]
@richgcook could you move your use-case comment into that other issue (& close this one)?

The more people mention it's a problem, the more likely we'll go fix it.
