### ISSUE TITLE
x-init doesn't run after liveware rerender

### ISSUE THREAD

**Issue by leoneparise** [alpinejs/alpine#488]
I'm trying to use `x-init` property to load `imask` on some input fields. It works on first load but stop working after a livewire refresh. Is it a bug in alpine? 

```html
<x-input-row name="phone_number" 
             x-data="{ mask: '(00)000000000' }"
             x-init="IMask($refs.input, { mask })">
    <label for="phone_number">Telefone*</label>
    <input wire:model="phone_number"
           id="phone_number"
           name="phone_number"
           type="tel"
           placeholder="(DD)999999999"
           autocorrect="off"
           autocomplete="off"
           x-ref="input"/>
</x-input-row>
```

**Comment by JuanDeLeon** [comment]
See https://github.com/livewire/livewire/issues/920#issuecomment-623680787
Looks like the same issue.

**Comment by SimoTod** [comment]
@leoneparise 

x-init runs only the first time Alpine starts a component.
After that point Livewire replaces part of your html with a new input field but this does not destroy and recreate an Alpine component so x-init won't run again.

You can use dispatchBrowserEvent in livewire to dispatch an event and use an alpine directive to listen to that event and call IMask again.

Note, Livewire fires events on the root node so you probably need to use the window modifier in Alpine to intercept the event.

Also, you are sending a server request on each key stroke, is that what you want? If it's not, you might be interested in the lazy modifier (https://laravel-livewire.com/docs/properties#lazy-updating).

I hope it helps.

**Comment by leoneparise** [comment]
Thanks for your response @SimoTod. I found a solution :).

**Comment by Schrammi** [comment]
Could you share your solution?

**Comment by abishekrsrikaanth** [comment]
@SimoTod care to share your solution that you found?

**Comment by SimoTod** [comment]
the reason why the original issue did not work is described here https://github.com/alpinejs/alpine/issues/488#issuecomment-628785672
I did not code an example, it depends on your use case, what you need to bear in mind is that x-init only runs once so you need something like 
```html
<div x-data="{...}" x-init="yourFunction()" @livewire-refresh.window="yourFunction()">
   ...
</div>
```
```php
// in your livewire component (server side)
$this->dispatchBrowserEvent('livewire-refresh');
```

**Comment by TiagoSilvaPereira** [comment]
Thank you @SimoTod it worked very well here.

I have an Alpine component for image preview, and Livewire did not rerender it (sometimes it worked, sometimes not). So now I just fire an event from my Livewire component and ask my Alpine component to refresh the image URL:

```
<div
    image-url="{{ $editing && $photo->image ? \Storage::url($photo->image) : '' }}"
    x-data="imageViewer()"
    @refresh.window="refreshUrl()"
>
```

```js
function imageViewer(src = '') {
    return {
        imageUrl: src,
        refreshUrl() {
            this.imageUrl = this.$el.getAttribute("image-url")
        },
}
```

Livewire documentation for Browser Events: https://laravel-livewire.com/docs/2.x/events#browser

**Comment by manhthang2504** [comment]
Thank you. It help alot.
