### ISSUE TITLE
The result property inside the data object causes an error

### ISSUE THREAD

**Issue by k-ivan** [alpinejs/alpine#503]
Hi guys!
I get an error `TypeError: Cannot read property 'length' of null` in the console when I try to use the `result` property inside the data object. Created an example on [codepen](https://codepen.io/k-ivan/pen/JjYegOQ?editors=1010).

**Comment by SimoTod** [comment]
Yeah, you can't use the name 'result' because it conflicts with the variable used by Alpine to implement the saferEval function (utils.js). We should probably rename it.

**Comment by ryangjchandler** [comment]
> Yeah, you can't use the name 'result' because it conflicts with the variable used by Alpine to implement the saferEval function (utils.js). We should probably rename it.

Agree, should probably have some an `__alpine_` prefix.

**Comment by ryangjchandler** [comment]
@k-ivan @SimoTod I've opened up a PR to rename `result` to `__alpine_result`. The chances of somebody using `__alpine_result` should be super slim, so this is much safer.

An alternative method would be generating a random string each time the `saferEval` function is called, but this would introduce a performance overhead.
