### ISSUE TITLE
`Alpine.version` doesn't match on `2.3.5`

### ISSUE THREAD

**Issue by HugoDF** [alpinejs/alpine#519]
Mainly one for @calebporzio 

`Alpine.version` for `2.3.5` is "2.3.4".

When adding the `Alpine.version` field, it just reads from package.json, that means that for it to update a build needs to be run after bumping the version in `package.json`.

Depending on how you run the publish, we can add `prepack` script or something that will rerun the build after the version is bumped but before publish.

`pack` is the step where `npm publish` creates the package tarball, so automatically running the build before that should fix avoid this issue in future, assuming you use `npm publish` to publish 😄 

Happy to contribute this, just let me know how off my assumptions about your publish workflow are.

**Comment by carlmjohnson** [comment]
When I did my PR, it ended up with a bumped version.

It might be time to get formal about dev processes and releases. Maybe devs only commit to the main files and the dist files are only committed by Caleb or a bot or something.

**Comment by HugoDF** [comment]
> When I did my PR, it ended up with a bumped version.
> 
> It might be time to get formal about dev processes and releases. Maybe devs only commit to the main files and the dist files are only committed by Caleb or a bot or something. 

This is already the case to some extent

Like I said, the dist files need to be rebuilt after the package.json version is bumped which can be done automatically but I need to know how Caleb releases.
