### ISSUE TITLE
Automated testing via CI

### ISSUE THREAD

**Issue by thormeier** [alpinejs/alpine#53]
Hey again @calebporzio 

I've watched this repository for a while now and noticed the growth of the entire thing, quite amazing!

Is there any reason why no CI has been integrated yet? With the amount of issues and especially PRs created, it might make sense to add a CI to automatically execute the already existing tests on new commits/PRs.

Personally, I use Travis CI (https://docs.travis-ci.com/) for such things, as it's free for open source projects and has a nice GitHub integration.

What do you think?

Regards

**Comment by thormeier** [comment]
Nevermind, just noticed that you're using GitHub actions for that. Is there any way to report on build status publicly, though?

**Comment by calebporzio** [comment]
For some reason, it looks like they might have been disabled. Let's see if new PRs get a status. If so, we can close this.

Thanks for checking in on this!

**Comment by thormeier** [comment]
Observed the state of CI a bit now, to me it looks like the action to run the jest tests is only ever executed on commits to master (so, merge commits as well), bu there's no direct feedback of the state of the tests on PRs. Maybe it would make sense anyways to switch to something like Travis in order to have more feedback, what do you think?

**Comment by SimoTod** [comment]
I think it was just a missing configuration in the yml file: the PR above should fix it.
