### ISSUE TITLE
`x-for` with lots of `x-text` inside is quite slow

### ISSUE THREAD

**Issue by marcus-at-localhost** [alpinejs/alpine#530]
Hey I don't know if I'm missing something, but I've encountered a slow down of alpineJS rendering elements in a `x-for` loop, the more `x-text` are inside...

A codepen is below:

- I'm fetching a json file,
- prepare the json
- render the divs with the data (x-for)
- there is another x-for loop in the last (manually added) slide which goes over the same data again.
- initialize SwiperJS

It looks like this:
![slow-alpine-forloop](https://user-images.githubusercontent.com/1337223/83007064-6ce52200-a013-11ea-9579-b084386d9779.gif)

If I remove all the `x-text` elements, it renders the empty divs pretty quick.

Here is a codepen, with the app I was building (sans the images)

https://codepen.io/localhorst/pen/XWmwVOg

Any idea? Thanks!

**Edit:** It seems, like it's only so slow with dev tools open. I tested it with other browsers and dev tools closed and it's much faster...

**Comment by ryangjchandler** [comment]
Yeah, opening DevTools will have a hit of the performance. I opened the CodePen and refreshed a couple of times and it was near enough instant.

**Comment by marcus-at-localhost** [comment]
@ryangjchandler thanks for checking and confirming. I guess a bad performance would have been noticed by others as well, I've just never seen such slow DOM updates.
I'm going to close this.
