### ISSUE TITLE
@input & @keydown doesnt work

### ISSUE THREAD

**Issue by ctf0** [alpinejs/alpine#532]
am not sure if am doing something wrong but here is a demo for the issue https://jsfiddle.net/muah003/bgda2nr7/13/

**Comment by ryangjchandler** [comment]
Hi @ctf0, you need to add an `x-data` attribute to an element. Since the `input` is the only element that is using Alpine directives, you could put it directly on the `input` element:

```html
<input x-data @input="test()" @keydown.enter="other()">
```

**Comment by ctf0** [comment]
oh, thats why then, i thought `x-data` is needed only when we have a init data for the component.

thanx for the quick reply.

**Comment by ryangjchandler** [comment]
> oh, thats why then, i thought `x-data` is needed only when we have a init data for the component.
> 
> thanx for the quick reply.

No, every component needs an `x-data` attribute. `x-data` doesn't need a value, it just needs to be present.
