### ISSUE TITLE
`x-for` error message could be more explicit when more than a single root element

### ISSUE THREAD

**Issue by stuartjnelson** [alpinejs/alpine#539]
## Current Behavior

To be told that _you can't have more than one root element inside a `x-for`_ when I'd accidentally coded with two + root elements. Please not this is invalid HTML...

```
<ul x-data="handler()">
    <template x-for="item in items" :key="item">
        <span x-text="item"></span>
        <li x-text="item"></li>
    </template>
</ul>
```

The console error is;

```
VM342:3 Uncaught (in promise) ReferenceError: item is not defined
    at eval (eval at a (alpine.js:101), <anonymous>:3:27)
    at a (alpine.js:101)
    at ne.evaluateReturnExpression (alpine.js:1535)
    at alpine.js:1502
    at Array.forEach (<anonymous>)
    at ne.resolveBoundAttributes (alpine.js:1484)
    at ne.initializeElement (alpine.js:1403)
    at alpine.js:1387
    at alpine.js:1377
    at e (alpine.js:77)
```

## Expected Behavior

To have an error message that says the problem is multiple root elements inside `x-for` rather than `ReferenceError: ${thing} is not defined`

## Failure Information (for bugs)

[Codepen demo](https://codepen.io/stuartjnelson/pen/bGVXQJo)

**Comment by SimoTod** [comment]
Thanks Stuart, I don't think it's a bug since it's in the documentation but feel free to send a PR. Thanks

**Comment by HugoDF** [comment]
There's a way to check this. We could add a warning if `templateEl.content.children > 1`. 

Something like `Alpine: [x-if/x-for] <template> tags should have a single root element.`

**Comment by SimoTod** [comment]
Stuart hasn't replied so I guess he doesn't mind if you pick it up. 👍

**Comment by stuartjnelson** [comment]
Hi @SimoTod sorry for slow reply! 

@HugoDF yes that is exactly the kind of thing I was thinking of. I'm just writing an article on Alpine and one of the massive positive I think is that the main contributors are really friendly and very actively developing Alpine. NICE ONE! 2 day turn around from reporting a "issue" to seeing it implemented is amazing.

Too often I think in web development we get hung up on using exactly the right words and forums/issues/slack channels etc get persnickety. Thanks for being friendly

**Comment by c-nv-s** [comment]
is this limitation of a single root element in templates ever going to be lifted? I've seen similar complaints reported for Vue and they lifted the restriction in a later version. Is it also possible to lift it with Alpinejs?
