### ISSUE TITLE
x-ref maybe not working

### ISSUE THREAD

**Issue by darsenault** [alpinejs/alpine#556]
Hello. No matter what I try or Google I cannot get any example using x-ref working. 

From the examples on Alpine's GH page:

`<div x-ref="foo"></div><button x-on:click="$refs.foo.innerText = 'bar'"></button>`

Does nothing.

From this page, x-ref example does nothing.
https://shaneiadt.github.io/2020/03/12/Lets-Do-AlpineJs/

```
<div>
    <button
        class="btn btn-primary"
        x-on:click="fetch('https://jsonplaceholder.typicode.com/todos/1')
                .then(response => response.json())
                .then(json => { $refs.todo.innerHTML = JSON.stringify(json) })">
        Fetch
    </button>

    <div x-ref="todo">
    Click button above to fetch some data
    </div>
</div>
```

In this latter example there is no network fetch. It's almost like @click is not working. I have also tried x-on:click. 

I am using the latest version, 2.3.5 on macOS Catalina 10.15.2 with Safari (latest) and Chrome (latest).

Assistance is respectfully requested and will be greatly appreciated.

**Comment by muzafferdede** [comment]
i think you just forgot to include `x-data="{}"` on the wrapper

**Comment by muzafferdede** [comment]
I think you just forgot to include `x-data="{}"` on the wrapper. Alpine component will not initialize if wrapper div does not has `x-data` attribute. And your fetch returns json. Binding inner html to json string? 

```html
<div x-data="{}">
    <button
        class="btn btn-primary"
        x-on:click="fetch('https://jsonplaceholder.typicode.com/todos/1')
                .then(response => response.json())
                .then(json => { $refs.todo.innerHTML = JSON.stringify(json) })">
        Fetch
    </button>

    <div x-ref="todo">
    Click button above to fetch some data
    </div>
</div>
```

**Comment by darsenault** [comment]
muzafferdede: fantstic and thank you! It was indeed the missing x-data in the wrapper div.
