### ISSUE TITLE
Dynamic / variable class names?

### ISSUE THREAD

**Issue by maximelebreton** [alpinejs/alpine#562]
Hello, and thanks for your work!
I'm a Vue fan, and I enjoy your library even if there is some differences.

About Vue, on a `:class` attribute, I assume that when an **input** is:
```html
<div x-data="{ variable1: 'foo', variable2: 'bar'  }">
    <button :class="{ [variable1]: true }">Foo</button>
    <button :class="variable2">Bar</button>
</div>
```

The **expected output** is (like Vue):
```html
<div>
    <button class="foo">Foo</button>
    <button class="bar">Bar</button>
</div>
```

But here is the Alpine output:
```html
<div>
    <button class="[variable1]">Foo</button>
    <button class="variable2">Bar</button>
</div>
```

Is it a bug, or a limitation?

And is there a way to bind dynamic class names (based on variables or expressions)?

Thanks for your help!

**Comment by HugoDF** [comment]
What you've posted work as you expect, I've put it into a CodePen: https://codepen.io/hugodf/pen/vYLLEWb

Are you including Alpine.js onto your page?

HTML output, note that Alpine.js keeps the `:class` attributes, but also adds the `class` ones:

```html
<div x-data="{ variable1: 'foo', variable2: 'bar'  }">
  <button :class="{ [variable1]: true }" class="foo">Foo</button>
  <button :class="variable2" class="bar">Bar</button>
</div>
```

**Comment by maximelebreton** [comment]
@HugoDF Aargh, I was looking to the `:class` attribute (and not the `class`, who was at the end of a large tag with many attributes).

I'm used to seeing `Vue` markup, who removes the attributes after compile.

Thanks for the answer, and sorry for this!

**Comment by HugoDF** [comment]
You can try out the devtools, dunno if they would have helped in this case.

https://github.com/Te7a-Houdini/alpinejs-devtools

**Comment by c-nv-s** [comment]
> What you've posted work as you expect, I've put it into a CodePen: https://codepen.io/hugodf/pen/vYLLEWb
> 
> Are you including Alpine.js onto your page?
> 
> HTML output, note that Alpine.js keeps the `:class` attributes, but also adds the `class` ones:
> 
> ```
> <div x-data="{ variable1: 'foo', variable2: 'bar'  }">
>   <button :class="{ [variable1]: true }" class="foo">Foo</button>
>   <button :class="variable2" class="bar">Bar</button>
> </div>
> ```

just want to say that I was searching for a way to set dynamic class names and attribute names in the documentation and could not find any.
If I hadn't seen this issue I would have probably given up assuming it was not possible.
would be very useful to include in the docs
```
<button :class="{ [variable1]: true }" class="foo">Foo</button>
<!-- or -->
<button :class="{ ['base-name-' + variable1]: true }" class="foo">Foo</button>
```
