### ISSUE TITLE
Bug in component dispatch?

### ISSUE THREAD

**Issue by thiagomajesk** [alpinejs/alpine#573]
Hello everyone!

I was doing some work today and came across this weird issue with `$dispatch`. I don't know exactly why but it doesn't seem to be working properly for me. I have an example here:
https://codepen.io/thiagomajesk/pen/MWKjeMZ.

I'm trying to dispatch some events between components and I can't figure out what is happening.

Events are not being captured:

```html
<section x-data="{items: ['foo']}">
  <p @foo-event="alert($event.detail.items)" x-text="items"></p>
  <button @click="$dispatch('bar-event', {items: items})">Transfer</button>
</section>

<section x-data="{items: ['bar']}">
  <p @bar-event="alert($event.detail.items)" x-text="items"></p>
  <button @click="$dispatch('foo-event', {items: items})">Transfer</button>
</section>
```

Also, for some reason, the Alpine's README example only works if I declare the event in the root element (the second example simply doesn't work):

```html
<div x-data="" @custom-event="alert($event.detail.foo)">
  <button @click="$dispatch('custom-event', { foo: 'bar' })">Works</button>
</div>

<div x-data="">
  <div @custom-event="alert($event.detail.foo)"></div>
  <button @click="$dispatch('custom-event', { foo: 'bar' })">Doesn't Work</button>
</div>
```

**Comment by ryangjchandler** [comment]
When listening for the event, you should add the `.window` modifier:

```
@custom-event.window=""
```

**Comment by thiagomajesk** [comment]
Thanks a lot for the reply @ryangjchandler!

I failed to see that this is in fact already documented in the `x-on` section: https://github.com/alpinejs/alpine#x-on. 

Do you think that we could improve the documentation to include a note about that in the `$dispatch` section? It wasn't clear to me at first just focusing on the dispatching part.

**Comment by ryangjchandler** [comment]
@thiagomajesk feel free to make a PR with some documentation improvements.
