### ISSUE TITLE
flatMap usage cause issue on Edge

### ISSUE THREAD

**Issue by muzafferdede** [alpinejs/alpine#576]
There is a `flatMap` use case in `getXAttrs` function which cause Edge to stop working on current master. The use case implemented when Caleb was working on `x-bind`. So i think it is still `WIP`. Just want to put it here to remind.

**Comment by HugoDF** [comment]
The GitHub Action for CI has been failing on install step recently with something about corejs 3, maybe that's related.

**Comment by SimoTod** [comment]
which version of Edge do you use?
flatMap should be supported by the latest versions.

**Comment by muzafferdede** [comment]
> ~which version of Edge do you use?~
> ~flatMap should be supported by the latest versions.~
> 
> So it seems that Edge 16-18 (old version not using chromium) supports the module/nomodule syntax so it doesn't use the legacy version with the polyfills and babel does not transpile it :( so before tagging the version we need to rewrite that part. Thanks @muzafferdede

@SimoTod i wanted to inform as:

- i use Edge 18
- I think Edge 12 - 18 does not support flatMap according to [caniuse](https://caniuse.com/#feat=array-flat)

@HugoDF i think you also did read [this](https://github.com/babel/babel/issues/9749#issuecomment-475686062) as it's mentioning the issue. So not sure which path to follow for a possible PR.

**Comment by SimoTod** [comment]
It makes sense. We don't really need flatMap to be fair, we can achieve the same result using reduce. I've created a PR for that. Thanks for pointing this out.

**Comment by HugoDF** [comment]
Fix has been applied by Caleb on master
