### ISSUE TITLE
DOM doesn't update when Moment instance is changed

### ISSUE THREAD

**Issue by PaulMorel** [alpinejs/alpine#592]
Hey, I'm working on a project that uses both Alpine and Moment. 

I have a tag with the `x-text` directive, displaying the date from the moment instance. Whenever I update value the instance, the DOM doesn't update. The new value is actually updated if you check with a `console.log`. However, whenever there's something else that triggers a DOM update, the new date is correctly displayed.

Here's an example I made on JSFiddle: https://jsfiddle.net/fqy9gpet/7/

First two buttons change the date, third button toggles an unrelated paragraph. The only time the date is updated is when I toggle the unrelated text.

In the mean time I've found a workaround, but it's not clean. By toggling a dummy variable at the same time as the date changes, it triggers a DOM update. 

Here's a JSFiddle with the workaround: https://jsfiddle.net/f53hv7x9/2/

Is this an Alpine thing or a Moment thing?

Using **Alpine 2.4.1** & **Moment 2.27.0**

Thanks!

**Comment by HugoDF** [comment]
This is kind of an Alpine thing.

What's happening is that you're changing the moment instance, but Alpine doesn't detect it, you would get the same issue if you have an object and you update a property.

The solution is to replace the instance. So `date = moment(...)`.

**Comment by PaulMorel** [comment]
That was my original though. The changes only happen on the `_d` property of the moment object. The rest of the object doesn't change.

Indeed replacing the instance works, however you have a create a new instance  since moment instances are mutable.

`date = date.subtract('1', 'days')` is redundant and doesn't update the DOM

`date = date.clone().subtract('1', 'days')` creates a new instance, assigns it and updates the DOM
