### ISSUE TITLE
Naked x-data exception.

### ISSUE THREAD

**Issue by shanna** [alpinejs/alpine#593]
A naked `x-data` attributes, say `<div x-data></div>` results in an unmatched `}` exception being generated inside `saferEval`. I'm not sure if I cut/paste this from example code somewhere, decided on my own that it would be treated the same way as `x-data="{}"` or it was just a mistake on my part but it wasn't obvious where in my HTML the issue was.

Would be worth catching the error beforehand and explaining the naked x-data isn't possible, setting a default and/or catching the eval as well if there are other syntax errors in the evaled `$expression`?

**Comment by HugoDF** [comment]
Do you have a codepen with this happening? I'm not able to reproduce, see [this CodePen](https://codepen.io/hugodf/pen/PoZpyJQ) 

`x-data` is supposed to be equivalent to `x-data="{}"`, I might double check that we've got a test that it doesn't break 🙂 .

**Comment by shanna** [comment]
Sorry I should have checked first before posting the ticket. I've dug around a bit more this morning and the issue turns out to be related to alpines interaction with the rest of my stack (elixir's phoenix_live_view).

phoenix_live_view has some DOM manipulation code (mergeAttrs) which when executed triggers Alpine's MutationObserver() in an unexpected way causing the error if I don't explicitly set `x-data="{}"`. Here is a codepen of the extracted function triggering the error in alpine: https://codepen.io/shanehanna/pen/pogPPJZ

Neither library is really at fault, it's more of a gotcha with the two libraries trying to operate on the same DOM perhaps so feel free to close if it's going to be painful since I know how to work around it now.

**Comment by SimoTod** [comment]
This should be easily fixable at line https://github.com/alpinejs/alpine/blob/master/src/component.js#L346
Using the same strategy as line https://github.com/alpinejs/alpine/blob/master/src/component.js#L17 if anyone wants to send a PR

**Comment by HugoDF** [comment]
thanks for the pointer @SimoTod 😄
