### ISSUE TITLE
x-bind converts attributes to lowercase

### ISSUE THREAD

**Issue by shmshd** [alpinejs/alpine#594]
When given `:viewBox`, x-bind renders the attribute to lowercase which causes the issue for SVG design.

![info](https://user-images.githubusercontent.com/11484121/85251062-6195e280-b469-11ea-9c6a-dc6379269e73.png)

**Comment by HugoDF** [comment]
This is a tricky one since it's not really an Alpine.js issue, it's "just" that HTML attributes are case-insensitive.

Not sure how we might work around this.

**Comment by ryangjchandler** [comment]
Hey guys - I've just opened up a PR that adds a new `.camel` modifier to `x-bind` so instances like this won't need a hacky if statement to check the element type.

**Comment by shmshd** [comment]
@ryangjchandler This feature should also be explained in the documentation

**Comment by ryangjchandler** [comment]
> @ryangjchandler This feature should also be explained in the documentation

Yeah, I didn't get time to do the docs yesterday - will do this evening.

**Comment by shmshd** [comment]
@HugoDF will the PR for this issue merged for the next minor update?

**Comment by HugoDF** [comment]
@shmshd it's now up to @calebporzio to merge and release

Latest on the PR is that he had a question about the approach (adding a modifier vs supporting camelcased attributes)

**Comment by shmshd** [comment]
@HugoDF my mistake. Didn't notice the conversation in the PR.

**Comment by fnick851** [comment]
Is there still a way to x-bind:viewBox without removing the casing? I don't find any information in the documentation. Is it removed? How are we supposed to use Alpine with SVG viewBox?

**Comment by SimoTod** [comment]
x-bind:view-box.camel as per PR
