### ISSUE TITLE
MacOS Safari <img/> :src binding not working

### ISSUE THREAD

**Issue by Krzemo** [alpinejs/alpine#599]
System:
MacOS 10.14.6
Safari 13.1.1

When doing <img :src="variableName"/> on Safari and changing variableName value with JS, value gets updated, but Safari doesnt change the image (Chrome and FF does).
Interesting part is that when trying to change the image via:
`document.getElementById('img_tag_id').src = variableName;`
it works OK.....

**Comment by ryangjchandler** [comment]
It's worth noting that changing the `.src` property and changing the `src` attribute aren't quite the same, which would explain why they are behaving differently. However, I've recreated a [CodePen](https://codepen.io/ryangjchandler/pen/KKVqwrv) that simply changes the `src` on click of a `<button>`. Running in 13.1 the image updates correctly.

Can you confirm that you've got no console errors?

**Comment by Krzemo** [comment]
Ryan thank you.
This is interesting - it works ok.
I was debugging it extensively prior to posting this issue and I saw this var changing as expected in Safari but not the image ...
I will dig deeper into it later.
Meanwhile I will close the issue.
Tx again.

**Comment by victorcngo** [comment]
hey folks! did anyone came up with something? a fix, a workaround?

**Comment by SimoTod** [comment]
In v3, i think you can use `<img x-effect="$el.src = variableName">`
