### ISSUE TITLE
[Idea] Add ability to define a component controller

### ISSUE THREAD

**Issue by panda-madness** [alpinejs/alpine#60]
This might be something that goes a little against the project's philosophy, but I'll put it out there nonetheless.

I think it would be neat if we could (optionally) define a controller class/object/whatever for Alpine, that would bind to existing HTML in the same way Stimulus does.

I'm envisioning something like the following (basically a modified copy of Stimulus's conventions):

```js
class MyController extends AlpineController {

    data = { testInput: null, testCheckbox: null, submitted: false };

    connected() { // lifecycle hooks
        this.data;
        this.$refs;
    }

    async submitForm($event) { // long-form event handlers
       await fetch(...);
       // do a million other things
       this.data.submitted = true;
    }
}

Alpine.controller('my-controller', MyController);
```
```html
<div x-controller="my-controller">
    <form @submit="submitForm"> <!-- all of the controller's methods and data in scope here -->
        <input type="text" x-model="testInput">
        <select x-model="testSelect">
            ...
        </select>
        <div x-show="submitted">We submitted the form!</div>
    </form>
</div>
```

I'm doing something similar with an actual Stimulus + alpine combo, but there are some pain points (very verbose html, communication between a Stimulus controller and alpine).

I've looked through alpine's source, but I didn't grok it fully yet, so I'm unaware of any technical challenges that could arise, but would love your thoughts!

**Comment by thormeier** [comment]
Maybe I don't fully get the idea, but what would be the benefit of this over using the approach described in `Extract Component Logic` in https://github.com/alpinejs/alpine/blob/master/README.md#x-data ? As far as I can see, such a behaviour should basically work, shouldn't it?

**Comment by calebporzio** [comment]
What @thormeier said.

Here's what your controller example would look like with the current strategy.

What do you think? (didn't test the exact code, but should work)

```js
function myController() {
    return {
        testInput: null,
        testCheckbox: null,
        submitted: false,
        init() { // some init hook
            //
        },
        submitForm($event) { // long-form event handlers
            fetch(...).then(() => {
                this.submitted = true;
            })
         },
    }
}
```
```html
<div x-data="myController()" x-init="init()">
    <form @submit="submitForm">
        <input type="text" x-model="testInput">
        <select x-model="testSelect">
            ...
        </select>
        <div x-show="submitted">We submitted the form!</div>
    </form>
</div>
```
