### ISSUE TITLE
X-Spread not working

### ISSUE THREAD

**Issue by computerfr33k** [alpinejs/alpine#602]
I was trying to test out the `x-spread` functionality as it is shown in the readme, but it does not work for me. Either I'm missing something which is causing it to not work. Or there is a bug or the documentation needs to be fixed with a working example.

I have copied the example from the readme, which can be seen here:
https://codepen.io/ericp_mrel/pen/XWXggqj

**Comment by HugoDF** [comment]
That's odd, from memory I believe x-data is supposed to call the function automatically even without the `()`

**Comment by ryangjchandler** [comment]
@HugoDF `x-data="dropdown"` has a `typeof === 'string`, not `function` so the return value would actually be a function, not the result of that function. `x-init` on the other hand checks the return type of the eval, if it's a function, it then calls it. Maybe something we should add..
