### ISSUE TITLE
2.4 transition behavior regression

### ISSUE THREAD

**Issue by KevinBatdorf** [alpinejs/alpine#612]
Here's the setup:

Alpine 2.3.5: https://codepen.io/KevinBatdorf/pen/gOPxojN
Alpine 2.4.1: https://codepen.io/KevinBatdorf/pen/c89c2b1ea994646bca5cd254b4152611

Notice the flickering animations on 2.4.1

~I have a fix ready but will see if there's a test I can add.~

**Comment by loweoj** [comment]
Adding another example of this bug. When alpine is pinned to 2.4.1 you can see error flashes on the background when typing continuously into the input for a little while - https://codepen.io/loweoj/pen/wvMreYx
