### ISSUE TITLE
Using :class transitions without x-show or x-if

### ISSUE THREAD

**Issue by booni3** [alpinejs/alpine#620]
I am trying to create an effect where my div switches to green and then fades back to white. The below example fades in and out using the tailwind transition and duration class.

```html
<div x-data="{ flash: false }"
     class="transition duration-300"
     :class="{ 'bg-green-200': flash }"
     x-init="
       @this.on('work-done', () => {
            flash = true;
            setTimeout(() => { flash = false }, 300);
        })"
>
    This should flash on and fade out
</div>
```

Adding `x-transition`s has no effect in this case as we are not using it with x-show or x-if. Tailwind does not provide asymmetrical or one-sided transitions. 

I realise we could implement this manually, but alpine already almost provides the solution (at least through its syntax). Is there a way that it can do this?

**Comment by ryangjchandler** [comment]
@booni3 I've replicated this using a button to change the values instead and it seems to work fine. https://codepen.io/ryangjchandler/pen/eYJGLBJ

The problem you're having could be to do with nested short closures and scopes not being carried correctly.

**Comment by SimoTod** [comment]
I would use a simple css animation for that effect (you can google 'css blinking animation'). X-transition was built to enanche x-show or x-if. Without a change of state, it wouldn't make much sense. If you want to use alpine, the only way is the one you used: setting a variable in x-init and set it back after x seconds

**Comment by booni3** [comment]
@ryangjchandler thanks for the quick response and your suggestion. I was hoping to be able to use x-transition to be able to set an asymmetrical transition.

Thanks a lot for your suggestion though. Using your idea in the opposite direction gives me what I was looking for.


```html
<tr wire:key="{{ $key }}"
    x-data="{ flash: true }"
    @click="flash = false; setTimeout(() => flash = true, 1000)"
    class="text-lg bg-green-200"
    :class="{ 'row-fade': flash }"
></div>
```
```css
.row-fade {
    background: white !important;
    transition: 1s !important;
}
```
![Kapture 2020-06-29 at 22 34 29](https://user-images.githubusercontent.com/20134485/86058788-55a5b400-ba59-11ea-8e4b-adfa832e3ed2.gif)

**Comment by jsmestad** [comment]
@booni3 Thank you so much for posting this solution. I was able to animate a checkbox with the same technique.

```html
      <div class="pretty p-icon p-round pulse" phx-update="ignore" >
        <input
              x-data="{animate: false}"
              x-on:click="animate = true; setTimeout(() => animate = false, 1000);"
              type="checkbox"
              name="checked"
              value="yes"
              phx-update="ignore"
              :class="{ 'animate': animate }"/>
        <div class="state p-success">
          <i class="icon fas fa-check-circle text-green"></i>
          <label class="pl-2">My TODO Item</label>
        </div>
      </div>
```
