### ISSUE TITLE
x-data order of properties significant to $watch 

### ISSUE THREAD

**Issue by pthompson** [alpinejs/alpine#625]
I am using AlpineJS with Phoenix LiveView and am having an issue with `$watch`. I have found that the order of the properties in the x-data object is significant. If I have two properties, one being the watched property and the other a property assigned in $watch to the watched property. The watched property has to be declared after the one being updated by the watch in x-data for the $watch to work.

In this example, I watch a `count` property, which is updated from a LiveView `@count` In my `$watch` I am assigning `shadowCount` to the new value of `count`. If I put `shadowCount` before `count` in `x-data`, it works. If it follows, it doesn't work.

By works/doesn't work, I mean that the `shadowCount` does not update in the not working case. It does update in the working case.

Works:
------
```html
<div id="counter"
      x-data="{shadowCount: 0, count: <%= @count %>}"
      x-init="() => {
        $watch('count', value => {
          shadowCount = value
        })
      }">
  <h1>The watched count is: <span x-text="count"></span></h1>
  <h1>The shadow count is: <span x-text="shadowCount"></span></h1>
  <button phx-click="decrement"> Decrement </button>
  <button phx-click="increment"> Increment </button>
</div>
```

![works](https://user-images.githubusercontent.com/204189/86170722-69403180-bad0-11ea-870a-b71634af0fca.gif)

Doesn't work:
-------------

```html
<div id="counter"
      x-data="{count: <%= @count %>, shadowCount: 0}"
      x-init="() => {
        $watch('count', value => {
          shadowCount = value
        })
      }">
  <h1>The watched count is: <span x-text="count"></span></h1>
  <h1>The shadow count is: <span x-text="shadowCount"></span></h1>
  <button phx-click="decrement"> Decrement </button>
  <button phx-click="increment"> Increment </button>
</div>
```

![not-working](https://user-images.githubusercontent.com/204189/86170746-72310300-bad0-11ea-970d-d0c755c1cd5a.gif)

----

Perhaps it is an ordering issue with the way LiveView traverses nodes. I wonder if a similar pattern would work or not with LiveWire.

**Comment by pthompson** [comment]
I uploaded a repro to https://github.com/pthompson/alpine_x_data_order_bug_repro.

**Comment by ryangjchandler** [comment]
Hey @pthompson, I haven't had any luck reproducing this outside of a Phoenix environment so I'm guessing it is something to do with LiveView as opposed to Alpine. Have you tried cross-posting this issue to the LiveView repo too?

**Comment by SimoTod** [comment]
@pthompson There's a bit of mix-up between frontend and backend, you need to rethink your logic.
You use a LiveView function (server side) to increment and decrement the counter so the watcher doesn't really work here.

I believe that what happens here is:
- you load the page, the component starts and sets the watcher.
- you click on the button and trigger a server side update
- LiveView changes count and updates the x-data attribute
- The alpine mutation observer picks it up and reevaluates x-data (all attributes, Alpine doesn't know the old values at this point)
- it evaluates `count: ...` first, triggering the watcher and updating `shadowCount` accordingly
- it evaluates `shadowCount: 0` then, reverting the value to 0 straight away.

Watchers are only useful if it's a pure frontend interaction but, if it's a server side change, you should ditch the watcher and just update shadowCount on the server.

I assume your real case is slightly more complicate but same considerations apply.
I hope it helps.

**Comment by pthompson** [comment]
Thanks for the explanation @SimoTod. That makes a lot of sense.

**Comment by pthompson** [comment]
Thanks guys for looking at this and for all the work on Alpine.js! It is a great complement to Phoenix LiveView.
