### ISSUE TITLE
Transition Bug

### ISSUE THREAD

**Issue by brnmonteiro** [alpinejs/alpine#642]
Is this a bug?

![Kapture 2020-07-07 at 17 27 06](https://user-images.githubusercontent.com/6596579/86838950-27d2f780-c077-11ea-8d8e-ab4df6dc6d9c.gif)

When I use x-show.transition this happen..

Thanks

**Comment by SimoTod** [comment]
Can you post the whole alpine component? Is there anything causing an update every seconbds? (setInteval, recursive whatchers, etc)

**Comment by SimoTod** [comment]
@brnmonteiro any news?

**Comment by brnmonteiro** [comment]
Hi @SimoTod, never mind... 
I changed to v-if with templates and works. Sorry about the delay to reply the issue.
