### ISSUE TITLE
Transitions broken in v2.4.1

### ISSUE THREAD

**Issue by bep** [alpinejs/alpine#643]
I have an app with a tree that uses `x-show.transition` to show/hide nodes.

This has worked great in "all" AlpineJS versions, but when upgrading from v2.4.0 to v2.4.1 the transitions happens on any update, even if the `x-show` boolean changes or not, which makes for a very busy tree.

I understand that v2.4.1 was a reversal of a commit that introduced a related issue, but the reversal does not look correct to me (in that they do not match that great):

https://github.com/alpinejs/alpine/pull/543/files
https://github.com/alpinejs/alpine/commit/91b057d4c4295c4edf459716e800c7fbffd0e211

**Comment by SimoTod** [comment]
Hi @bep, Caleb is aware (#612) and it will be fixed in the next release. If you are experiencing issues, you need to stick to 2.4.0 or 2.3.5 for now.

**Comment by bep** [comment]
@SimoTod OK, thanks, 2.4.0 works fine for me.
