### ISSUE TITLE
x-on: timeout inside handler does not work

### ISSUE THREAD

**Issue by robbevp** [alpinejs/alpine#656]
I wanted to write an event handler that sets a value to true, then set a timeout and set it back to false. However the set within the callback does not work. I've tried to extract as much as possible from my logic, but I still can't get this to work.

With the following event handler, the `highlight` prop is set to true, and my `console.log()` works, but the `highlight` prop is not set to false again.

```js
handleHighlight() {
  this.highlight = true;
    setTimeout(function () {
      this.highlight = false;
      console.log("reached")
    }, 1500)
  },
};
```

A codepen that show this in action: https://codepen.io/RobbeVP/pen/rNxqyJj

**Comment by SimoTod** [comment]
`this` inside a function defined like that is the global object. It's the way javascript handle scopes. (try to console log `this` inside the callback).
You can either use an arrow function or bind this to the callback https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind

**Comment by robbevp** [comment]
🤦 
Should have know that. Thanks for your help
