### ISSUE TITLE
x-for not defined for options in select

### ISSUE THREAD

**Issue by dessery85** [alpinejs/alpine#658]
Hi Guys

I have been wrestling with this one for hours now and I am completely confused. I am hoping someone can shed some light on it for me. 

I have an HTML Select which I want to populate with some data from an API. I am using a template with x-for to loop through an array and output each Option but I receive the following error:

_Uncaught ReferenceError: jobLocation is not defined_

I have stripped back my code to the most basic level and still have the same problem, this is my code:

```
<div x-data="app()" x-init="init()">
            <select x-model="location">
                <template x-for="jobLocation in jobLocations">
                    <option x-bind:value="jobLocation" x-text="jobLocation"></option>
                </template>
            </select>
        </div>

        <script type="text/javascript">
            function app() {
                return {
                    location: "Location",
                    jobLocations: [],
                    init() {
                        this.jobLocations = ['Location', 'Test 1', 'Test 2']
                    }
                };
            }
        </script>
```

But if I move the template out of the select and change the option to a div, it correctly outputs the values. Like so:

```
<div x-data="app()" x-init="init()">
            <select x-model="location">
                
            </select>

            <template x-for="jobLocation in jobLocations">
                <div x-text="jobLocation"></div>
            </template>
        </div>
```

Now just to really confuse things, I decided to re-create the code in a JSFiddle to share here, and it works in the fiddle!!

https://jsfiddle.net/xyhpnebL/2/

On my version I am using Alpinejs 2.4.1 but I have also tested with 2.1.2 which is what the Fiddle uses but have the same issue. I don’t know if it makes a difference but I installed it via yarn and it’s being bundled with webpack and its being bundled into a script which is defer loaded in the footer of my site. 

Does anyone have any idea what might be going on and how I can work around it?

Many thanks
David

**Comment by SimoTod** [comment]
If we can't replicate in a jsfiddle or codepen, it's going to be hard to debug. 
At a first glance, there's nothing wrong with your code snippet.

Do you use other libraries which may conflict with Alpine?

P.s. From what you described, it doesn't seem an issue with Alpine since it's not possible to replicate it so it would probably fit better in the discussion tab.

**Comment by dessery85** [comment]
Hi Simone

Many thanks for getting back to me. I feel better knowing that I am not doing something stupid anyway! jQuery is loaded as part of the platform the site is built on but I haven't had an issue with that before. I will try stripping out some other custom scripts though and see how that goes. I will let you know if I discover anything of interest.

Many thanks
David

**Comment by dessery85** [comment]
Unfortunately I haven't been unable to find the source of the issue and resolve the problem but as deadlines are looming and the data will not change after the initial page load so i don't need it to be reactive, I have just added an x-ref to the select field and used pure JS to append the option elements to the select. 

Many thanks for your help

All the best
David

**Comment by SimoTod** [comment]
@dessery85 Are you okay with closing this issue since we can't replicate? Thanks

**Comment by dessery85** [comment]
@SimoTod Yes absolutely, thank you very much!
