### ISSUE TITLE
Nested component not allowed?

### ISSUE THREAD

**Issue by yaquawa** [alpinejs/alpine#662]
I expect this give me 'FOO', but it got me nothing.
Is there any way to refer outer component's data?

```html
<div x-data="{foo: 'FOO'}">
    <div x-data="{bar: 'BAR'}">
        <div x-text="foo"></div>
    </div>
</div>
```

**Comment by HugoDF** [comment]
You can't refer to the outside scope at the moment.

The solution we recommend is to synchronise data using events.

See the following post https://codewithhugo.com/alpinejs-component-communication-event-bus/

The approaches that work for sibling components will also work for nested components (despite the post not having explicit examples)

**Comment by yaquawa** [comment]
Thanks. I'm looking forward to having the ability to get data from parent component.
