### ISSUE TITLE
Incorrect binding for attributes with numbers in name

### ISSUE THREAD

**Issue by danprince** [alpinejs/alpine#666]
```html
<svg x-data="{ x: 10, y: 10 }">
  <line x1="0" y1="0" :x2="x" :y2="y" />
</svg>
```

Produces the following html:

```js
<svg>
  <line x1="0" y1="0" x="10" y="10" />
</svg>
```

The `x2` and `y2` attributes have the trailing number stripped. The same happens if you bind `x1` and `y1`.

A little bit of experimentation shows that Alpine strips all numeric content and everything that follows it from attribute names. Guessing there's an overly strict regex somewhere?

```html
<line :test123foo="4" />

<!-- becomes -->

<line test="4" />
```

**Comment by HugoDF** [comment]
Interesting, as far as I know the regex is at https://github.com/alpinejs/alpine/blob/master/src/utils.js#L96

**Comment by HugoDF** [comment]
On second look, it's probably here: https://github.com/alpinejs/alpine/blob/master/src/utils.js#L137

**Comment by HugoDF** [comment]
Good catch & fix 👍👍

**Comment by danprince** [comment]
Short term workaround is to use a `<polyline>` instead of a regular line.

```html
<line x1="10" y1="10" :x2="x" :y2="y" />
```

```html
<polyline :points="`10,10,${x},${y}`" />
```
