### ISSUE TITLE
x-for not working with spatie form-backend-validation

### ISSUE THREAD

**Issue by SamuelNitsche** [alpinejs/alpine#672]
I tried using alpine together with spaties [form-backend-validation](https://github.com/spatie/form-backend-validation) but ran into an issue with x-for.

In this code, alpine should loop over the items array inside the form object. On the initial load this works perfectly fine but when I click the button to add an item alpine does not add the item to the list.

See [the demo](https://modest-mirzakhani-754396.netlify.app/)

```html
<div x-data="init()">
  <template x-for="item in form.items">
    <div>
      <p x-text="item"></p>
    </div>
  </template>

  <button @click="form.items.push('baz')">Add</button>
</div>

<script>
    function init() {
        return {
            form: new Form({
                items: [
                    'foo',
                    'bar'
                ]
            })
        }
    }
</script>
```

I got it working in vue with the following code.

```vue
<template>
  <div>
    <template v-for="item in form.items">
      <p v-text="item"></p>
    </template>

    <button @click="form.items.push('baz')">Add</button>
  </div>
</template>

<script>
    export default {
        data() {
            return {
                form: new Form({
                    items: [
                      'foo',
                      'bar',
                    ]
                })
            }
        }
    }
</script>

```

**Comment by SimoTod** [comment]
ES6 classes are not reactive in Alpine. Only object literals, arrays and primitive types such as strings, numbers, etc. The underlying reactivity layer (salesforce membrane) doesn't support it.
As a workaround (not ideal but it's not fixable otherwise) you can add a timestamp variable and update it every time you push something to the form.

**Comment by SamuelNitsche** [comment]
Yeah, I can confirm that the workaround "fixes" the problem. Maybe I will go with this one. Thank you for the explanation.
