### ISSUE TITLE
x-html binding resets state

### ISSUE THREAD

**Issue by nekudo** [alpinejs/alpine#680]
Hello,

this one is a little hard to explain, so here is an example:

```
<html>
    <head>
        <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    </head>
    <body>


<section x-data="myComponent()" x-init="init($el)">
    <form>
        <div x-html="tacontainer"></div>
        <div x-html="response"></div>
        <button x-on:click.prevent="foo">Click Me!</button>
    </form>
</section>


<script>
    function myComponent() {
        return {
            // data
            tacontainer: '',
            response: '',

            // methods
            init($el) {
                this.tacontainer = '<textarea>Change Me!</textarea>';
            },

            foo() {
                this.response = 'just a test...';
            },
        }
    }
</script>

    </body>
</html>
```

Here is how to reproduce the problem:

1. Change the text inside the textarea.
2. Click the button.

Result: The text in the textarea goes back to "Change me!" even though the foo method does only change the content of the second x-html binding.

It seems the state of the component (or at least the x-html bindings) gets reset as soon a one binding is changed.

Am I missing something or is this a bug?

Simon

**Comment by SimoTod** [comment]
It's the expected behavior, the whole component gets reevaluated when something changes. X-html inserts the html inside the specified element, it's not designed to maintain the state. If your content doesn't need to be reactive, it's better to use x-init and inject the html once.

**Comment by nekudo** [comment]
Hi. Thanks for the reply. That's exactly what I ended up doing. Just wanted to make sure this is not a bug.
