### ISSUE TITLE
x-bind to xlink:href does not work

### ISSUE THREAD

**Issue by bep** [alpinejs/alpine#684]
```html
<svg >
        <use x-bind:xlink:href="myicon"></use>
</svg>
```

**Comment by muzafferdede** [comment]
This sample is working fine if it is what you are trying to do:
```html
<svg x-data="{}">
  <use x-bind:xlink:href="'#myicon'"></use>
</svg>
```

**Comment by bep** [comment]
Not sure what you mean by "working fine".

This example should be more complete:

```
<svg x-data="{ myicon: '#myicon' }}" >
        <use x-bind:xlink:href="myicon"></use>
</svg>
```

The icon isn't showing. 

My current workaround is this behind-the-scenes hack:

```html
use.setAttributeNS('http://www.w3.org/1999/xlink', 'xlink:href', data.icon);
```

I think the clue lives in `setAttributeNS`.

**Comment by ryangjchandler** [comment]
@bep It appears that the attribute is being bound correctly. Here is a CodePen: https://codepen.io/ryangjchandler/pen/gOPNdRV.

For what it's worth, `xlink:` attributes are deprecated since SVG v2. You're better off using the regular `href` attribute.

**Comment by muzafferdede** [comment]
By "working fine" i mean it should be fine :) 

Perhaps you are doing some typo? 

if i do like so:
```html
<svg x-data="{ myicon: '#myicon'}" >
  <use x-bind:xlink:href="myicon"></use>
</svg>
```
i end up with:
```html
<svg x-data="{ myicon: '#myicon'}">
   <use x-bind:xlink:href="myicon" xlink:href="#myicon"></use>
</svg>
```
~in your sample code you got double curly braces in the end of x-data~. 

I am not sure svg behaves weird when it's come to binding hrefs

**Comment by bep** [comment]
@ryangjchandler your codepen uses `href`, which isn't exacly the same `xlink:href` does not work ... but you are right, it's working, which is what I care about.

**Comment by ryangjchandler** [comment]
> @ryangjchandler your codepen uses `href`, which isn't exacly the same `xlink:href` does not work ... but you are right, it's working, which is what I care about.

As I said `xlink:href` is deprecated and might not be supported by all browsers.

**Comment by SimoTod** [comment]
I can confirm that xlink:href does not work for me (chrome 84) even using plain html. Alpine seems to create the attribute as expected so it's probably because it's deprecated.

**Comment by ryangjchandler** [comment]
@bep FWIW, if you can see that the attribute has been bound to the element correctly in DevTools, just check MDN for the attribute as well, that's all I did to tell you it was deprecated.
