### ISSUE TITLE
[FR] Nested transitions

### ISSUE THREAD

**Issue by aerni** [alpinejs/alpine#70]
It would be great to be able to nest transitions. A common use case is a modal, where you want to fade-in the background before the content. This is an [example](https://tahazsh.com/nested-transitions-in-vue) in Vue.

**Comment by calebporzio** [comment]
You actually can. Here's a pen: https://codepen.io/calebporzio/pen/xxbPXdP

**Comment by aerni** [comment]
Awesome! Thank you for taking the time with the pen.
