### ISSUE TITLE
class object doesn't seem to be reactive

### ISSUE THREAD

**Issue by kevinruscoe** [alpinejs/alpine#71]
I took the "dropdown" example and tried to change it be class based

https://codepen.io/kevdotbadger/pen/ExaLExy

However, it's not working. Is changing the value in my classes object not allowed? Or does it not trigger a redraw?

**Comment by SimoTod** [comment]
Hi @kevinruscoe, today's release should fix your issue (1.8.0, I tried your pen with the new version and it seems okay).

**Comment by calebporzio** [comment]
Thanks for checking in on that!

**Comment by fredcarle** [comment]
@kevinruscoe I'm trying to use a class as well and getting no reactivity. I'd be curious to see how you had it set up but your codepen doesn't exist anymore. Would you care to share an example once more?

**Comment by HugoDF** [comment]
@fredcarle if you use the IE11 build you should be able to use a class

We introduced a new reactivity library into Alpine.js `2.1.0` release which doesn't support classes so anything before that should work as well I think

**Comment by CarstenRuetz** [comment]
@HugoDF I just ran into this very problem.

A pity that you did throw support for classes out. 
Is there any other good way to make this work? 

I've got this example, which works with 1.9.5 but not 2.8.2 (latest at the time of writing).

```
class Reactive {
    constructor(x) {
        this.x = x
    }
}

var r = new Reactive(111)


<div x-data="{ elem: r }">
  <span x-text="elem.x"></span><br />
  <a href="#" @click="elem.x = 2">change member variable</a><br />
  
</div>

```
