### ISSUE TITLE
x-show content flashes before disappearing on page load

### ISSUE THREAD

**Issue by splashsky** [alpinejs/alpine#710]
Hey guys! Not sure if this has been addressed at any point before, and it might simply be a limitation of DOM behavior, but I have tabs and a modal that use Alpine to hide them prior to user interaction. When I refresh the page, for the briefest moment, all of these elements meant to be hidden are visible, even using the `x-cloak` and `x-show` attributes. Is there a way to address this?

![Peek 2020-08-16 22-49](https://user-images.githubusercontent.com/12104206/90355722-d709d380-e012-11ea-8513-72603be0ea1a.gif)

**Comment by mblarsen** [comment]
Be sure that you've added `[x-cloak]` to your style sheet somewhere. Or even better add it to your HTML head so that it is there before you stylesheets load:

```html
        <style>
            [x-cloak] {
                display: none;
            }
        </style>
```

**Comment by ryangjchandler** [comment]
@mblarsen has provided the correct answer, Alpine doesn't provide the styling for `x-cloak` since each developer will have their own way of hiding an element but `display: none;` is the generally best way to do it.

**Comment by splashsky** [comment]
For future reference, I fixed the problem by adding just a classless `div` wrapper over the element I was hiding and added the `x-cloak` and `x-show` attributes to that instead.

My best guess is that it was rendering my content first, then applying hidden over the top of it, which led to the issue I had.

**Comment by XaBerr** [comment]
Hi, I've the same problem!
I've tried all the suggested solutions but none of them worked.

![bug-flahs-modals](https://user-images.githubusercontent.com/16030020/92715148-5dd57600-f35d-11ea-8418-9f79e236e341.gif)

The function I’m using is "x-show"
```html
<div x-show="showModalDelete" x-on:click.away="showModalDelete = false" class="fixed bottom-0 inset-x-0 px-4 pb-4 sm:inset-0 sm:flex sm:items-center sm:justify-center">
        <div class="fixed inset-0 transition-opacity">
```

I've also tried `:style="showModalDelete ? 'display:flex' : 'display:none'"`

**Comment by KevinBatdorf** [comment]
@XaBerr Did you add `x-cloak`? It's not in your markup there.

Also, I typically will use `!important` on the x-cloak style rule:

```html
<style>
  [x-cloak] { display: none !important; }
</style>
```

**Comment by XaBerr** [comment]
Yes, I've tried to put it in my header but doesn't works
```
        <style>
            [x-cloak] { display: none !important; }
        </style>
    </head>
```

**Comment by XaBerr** [comment]
To be more precise, when I add x-cloak the "divs" disappear but then the show button no longer works

**top-page**
```html
    <style>
        [x-cloak] {display: none;}
    </style>
```

**button**
```html
<button x-on:click="resetModal(); showModalInsert = true;">
```

**modal**
```html
<div x-cloak x-show="showModalInsert || showModalModify" x-on:click.away="showModalInsert = false; showModalModify = false;" >
```

**Comment by XaBerr** [comment]
> @XaBerr Did you add `x-cloak`? It's not in your markup there.
> 
> Also, I typically will use `!important` on the x-cloak style rule:
> 
> ```
> <style>
>   [x-cloak] { display: none !important; }
> </style>
> ```

Yes, now is working
