### ISSUE TITLE
Invalid multiple element root error on IE11

### ISSUE THREAD

**Issue by brennaveen-rea** [alpinejs/alpine#714]
I'm not sure if I am doing something wrong, but for some reason every `x-for` on IE causes the following warning to be shown in the console even though I only have one child node in my loop.  The error is not displayed in Chrome.

```
Alpine: <template> tag with [x-for] encountered with multiple element roots. Make sure <template> only has a single child node.
```

I can replicate the problem even with a very basic application like this:

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <script
            type="module"
            src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.6.0/dist/alpine.min.js"
        ></script>
        <script
            nomodule
            src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.6.0/dist/alpine-ie11.min.js"
            defer
        ></script>
    </head>
    <body>
        <div x-data="test()">
            <template x-for="link in links">
                <div>
                    <span x-text="link.name"></span>
                </div>
            </template>
        </div>
        <script>
            function test() {
                return {
                    links: [
                        {
                            name: 'link1',
                        },
                        {
                            name: 'link2',
                        },
                    ],
                };
            }
        </script>
    </body>
</html>
```

**Comment by ryangjchandler** [comment]
@brennaveen-rea - which version of Alpine are you using? You should be able to do `Alpine.version` in the console to find out :)

**Comment by brennaveen-rea** [comment]
Apologies, I am seeing this problem on v2.4.1, but I have tried it on v2.5.0 and 2.6.0 and experienced the same problem.

**Comment by ryangjchandler** [comment]
> Apologies, I am seeing this problem on v2.4.1, but I have tried it on v2.5.0 and 2.6.0 and experienced the same problem.

No worries, I can see the v2.6.0 in the code snippet you provided above.

**Comment by KevinBatdorf** [comment]
What if you add a `:key=""` to the `<template>`?

Also, what does the rendered markup look like?

**Comment by ryangjchandler** [comment]
@brennaveen-rea - I'm can't reproduce this on IE11. Could you share the rendered markup please, and perhaps try @KevinBatdorf's suggestion with `:key`.

**Comment by ryangjchandler** [comment]
Sorry, I've reproduce the problem. The rendered content looks fine, but there is still a warning in the console. I've got a feeling this is down to the `<template>` polyfill used in the IE11 not returning the correct value for `el.content.childElementCount`. I'll do some digging and see what I find.

**Comment by brennaveen-rea** [comment]
Alas, adding the key didn't work.

Here is the rendered markup:

![image](https://user-images.githubusercontent.com/64163994/90660074-0edb6b80-e20b-11ea-876c-c1d995055a16.png)
![image](https://user-images.githubusercontent.com/64163994/90660206-3af6ec80-e20b-11ea-992a-0cdc5e9140d7.png)

I don't know if it makes a difference, but my IE is Version: 11.719.18362.0, Update Version: 11.0.180

**Comment by ryangjchandler** [comment]
@brennaveen-rea - functionally it is working, the `x-for` is being evaluated correctly, but the warning is still being logged.

**Comment by HugoDF** [comment]
> `<template>` polyfill used in the IE11 not returning the correct value for `el.content.childElementCount`. I'll do some digging and see what I find.

this makes sense, we could strip that warning for IE11

**Comment by brennaveen-rea** [comment]
Great, I'll just ignore the warning on IE for now.  Thanks to everyone for looking into this so quickly!

**Comment by ryangjchandler** [comment]
> > `<template>` polyfill used in the IE11 not returning the correct value for `el.content.childElementCount`. I'll do some digging and see what I find.
> 
> 
> 
> this makes sense, we could strip that warning for IE11

That's one option, or we use `el.content.childNodes.length` instead which the polyfill uses itself.

**Comment by HugoDF** [comment]
> > > `<template>` polyfill used in the IE11 not returning the correct value for `el.content.childElementCount`. I'll do some digging and see what I find.
> > 
> > 
> > this makes sense, we could strip that warning for IE11
> 
> That's one option, or we use `el.content.childNodes.length` instead which the polyfill uses itself.

done, thanks for the tip

**Comment by calebporzio** [comment]
Thanks for the thorough issue @brennaveen-rea.

For now, to remove those warnings, you can add the following Polyfill for IE11: https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/childElementCount#Polyfill_for_IE8_IE9_Safari

We will likely include this in the next tagged version of Alpine. Thanks.
