### ISSUE TITLE
x-model with multiple checkboxes

### ISSUE THREAD

**Issue by mokhosh** [alpinejs/alpine#739]
In vuejs if you `v-model="categories"` multiple checkboxes where `categories` is an `Array`, you will have an array of selected items when you check them.
But in alpinejs you get an array of one item like this: `['on']`, and you have to `x-model` them with indexes to get a working array which is horrendous:

```html
<div x-data="{ categories: [] }">
    <input type="checkbox" x-model="categories[0]">
    <input type="checkbox" x-model="categories[1]">
    <input type="checkbox" x-model="categories[2]">
    <input type="checkbox" x-model="categories[3]">
    <input type="checkbox" x-model="categories[4]">
    <input type="checkbox" x-model="categories[5]">
    <input type="checkbox" x-model="categories[6]">
</div>
Instead of
<div x-data="{ categories: [] }">
    <input type="checkbox" x-model="categories">
    <input type="checkbox" x-model="categories">
    <input type="checkbox" x-model="categories">
    <input type="checkbox" x-model="categories">
    <input type="checkbox" x-model="categories">
    <input type="checkbox" x-model="categories">
    <input type="checkbox" x-model="categories">
</div>
```

**Comment by KevinBatdorf** [comment]
The second one should work if you set the value. Isn't that required in Vue too?

**Comment by KevinBatdorf** [comment]
See here: https://codepen.io/KevinBatdorf/pen/xxVLOxX

**Comment by ryangjchandler** [comment]
Yeah, @KevinBatdorf is right, the second one should work if you set the value of the checkboxes.

**Comment by mokhosh** [comment]
You're right. I'm making a template, and the backend team should provide the values. I didn't think it will make a difference.

Thanks guys.
