### ISSUE TITLE
It cannot find component by id.

### ISSUE THREAD

**Issue by VahanDrnoyan** [alpinejs/alpine#757]
Hello, 

I have doubts if this is an issue or misconfiguration by me, however, I have implemented all according to the documentation.

I am trying to implement a modal opening and closing with @entangle.

An example from the documentation is this:

<img width="844" alt="Screenshot 2020-09-09 at 19 47 22" src="https://user-images.githubusercontent.com/23120503/92621794-57032080-f2d5-11ea-8201-30650ee23ab7.png">

Here is how I use the blade component:

<img width="523" alt="Screenshot 2020-09-09 at 19 35 53" src="https://user-images.githubusercontent.com/23120503/92620983-561dbf00-f2d4-11ea-894e-3934d82127bc.png">

Here is how the x-data is used:

<img width="822" alt="Screenshot 2020-09-09 at 19 36 32" src="https://user-images.githubusercontent.com/23120503/92621110-75b4e780-f2d4-11ea-8f4d-6e184715183f.png">

Here is which error I got:

<img width="822" alt="Screenshot 2020-09-09 at 19 37 02" src="https://user-images.githubusercontent.com/23120503/92621166-882f2100-f2d4-11ea-9b38-893d3f6167c1.png">

Here is the code from which the error originates, within Alpin js code.

<img width="822" alt="Screenshot 2020-09-09 at 19 37 34" src="https://user-images.githubusercontent.com/23120503/92621356-c4fb1800-f2d4-11ea-8f47-4dab7cf3fe77.png">

Here is how it looks in the elements panel:

<img width="844" alt="Screenshot 2020-09-09 at 19 44 51" src="https://user-images.githubusercontent.com/23120503/92621581-07245980-f2d5-11ea-853e-14d61bd2b493.png">

Thank you!

**Comment by calebporzio** [comment]
Hey @VahanDrnoyan, would you mind re-posting this on the github.com/livewire/livewire repository? I think it's better suited for that repo - thanks!
