### ISSUE TITLE
using alpinejs in 'gridsome build' "Could not generate HTML for" "ReferenceError: navigator is not defined" errors thus static files are not generated at all.

### ISSUE THREAD

**Issue by roiji** [alpinejs/alpine#764]
Hi!

I am creating a static website using Gridsome, TailwindCSS, and @gridsome/source-wordpress.
I was implementing [this navigation component](https://tailwindcomponents.com/component/responsive-navbar-with-dropdown) but instead of using the CDN, I opted to use npm and import alpinejs on the template.

In `src/templates/Default.vue`:
```
<script>
import 'alpinejs';

export default {
	...
}
</script>
```

When I run `gridsome develop`, the site is loading well and I didn't have any problem with my web development, but when I finally did run the `gridsome build` command to generate the static files (for uploading to my server) that's when the error arise.

```
Could not generate HTML for "/404/":
ReferenceError: navigator is not defined
    at isTesting (node_modules/alpinejs/dist/alpine.js:71:0)
    at assets/js/app.ae4080bd.js:2465:8
    at assets/js/app.ae4080bd.js:592:28
    at Object.3yRE (node_modules/alpinejs/dist/alpine.js:5:1)
    at Module.O/VM (assets/js/app.ae4080bd.js:4270:14)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.0 (assets/js/app.ae4080bd.js:263:18)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at assets/js/app.ae4080bd.js:118:18
```
This 404 page did not exist before so I created it. But even after creating the page, I still got the error.

Opening the file `alpine.js`, VSCode points me to this function:
```
  function isTesting() {
    return navigator.userAgent.includes("Node.js") || navigator.userAgent.includes("jsdom");
  }
```

My solution is to use the CDN for the meantime :(
```
export default {
	metaInfo: {
		link: [
		script: [
			{
				src: 'https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js',
				defer: true
			}
		],
	}
}
</script>
```

**Comment by SimoTod** [comment]
Alpine cannot execute server side since it relies on some browser APIs. It looks like gridsome is trying to process the page on the server running your js which will trigger that error. It doesn't look like an Alpine issue, I'm not familiar with the tool but you ahould look at their documentation to understand how to include scripts without processing them during the build phase.

**Comment by HugoDF** [comment]
I don't think using Alpine with Vue/React/other JS frameworks that provide reactivity/declarative templating is explicitly supported.

Like Simone said, you'll need to find a way to tell Gridsome not to run the Alpine.js import during server/static rendering.

It also seems like you have a workaround so I'll be closing the issue unless you have any further questions

**Comment by dubcanada** [comment]
While I agree that support is off the table, I do think that in this particular case the `isTesting` method can be updated to include a check for window.

If this is the only instance of it.

**Comment by calebporzio** [comment]
Thanks for helping on this @HugoDF and @SimoTod. Your responses are perfect. Closing this.
