### ISSUE TITLE
x-init called 3 times

### ISSUE THREAD

**Issue by georgeboot** [alpinejs/alpine#774]
I use Apine 2.7.0 together with LiveWire 2.2.3

When I run my component, the `init` function is called 3 times. The first 2 times it errors with the following error:
`Uncaught TypeError: can't access property "on", this.$wire is undefined`.

The 3rd time however, it succeeds.

This seems incorrect.

1. Why isn't `$wire` availalble in the first place?
2. Why does it "retry" the call 2 times?

```blade
<main>
    <div wire:ignore>
        <div x-data="resultsChart()" x-init="init"></div>
    </div>
</main>

@push('scripts')
<script>
    function resultsChart() {
        return {
            chart: null,
            init() {
                console.log('this line shows up 3 times');

                this.$wire.on('update', () => {
                    this.update()
                })

                console.log('this line only shows up once');
                
                this.chart = new ApexCharts(this.$el, {
                    // .. some more chart options

                    series: [
                        {
                            data: this.$wire.results,
                        }
                    ],
                })
                
                this.chart.render()
            },
            update() {
                this.chart.updateSeries([
                    {
                        data: this.$wire.results,
                    }
                ])
            }
        }
    }
</script>
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
@endpush
```

**Comment by georgeboot** [comment]
Turns out you need to load the Livewire script **before** you load alpine.

This is because the Livewire scripts, include this:

```js
/* Make Alpine wait until Livewire is finished rendering to do its thing. */
window.deferLoadingAlpine = function (callback) {
    window.addEventListener('livewire:load', function () {
        callback();
    });
};
```

If Alpine is already loaded at that stage, it won't work. It only works when Alpine is loaded after this script is executed.

**Comment by ryangjchandler** [comment]
@georgeboot - are you loading Alpine at the end of the `<body>` tag or in the `<head>` using the `defer` attribute?

**Comment by georgeboot** [comment]
@ryangjchandler I was loading alpine at the end of the `body` without defer, but **before** loading Livewire. That turns out to be crucial.

**Comment by ryangjchandler** [comment]
> @ryangjchandler I was loading alpine at the end of the `body` without defer, but **before** loading Livewire. That turns out to be crucial.

Yeah, Livewire needs to hook into Alpine before hand. If you didn't want to put it at the end of the `<body>` you could move it into the `<head>`, as the Alpine documentation suggests.

**Comment by georgeboot** [comment]
We have some more dependencies in the `app.js` we compile, so that won't work. Could split them up I guess but this also works now :)

**Comment by ryangjchandler** [comment]
> We have some more dependencies in the `app.js` we compile, so that won't work. Could split them up I guess but this also works now :)

Yeah, no worries. Glad you got it sorted - that's probably something that needs to be added to the Livewire docs if it hasn't been already /cc @calebporzio

**Comment by calebporzio** [comment]
@georgeboot, would love a PR to the docs for this
