### ISSUE TITLE
Templates? Custom tags?

### ISSUE THREAD

**Issue by aolko** [alpinejs/alpine#78]
Can you implement a support for templates and custom tags similar to [this](https://github.com/riot/examples/tree/gh-pages/todo-app)?

**Comment by ryangjchandler** [comment]
Alpine isn't intended for this. Alpine is designed to work with your existing markup, using a Vue-like syntax. Adding templates requires some sort of compiled / transpiler and heavier bundles.

**Comment by the94air** [comment]
Alpine would be a life for us. This won't save us any problems more than it will generate. In Vue for example, at the end of the day you will find your self dealing with xMB bundles. Then, you try to solve the issue by using a static site generator For SSR and code splitting or worst, a custom back-end implementation for SSR. Then you use nodejs with PHP for SSR which doesn't make sense at all. We shouldn't do the same mistake over and over. Let's get back to Regular DOM for the sense of our minds.

**Comment by ryangjchandler** [comment]
> Alpine would be a life saver for us. This won't save us any problems more than it will generate. In Vue for example, at the end of the day you will find yourself dealing with xMB bundles. Then, you try to solve the issue by using a static site generator for SSR and code splitting or worst, a custom back-end implementation for SSR. Then you use nodejs with PHP for SSR which doesn't make sense at all. We shouldn't do the same mistake over and over. Let's get back to Regular DOM for the sense of our minds.

💯. Keep your DOM, forget the VDOM. Everyone's lives are so much easier!

**Comment by aolko** [comment]
> > Alpine would be a life saver for us. This won't save us any problems more than it will generate. In Vue for example, at the end of the day you will find yourself dealing with xMB bundles. Then, you try to solve the issue by using a static site generator for SSR and code splitting or worst, a custom back-end implementation for SSR. Then you use nodejs with PHP for SSR which doesn't make sense at all. We shouldn't do the same mistake over and over. Let's get back to Regular DOM for the sense of our minds.
> 
> 💯. Keep your DOM, forget the VDOM. Everyone's lives are so much easier!

Well then, i invite you to visit any other big website/webapp (like youtube) and look at it's source. It's easier to roll your own components, rather then stumble through ids and classes.

**Comment by coderofsalvation** [comment]
Why not get creative with importing templates and modules? 
This whole build-your-components was partially born out of a lack of these:

https://www.html5rocks.com/en/tutorials/webcomponents/imports/

**Comment by 99bits** [comment]
> I think alpinejs + grapesjs snippets could just solve all this. Worstcase, you could get creative with importing templates and modules. Does alpinejs work with template-tags?
> 
> https://www.html5rocks.com/en/tutorials/webcomponents/imports/

@coderofsalvation can you explain more about how AlpineJs and GrapeJs is working together.  Cheers
