### ISSUE TITLE
@click is not working in another x-data

### ISSUE THREAD

**Issue by imran-itmajlis** [alpinejs/alpine#786]
![image](https://user-images.githubusercontent.com/68069779/93794635-f3261380-fc55-11ea-98a6-add0b13c7f3a.png)

**Comment by SimoTod** [comment]
showForm doesn't exist in x-data

**Comment by imran-itmajlis** [comment]
> showForm doesn't exist in x-data

it is there in Parent Div

![image](https://user-images.githubusercontent.com/68069779/93857009-8bb0a800-fcd7-11ea-9e8b-6f486da13e61.png)

as I highlighted the Add New and List Record Buttons they are Working But inside of Another x-data showForm is Not Working

**Comment by SimoTod** [comment]
Alpine components don't have access to the parent scope.
There is a long conversation here if you need more details: https://github.com/alpinejs/alpine/issues/49

It was never implemented in core but there are alternative:
- You can use events to communicate between components (You can find many examples in old tickets and discussions)
- You can use Spruce to menage shared states (https://github.com/ryangjchandler/spruce)
- For simple cases, You can use the $parent helper from https://github.com/alpine-collective/alpine-magic-helpers

For your specific case, maybe the third option is the easiest one

**Comment by imran-itmajlis** [comment]
> Alpine components don't have access to the parent scope.
> There is a long conversation here if you need more details: #49
> 
> It was never implemented in core but there are alternatives:
> 
> * You can use events to communicate between components (You can find many examples in old tickets and discussions)
> * You can use Spruce to menage shared states (https://github.com/ryangjchandler/spruce)
> * For simple cases, You can use the $parent helper from https://github.com/alpine-collective/alpine-magic-helpers
> 
> For your specific case, maybe the third option is the easiest one

Thanks for your guidance and support
