### ISSUE TITLE
x-show not working in conjunction with flex

### ISSUE THREAD

**Issue by cgrisar** [alpinejs/alpine#791]
Suggesting to change the style attribute to

display:none !important

Without the !important flag, situations occur when the content is displayed, even when condition is falsy

**Comment by SimoTod** [comment]
Setting `!important` is a bad practice, especially in a third party library, because it breaks the natural order of CSS rules.
Do you have an example where it does not work?

**Comment by cgrisar** [comment]
OK, it seems tailwind proposes important as standard.
One has to set important to false when building the framework

**Comment by ryangjchandler** [comment]
> OK, it seems tailwind proposes important as standard.
> One has to set important to false when building the framework.
> 
> x-show works if that important flag is set to false

That's not actually true. By default, Tailwind won't use `!important` with utility classes, please see here: https://tailwindcss.com/docs/configuration#important

**Comment by stefanfisk** [comment]
Had there been any thoughts about using a property instead of inline styles, like for `x-cloak`? That would allow customizations for weird setups like when using `!important`.

**Comment by camillo777** [comment]
Same here with Bulma CSS... if I put "is-flex" class, the div is not hidden

**Comment by HugoDF** [comment]
Could you share the `is-flex` CSS?

It's always been my understanding that inline-styles have higher precedence styles from a CSS file

**Comment by KevinBatdorf** [comment]
> It's always been my understanding that inline-styles have higher precedence styles from a CSS file

@HugoDF That is the case, unless you use `!important`, which Bulma uses:

```css
.is-flex {
  display: flex !important;
}
```

**Comment by HugoDF** [comment]
I mean the workarounds would be:

- toggle the `is-flex` class along with using `x-show`
- bind `style` directly and `display: none!important`

**Comment by mccarlosen** [comment]
I solved it using a parent element:

```html
<div x-show="!files.length">
    <div class="is-flex is-justify-content-center">
        <p class="help has-text-grey">Not found</p>
   </div>
</div>
```

**Comment by KondorB** [comment]
I also think that `!important` on the `display: none` toggled by `x-show`  is, well, important. At least there should be an option to add it. Specifically to avoid gross workarounds with Tailwind - it uses `!important` on utility classes to override base styles, third-party styles and Tailwind's extracted components styling.

**Comment by cgrisar** [comment]
you can deactivate the !important setting in tailwind

**Comment by stefanfisk** [comment]
`important: true` is not the default, but there are quite a few people out here who need it enabled for whatever reasons.

**Comment by KondorB** [comment]
> you can deactivate the !important setting in tailwind
> […](#)

It is even disabled by default. It is quite useful though, that's why it's often enabled in projects.

**Comment by KondorB** [comment]
Right now the most elegant workaround, in case anybody is facing the same issue with Alpine and Tailwind goes something like this:

```
x-bind:class="{'inline-flex': !show, 'hidden': show}"
```

**Comment by jcasanova** [comment]
I don't see any downside, as the x-show directive should have the final word regarding display (none) of the element. And this is the only style rule affected by the directive.

@calebporzio what's your status re:v3, is it something you plan to release in a few weeks or more like end of the year ?

**Comment by stefanfisk** [comment]
Personally I'd much prefer the option of using a property or class for applying the `display: none`, just like how I need to supply the styles for `x-cloak`.

**Comment by calebporzio** [comment]
@jcasanova , thanks for the input. In a few weeks!
