### ISSUE TITLE
x-if not working with select 2

### ISSUE THREAD

**Issue by vahidalvandi** [alpinejs/alpine#794]
```
    <templete x-show="receiver_type === 'team'" class="col-md-3 col-12">
                            <div class="form-group">
                                <label for="team">نام تیم</label>
                                <select name="team_id" style="width: 100%" id="js-data-team-ajax"></select>
                            </div>
                        </templete>
```
but work fine with x-show

**Comment by SimoTod** [comment]
Template is misspelled + you still use x-show but I believe you just typed it wrong in the ticket.
When do you run select2? If it's on domready, the div won't be in the page yet (stuff inside a template tag are not considered as active DOM by browsers) so it's not going to work.

**Comment by HugoDF** [comment]
I wrote a post about `select2` integration with Alpine.js if you're interested https://codewithhugo.com/alpinejs-jquery-plugin-integration-select2/

**Comment by calebporzio** [comment]
Thanks for posting @HugoDF 

Please reference that @vahidalvandi !
