### ISSUE TITLE
It is possible to filter output data ?

### ISSUE THREAD

**Issue by shankhadevpadam** [alpinejs/alpine#803]
Is it possible to filter output data as vuejs in alpine js? I want to capitalize on the status data.

```
<strong x-text="status"></strong>
```

**Comment by SimoTod** [comment]
There isn't anything using a nice syntax but you can do
`x-text="status.charAt(0).toUpperCase() + status.slice(1)"`.

If you use it in multiple places, you can extract it to a helper function
```javascript
function capitalize(string) {
   return string.charAt(0).toUpperCase() + string.slice(1)
}
```
And use `x-text="capitalize(status)"`

**Comment by shankhadevpadam** [comment]
Thanks @SimoTod
