### ISSUE TITLE
Cannot uncheck checkboxes with pre-set values

### ISSUE THREAD

**Issue by mokhosh** [alpinejs/alpine#814]
First I thought it has to do with Livewire, but after a lot of head scratching I checked Alpine without Livewire and the problem is still there.

Created a pen to demonstrate the problem. As you can see unchecked checkboxes can be checked and unchecked, but the ones that are set on load cannot:

https://codepen.io/mokhosh/pen/rNLVmvq

**Comment by HugoDF** [comment]
The issue in your case is that the "value" is `"2", "3"` but in your array you've got `2, 3` (as numbers).

If you switch to `<div x-data="{ categories: ['2', '3'] }">` it fixes the issue.

See https://codepen.io/hugodf/pen/KKMpmBQ?editors=1111

However, there is probably an underlying bug here.

**Comment by SimoTod** [comment]
Alternatively, if you need to use integer, you also need to add the number modifier to x-model (which would also fox the pen) otherwise you will end up with mismatching items

**Comment by mokhosh** [comment]
Thank you guys so much.

> However, there might be an underlying bug here, since the checkboxes are being set to checked (despite the type mismatch) but they're not updating (due to the type mismatch). The initialisation & update of the checkboxes should probably behave consistently (either always care about types or never do).

@HugoDF Yes, that was the strange part.

**Comment by HugoDF** [comment]
> Thank you guys so much.
> 
> > However, there might be an underlying bug here, since the checkboxes are being set to checked (despite the type mismatch) but they're not updating (due to the type mismatch). The initialisation & update of the checkboxes should probably behave consistently (either always care about types or never do).
> 
> @HugoDF Yes, that was the strange part.

Created a PR to fix the inconsistency 😄

**Comment by mokhosh** [comment]
You guys are super awesome
