### ISSUE TITLE
X-init triggered multiple times?

### ISSUE THREAD

**Issue by sawirricardo** [alpinejs/alpine#817]
Hi, It's been a great experience using alpine. I have encountered an issue where i have this
`<section x-data="someData()" x-init="someInit()">`
`<!-- layout will be 2 grid -->`
    `<div> <!-- Some logic happening here  --></div>`
    `<div> <!-- some content with rendering  x-loop, x-if --></div>`
`</section>`

in my someInit(), i console.log('init') and what's happening is that it logs **multiple time** 'init'. I don't have any idea how can this happen.

However, when I put x-data and x-init 1 level down, like this
`<section>`
`<!-- layout will be 2 grid -->`
    `<div x-data="someData()" x-init="someInit()"> <!-- Some logic happening here  --></div>`
    `<div> <!-- some content with rendering  x-loop, x-if --></div>`
`</section>`

it only console.log once. (intended behaviour here).

How can this happen? or do you have any idea how to work around this? I put x-data in section in order to give access to second div to access the data.

Thank you.

**Comment by sawirricardo** [comment]
Hi, I have fixed it. I think, it is due to my structuring in x-for inside the div. You have to be careful with using x-show or x-if. and if you use div or template. if you fetch data, please watch if the data has been loaded or now. if x-show not working, use x-if.  I think the dom is quite messed up knowing the structure is quite complex here haha

**Comment by joshDamian** [comment]
In my case, in had to change my x-init function from 'init' to something else

**Comment by amiranagram** [comment]
> In my case, I had to change my x-init function from 'init' to something else

Don't know why it happens but this is the fix. Thanks @joshDamian.

**Comment by SimoTod** [comment]
> > In my case, I had to change my x-init function from 'init' to something else
> 
> Don't know why it happens but this is the fix. Thanks @joshDamian.

Functions called init are auto invoked in Alpine v3 (https://alpinejs.dev/directives/init#auto-evaluate-init-method). If you add x-init="init()", init will be called twice.

**Comment by amiranagram** [comment]
> > > In my case, I had to change my x-init function from 'init' to something else
> > 
> > 
> > Don't know why it happens but this is the fix. Thanks @joshDamian.
> 
> Functions called init are auto invoked in Alpine v3 (https://alpinejs.dev/directives/init#auto-evaluate-init-method). If you add x-init="init()", init will be called twice.

Oh, I missed this in the docs.

**Comment by pansani** [comment]
I was facing this same issue using x-for into a template. I went to the file where alpinejs was loaded, and saw that it had to `<script>` tags of alpinejs, by leaving only one, it loaded my metrics once.
