### ISSUE TITLE
IE11 x-for issue when using x-for within a select element

### ISSUE THREAD

**Issue by thomasgreen** [alpinejs/alpine#821]
I've been trying to get a `x-for` loop working to print out options in a select element, however, whenever I do so, I get the following console error in IE11 "'attributeValue is undefined'". In modern browsers, it works as expected. If I was to replace the select/options element with divs the `attributeValue` data works as expected in IE11, so I feel like this is somehow specific to the select element.

Basic CodePen of what I am trying to do: https://codepen.io/tomgreen_/pen/NWrGaPq

I have followed the documentation to add alpine to my project to support IE11:
```
<script type="module" src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"></script>
<script nomodule src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine-ie11.min.js" defer></script>
```

**Comment by SimoTod** [comment]
Your option tags don't have a value attribute. Modern browsers are probably more permissive but your html is not valid until Alpine kicks in. If you can't generate the select on the server, you can probably add an empty value attribute which should be replaced when Alpine kicks in. You probably need to manually handle the selected option if you need to preselect something.

**Comment by EyePulp** [comment]
@thomasgreen Howdy - I'm running into this same issue and I tried @SimoTod's fix, but continue to get `undefined` errors.

Were you able to work around this under IE11?
