### ISSUE TITLE
:class fails when the evaluated value is undefined

### ISSUE THREAD

**Issue by bbugh** [alpinejs/alpine#825]
Working on some validation code, sometimes the result of the `errorClass()` doesn't require a value, e.g. `is-valid` and `is-invalid` should only be shown when the field is dirty. It's possible to return an empty string, but it would be nice if alpine handled the `undefined` value rather than raising a `split` error.

It appears that the issue is here, which does not check if the value is present:

https://github.com/alpinejs/alpine/blob/999356ab53776caec8433eefccc96cde985c927d/src/utils.js#L180-L182

When `value` is not an object or array, I believe this code is called in `handleAttributeBindingDirective`:

https://github.com/alpinejs/alpine/blob/dd43c48223a1ad77b098ff470ac65bf159b7a0fe/src/directives/bind.js#L64-L66

I'm not sure what the repercussions of changing this are. It seems like the right thing to do is to fix 

I would submit a PR but this section of the code seems to be untested, and I'm not sure of the implications to change it. It seems like the right thing to do is change `convertClassStringToArray` to handle the non-`split`able value and return an empty array or undefined, not sure which.

**Comment by HugoDF** [comment]
@bbugh `class` binding is tested in the `bind` tests.

We could default to an empty string in the case of `class` alternatively we could point this out in the README.

Up to @calebporzio on what he prefers.

**Comment by calebporzio** [comment]
Yeah, I think defaulting to an empty string if undefined is the right move to make the .split work and not throw a fit.

**Comment by calebporzio** [comment]
Closing this - I'd welcome a PR

**Comment by bbugh** [comment]
I am attempting to PR this since it seems to be an easy fix, but for the life of me I cannot write a test that fails with the `split` error.  Jest is consuming all `console.log` and `throw`s in every configuration I've tried so I'm not seeing any way to test it accurately. Even adding a `throw` to `start()` doesn't fail.

```js
test.only('undefined class binding is ignored', async () => {
    document.body.innerHTML = `
        <div x-data="{ errorClass: (hasError) => { if (hasError) { return 'red' } } }">
            <span id="error" x-bind:class="errorClass(true)">should be red</span>
            <span id="empty" x-bind:class="errorClass(false)">should be empty</span>
        </div>
    `
    // // Without the fix, this should throw error about slice here, but doesn't
    Alpine.start()

    // // Also does not throw
    // expect(() => { Alpine.start() }).toThrow()
        
    // Also does not throw
    // expect(Alpine.start).toThrow()

    // Also does not throw
    // expect(() => {
    //     Alpine.start()
    
    //     expect(document.querySelector('#error').classList.value).toEqual('red')
    //     expect(document.querySelector('#empty').classList.value).toEqual('')
    // }).toThrow()

    // This test technically fails, but not in the expected way with an Error
    expect(document.querySelector('#error').classList.value).toEqual('red')
    expect(document.querySelector('#empty').classList.value).toEqual('')
})
```

I confirmed that this reproduces the error in CodeSandbox (shows up in the main window browser console, not the codesandbox console): https://codesandbox.io/s/bold-bird-qklky?file=/index.html:185-463

Is the test configuration set up some how not to catch errors? It seems like there could be other secretly failing tests if this is the case.

**Comment by SimoTod** [comment]
`start()` is an async function so you can't check if an exception is thrown in that way (see https://github.com/facebook/jest/issues/1377 and https://jestjs.io/docs/en/asynchronous).

What you need is something like
```javascript
test('undefined class binding resolves to empty string', async () => {
    document.body.innerHTML = `
        <div x-data="{ errorClass: (hasError) => { if (hasError) { return 'red' } } }">
            <span id="error" x-bind:class="errorClass(true)">should be red</span>
            <span id="empty" x-bind:class="errorClass(false)">should be empty</span>
        </div>
    `

    // Test that Alpine.start resolves correctly (If an error is thrown, the promise will be rejected)
    await expect(Alpine.start()).resolves.toBeUndefined() //<-- because start doesn't return anything

    expect(document.querySelector('#error').classList.value).toEqual('red')
    expect(document.querySelector('#empty').classList.value).toEqual('')
})
```

**Comment by bbugh** [comment]
@SimoTod thanks! Unfortunately, that also does not result in an error, but it should, based on the reproduction in the code sandbox. 

```
 PASS  test/bind.spec.js
  ✓ undefined class binding resolves to empty string (24ms)
```

<img width="636" alt="Pasted_Image_10_25_20__7_32_AM" src="https://user-images.githubusercontent.com/438465/97107194-4ac00080-1694-11eb-94b1-dd25760dad32.png">

```
commit 56443ea715afcb0139b46f9de14a9432a952300e (HEAD -> master, tag: v2.7.2, origin/master, origin/HEAD)
Author: Caleb Porzio <calebporzio@gmail.com>
Date:   Thu Oct 22 10:50:24 2020 -0400

    Publish 2.7.2
```

**Comment by SimoTod** [comment]
Yeah, I wrote something like because it wasn't the final implementation since I was typing from mobile and I didn't test it. 
You also need to take into account that errors are deferred in Alpine (see https://github.com/alpinejs/alpine/blob/master/src/index.js#L95).
The easiest way for me would be to make setTimeout sync in your test -> https://github.com/SimoTod/alpine/runs/1305125541?check_suite_focus=true

**Comment by bbugh** [comment]
Ah ha! I did not see the `setTimeout` deferment when I was digging through the code. It makes sense why I couldn't find the error. At first I thought I was going crazy, like did I forget how to write tests?! 🤪

I made https://github.com/alpinejs/alpine/pull/847 for this.
