### ISSUE TITLE
AlpineJS components not reinitalised after Morphdom

### ISSUE THREAD

**Issue by acetinick** [alpinejs/alpine#826]
I am using [Stimulus Reflex](https://github.com/hopsoft/stimulus_reflex), which is a Rails library similar to LiveView to create reactive screens by replacing the DOM over websockets using Morphdom library.

For all components that are contained within the HTML injected by SR,  the components are not getting picked up by AlpineJS for initialisation.

Stimulus Reflex provides an afterReflex javascript callback, and I am putting this line as referenced in https://github.com/alpinejs/alpine/issues/282 without success.  

```
afterReflex(element, reflex) {
        Alpine.discoverUninitializedComponents(function(el){ Alpine.initializeComponent(el) })
    }
```

Any ideas of what I am missing here that I could add to the afterReflex() method to help pick up dynamically inserted components?

---- 

UPDATE: 

Issue is related to morphdom which is what [Stimulus Reflex](https://github.com/hopsoft/stimulus_reflex) uses under the covers to replace HTML over websockets.

Here is a codepen to replace the issue just with Alpine JS and morphdom 
https://codepen.io/acetinic/pen/mdELYZW

**Comment by SimoTod** [comment]
I've never used stimulus reflex so I don't know what gets passed into the callback but it look like you called the parameter element and inside the callback you use el which doesn't exist. Try to change el to element

**Comment by acetinick** [comment]
Yea the element parameter is the element that triggered the reflex,  so not related to the new componenets that we trying to reinitialise.

The closest I have got is putting this in morphdom's **onBeforeElUpdated** event method,  but for some reason it doesn't reintialise all components,  just most of them.

`   if (fromEl.__x) {
        window.Alpine.clone(fromEl.__x, toEl)
    }`

**Comment by SimoTod** [comment]
Sorry, I've just woken up and I didn't read the code of your first question properly. Looking at their documentation it should work (you need the second snippet to keep the states of components that were already initialised).
Maybe put a console log in the first snippet and check that:
- it's called
- it can access the Alpine object

Also, if you manually trigger Alpine.discoverEtcEtc from the console, does it work or do you get errors?

**Comment by acetinick** [comment]
Well in this method, I add the following code and I get no console output, not sure why.

![image](https://user-images.githubusercontent.com/571649/96090650-35e3b000-0ed1-11eb-86bf-35cfa2d827d3.png)

**Comment by HugoDF** [comment]
Hey @acetinick have you managed to get to the bottom of this issue?

Any more info you can provide us?

**Comment by acetinick** [comment]
Hi @HugoDF ,

I have managed to replicate the issue here in a code pen https://codepen.io/acetinic/pen/mdELYZW

You can see in example that after clicking the 'morph' button, it replaces the content with a similar AlpineJS controller, but it doesn't intialise properly until you press the "ACTION" button.

The issue is directly related to using morphdom together with AlpineJS, and the content that gets replaced by morphdom.    I have updated the title, and description to be more specific.

**Comment by dkln** [comment]
Is this somewhat related to #756 ?

**Comment by juddkirby** [comment]
Hi all, hoping I can help close this issue off.

The solution for this issue - and any time morphdom is used to update an AlpineJS-aware DOM element - is to copy the alpine state from the old element to the new element in the **onBeforeElUpdated** hook provided by the morphdom API.

I've forked the codepen above, and added the implementation to the morphdom call.  You can see the state of the element is [retained post-morph](https://codepen.io/juddkirby/pen/YzGvXzN). 

The exact implementation of this differs per framework/library, depending on it's interface with morphdom but for CableReady/StimulusReflex specifically, an example for AlpineJS is included at the end of the [shouldMorph](https://cableready.stimulusreflex.com/customization#shouldmorph-callbacks) section in the docs.

@HugoDF Given that StimulusReflex/CableReady now provide official documentation on how to support AlpineJS, I think that this specific issue is closable.  @acetinick does this sound fair to you?

I think it would be worthwhile to add some docs into Alpine on integration with StimulusReflex, and other libraries, to assist users of this library to find the info they need.  I'd like to help by creating that, but that can be a separate issue.

@dkln the issues are related, but the use of Alpine.clone completely solves our problem here, so I don't think there's anything in this issue that will help on #756
