### ISSUE TITLE
Mistake in x-for documentation?

### ISSUE THREAD

**Issue by seb-jones** [alpinejs/alpine#830]
In the README under  [x-for](https://github.com/alpinejs/alpine#x-for) it says:

> Note: x-for must have a single element root inside of the `<template></template>` tag.

However right above that it has an example that has multiple div tags immediately within the template tag:

```html
<template x-for="(item, index, collection) in items" :key="index">
    <!-- You can also reference "collection" inside the iteration if you need. -->
    <!-- Current item. -->
    <div x-text="item"></div>
    <!-- Same as above. -->
    <div x-text="collection[index]"></div>
    <!-- Previous item. -->
    <div x-text="collection[index - 1]"></div>
</template>
```

Am I understanding the Note incorrectly or is this a mistake in the docs?

Thanks

Seb

**Comment by SimoTod** [comment]
Yeah, it shows 3 different ways of doing the same thing. You would just pick one depending on your use case.

**Comment by seb-jones** [comment]
Ahh okay, thanks. for clarifying.

**Comment by janlucaklees** [comment]
I just copied said code and couldn't get it to work. It was really frustrating. So here I am searching and finding this issue.

I would hate it to stay like this. The note barely catches your attention as grey as it is. And usually, example code is workable - just as the other examples in the README are.

I would like to see a wrapping `div` added, in the example, with a comment restating what is already said in the note below. If that is fine, I would go ahead and make a PR out of that.
