### ISSUE TITLE
Alpine update detection with Spruce / arbitrary functions

### ISSUE THREAD

**Issue by chapmanjacobd** [alpinejs/alpine#831]
I have a weird issue and I'm not really sure of the cause. 

On this page I can correctly search and alpine detects the new data and refreshes 

:heavy_check_mark:  https://unli.xyz/m/neighborhoods/neighborhoods.html

but on this page it does not automatically refresh and you have to insert/delete a character in the searchbox to have alpine refresh 

:x: https://unli.xyz/m/neighborhoods/compare.html

I will update this with a minimal example in a few hours if nothing stands out

**Comment by SimoTod** [comment]
The component reactivity in alpine is triggered by changes in component data (what you set in x-data).
Your x-data contains `{ items: [], filterString: "", s: {} };`.
The first example does an ajax call and pushes some of the results into `items`, triggering the reactivity.
The second example pushes some of the results to a different variable outside x-data hence not reactive. 
`filterString` is defined in x-data so, after that point, when you add o remove a character, it will trigger the reactivity again.
It doesn't look like a bug to me.

**Comment by chapmanjacobd** [comment]
Thanks. That makes sense
