### ISSUE TITLE
Transition event listeners firing intermittently

### ISSUE THREAD

**Issue by TheMangoTrain** [alpinejs/alpine#832]
Hello,

I have a series of tabs and a drawer. As the user hovers the tabs, the drawer content changes. When content changes, or the drawer is opening for the first time, the content fades-and-animates from the top of the drawer. This only happens when the drawer has finished animating. Essentially, I listen for the drawer animation to finish, then I fully render the content.

Generally, it works.
**See code here:**
https://codepen.io/MarsAndBack/pen/VwjjGbe?editors=0010

---

**PROBLEM:** Sometimes the drawer appears empty on first-open. When this happens, it seems like event listeners are not being triggered; why? They work most of the time.

**REPRODUCE:** Click a tab (e.g. tab1) and then click the header whitespace. Do this over-and-over with the same tab. Eventually the drawer will open empty. It happens often enough; it's noticeable.

---

My feeling is events are not being transmitted reliably.

I feel like nextTick should be involved here somewhere?

Initially I had a regular JS event listener on the drawer, in the open() func:

```
         drawerAnim = document.getElementById(drawer)
         drawerAnim.addEventListener('transitionend', function doneAnim(event) {
            console.log('Drawer finished opening')
            animateContent()          
            drawerAnim.removeEventListener('transitionend', doneAnim)
         })
```

Then I discovered Alpine's `x-on:transitionend` and use it like so:
`          x-on:transitionend="animateContent()"`

In either case, the behaviour is the same: the `transitionend` event fires only most of the time. In previous web dev, it has always fired reliably for me.

A worst-case fix, I can fire the animateContent() early in the initial opening func, but then there's no animation occuring on first-open of the drawer. At least there's always content.

**On a side note:**
For swapping content in the already-open-drawer, I had to use a small delay for the animation to actually be visible. So strange?

```
//...
  } else {
    
    // Doesn't work: no visible animation, content is displayed right away
    animateContent()

    // Works: Adding a miniscule delay makes it so you can see the full animation. Why is this needed?
     setTimeout(() => { 
       animateContent()
     }, 1)

  }
//...
```

**Comment by calebporzio** [comment]
Hey @TheMangoTrain - the problem seems to not happen if I reproduce the steps you described with plenty of time in between (hover, wait, click, wait, click-away, wait, etc...)

This tells me the the firing of the event is reliable, but the timing is not.

My suspicion is this would be browser related and you may have to restructure the logic of your component to support this randomness.

That said, I'm closing this unless more people experience this or the problem can be further refined to where we know Alpine is the culprit.

Thanks!
