### ISSUE TITLE
Upload the file for the second time, other data in the form will be cleared

### ISSUE THREAD

**Issue by nfhh** [alpinejs/alpine#833]
Upload the file for the second time, other data in the form will be cleared

eg:
class Zoom extends Component
{
    use WithFileUploads;

    public $form = [
        'image' => '',
        // These below will be set to null when upload the file for the second time
        'width' => 295,
        'height' => 413,
        'upsize' => false,
        'mode' => ModeType::FIT,
        'format' => FormatType::JPG,
        'sharp' => 0,
        'compress' => 100,
    ];

![image](https://user-images.githubusercontent.com/30310521/96538755-dec44d80-12cb-11eb-803f-71f398ce59a2.png)

**Comment by HugoDF** [comment]
Could you share the Alpine.js code? 

Not sure PHP is able to demonstrate an Alpine bug.

**Comment by nfhh** [comment]
sorry, I tested,not a bug
