### ISSUE TITLE
Changing one property seems to refresh all bindings

### ISSUE THREAD

**Issue by lupinitylabs** [alpinejs/alpine#837]
I had a weird issue with AlpineJS where the value of an input was overwritten when an input action changes an unrelated property.

I had the following email input and span:

```html
<input type="email" x-ref="inputemail" name="email" x-model.debounce="email" @input="loginInvalid = false" required autofocus>
<span class="Form-error" x-show="loginInvalid" x-cloak>Your email or password is wrong. Please try again.</span>
```

If loginInvalid was true, the input event would set loginInvalid to false and hide the span. However, the changed value of the input would immediately be overwritten by AlpineJS with the old property, thus it seemed that the keypress was lost. As I found out that's because of the model debounce, which will refresh the email property after the loginInvalid variable is changed. Removing `.debounce` does the trick.

What I perceive as an issue here is that AlpineJS would even refresh the value of the input even though the email property did not change at all. Are all properties always being refreshed if one of them changes, even those who have not been changed at all? This seems like a waste of resources to me and could lead to all kinds of unexpected behavior imo?

**Comment by ryangjchandler** [comment]
Currently, Alpine doesn't do any dependency tracking like Vue does so when one data property changes, the entire component is refreshed / re-evaluated.

**Comment by lupinitylabs** [comment]
> Currently, Alpine doesn't do any dependency tracking like Vue does so when one data property changes, the entire component is refreshed / re-evaluated.

Gotcha. Is this a planned feature?

**Comment by ryangjchandler** [comment]
@lupinitylabs I can't speak for the project owner but I imagine this will be an optimisation made in a new major version of Alpine. The current reactivity core / library doesn't support dependency tracking so there would be quite a big shift in the core code.

**Comment by lupinitylabs** [comment]
Ok. Also one of the reasons I opted for Alpine is a small footprint. Bloating the code with features might take away this advantage. Anyways, maybe anyone finds a nifty slim solution for that.

I guess the issue can be closed.
