### ISSUE TITLE
[Feature Request] `x-enter` / `x-exit`

### ISSUE THREAD

**Issue by snellingio** [alpinejs/alpine#84]
Looking at adding an event for when a dom element enters the current viewport.

This can be done in one of two ways, 

1. InteractionObserver 
1. MutationObserver with listeners on `load`, `scroll`, & `resize`

The issue with InteractionObserver is that it [does not support IE 11](https://caniuse.com/#feat=intersectionobserver). The polyfill would most likely be several times the size of alpine altogether, even gzipped.

The issue with MutationObserver is that it requires a lot more code (more to maintain), and requires some sort of throttle (usually 100ms) to not thrash on every scroll pixel. You can see a couple of examples [here](https://github.com/camwiegert/in-view) and [here](https://github.com/russellgoldenberg/enter-view).

We could do something like `x-enter` / `x-exit` and we could implement the `once` feature as a future expansion. I'm not overly picky on this, and am fine with whatever syntax @calebporzio would prefer.

Ideally, I'd like to see it work similar to `x-on` where it, the JavaScript expression set as it's value is executed.

The correct answer here might be to not push this feature inside core. 

I'm going to start thinking about this a little bit more this week. If anyone would like to take a stab at it, go for it. I'll probably get more serious about it sometime next week. 

This feature is a blocker for me to entirely replace a custom JavaScript implementation, which I really would like to nuke into oblivion.

**Comment by snellingio** [comment]
I believe it would be much more performant to go the InteractionObserver route, but, it looks like I can get away with not implementing this as a new feature.

Instead, adding the same condition to the global `resize`, `load`, and `scroll` seems to fire correctly.

Rough working example:
```
<div id="id123" x-data="{}"
     @resize.window="{ inViewport(document.getElementById('id123')) ? true: false }"
     @load.window="{ inViewport(document.getElementById('id123')) ? true: false }"
     @scroll.window="{ inViewport(document.getElementById('id123')) ? true : false }">
    Test
</div>
```

See a codepen example here: [https://codepen.io/snellingio/pen/wvBxPoj](https://codepen.io/snellingio/pen/wvBxPoj)

I'm going to leave this open for another few days or to see if anyone has any feedback around this. I still believe it would be good to have a shortcut rather than this overly verbose condition. If there is interest, we can probably add a simple utility to the `./utils` folder, and then add a new directive of `x-viewport` or something.

**Comment by calebporzio** [comment]
Very cool little solution.

For now, I'd like to keep this out of the core, but I'll likely be adding a custom directives feature soon that should make it easy for you to create your own `x-enter` type thing.

Thanks for posting a solution to this, closing for now. Be on the lookout for that soon. Thanks @snellingio!
