### ISSUE TITLE
x-for not working with multiple x-show

### ISSUE THREAD

**Issue by MichaelDimmitt** [alpinejs/alpine#843]
## x-for not working with multiple x-show, <br/>state is destroyed after first show

version: 2.7.2
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.2/dist/alpine.min.js" ></script>

## Not working: <br/>first x-show wins irregardless of x-for index
```html
   <div x-data="{arr: ['bar', 'foo']}">
    <template x-for="(tab, index) in arr" :key="index">
      <div x-show="tab === 'foo'" x-text="'index: ' + index + ', Foo'"></div>
      <div x-show="tab === 'bar'" x-text="'index: ' + index + ', Bar'"></div>
    </template>    
  </div>
```
## Actual
```
index: 1, Foo
```
## Expected behavior:
```
index: 0, Bar
index: 1, Foo
```
## Not working: <br/>flipped x-show order in html<br/>first x-show wins irregardless of x-for index
```html
<div x-data="{arr: ['bar', 'foo']}">
    <template x-for="(tab, index) in arr" :key="index">
      <div x-show="tab === 'bar'" x-text="'index: ' + index + ', Bar'"></div>
      <div x-show="tab === 'foo'" x-text="'index: ' + index + ', Foo'"></div>
    </template>    
  </div>
```
## Actual
```
index: 0, Bar
```
## Expected behavior:
```
index: 0, Bar
index: 1, Foo
```
## Consequence, if no javascript is used<br/>display none style will not be applied:
```html
  <div x-data="{arr: ['bar', 'foo']}">
    <template x-for="(tab, index) in arr" :key="index">
      <div x-show="tab == 'foo'">Foo</div>
      <div x-show="tab == 'bar'">Bar</div>
    </template>    
  </div>
```
alpine.js:1864 Uncaught ReferenceError: tab is not defined
    at eval (eval at c (alpine.js:118), <anonymous>:3:36)
    at c (alpine.js:118)
    at pe.evaluateReturnExpression (alpine.js:1705)
    at alpine.js:1681
    at Array.forEach (<anonymous>)
    at pe.resolveBoundAttributes (alpine.js:1654)
    at pe.initializeElement (alpine.js:1581)
    at alpine.js:1565
    at alpine.js:1555
    at e (alpine.js:90)

## Actual
```
Foo
Bar
Bar
```
## Expected behavior:
```
Bar
Foo
```

Happy to add clarity,
This took a bit of investigation to understand what was actually occuring in the dom.

**Comment by HugoDF** [comment]
I believe your issue is that Alpine doesn't allow multiple child Nodes in `template`

```
​<​div​ ​x-data​="​{arr: ['bar', 'foo']}​"​>​
    ​<​template​ ​x-for​="​(tab, index) in arr​" ​:key​="​index​"​>​
      <div>
        ​<​div​ ​x-show​="​tab === 'foo'​" ​x-text​="​'index: ' + index + ', Foo'​"​>​</​div​>​
        ​<​div​ ​x-show​="​tab === 'bar'​" ​x-text​="​'index: ' + index + ', Bar'​"​>​</​div​>​
      </div>
    ​</​template​>​    
  ​</​div​>
```

**Comment by MichaelDimmitt** [comment]
@HugoDF , thank you this was the solution

```html
<div x-data="{arr: ['bar', 'foo']}">
  <template x-for="(tab, index) in arr" :key="index">
    <div>
      <div x-show="tab === 'bar'" x-text="'index: ' + index + ', Bar'"></div>
      <div x-show="tab === 'foo'" x-text="'index: ' + index + ', Foo'"></div>
    </div>
  </template>    
</div>
```
