### ISSUE TITLE
I look at it. Does it work with x-show? I see examples of using x-text only. I tried the $component like the example below, it did not work. Does the reference parent need not be wrapped around the children? I will appreciate your help. Thanks

### ISSUE THREAD

**Issue by yanlenner** [alpinejs/alpine#845]
I look at it. Does it work with x-show? I see examples of using x-text only. I tried the $component like the example below, it did not work. Does the reference parent need not be wrapped around the children? I will appreciate your help. Thanks
```
<div class="showpackages" x-data="{showAddonPackages:false}" id="showAddonPackagesID">
       <div x-data='{showSingleOrDouble: false}'>
                 <div>
                  <input type="radio" name="test" @click="showSingleOrDouble = false"> Single Arch Case
                    <input type="radio" name="test" @click="showSingleOrDouble = true"> Double Arch Case
                 </div>
                  <div x-show="!showSingleOrDouble">   
                        <input type="radio" name="package_type" value="1601.50" @click="$component('showAddonPackagesID').showAddonPackages = true">
                        <input type="radio" name="package_type" value="1751.50" @click="$component('showAddonPackagesID').showAddonPackages = false">
                    </div>
                <div x-show=showSingleOrDouble>               
                        <input type="radio" name="package_type" value="3,203" @click="$component('showAddonPackagesID').showAddonPackages = true"> 
                        <input type="radio" name="package_type" value="3681.00" @click="$component('showAddonPackagesID').showAddonPackages = false">
                    </div>
       </div>

// This is the div I want to show
        <div x-show="showAddonPackages">
                  ....items to show
         </div>
</div>
```

_Originally posted by @ApetweBc in https://github.com/alpinejs/alpine/discussions/740#discussioncomment-59683_

**Comment by KevinBatdorf** [comment]
@yanlenner You opened an issue with someone else's discussion comment but I think maybe forgot to add your own comments?

Alpine scopes all data to the component it's nested in, so if you add `x-data` inside another component, the parent won't be accessible anymore. The code in your comment (using `$component()` helper) however, works but isn't a part of Alpine core. 

If you need help using `$component()` then it's probably better to open an issue on the repo where that code is hosted: https://github.com/alpine-collective/alpine-magic-helpers#component
