### ISSUE TITLE
Checkbox x-model values are duplicated if node is moved in the DOM

### ISSUE THREAD

**Issue by aaronjpitts** [alpinejs/alpine#852]
I am creating a set of responsive search filters, which requires moving a form to a different DOM node (but all within the same Alpine.js component. I've noticed that doing this causes Alpine to keep duplicating the results for each checkbox. I've made a simple codepen which clearly demonstrates the problem: https://codepen.io/aaronjpitts/pen/yLJbKyR

If you toggle the check boxes and resize the window to below 768px (so the form moves to the mobile container) you will see toggling a checkbox will show it twice, it seems every time the DOM node containing the x-models is moved, it will keep duplicating the values in memory.

Many thanks in advance and please let me know if there is a better way to move the DOM nodes which can avoid this bug 👍 
Keep up the great work!

Best,
Aaron

**Comment by HugoDF** [comment]
@aaronjpitts In this case I think Alpine.js is working as designed, any reason you're not just showing/hiding the relevant divs based on the breakpoint?

I've forked your code to the following and it seems to work without a hitch https://codepen.io/hugodf/pen/dyXeLZg.

What I'm getting at is that when using Alpine, you're supposed to lean on the directives instead of manipulating the DOM directly (if possible), hopefull my fork of your codepen shows you a way to achieve what you were doing in your original without using direct DOM manipulation.

**Comment by HugoDF** [comment]
Just for extra context during my investigation. On every "resize", you get one more instance of the checkbox/the value gets duplicated onces more, so instead of `classic` the value is `classic,classic` (on first resize), `classic,classic,classic` (on 2nd resize) and so on.

**Comment by aaronjpitts** [comment]
Hi @HugoDF, Thank you for taking the time to answer. Yes, with my version, on every resize which move's the DOM's element the values get duplicated. I just did it my way to only have to have one version of the markup, not a separate mobile and desktop set of checkboxes.

**Comment by HugoDF** [comment]
> Hi @HugoDF, Thank you for taking the time to answer. Yes, with my version, on every resize which move's the DOM's element the values get duplicated. I just did it my way to only have to have one version of the markup, not a separate mobile and desktop set of checkboxes.

If you have to do it this way, you could try using `x-html` instead of doing manual DOM manipulation which ends up confusing Alpine

**Comment by aaronjpitts** [comment]
HI @HugoDF, how would you use `x-html `to responsively move an element in the DOM? As far as I can see, x-html is just `innerHTML` and that won't actually move a DOM element. Please correct me if I"m wrong.

Thank you for your help so far.

**Comment by HugoDF** [comment]
You can use `x-html` to conditionally render the HTML in the mobile or desktop container.

I'm not sure why you're so interested in moving the DOM elements, when you do that it causes issues for Alpine.

Using imperative DOM manipulations is not strictly supported by Alpine, if you want to investigate further and create a PR, you can see if @calebporzio accepts it but as far as I'm concerned there's nothing to fix here (considering the available workaround)

**Comment by aaronjpitts** [comment]
I think I've been overcomplicating it trying to just use one DOM element. I'll stick to using the Alpine directives and maintain a separate mobile and desktop elements like you suggested. So I'll close this as there is no issue.

Thank you very much for your time, Hugo!

**Comment by HugoDF** [comment]
Cool thanks @aaronjpitts
