### ISSUE TITLE
SyntaxError: Unexpected token ';'

### ISSUE THREAD

**Issue by joelparkerhenderson** [alpinejs/alpine#855]
I'm using Alpine, and for the first time I'm trying it via webpack and node, yet get this error:

```sh
   webpack-internal:///./node_modules/alpinejs/dist/alpine.js 113:11 Uncaught SyntaxError: Unexpected token ';'
```

Package lock seems to be current:

```
"resolved": "https://registry.npmjs.org/alpinejs/-/alpinejs-2.7.3.tgz",
```

What I'm learning is that this may be a babel related issue, and/or an issue with something incorrectly loading alpinejs as an HTML file rather than as a JavaScript file.

The HTML head includes a typical script tag:

```html
<script defer type="text/javascript" src="/js/app.js"></script>
```

The relevant web page does actually load in a typical browser.

In case it's relevant, I'm using Alpine in a typical new Elixir Phoenix project, using the typical default webpack.config:

```js
const path = require('path');
const glob = require('glob');
const HardSourceWebpackPlugin = require('hard-source-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const TerserPlugin = require('terser-webpack-plugin');
const OptimizeCSSAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = (env, options) => {
  const devMode = options.mode !== 'production';

  return {
    optimization: {
      minimizer: [
        new TerserPlugin({ cache: true, parallel: true, sourceMap: devMode }),
        new OptimizeCSSAssetsPlugin({})
      ]
    },
    entry: {
      'app': glob.sync('./vendor/**/*.js').concat(['./js/app.js'])
    },
    output: {
      filename: '[name].js',
      path: path.resolve(__dirname, '../priv/static/js'),
      publicPath: '/js/'
    },
    devtool: devMode ? 'eval-cheap-module-source-map' : undefined,
    module: {
      rules: [
        {
          test: /\.js$/,
          exclude: /node_modules/,
          use: {
            loader: 'babel-loader'
          }
        },
        {
          test: /\.[s]?css$/,
          use: [
            MiniCssExtractPlugin.loader,
            'css-loader',
            'sass-loader',
          ],
        },
        {
          test: /\.(eot|otf|ttf|woff|woff2)$/,
          use: [
            {
              loader: 'file-loader',
              options: { 
                name: '[name].[ext]', 
                outputPath: '../fonts' 
              }
            },
          ],
        }
      ]
    },
    plugins: [
      new MiniCssExtractPlugin({ filename: '../css/app.css' }),
      new CopyWebpackPlugin([{ from: 'static/', to: '../' }])
    ]
    .concat(devMode ? [new HardSourceWebpackPlugin()] : [])
  }
};
```

Guidance much appreciated, thank you!

**Comment by HugoDF** [comment]
Hey @joelparkerhenderson have you got a minimum reproduction case repository you can share?

It's going to be very difficult to debug a build issue without the full build config code.

**Comment by joelparkerhenderson** [comment]
Yes thank you. Here's loading via a script tag, rather than via npm, webpack, etc.:

```html
<body>
        <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.3/dist/alpine.min.js" defer></script>
```

The error message is:

```sh
https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.3/dist/alpine.min.js 6:1783 Uncaught SyntaxError: Unexpected token ';'
```

**Comment by SimoTod** [comment]
That error suggests you have a typo in your markup, can you post the component?

**Comment by joelparkerhenderson** [comment]
Yes thank you and I'll simplify it. 

Is it accurate that errors above are potentially because the page HTML/JS has problems that are due to me, rather than the errors above being because of Alpine itself?

Perhaps another way to ask the same question using another perspective, is Alpine HTML/JS doing some kind of processing akin to a "eval" inside of the Alpine script, such that what I wrote on the page would be causing the errors to seem to be coming from inside of Alpine?

If so, Is there a recommended way that I can process my page, such as a linter or preprocessor, that could potentially help verify the page is written correctly such that it's the correct input to Alpine?

**Comment by HugoDF** [comment]
Alpine uses a sort of `eval` to run the contents of directives (`x-data`, `x-on:click`) etc.

So yes, if you've got invalid JavaScript in directives, an error with be thrown that looks like it's coming from Alpine but is actually caused by the code being evaluated.

There's a PR and another issue to address this.

**Comment by HugoDF** [comment]
@joelparkerhenderson with the latest Alpine.js release, you should get a warning with the expression/element at which the syntax error is happening

**Comment by Heiss** [comment]
Hello,

i am trying to use alpine in combination with webpack and babel, but i am getting "unexpected token: @click.away". I tried to figure out, how to configure it right. Is there somewhere an example or  tutorial to do so? Or is it not possible to work together?
My package.json looking very similar to the first issuer.

Thank you.

**Comment by HugoDF** [comment]
> i am trying to use alpine in combination with webpack and babel, but i am getting "unexpected token" for this line: "@click.away="closeSideMenu". I tried to figure out, how to configure it right. Is there somewhere an example or tutorial to do so? Or is it not possible to work together?
`@click.away="closeSideMenu"` looks correct, when using Webpack make sure that if you're using a function in `x-data`, you're setting it as a `window` variable. By default webpack will create a private scope for your module.

**Comment by HugoDF** [comment]
> Hello,
> 
> i am trying to use alpine in combination with webpack and babel, but i am getting "unexpected token" for this line: "@click.away="closeSideMenu". I tried to figure out, how to configure it right. Is there somewhere an example or  tutorial to do so? Or is it not possible to work together?
> My package.json looking very similar to the first issuer.
> 
> Thank you.

Is the issue with the `@`? Does the same happen if you use `x-on:click.away` instead?
