### ISSUE TITLE
x-on:change called multiple times when used with Livewire

### ISSUE THREAD

**Issue by kevinvayro** [alpinejs/alpine#861]
I have a Laravel Livewire form and I am using Alpine to toggle a modal which shows an image cropping interface when a new image is selected using the form input before passing the cropped image to Livewire.

```
<div class="col-span-6" x-data="modal()">
  ...
  <input type="file" class="hidden" id="image-upload" x-on:change="imageSelected"/>
  ...
</div>
```

```
<script>
function modal() {
  return {
    show: false,
    open() { this.show = true },
    close() { this.show = false },
    isOpen() { return this.show === true },
    imageSelected() {
      console.log('new image selected');
    }
  }
}

document.getElementById("image-upload").addEventListener('change', handleFile, false)

function handleFile() {
  console.log('uploading image...')
  var x = document.getElementById("image-upload").files;
  console.log(x);
  @this.uploadFile(x[0].name);
}
</script>
```

`@this.uploadFile(x[0].name);` function in Livewire is currently just appending the received parameter to an array property.

I am currently using an Alpine `x-on:change` and `addEventListener('change', handleFile, false)` to try and debug if the issue is Alpine or a JS concern.

The first two times I select a file and upload it, everything works fine as expected. The `x-on:change` function is called once and the `addEventListener` function is also called once. When I upload my third file, things start to go wrong.

The `x-on:change` function is called three times and I get `new image selected` printed to the console three times. The handleFile function is still only called once from the event listener and I see `uploading image...` printed once as expected. The same happens when I select my fourth file. 

When I select my fifth and sixth file, the `x-on:change` function is called five times, I select my seventh and eight file and function is called seven times. This pattern repeats with the function being called an additional two times after every two Livewire updates.

If I remove the call to the Livewire function then everything works okay so I'm not sure if this is an Alpine issue or a Livewire problem?

**Comment by calebporzio** [comment]
This sounds like a Livewire issue.

Please re-submit on that repo: livewire/livewire

Thanks!
