### ISSUE TITLE
IE polyfill bug not destructuring template literals and functions

### ISSUE THREAD

**Issue by jasonrockacy-jobvite** [alpinejs/alpine#865]
I noticed that the IE script for alpine does not process **template literals** in `x-data`, `x-text`, `x-html`, and `x-bind`, nor does it throw an error to explain why it is broken. When I used the ES5 syntax of concatenation `x-text="'some text' + variable + 'some more text'"` everything works again.

Also, when you place functions in x-data (both from an external function in a script tag or used directly in `x-data`) per Alpine.js [example for x-data](https://github.com/alpinejs/alpine#x-data) :

```
<div x-data="dropdown()">
    <button x-on:click="open">Open</button>

    <div x-show="isOpen()" x-on:click.away="close">
        // Dropdown
    </div>
</div>

<script>
    function dropdown() {
        return {
            show: false,
            open() { this.show = true },
            close() { this.show = false },
            isOpen() { return this.show === true },
        }
    }
</script>
```

Specifically, when defining functions in `open() {this.show = true}`, it does not make them into ES5 functions, which would be in format `open: function () {this.show = true}`. After days of trying to debug the issue (with the only error to say: 
`SCRIPT1003: Expected ':' alpine-ie11.js (line information)`), i figured there was an issue with the IE polyfills not addressing those areas. When I structured the functions into ES5 function syntax, everything works again.

Hopefully, you will be able do address these issues in future version of Alpine.js

Thank you all for all of your hard work! I love Alpine, and cannot wait for what the future brings :)

Kind Regards,
Jason

**Comment by ryangjchandler** [comment]
@jasonrockacy-jobvite If you need to support IE11, you need to write those functions for IE11. Alpine isn't responsible for transpiling your code into browser-compatible syntax.

**Comment by HugoDF** [comment]
I built this prototype to do compilation for IE11 in alpine directives https://github.com/HugoDF/alpine-inline-transpile

It's not battle tested yet, but would be interested in your feedback.

As Ryan said, it's not Alpine.js' job to deal with making the code you write be IE11-compatible

**Comment by HugoDF** [comment]
@jasonrockacy-jobvite I'll close this for now, let us know if you've got any follow up questions
