### ISSUE TITLE
$watch doesn't work when property changed using setter

### ISSUE THREAD

**Issue by dafiulh** [alpinejs/alpine#869]
```html
<div x-data="data()" x-init="$watch('text', console.log)">
  <button @click="text = 'directly'">Change 'text' directly</button>
  <button @click="newText = 'setter'">Change 'text' with setter</button>
  <div x-text="text"></div>
<div>
<script>
  window.data = () => ({
    text: 'initial',
    set newText(v) {
      this.text = v;
    }
  });
</script>
```

When I click `Change 'text' directly` button, DOM changes and $watch callback get fired (console logging `text` new value). However, when I click the other button, DOM changes but $watch callback doesn't seem to get fired, even though they both basically do the same thing.
See demo [here](https://jsbin.com/befifux/5/edit?html,console,output)

**Comment by SimoTod** [comment]
It's expected. Reactivity in Alpine works thank to a layer of js proxies to intercept when a variable changes. Setters are low level constructs and inside their block, this is the final object so you have already past alpine.
I don't think it's technically possible with the current architecture.
I suggest you use a normal function callet setText.

**Comment by dafiulh** [comment]
Hmm, okay then.
Thanks for clarifying!
