### ISSUE TITLE
Multiple x-refs with the same value (returns the last child element that matches rather than, like querySelector does, the first)

### ISSUE THREAD

**Issue by richgcook** [alpinejs/alpine#900]
As per my discussion with @HugoDF on the [Discord channel](https://discord.com/channels/697534128706551828/697534289419436142/782731337059794975)

> Is there any reason, if multiple x-refs with the same value exist, why $refs returns the last child element that matches rather than, like querySelector does, return the first?

Hugo's reply:
> The implementation walks the elements and overrides the ref when the attribute is found, so the last walked element for a given ref will be the one accessible through $refs. This is not necessarily wanted behaviour, just how it's implemented and could be a bug, probably worth raising in the repo.

And thus here I am!

**Comment by HugoDF** [comment]
For reference, the implementation is here https://github.com/alpinejs/alpine/blob/master/src/component.js#L444-L459

**Comment by KevinBatdorf** [comment]
It makes sense to me that it should be the first one in the case where you may happen to have more than one

**Comment by calebporzio** [comment]
Hmmm I think I'm going to close this as $refs aren't meant to support duplicates.

It's an interesting point though.

**Comment by richgcook** [comment]
I think this is fair 👍

**Comment by mrcsmcln** [comment]
I think this could be a worthwhile feature to implement.

Vue supports multiple $refs with the same name, a feature I've used extensively. For me, this works out to be a good approach when you need to do some more complicated looping over DOM items.

For example, observing items with IntersectionObserver:

Current approach:

```js
const observer = new IntersectionObserver(callback)

for (const el of this.$el.querySelectorAll('[data-observe]')) {
  observer.observe(el)
}
```

But a less DOM-y approach could look like this:

```js
const observer = new IntersectionObserver(callback)

for (const el of this.$refs.observe) {
  observer.observe(el)
}
```

While there's nothing inherently wrong with using data attributes per the former approach, I feel like it's a better DX to use $refs when we can.

**Comment by SimoTod** [comment]
The main problem with returning an array when you have multiple refs with the same name is the ambiguity (at runtime you never know what type you will get). Vue v2 for example only returns array for refs defined in v-for (even if it's a single node) and I think they actually removed that behaviour in v3 because of that reason. (https://v3.vuejs.org/guide/migration/array-refs.html).

**Comment by Mushr0000m** [comment]
> Hmmm I think I'm going to close this as $refs aren't meant to support duplicates.
> 
> It's an interesting point though.

@calebporzio Just to be sure if I have a blade component that use an alpine component that have a `x-ref` like this : 
```
<div class="input-number" x-data='inputNumber()'>
    <input type="number" x-ref="input" {{ $attributes }}>
    <i class="minus" x-on:click="stepDown()"></i>
    <i class="plus" x-on:click="stepUp()"></i>
</div>
```
Is this considered duplicates x-ref when having multiple times this component on the page (like with ID) ? Because right now I face this issue of the $refs.input always giving me the last input in the page if I have multiple instances.

**Comment by davisngl** [comment]
@Mushr0000m I might be late to this, but, at least now, when you have 2 or more separate Alpine components (denoted that Alpine component is an HTML element with `x-data` *at least* on it), you can have them have their own set of refs that can be the same name across multiple instances of those components - they will pick up the correct ref.

Simple way to test it out would be to import Alpine as script, have this in the body:
```
      <div x-data x-init="() => console.log($refs.input.value)">
        <input type="text" x-ref="input" value="first input">
      </div>

      <div x-data x-init="() => console.log($refs.input.value)">
          <input type="text" x-ref="input" value="second input">
      </div>
```

and they would output accordingly:
[Output in console](https://imgur.com/a/p8ykRvJ)

I used Alpine `3.10.3` for this example.

Hope that helps.
