### ISSUE TITLE
Outdated example `x-on:keydown.cmd.enter="foo"` in README.md

### ISSUE THREAD

**Issue by pohlt** [alpinejs/alpine#915]
`x-on:keydown.cmd.enter="foo"` does not work for me. `x-on:keydown.enter="foo"` does.

If you can confirm, that this has changed, I can prepare a PR for all languages.

**Comment by pohlt** [comment]
Anyone?

**Comment by KevinBatdorf** [comment]
`cmd.enter` works for me in Chrome on Mac. What OS/browser? 

https://codepen.io/KevinBatdorf/pen/4aa25651cc7dfcf9e1dbdf76db294021?editors=1001

Can you give an example of it not working?

**Comment by pohlt** [comment]
Just tested your codepen example (added a line without the `cmd`) on Win10 and Linux (both Chrome 87) and it only works without the `cmd`.

**Comment by KevinBatdorf** [comment]
Ho about `keydown.super.enter` or `keydown.meta.enter`?

**Comment by pohlt** [comment]
D'oh! That was the right question! Thanks a lot!
I'm not using Macs regularly, so I didn't get that the `cmd` refers to the command key. When I press the Win key it works as expected.
Maybe a less Mac-centric modifier in the example would help others to avoid the same misunderstanding.
