### ISSUE TITLE
Updating the Russian translation

### ISSUE THREAD

**Issue by maxsite** [alpinejs/alpine#920]
I made an update of the Russian translation for Alpine. File in the attachment. Thanks.
[README.ru.md.txt](https://github.com/alpinejs/alpine/files/5659098/README.ru.md.txt)

**Comment by HugoDF** [comment]
@maxsite are you able to create a PR instead?

**Comment by maxsite** [comment]
no

**Comment by proweb** [comment]
@HugoDF @maxsite 
[PR created](https://github.com/alpinejs/alpine/pull/927)

**Comment by calebporzio** [comment]
Thanks!
