### ISSUE TITLE
Shift + Slash keydown combo doesn't work

### ISSUE THREAD

**Issue by lleger** [alpinejs/alpine#926]
Trying to use the <kbd>?</kbd> key to initiate an action in Alpine (show a modal). The only way to do that is actually with <kbd>Shift</kbd> <kbd>/</kbd>, however this combo doesn't work.

Weirdly, other combos _do_ work.

- ✅ Cmd + enter (from test suite)
- ✅ Cmd + Slash
- ✅ Slash
- ❌ Shift + slash

See this fiddle for example repro:
https://jsfiddle.net/zvs3brxw/

Am I doing something wrong/misunderstanding how to wire this up, or is this a bug?

**Comment by KevinBatdorf** [comment]
You need to use `x-on:keydown.shift.?="count++"` for this to work, because with `shift` pressed, you're then pressing the `?` key.

**Comment by lleger** [comment]
🤦 I figured I was doing something wrong and yet that never occurred to me. Thank you!
