### ISSUE TITLE
defective readme re :key binding

### ISSUE THREAD

**Issue by markfirmware** [alpinejs/alpine#930]
Note: the :key binding is optional, but HIGHLY recommended.

Why? What does it do?

**Comment by SimoTod** [comment]
When refreshing, without keys alpune would discard all the old elements and recreate them from scratch. With keys, alpine rearranges the existing elements and it just creates/deletes the one he needs to.
If, for instance, you have elements with a dom state like input fields inside a for item, without keys they would reset to the default value each time.

**Comment by markfirmware** [comment]
Thanks!
