### ISSUE TITLE
x-text wil not work unless inside of component

### ISSUE THREAD

**Issue by markfirmware** [alpinejs/alpine#956]
Lesson learned: always start a reduced case with \<div x-data\>

https://codepen.io/markfirmware/pen/gOwXobK

**Comment by markfirmware** [comment]
Always use

    <html x-data>

to keep your app happy happy happy.

**Comment by KevinBatdorf** [comment]
Better to keep your component scope as tight as possible actually. If you add it to the <html> tag you then have an expensive observer callback running on every dom mutation. 

I'd say never use it there or on the <body> either. Just scope it to exactly what you need.

**Comment by markfirmware** [comment]
Ok. Please take a look at https://codepen.io/markfirmware/pen/MWjOVVx - this is more like my original problem. I now see that I need to add x-data on the div that uses $component in order for it to work - it is referring to a component that is next to it.

**Comment by KevinBatdorf** [comment]
That's right, just add x-data to the outer component in this case: 

```html
<div x-data x-text="$component('counter').state"></div>
```

You're also missing some quotes there too (which I added in above).

**Comment by markfirmware** [comment]
Ok. Now about the quotes. Are they not redundant when there are (roughly speaking) no spaces in the value?

**Comment by KevinBatdorf** [comment]
It's invalid HTML according to the spec: https://html.spec.whatwg.org/multipage/syntax.html#unquoted

It's also just a bad practice in my opinion. Maybe you're thinking of JSX? That's not HTML so it has it's own rules and best practices.

**Comment by markfirmware** [comment]
I heard that it was valid html but not xhtml. I will defer.

Thanks for the swift help!

**Comment by KevinBatdorf** [comment]
It's not valid specifically because you included other characters not valid. I'll quote the spec I shared above:

> **Unquoted attribute value syntax** 
> The attribute name, followed by zero or more ASCII whitespace, followed by a single U+003D EQUALS SIGN character, followed by zero or more ASCII whitespace, followed by the attribute value, which, in addition to the requirements given above for attribute values, must not contain any literal ASCII whitespace, any U+0022 **QUOTATION MARK characters (")**, U+0027 APOSTROPHE characters ('), U+003D EQUALS SIGN characters (=), U+003C LESS-THAN SIGN characters (<), U+003E GREATER-THAN SIGN characters (>), or U+0060 GRAVE ACCENT characters (`), and must not be the empty string. 

Browsers will probably figure it out, but it's not guaranteed.

**Comment by markfirmware** [comment]
Ok
