### ISSUE TITLE
Using x-text inside x-spread doesn't work. Throws error!

### ISSUE THREAD

**Issue by singhhrpreet** [alpinejs/alpine#957]
JS Code:
```
loginForm = function() {
    return {
        errors: {},
        errorsMessage:{
            ['x-text']() {
                return this.errors.message;
            },
            ['x-show']() {
                return this.errors.message != '';
            }
        }
    }
}
```

HTML:
```
<div x-spread="errorsMessage"></div>
```

throws this error:
![image](https://user-images.githubusercontent.com/20049511/103150742-d80af880-479c-11eb-8722-9cbdecf3ab43.png)

If I remove the `[x-text]`, it works fine.

**Comment by KevinBatdorf** [comment]
In your example, `this.errors.message` is undefined, so it can't be used with `x-text`. 

Update to this: `errors: { message: '' }`

**Comment by singhhrpreet** [comment]
Thanks @KevinBatdorf, that worked.

Since it worked like this
```
<div x-spread="errorsMessage" x-text="errors.message"></div>
```
where I can bind the value of `errors.message` to the element by having errors as an empty object.

I assumed it would work inside `x-spread` too.

**Comment by KevinBatdorf** [comment]
It's probably a bug with `x-spread`. You can leave the issue open.

**Comment by singhhrpreet** [comment]
@KevinBatdorf 👍
