### ISSUE TITLE
Replace harcode turbolinks:load with custom event

### ISSUE THREAD

**Issue by pfrlv** [alpinejs/alpine#96]
```js
// It's easier and more performant to just support Turbolinks than listen
// to MutationOberserver mutations at the document level.
document.addEventListener("turbolinks:load", () => {
  this.discoverUninitializedComponents(el => {
    this.initializeComponent(el)
  })
})
```

I think it's better to be able to change the event of loading and updating components, for example for Swup, Pajax, etc.. Add an option such as `updatedEvent: 'swup:contentReplaced'`.

**Comment by calebporzio** [comment]
Ah, yeah, I'd be open to the customization. Something simple like:

`Alpine.triggerRefreshOnEvent('swup:contentReplaced')`

It could be like one line added to the index.js file.

I'd be open to a PR. Closing for now.

**Comment by phacks** [comment]
I went ahead and created a PR for this!

Also, I feel that this should appear somewhere in the docs: I had to dig into the code to figure out that Alpine was listening to the specific `turbolinks:load` event and dispatch that one manually in my InstantClick powered app.

Happy to create a PR for that also if you agree!
