### ISSUE TITLE
Select Option 'selected disabled' Not Defaulting

### ISSUE THREAD

**Issue by jjjrmy** [alpinejs/alpine#970]
If you have a select input with a default option using `value="" selected disabled` and `x-model` with a null value, it will not default to that first option. Without the `x-data` it works fine.

https://codepen.io/jjjrmy/pen/gOwvRBg?editors=1000

On the example the Year input has the desired results. Only the ones using Alpine are not behaving correctly.

`"alpinejs": "^2.8.0",`

**Comment by ryangjchandler** [comment]
Have you tried setting the default value to an empty string instead of null?

**Comment by jjjrmy** [comment]
> Have you tried setting the default value to an empty string instead of null?
@ryangjchandler 

Yes, check the example, empty string and null have same results.
It works fine if you don't use the `disabled` prop.

**Comment by SimoTod** [comment]
You can use `:disabled="true"` instead of `disabled`.
x-model while try to set the select to the matching value when Alpine kicks
in but, being disabled, it will select the next available option.
Whit the suggested change, alpine will add the disabled attribute after

**Comment by colinaut** [comment]
Ran into a situation where `:disabled="true"` doesn't help. I am working on a form which has fieldset sections that are hidden using x-show. When the x-show is shown any select fields inside that have x-model are set to the the first non-disabled option.

I made a codepen to show this https://codepen.io/colinaut/pen/wvJENbx

**Comment by colinaut** [comment]
Found a solution! Instead of `:disabled="true"`, set up so that your x-data variable defaults to null and then use to `:disabled
="variable"` on the initial option. I updated the [codepen](https://codepen.io/colinaut/pen/wvJENbx) showing this solution!
