### ISSUE TITLE
@click does not work outside of a component

### ISSUE THREAD

**Issue by abinoda** [alpinejs/alpine#971]
This does not work:
```
<button @click="alert('hi')">hi</button>
```

But this does:
```
<div x-data>
  <button @click="alert('hi')">hi</button>
</div>
```

Is there a way to use `@click` without declaring its parent as a component with `x-data`?

**Comment by SimoTod** [comment]
Alpine is a component based library. You always need to define a component to use any of its directives.

Please note this is not a bug, when opening an issue, you can select 'ask a question' to post on the discussion tab which is a better place for this kind of threads. 

About the question, If you don't have other data you can define x-data on the same tag
```html
<button x-data @click="...">click me</button>
```
