### ISSUE TITLE
Error when adding component with extracted data/behavior after page load

### ISSUE THREAD

**Issue by jreviews** [alpinejs/alpine#98]
Per https://twitter.com/getJReviews/status/1217956477362737152

Taking one of the doc examples, if you open dev tools and edit the browser HTML and paste the code below:

```
<div x-data="dropdown()">
    <button x-on:click="open()">Open</button>

    <div x-show="isOpen()" x-on:click.away="close()">
        // Dropdown
    </div>
</div>
<script>
    function dropdown() {
        return {
            show: false,
            open() { this.show = true },
            close() { this.show = false },
            isOpen() { return this.show === true },
        }
    }
</script>
```
The following error is shown in the console:

VM5352:3 Uncaught ReferenceError: dropdown is not defined. 

If you add the same component with embedded data/behavior, then it works fine:

```
<div x-data="{ open: false }">
    <button @click="open = true">Open Dropdown</button>

    <ul
        x-show="open"
        @click.away="open = false"
    >
        Dropdown Body
    </ul>
</div
```

**Comment by SimoTod** [comment]
@jreviews 

It's not related to Alpine, it's how the JS Engine works: If you past only the script tag in DevConsole and you try to call the function, you'll get the same error. Even simpler, paste "<script> alert('ok') </script>" in the Elements tab of the dev console, it won't work.

A browser won't add a new function to the Execution context if you inject it via the dev console in that way.

**Comment by jreviews** [comment]
@SimoTod Thanks! Closing this now.
