### ISSUE TITLE
template error message says there are multiple root elements when there are none

### ISSUE THREAD

**Issue by markfirmware** [alpinejs/alpine#986]
https://codepen.io/markfirmware/pen/YzGLJje

    <div>the console reports multiple element roots, but there are none</div>

    <div x-data>
      <template x-if="true">
      </template>
    </div>

Console:

    "Alpine: <template> tag with [x-if] encountered with multiple element roots. Make sure <template> only has a single child element."

**Comment by HugoDF** [comment]
I guess the solution here is to remove "only"?

**Comment by KevinBatdorf** [comment]
Probably should just say something more generic like:

> Alpine: <template> tag with [${directive}] encountered with unexpected number of element roots. Make sure \<template\> has a single child element.

**Comment by markfirmware** [comment]
> Probably should just say something more generic like:
> 
> > Alpine:  tag with [${directive}] encountered with unexpected number of element roots. Make sure <template> has a single child element.

while we are at it, are you sure that root elements is a thing? I am inclined to think that child elements is what they are.

**Comment by KevinBatdorf** [comment]
Probably should say "root elements" and not "element roots" but also probably doesn't matter either. I have no preference one over the other.

Root elements are the top most elements of a document or template fragment. I don't know if it's a valid word in the spec but it's how VueJs refers to it.

**Comment by markfirmware** [comment]
Ok, shall I proceed with a pr?

**Comment by markfirmware** [comment]
Repaired in https://github.com/alpinejs/alpine/pull/988
