### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by phuclh** [alpinejs/alpine#998]
I tried to fire an event to Livewire by using `$wire.emit`, but I got this error:

<img width="851" alt="Screen Shot 2021-01-09 at 11 41 27 PM" src="https://user-images.githubusercontent.com/6707194/104117188-33c49e00-52d4-11eb-9957-b4d9057ab98f.png">

I am using Alpinejs 2.8.0.

```
<button x-on:click="$wire.emit('some-event', 'foo', 'bar')" type="button" class="text-gray-400 hover:text-gray-500 focus:outline-none focus:text-gray-500 transition ease-in-out duration-150" aria-label="Close">
    <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
    </svg>
</button>
```

**Temporary solution:** I have to call a method by using `$wire.someMethod()`, then emit event inside `someMethod()`.

**Comment by KevinBatdorf** [comment]
I'm not totally familiar with Livewire. What's in Store.js on line 52?

**Comment by phuclh** [comment]
<img width="483" alt="Screen Shot 2021-01-10 at 7 06 05 PM" src="https://user-images.githubusercontent.com/6707194/104144125-e64d3d00-5376-11eb-9dec-8092a4a0fff6.png">

@KevinBatdorf

**Comment by KevinBatdorf** [comment]
Okay [I found the file too](https://github.com/livewire/livewire/blob/master/js/Store.js#L51). To the right of your screenshot (where it is cutoff), is there a file and line number showing that's different? 

I might not be of much help though since I'm not very familiar with Livewire. Maybe someone else will chime in here, or you should try the Livewire discussion/Discord as well.

**Comment by HugoDF** [comment]
Like Kevin I'm not familiar with Livewire, but it sounds to me like there's a listener missing for "some-event" (no idea how Livewire works so this might be fine)

**Comment by dadley** [comment]
Try `Livewire.emit('some-event', 'foo', 'bar')` instead, this solved the problem for me.

**Comment by felixsc** [comment]
> Try `Livewire.emit('some-event', 'foo', 'bar')` instead, this solved the problem for me.

Solved it for me as well.

**Comment by phuclh** [comment]
@dadley it works for me. Thank you :D
